\documentclass[10pt,twoside]{article}

%!\VignetteEncoding{UTF-8}
%\VignetteIndexEntry{plant physiology}
%\usepackage{Sweave}

\usepackage{suppmat}
\usepackage{listings}
\usepackage[T1]{fontenc} % Better underscores, shockingly.

\newcommand{\plant}{\textsc{plant}}

\usepackage{graphicx}
% We will generate all images so they have a width \maxwidth. This means
% that they will get their normal width if they fit onto the page, but
% are scaled down if they would overflow the margins.
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}

\title{Description of the \texttt{FF16} physiological model}
\date{}

\usepackage[]{natbib}
\bibliographystyle{mee}

\begin{document}

\maketitle

\tableofcontents

\section{Introduction}

This document outlines the core physiological model used in the {\plant}
package. This model has primarily been developed elsewhere, in particular in
\citet{Falster-2011}. The model's equations are presented here not as original findings,
but rather so that users can understand the full system of equations being
solved within {\plant}.

The purpose of a physiological model in {\plant} is to take a plant's
current size, light environment, and physiological parameters as inputs,
and return its growth, mortality, and fecundity rates. In the \texttt{FF16}
physiological model, these vital rates are all
derived from the rate at which living biomass is produced by the plant,
which in turn is calculated based on well-understood physiology (Fig.
\ref{fig:schematic-phys}). Various physiological parameters
influence demographic outcomes. Varying these parameters allows accounting for
species differences, potentially via traits (see last
section). Tables
\ref{tab:definitions}, \ref{tab:params_core}, \ref{tab:params_hyper} summarize the
units and definitions of all variables, parameters, and hyper-parameters used in
the material below.

\begin{figure}[h!]
\centering
\includegraphics[width=15cm,height=15cm,keepaspectratio]{figures/schematic-phys}
\caption{Physiological model in {\plant}, giving
demographic rates on the basis of its traits, size, and light environment, as functions of
net mass production. The dashed arrow towards mortality indicates that, although the mortality rate is assumed to depend on mass production, no
mass is actually allocated there. Figure adapted from
\citet{Falster-2011} and \citet{Falster-2015}.}
\label{fig:schematic-phys}
\end{figure}

\section{Growth}\label{growth}

\subsection{Leaf photosynthesis}\label{leaf-photosynthesis}

We denote by \(p(x, E)\) the gross rate of leaf photosynthesis per unit
leaf area within the canopy of a plant with traits \(x\) at light
level \(E(z)\), where \(z\) is height within the canopy.
We assume a relationship of the form
\begin{equation}\label{eq:photosynthesis}
p(x, E(z)) = \frac{\alpha_{{\rm p1}}}{E(z) + \alpha_{{\rm p2}}},
\end{equation}
for the average of \(p\) across the year. The parameters
\(\alpha_{{\rm p1}}\) and \(\alpha_{{\rm p2}}\) are derived from a detailed leaf-level
model and measure, respectively, maximum annual photosynthesis and the light levels at 50\% of this maximum. The average rate of
leaf photosynthesis across the plant is then
\begin{equation}\label{eq:photosynthesis_av}
\bar{p}(x, H, E_{a}) = \int_0^H p(x, E_a(z)) \, q(z, H) \, {\rm d}z,
\end{equation}
where \(q(z, H)\) is the vertical distribution of leaf area with respect to height \(z\) (Eq.
\ref{eq:crown3}).

\subsection{Mass production}\label{standard-model-for-mass-production}

The amount of biomass available for growth,
\({\rm d}B  / {\rm d}t\), is given by the difference between income
(total photosynthetic rate) and losses (respiration and turnover) within the
plant \citep{Makela-1997, Thornley-2000, Falster-2011},
\begin{equation}\label{eq:dbdt}
\underbrace{\strut \frac{{\rm d}B}{{\rm d}t}}_\textrm{net biomass production}
= \underbrace{\strut \alpha_{\rm bio} }_\textrm{mass per C} \,
\underbrace{\strut \alpha_{\rm y} }_\textrm{yield}
\big( \underbrace{\strut A_{\rm l} \, \bar{p}}_\textrm{photosynthesis} -
\underbrace{\strut \, \sum_{i = {\rm l}, {\rm b}, {\rm s}, {\rm r}}{M_i \, r_i}}_\textrm{respiration}\big)
- \underbrace{\strut \sum_{i = {\rm l}, {\rm b}, {\rm s},  {\rm r}}{M_i \, k_i}}_\textrm{turnover}.
\end{equation}
Here, \(M, r\), and \(k\) refer to the mass, maintenance respiration rate, and
turnover rate of different tissues, denoted by subscripts \(l\) = leaves,
\(b\) = bark, \(s\) = sapwood, and \(r\) = roots. \(\bar{p}\) is the assimilation
rate of CO\(_2\) per unit leaf area, \(\alpha_{\rm y}\) is yield (i.e., the fraction of
assimilated carbon fixed in biomass, with the remaining fraction being lost
as growth respiration; this comes in addition
to the costs of maintenance respiration), and \(\alpha_{\rm bio}\) is the amount of biomass per unit carbon fixed. Gross photosynthetic production is proportional to leaf area,
\(A_{\rm l} = M_{\rm l} / \phi\), where \(\phi\) is leaf mass per
area. The total mass of living tissues is
\(M_{\rm a} = M_{\rm l} + M_{\rm b} + M_{\rm s} + M_{\rm r}.\)

\subsection{Height growth}\label{height-growth-rate}

The key measure of growth required by the demographic model is the
rate of height growth, denoted $g(x, H, E_{a})$. To model height growth
requires that we translate mass
production into height increment, accounting for the costs of
building new tissues, allocation
to reproduction, and architectural layout. Using the chain rule, height growth
can be decomposed into a product of physiologically relevant terms
\citep{Falster-2011},
\begin{equation} \label{eq:dhdt}
g(x, H, E_{a}) = \frac{{\rm d}H}{{\rm d}t} = \frac{{\rm d}H}{{\rm d}A_{\rm l}}
\times \frac{{\rm d}A_{\rm l} }{{\rm d}M_{\rm a}}
\times \frac{{\rm d}M_{\rm a}}{{\rm d}B}
\times \frac{{\rm d}B}{{\rm d}t}.
\end{equation}

The first factor,
\({\rm d}H / {\rm d}A_{\rm l}\), is the growth in plant height
per unit growth in total leaf area -- accounting for the architectural
strategy of the plant. Some species tend to leaf out more than grow
tall, while other species emphasise vertical extension.

The second factor,
\({\rm d}A_{\rm l} / {\rm d}M_{\rm a}\), accounts for the
marginal cost of deploying an additional unit of leaf area, including
construction of the leaf itself and various support structures. As such,
\({\rm d}A_{\rm l} / {\rm d}M_{\rm a}\) can itself be
expressed as a sum of construction costs per unit leaf area,
\begin{equation}\label{eq:daldmt}
\frac{{\rm d}A_{\rm l}}{{\rm d}M_{\rm a}}
= \bigg( \frac{{\rm d}M_{\rm l}}{{\rm d}A_{\rm l}} + \frac{{\rm d}M_{\rm s}}{{\rm d}A_{\rm l}} + \frac{{\rm d}M_{\rm b}}{{\rm d}A_{\rm l}} + \frac{{\rm d}M_{\rm r}}{{\rm d}A_{\rm l}}\bigg)^{-1}.
\end{equation}

The third factor,
\({\rm d}M_{\rm a} / {\rm d}B\), is the fraction
of net biomass production (Eq. \ref{eq:dbdt}) that is allocated to
growth rather than reproduction or storage. In the \texttt{FF16} physiological model,
we let this growth fraction decrease with height according to the function
\begin{equation}\label{eq:allocation}
\frac{{\rm d}M_{\rm a}}{{\rm d}B}(H) = 1 -
\frac{\alpha_{{\rm f1}}} {1 + \exp\left(\alpha_{{\rm f2}} \left(1 - H / H_{\rm mat}\right)\right)},
\end{equation}
where $\alpha_{{\rm f1}}$ is the maximum possible allocation ($0-1$) and $\alpha_{{\rm f2}}$
determines the sharpness of the transition \citep{Falster-2011}.

\subsection{Diameter growth}

Analogously, the growth in basal area $A_{\rm st}$ can be
expressed as the sum of growth in sapwood, bark, and heartwood areas
($A_{\rm s}, A_{\rm b}$, and $A_{\rm h}$, respectively),
$$\frac{{\rm d}A_{\rm st}}{{\rm d}t} = \frac{{\rm d}A_{\rm b}}{{\rm d}t} + \frac{{\rm d}A_{\rm s}}{{\rm d}t} + \frac{{\rm d}A_{\rm h}}{{\rm d}t}.$$
Applying the chain rule, we derive an equation for basal area growth that contains many of the same
elements as Eq. \ref{eq:dhdt},
\begin{equation}\label{eq:dast}
\frac{{\rm d}A_{\rm st}}{{\rm d}t} = \left(\frac{{\rm d}A_{\rm s}}{{\rm d}A_{\rm l}} + \frac{{\rm d}A_{\rm b}}{{\rm d}A_{\rm l}}\right) \times
\frac{{\rm d}A_{\rm l}}{{\rm d}M_{\rm a}} \times \frac{{\rm d}M_{\rm a}}{{\rm d}B} \times \frac{{\rm d}B}{{\rm d}t} + \frac{{\rm d}A_{\rm h}}{{\rm d}t} .
\end{equation}
Diameter growth is then given by the geometric relationship between stem
diameter $D$ and $A_{\rm st}$,
\begin{equation} \label{eq:dDdt}
\frac{{\rm d}D}{{\rm d}t} = \left(\pi \, A_{\rm st}\right)^{-0.5} \, \frac{{\rm d}A_{\rm st}}{{\rm d}t}.
\end{equation}

\section{Functional-balance model for
allocation}\label{a-functional-balance-model-for-allocation}

Here we describe an allometric model linking to a plant's height its various other size dimensions
required by most ecologically realistic vegetation models
(i.e., the masses of leaves, sapwood, bark, and fine
roots). This approach allows us to track only the
plant's height, while still accounting for the mass needs to build
leaves, roots, and stems. The growth rates of various tissues can then
also be derived (Table \ref{tab:allometry}).

\subsection{Leaf area}\label{leaf-area}


Based on empirically observed allometry \citep{Falster-2011}, we assume an allometric power-law
scaling relationship between the accumulated leaf area of a plant and
its height,
\begin{equation}\label{eq:ha}
H = \alpha_{{\rm l1}} \, \left(A_{\rm l} \, {\rm m^{-2}}\right)^{\alpha_{{\rm l2}}}.
\end{equation}
This relationship is normalised around a leaf area of 1m${^2}$.

\subsection{Vertical distribution of leaf
area}\label{vertical-distribution-of-leaf-area}

We follow the model of \citet{Yokozawa-1995} describing the vertical
distribution of leaf area within the crowns of individual plants. This
model can account for a variety of canopy profiles through a single
parameter \(\eta\). Setting \(\eta = 1\) results in a conical canopy, as
seen in many conifers, while higher values, e.g., \(\eta = 12\) , give a
top-heavy canopy profile similar to those seen among angiosperms. We denote
by \(A_{{\rm s},z}\) the sapwood area at height \(z\) within the plant, by \(q(z, H)\) the vertical distribution of leaf area of
leaf area with respect to height \(z\), and by \(Q(z, H)\) the cumulative fraction of a
plant's leaves above height \(z\). As defined previously, \(A_{\rm s}\) is the sapwood
area at the base of the plant. Following \citet{Yokozawa-1995}, we
assume a relationship between \(A_{{\rm s},z}\) and height such that
\begin{equation}\label{eq:crown1}
\frac{A_{{\rm s},z}}{A_{\rm s}} = \left(1 - \left(\frac{z}{H}\right)^\eta\right)^2.
\end{equation}

We also assume that each unit of leaf area is supported by a fixed area \(\theta\) of
sapwood \citep[in agreement with the pipe model;][]{Shinozaki-1964}, so that the total canopy
area of a plant relates to its basal sapwood area \(A_{\rm s}\),
\begin{equation}\label{eq:crown2}
A_{\rm s} = \theta \, A_{\rm l}.
\end{equation}
The pipe model is assumed to hold within individual plants, as well as
across plants of different size. It follows that
\begin{equation}\label{eq:crown1}
Q(z, H) = \left(1-\left(\frac{z}{H}\right)^\eta\right)^2.
\end{equation}
Differentiating with respect to \(z\) then yields a solution for the
probability density of leaf area as a function of height,
\begin{equation}\label{eq:crown3}
q(z, H) = 2\frac{\eta}{H}\left(1-\left(\frac{z}{H}\right)^{\eta}\right) \left(\frac{z}{H}\right)^{\eta-1}.
\end{equation}

\subsection{Sapwood mass}\label{mass-of-sapwood}

Integrating \(A_{{\rm s},z}\) yields the total mass of
sapwood in a plant,
\begin{equation}\label{eq:ms1}
M_{\rm s}  = \rho \int_0^H A_{{\rm s},z} \, {\rm d}z = \rho A_{\rm s} H \eta_{\rm c} ,
\end{equation}
where \(\eta_{\rm c} = 1 - \frac{2}{1 + \eta} + \frac{1}{1 + 2\eta}\)
\citep{Yokozawa-1995}. Substituting from Eq. \ref{eq:crown2}  into Eq.
\ref{eq:ms1} then gives an expression for sapwood mass as a function of
leaf area and height,
\begin{equation}\label{eq:ms2}
M_{\rm s} = \rho \, \eta_{\rm c} \, \theta \, A_{\rm l}  \, H.
\end{equation}

\subsection{Bark mass}\label{bark-mass}

Bark and phloem tissue are modelled using an analogue of the pipe model,
leading to a similar equation as that for sapwood mass (Eq.
\ref{eq:ms2}). The cross-section area of bark per unit leaf area is
assumed to be a constant fraction \(\alpha_{{\rm b1}}\) of sapwood area per unit leaf
area such that
\begin{equation}\label{eq:mb}
M_{\rm b} = \alpha_{{\rm b1}} M_{\rm s}.
\end{equation}

\subsection{Root mass}\label{root-mass}

Also consistent with the pipe model, we assume a fixed ratio of
root mass per unit leaf area,
\begin{equation}\label{eq:mr}
M_{\rm r} = \alpha_{{\rm r1}} \, A_{\rm l}.
\end{equation}
Even though nitrogen and water uptake are not modelled explicitly,
imposing a fixed ratio of root mass to leaf area ensures that
approximate costs of root production are included in calculations of
carbon budget.

\section{Seed production}\label{seed-production}

The rate of seed production, \(f(x, H, E_{a})\), is a direct
function of the mass allocated to reproduction,
\begin{equation}\label{eq:fecundity}
f(x, H, E_{a}) = \frac{(1 - \frac{{\rm d}M_{\rm a}}{{\rm d}B}) \times \frac{{\rm d}B}{{\rm d}t}}{
\omega + \alpha_{{\rm f3}}},
\end{equation}
where \(\omega\) is the mass of the seed and \(\alpha_{{\rm f3}}\) is the cost
per seed of accessories, such as fruits, flowers, and dispersal
structures. The function $\frac{{\rm d}M_{\rm a}}{{\rm d}B}$ is the fraction
of $\frac{{\rm d}B}{{\rm d}t}$ that is allocated to growth (from Eq. \ref{eq:allocation}, while
$1-\frac{{\rm d}M_{\rm a}}{{\rm d}B}$ gives the fraction allocated
to reproduction).

\section{Mortality}\label{mortality}

Instantaneous rates of plant mortality are given by the sum of a growth-independent and a growth-dependent rate
\citep{Falster-2011, Moorcroft-2001},
\begin{equation}\label{eq:mortality}
d(x, H, E_{a}) = d_{{\rm I}}(x, H) + d_{{\rm G}}(x, H, E_{a}).
\end{equation}
The growth-independent rate is taken to be constant, independent of
plant performance, but potentially varying with species traits. The
growth-dependent rate is assumed to decline exponentially with the rate
of mass production per unit leaf area,
\begin{equation}\label{eq:mortality_GD}
d_{{\rm G}}(x, H, E_{a}) = \alpha_{{\rm dG1}} \exp(-\alpha_{{\rm dG2}} X),
\end{equation}
where \(X = {\rm d}B/{\rm d}t / A_{\rm l}\). This
relationship allows for plants to increase in mortality as their growth rate
approaches zero, while allowing for species to differ in
the parameters \(\alpha_{{\rm dG1}}\) and \(\alpha_{{\rm dG2}}\).

We also require a function \(S_{\rm G}  (x^\prime, H_0, E_{{\rm a}0})\) for plant survival
through germination. For the demographic model to behave smoothly,
\(S_{\rm G}  (x^\prime, H_0, E_{{\rm a}0}) / g(x, H_0, E_{{\rm a}0})\) should approach zero as
\(g(x, H_0, E_{{\rm a}0})\) approaches zero. Following \citet{Falster-2011},
we use the function
\begin{equation} \label{eq:pi1}
S_{\rm G} (x^\prime, H_0, E_{{\rm a}0}) = \frac1{1 + X^2},
\end{equation}
where $X = \alpha_{{\rm d0}} \frac{A_{\rm l}}{{\rm d}B / {\rm d}t}$ and $\alpha_{{\rm d0}}$ is a
constant. Eq. \ref{eq:pi1} is consistent with Eq.
\ref{eq:mortality_GD}, as both cause survival to decline with mass production.

\section{Hyper-parameterisation of physiological model via
traits}\label{traits}

The \texttt{FF16} physiological model includes default values for all needed parameters
(Table \ref{tab:params_core}). Species are known to vary considerably
in many of these parameters, such as $\phi$, $\rho$, $\nu$, and $\omega$; so by varying parameters
one can account for species differences. When altering a parameter in the model, however,
one must also consider whether there are trade-offs linking parameters.

{\plant} allows for the
hyper-parameterisation of the \texttt{FF16} physiological model via plant functional traits: this enables
simultaneous variation in multiple parameters in accordance with an assumed trade-off. In the
\texttt{FF16} physiological model, we implement the relationships described below. For more
details, see \texttt{make\_FF16\_hyperpar.R}.

\subsection{Leaf mass per unit area}

The trait leaf mass per unit area, denoted by $\phi$, directly influences growth by changing
${\rm d}A_{\rm l} / {\rm d}M_{\rm a}$. In addition, we
link $\phi$ to the rate of leaf turnover,
based on a widely observed scaling relationship from \citet{Wright-2004},
$$k_{\rm l} = \beta_{{\rm kl1}} \, \left(\frac{\phi}{\phi_0}\right)^{-\beta_{{\rm kl2}}}.$$
This relationship is normalised around $\phi_0$, the global mean of $\phi$. This
allows us to vary $\beta_{{\rm kl1}}$ and $\beta_{{\rm kl2}}$ without displacing the relationship from the
observed mean.

We also vary the mass-based leaf respiration rate so that it stays constant per unit leaf area and
varies with $\phi$ and nitrogen per unit leaf area $\nu$, as empirically observed by \citet{Wright-2004},
$$r_{\rm l} = \frac{\beta_{{\rm lf4}}\, \nu}{\phi}.$$

\subsection{Wood density}

The trait wood density, denoted by $\rho$, directly influences growth by changing
${\rm d}A_{\rm l} / {\rm d}M_{\rm a}$. In addition, we allow for
$\rho$ to influence the rate of growth-independent mortality,
$$d_{\rm I} = \beta_{{\rm dI1}} \, \left(\frac{\rho}{\rho_0}\right) ^ {-\beta_{{\rm dI2}}},$$
and also the rate of sapwood turnover,
$$k_{\rm s} = \beta_{{\rm ks1}} \, \left(\frac{\rho}{\rho_0}\right)^ {-\beta_{{\rm ks2}}},$$
As for $\phi$, these relationships are normalized around $\rho_0$, the global mean of $\rho$.
By default, $\beta_{{\rm kI2}}$ and $\beta_{{\rm ks2}}$ are set to zero, so these linkages
only become present when these parameters are set to something other than their default values.

The rate of sapwood respiration per unit volume is assumed to be constant, so
sapwood respiration per unit mass varies as
$$r_{\rm s}  = \frac{\beta_{{\rm rs1}}}{\rho},$$
where $\beta_{{\rm rs1}}$ is a default rate per volume of sapwood.
Similarly, the rate of bark respiration per unit mass varies as
$$r_{\rm b} = \frac{\beta_{{\rm rb1}}}{\rho},$$
with $\beta_{{\rm rb1}} = 2 \beta_{{\rm rs1}}$.

\subsection{Seed mass}

Effects of the trait seed mass, denoted by $\omega$, are naturally embedded in the equation determining
fecundity (Eq. \ref{eq:fecundity}) and the initial height of seedlings. In addition,
we let the accessory cost per seed be a multiple of seed size,
$$\alpha_{{\rm f3}} = \beta_{{\rm f1}} \omega,$$
as empirically observed \citep{Henery-2001}.

\subsection{Nitrogen per unit leaf area}

Photosynthesis per unit leaf area and respiration rates per unit leaf mass (or area)
are assumed to vary with leaf nitrogen per unit area, $\nu$. The calculation of respiration rates is already described above. To calculate the average annual photosynthesis for a leaf,
we integrate the instantaneous rate per unit leaf area over the annual solar trajectory,
using a rectangular-hyperbolic photosynthesis light response curve,

$$p(\nu, E) = \frac1{365 \textrm{d}}\int_0^{365 \textrm{d}}\frac{Y(t) + A_{\rm max} - \sqrt{(Y(t) + A_{\rm max})^2 - 4 \beta_{{\rm lf2}} Y(t) A_{\rm max} }}{2 \beta_{{\rm lf2}}} {\rm d}t,$$
where
\begin{itemize}
\item $A_{\rm max}$ is the maximum photosynthetic capacity of the leaf,
\item $\beta_{{\rm lf2}}$ is the curvature of the light response curve,
\item $Y(t) = \beta_{{\rm lf3}} I(t)$ is the initial yield of the light response curve, with $\beta_{{\rm lf3}}$ being the quantum yield parameter,
\item $I(t) = k_{\rm I} \, I_0(t)\, E$ is the intensity of light on the leaf surface, and
\item $I_0(t)$ is light incident on a surface perpendicular to the sun's rays directly above the canopy at time $t$.
\end{itemize}
The profile of $I_0(t)$ is given by a solar model adapted from \citet{TerSteege-1997}.

We allow for the maximum photosynthetic capacity of the leaf to vary with leaf nitrogen per unit area, as
\begin{equation} \label{eq:amax}
A_{\rm max} = \beta_{{\rm lf1}} \, \left(\frac{\nu}{\nu_0}\right)^{\beta_{{\rm lf5}}},
\end{equation}
where $\beta_{{\rm lf1}}$ and $\beta_{{\rm lf5}}$ are constants. The relationships is normalized around $\nu_0$, the global mean of leaf nitrogen per unit area.

Values of $p(\nu, E)$ are calculated across a range of values of $E$, and then an expression of the form in Eq. \ref{eq:photosynthesis} is fitted to extract the parameters
$\alpha_{{\rm p1}}$ and $\alpha_{{\rm p2}}$, such that these become functions of $\nu$.

\clearpage

\section{Tables}\label{tables}

\begin{table}[h!]
\caption{Key variables of the \texttt{FF16} physiological model. For mass ($M$), respiration ($r$), and turnover ($k$)
variables, subscripts refer to any of the following tissues: \({\rm l}\) = leaves, \({\rm b}\) = bark, \({\rm s}\) = sapwood,
\({\rm r}\) = roots, \({\rm a}\) = all living tissue. For area \(A\) variables, subscripts refer to any of the following: \({\rm l}\) = leaves, \({\rm st}\) = total stem cross-section, \({\rm s}\) = sapwood cross-section, \({\rm b}\) = bark cross-section, \({\rm h}\) = heartwood cross-section.}
\centering
\begin{tabular}{p{2cm}p{2.5cm}p{8cm}}
\hline
Symbol & Unit & Description \\
\hline
\multicolumn{3}{l}{\textbf{Plant construction}} \\
$x$ & & Vector of traits for a species\\
$H_0$ & m & Height of a seedling after germination\\
$H$ & m & Height of a plant\\
$B$ & kg & Biomass originating from parent plant\\
$M_i$ & kg & Mass of tissue type $i$ retained on plant \\
$A_i$ & m$^2$ & Surface area or area of cross-section of tissue type $i$\\
$q(z, H)$ & m$^{-1}$ & Vertical distribution of leaf area across heights $z$ for a plant with height $H$\\
$Q(z, H)$ &  & Fraction of leaf area above height $z$ for a plant with height $H$\\
\multicolumn{3}{l}{\textbf{Mass production}} \\
$p,\bar{p}$ & mol yr$^{-1}$ m$^{-2}$ & Photosynthetic rate per unit area \\
$r_i$ & mol yr$^{-1}$ kg$^{-1}$  & Respiration rate per unit mass of tissue type $i$ \\
$k_i$ & yr$^{-1}$ & Turnover rate for tissue type $i$ \\
\multicolumn{3}{l}{\textbf{Environment}} \\
$a$ & yr& Patch age\\
$E_{a}$ & & Profile of canopy openness within a patch of age $a$\\
$E_{a}(z)$&& Canopy openness at height $z$ within a patch of age $a$\\
\multicolumn{3}{l}{\textbf{Demographic outcomes}} \\
$g(x, H, E_{a})$ & m yr$^{-1}$ & Height growth rate of a plant with traits $x$ and height $H$ in the light environment $E_a$ in a patch of age $a$ \\
$f(x, H, E_{a})$ & yr$^{-1}$ & Seed production rate of a plant with traits $x$ and height $H$ in the light environment $E_a$ in a patch of age $a$\\
$d(x, H, E_{a})$ & yr$^{-1}$ & Instantaneous mortality rate of a plant with traits $x$ and height $H$ in the light environment $E_a$ in a patch of age $a$\\
$S_{\rm G} (x, H_0, E_{{\rm a}0})$ & & Probability that a seed germinates successfully \\
\hline
\end{tabular}
\label{tab:definitions}
\end{table}

\newpage

\begin{table}[h!]
\caption{Equations of the allometric growth model implemented within the \texttt{FF16} physiological model, based on functional-balance assumptions (see text for details).
The key assumptions allocation model are listed in (a), under ``Function''. From these
assumptions, allocation functions are derived for tissue areas and tissue masses (b). Also
the growth rate of each tissue type can be expressed as a function of the growth rate of leaf area. For mass ($M$), respiration ($r$), and turnover ($k$)
variables, subscripts refer to any of the following tissues: \({\rm l}\) = leaves, \({\rm b}\) = bark, \({\rm s}\) = sapwood,
\({\rm r}\) = roots, \({\rm a}\) = all living tissue. For area \(A\) variables, subscripts refer to any of the following: \({\rm l}\) = leaves, \({\rm st}\) = total stem cross-section, \({\rm s}\) = sapwood cross-section, \({\rm b}\) = bark cross-section, \({\rm h}\) = heartwood cross-section.}
\centering
\begin{tabular}{p{2.5cm}p{3.5cm}p{5cm}p{4cm} }\\ \hline
Variable & Function & Allocation & Growth rate\\ \hline
\multicolumn{4}{l}{\textbf{(a) Assumed relationships with leaf area}} \\
Height &
$H = \alpha_{{\rm l1}} \, \left(A_{\rm l} \, {\rm m^{-2}} \right)^{\alpha_{{\rm l2}}}$ &
$\frac{{\rm d}H}{{\rm d}A_{\rm l}} = \alpha_{{\rm l2}} \alpha_{{\rm l1}} \left(A_{\rm l} \, {\rm m^{-2}} \right)^{\alpha_{{\rm l2}}-1}$ &
$\frac{{\rm d}H}{{\rm d}t} = \frac{{\rm d}H}{{\rm d}A_{\rm l}} \, \frac{{\rm d}A_{\rm l}}{{\rm d}t}$ \\
Sapwoood area &
$A_{\rm s} = \theta \, A_{\rm l}$ &
$\frac{{\rm d}A_{\rm s}}{{\rm d} A_{\rm l}} = \theta$ &
$\frac{{\rm d}A_{\rm s}}{{\rm d}t} = \frac{{\rm d}A_{\rm s}}{{\rm d} A_{\rm l}} \, \frac{{\rm d}A_{\rm l}}{{\rm d}t}$ \\
Bark area &
$A_{\rm b} = \alpha_{{\rm b1}} \, \theta \, A_{\rm l}$ &
$\frac{{\rm d}A_{\rm b}}{{\rm d} A_{\rm l}} = \alpha_{{\rm b1}} \, \theta$ &
$\frac{{\rm d}A_{\rm b}}{{\rm d}t} = \frac{{\rm d}A_{\rm b}}{{\rm d} A_{\rm l}} \, \frac{{\rm d}A_{\rm l}}{{\rm d}t}$ \\ \\
\multicolumn{4}{l}{\textbf{(b) Derived equations for mass of tissue }} \\
Leaf mass &
$M_{\rm l} = \phi \, A_{\rm l} $ &
$\frac{{\rm d}M_{\rm l}}{{\rm d}A_{\rm l}} = \phi$ &
$\frac{{\rm d}M_{\rm l}}{{\rm d}t} = \frac{{\rm d}M_{\rm l}}{{\rm d}A_{\rm l}} \, \frac{{\rm d}A_{\rm l}}{{\rm d}t}$ \\
Sapwood mass &
$M_{\rm s} = \rho \, \theta \, \eta_{\rm c} \, A_{\rm l} \, H $ &
$\frac{{\rm d}M_{\rm s}}{{\rm d}A_{\rm l}} = \rho \, \theta \, \eta_{\rm c} \, \big(H + A_{\rm l} \, \frac{{\rm d}H}{{\rm d}A_{\rm l}} \big)$ &
$\frac{{\rm d}M_{\rm s}}{{\rm d}t} = \frac{{\rm d}M_{\rm s}}{{\rm d}A_{\rm l}} \, \frac{{\rm d}A_{\rm l}}{{\rm d}t}$ \\
Bark mass &
$M_{\rm b} = \alpha_{{\rm b1}} \, \rho \, \theta \, \eta_{\rm c} \, A_{\rm l} \, H $ &
$\frac{{\rm d}M_{\rm b}}{{\rm d}A_{\rm l}} = \alpha_{{\rm b1}} \, \rho \, \theta \, \eta_{\rm c}\big(H + A_{\rm l} \, \frac{{\rm d}H}{{\rm d}A_{\rm l}} \big)$ &
$\frac{{\rm d}M_{\rm b}}{{\rm d}t} = \frac{{\rm d}M_{\rm b}}{{\rm d}A_{\rm l}} \, \frac{{\rm d}A_{\rm l}}{{\rm d}t}$ \\
Root mass &
$M_{\rm r} = \alpha_{{\rm r1}} \, A_{\rm l}$ &
$\frac{{\rm d}M_{\rm r}}{{\rm d}A_{\rm l}} = \alpha_{{\rm r1}}$ &
$\frac{{\rm d}M_{\rm r}}{{\rm d}t} = \frac{{\rm d}M_{\rm r}}{{\rm d}A_{\rm l}} \, \frac{{\rm d}A_{\rm l}}{{\rm d}t}$ \\
\hline \\
\end{tabular}
\label{tab:allometry}
\end{table}

\newpage

\begin{table}[h!]
\caption{Core parameters of the \texttt{FF16} physiological model.}
\input{growth_model_pars_core}
\label{tab:params_core}
\end{table}

\begin{table}[h!]
\caption{Parameters for hyper-parameterisation of the \texttt{FF16} physiological model.}
\input{growth_model_pars_hyper}
\label{tab:params_hyper}
\end{table}

\clearpage

\bibliography{refs}


\end{document}
