---
title: "Self-thinning"
author: "Becca"
format: html
editor: visual
---

## Create a classic self-thinning plot

#### Mean stem diameter against mean density, per unit area, on a double-log scale

```{r}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, eval = FALSE}
#remotes::install_github("traitecoevo/plant", branch = "develop", force = TRUE)
```

```{r load libraries}
library(plant)
library(tidyverse)
```

```{r}
plant_log_console()
```

Grow a stand of plants:

```{r}
p0 <- scm_base_parameters("FF16")

p0$strategy_default$recruitment_decay <- 5 
#stops seeds continuing to come into the stand from early on to isolate first "group" of plants that emerges around the same time

lma_trait <- trait_matrix(0.1457419, "lma")

p1 <- expand_parameters(p0, trait_matrix = lma_trait ,mutant = FALSE)

stand_results <- build_schedule(p1)

out <- run_scm_collect(stand_results)

tidy_stand <- tidy_patch(out)
stand_expand <- FF16_expand_state(tidy_stand)

patch_total <-
    stand_expand$species %>%
    integrate_over_size_distribution() %>%
    mutate(
      # create average sizes
      across(c(diameter_stem, area_stem, area_leaf, height, mass_above_ground), ~.x/density, 
             .names = "{.col}_av")
    )
```

2.  Plot stand:

```{r}
patch_total %>% 
    ggplot(aes(diameter_stem_av, density)) + 
             geom_line() + 
             scale_x_log10() +
             scale_y_log10() +
             xlab("stem diameter (m)") +
             ylab("density " ~(m^2)) +
             ggtitle("Self-thinning plot") +
             theme_classic(base_size = 18)
```
