---
title: "costs_huber_value"
output: html_document
date: "2022-11-16"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(plant)
library(furrr)
library(future)
library(wesanderson)
```


```{r}
run_individual <- function(trait_value, trait, ...){
  params <- tibble(...) 
  p0 <- scm_base_parameters("FF16w")
  
  s1 <- strategy(trait_matrix(params$trait_value,  params$trait), p0, birth_rate_list = 1)

  indv1 <- FF16w_Individual(s1)
  
  env <- FF16w_make_environment(vpd = params$vpd)
  env$set_soil_water_state(env$soil_moist_from_psi(params$psi*1e06)) 
  env$set_fixed_environment(params$E, 150)

  res <- plant::grow_individual_to_height(indv1, heights = params$height, env, time_max =100)

    if(is.na(res$rate[1])){
    res <- NA
  }
  res
}
```

```{r}

library(future)
library(furrr)

plan(multisession, workers = "6")

expand_grid(height = seq(0.4, 20, length.out = 50), trait_value = c(0.0001, 0.0005), trait = "theta", vpd = 1, psi = 0.1, E = 1) %>%
  mutate(results= future_pmap(., run_individual)) -> output
```


```{r}
output %>%
  mutate(state= map(results, ~pluck(.x, "state")%>% as_tibble())) %>%
  rename(to_height = height) %>%
  mutate(results_rm = map_lgl(results, ~length(.x) == 1)) %>% 
  filter(results_rm == "FALSE") %>%
  select(-results_rm) %>%
  mutate(individual = map(results, ~pluck(.x, "individual"))) %>%
  unnest(state) %>%
  mutate(trajectory = map(results, ~pluck(.x, "trajectory") %>% as_tibble())) %>%
  select(trajectory) %>%
  unnest(trajectory) %>% View()

  mutate(strategy = map(individual, ~.x[[1]]$strategy)) %>%
  mutate(assim_colimited_ = map_dbl(individual, ~.x[[1]]$aux("assim_colimited_"))) %>%
  mutate(hydraulic_cost_ = map_dbl(individual, ~.x[[1]]$aux("hydraulic_cost_"))) %>%
  mutate(a_l1 = map_dbl(strategy, ~pluck(.x, "a_l1")),
         a_l2 = map_dbl(strategy, ~pluck(.x, "a_l2")),
         theta = map_dbl(strategy, ~pluck(.x, "theta")),
         rho = map_dbl(strategy, ~pluck(.x, "rho")),
         eta = map_dbl(strategy, ~pluck(.x, "eta")),
         r_s = map_dbl(strategy, ~pluck(.x, "r_s")),
         k_s = map_dbl(strategy, ~pluck(.x, "k_s")),
         eta_c = 1 - 2 / (1 + eta) + 1 / (1 + 2 * eta)) %>%
  unnest(state) %>%
  mutate(total_area_leaf = (to_height / a_l1) ^(1.0 / a_l2)) %>%
  mutate(total_assim_colimited_ = total_area_leaf*assim_colimited_) %>%
  mutate(total_hydraulic_cost = total_area_leaf*hydraulic_cost_) %>%
  mutate(total_area_sapwood = total_area_leaf * theta) %>%
  mutate(total_mass_sapwood = total_area_sapwood * height * eta_c * rho)  %>%
  mutate(total_respiration_sapwood_mol_yr = r_s * total_mass_sapwood) %>%
  mutate(total_turnover_sapwood_mol_yr = k_s * total_mass_sapwood) %>%
  mutate(total_maintenance_sapwood_mol_yr = total_respiration_sapwood_mol_yr + total_turnover_sapwood_mol_yr) %>%
  mutate(total_maintenance_sapwood_umol_s = total_maintenance_sapwood_mol_yr*1e6/365/3600)-> output_states
```

```{r}
output_states %>%
  ggplot() +
  geom_line(aes(x=to_height, y=total_maintenance_sapwood_umol_s), col = "red") +
  geom_line(aes(x=to_height, y=total_assim_colimited_), col = "blue") +
  geom_line(aes(x=to_height, y=total_maintenance_sapwood_umol_s + total_hydraulic_cost), col = "purple")

```

```{r}

output %>% 
  mutate(state= map(results, ~pluck(.x, "state")%>% as_tibble())) %>%
  rename(to_height = height) %>%
  mutate(results_rm = map_lgl(results, ~length(.x) == 1)) %>% 
  filter(results_rm == "FALSE") %>%
  select(-results_rm) %>%
  group_by(trait_value) %>%
  filter(to_height < 17.2) %>%
  filter(to_height == max(to_height)) %>%
  ungroup() %>%
  mutate(trajectory = map(results, ~pluck(.x, "trajectory") %>% as_tibble())) %>%
  unnest(trajectory) %>%
  mutate(individual = map(results, ~pluck(.x, "individual"))) %>%
  mutate(strategy = map(individual, ~.x[[1]]$strategy))%>%
  mutate(a_l1 = map_dbl(strategy, ~pluck(.x, "a_l1")),
         a_l2 = map_dbl(strategy, ~pluck(.x, "a_l2")),
         theta = map_dbl(strategy, ~pluck(.x, "theta")),
         rho = map_dbl(strategy, ~pluck(.x, "rho")),
         eta = map_dbl(strategy, ~pluck(.x, "eta")),
         r_s = map_dbl(strategy, ~pluck(.x, "r_s")),
         r_l = map_dbl(strategy, ~pluck(.x, "r_l")),
         lma = map_dbl(strategy, ~pluck(.x, "lma")),
         k_s = map_dbl(strategy, ~pluck(.x, "k_s")),
         k_l = map_dbl(strategy, ~pluck(.x, "k_s")),
         a_b1 = map_dbl(strategy, ~pluck(.x, "a_b1")),
         k_b = map_dbl(strategy, ~pluck(.x, "k_b")),
         r_b = map_dbl(strategy, ~pluck(.x, "r_b")),
         a_r1 = map_dbl(strategy, ~pluck(.x, "a_r1")),
         k_r = map_dbl(strategy, ~pluck(.x, "k_r")),
         r_r = map_dbl(strategy, ~pluck(.x, "r_r")),
         eta_c = 1 - 2 / (1 + eta) + 1 / (1 + 2 * eta))%>%
  mutate(total_area_leaf = (height / a_l1) ^(1.0 / a_l2)) %>%
  mutate(total_area_bark = a_b1 * total_area_leaf * theta) %>%
  mutate(total_mass_bark = total_area_bark * height * eta_c * rho) %>%
  mutate(total_mass_leaf = total_area_leaf * lma) %>%
  mutate(total_mass_root = total_area_leaf * a_r1) %>%
  mutate(total_assim_colimited_ = total_area_leaf*assim_colimited_*60*60*12*365/1000000*2.45e-2 *0.7) %>%
  mutate(total_hydraulic_cost = total_area_leaf*hydraulic_cost_*60*60*12*365/1000000*2.45e-2 *0.7) %>%
  mutate(total_area_sapwood = total_area_leaf * theta) %>%
  mutate(total_mass_sapwood = total_area_sapwood * height * eta_c * rho)  %>%
  mutate(total_respiration_root_mol_yr = r_r * total_mass_leaf*2.45e-2 *0.7) %>%
  mutate(total_respiration_leaf_mol_yr = r_l * total_mass_root*2.45e-2 *0.7) %>%
  mutate(total_respiration_sapwood_mol_yr = r_s * total_mass_sapwood*2.45e-2 *0.7) %>%
  mutate(total_respiration_bark_mol_yr = r_b * total_mass_bark*2.45e-2 *0.7) %>%
  mutate(total_turnover_root_mol_yr = k_r * total_mass_leaf) %>%
  mutate(total_turnover_leaf_mol_yr = k_l * total_mass_leaf) %>%
  mutate(total_turnover_sapwood_mol_yr = k_s * total_mass_sapwood) %>%
  mutate(total_turnover_bark_mol_yr = k_b * total_mass_bark) %>%
  mutate(leftover = net_mass_production_dt) -> output_states
```

```{r}


output_states %>% 
  mutate(total_respiration = total_respiration_root_mol_yr + 
           total_respiration_leaf_mol_yr + 
           total_respiration_sapwood_mol_yr +
           total_respiration_bark_mol_yr,
         total_turnover = total_turnover_root_mol_yr +
           total_turnover_leaf_mol_yr +
           total_turnover_sapwood_mol_yr +
           total_turnover_bark_mol_yr) %>%
  mutate(total_maintenance = total_respiration + total_turnover + hydraulic_cost_) %>%
  mutate(maintenance_no_sapwood = 
           total_respiration_leaf_mol_yr + 
           total_respiration_root_mol_yr +
           total_turnover_leaf_mol_yr + 
           total_turnover_root_mol_yr) %>%
  mutate(maintenance_sapwood_no_hydro_cost = total_turnover_bark_mol_yr + total_respiration_bark_mol_yr + total_turnover_sapwood_mol_yr + total_respiration_sapwood_mol_yr) %>%
  mutate(hydro_cost = total_hydraulic_cost)  %>%
  mutate(maintenance_sapwood = total_turnover_bark_mol_yr + total_respiration_bark_mol_yr + total_turnover_sapwood_mol_yr + total_respiration_sapwood_mol_yr + total_hydraulic_cost) -> output_mutated
  
output_mutated %>% 
  mutate(hydro_cost = hydro_cost + maintenance_sapwood_no_hydro_cost) %>%
  mutate(maintenance_no_sapwood = maintenance_no_sapwood + hydro_cost) %>%
  select(maintenance_no_sapwood, hydro_cost, maintenance_sapwood_no_hydro_cost, total_assim_colimited_, height, trait_value) %>%
  pivot_longer(-c(height,trait_value))%>%
  mutate(name = factor(name, levels= c("total_assim_colimited_","maintenance_no_sapwood","hydro_cost","maintenance_sapwood_no_hydro_cost"), labels = c( "Surplus", "Other maintenance","Hydraulic sapwood costs","Non-hydraulic sapwood costs"))) %>%
  #   select(leftover, maintenance_no_sapwood, maintenance_sapwood_no_hydro_cost,hydro_cost, height, trait_value) %>%
  # pivot_longer(-c(height,trait_value))%>%
  # mutate(name = factor(name, levels= c("leftover", "maintenance_no_sapwood","hydro_cost", "maintenance_sapwood_no_hydro_cost"), labels = c("Surplus", "Other maintenance", "Hydraulic sapwood maintenance", "Non-hydraulic sapwood maintenance"))) %>%
  ggplot() +
  geom_area(aes(x = height, y = value, fill = name, col = name), linewidth = 0.5, position="identity") +
  # geom_line(aes(x = height, y = value, col = name), linewidth = 0.5) + 
  theme_classic()  +
  facet_wrap(~trait_value) +
  labs(x = "Height", fill = "Budget", col = "Budget", y = expression(paste(Dry~mass~carbon, " (kg"~yr^{-1},")"))) +
  geom_text(data = output_mutated %>% distinct(trait_value), aes(x = 10, y = 150, label = paste('SA:LA = ',trait_value)), size = 8)+
  theme(strip.text = element_blank(), text = element_text(size = 25)) +
  scale_color_manual(values= wes_palette("Cavalcanti1", n = 4)) +
  scale_fill_manual(values= wes_palette("Cavalcanti1", n = 4)) -> b

png("examples_vignettes/outputs/ESA_2022/dry_mass_carbon_partioned_height_hydraulic.png", height = 1000, width = 2250, res = 150)
b
dev.off()

output_mutated %>% 
  select(leftover, maintenance_sapwood, maintenance_no_sapwood, height, trait_value) %>%
  pivot_longer(-c(height,trait_value))%>%
  mutate(name = factor(name, levels= c("leftover", "maintenance_no_sapwood","maintenance_sapwood"), labels = c("Surplus", "Other maintenance", "Sapwood maintenance"))) %>%
  ggplot() +
  geom_area(aes(x = height, y = value, fill = name, col = name), linewidth = 0.5) + 
  theme_classic()  +
  facet_wrap(~trait_value) +
  labs(x = "Height", fill = "Budget", col = "Budget", y = expression(paste(Dry~mass~carbon, " (kg"~yr^{-1},")"))) +
  geom_text(data = output_mutated %>% distinct(trait_value), aes(x = 10, y = 150, label = paste('SA:LA = ',trait_value)), size = 8)+
  theme(strip.text = element_blank(), text = element_text(size = 25)) +
  scale_color_manual(values= wes_palette("Cavalcanti1", n = 4)) +
  scale_fill_manual(values= wes_palette("Cavalcanti1", n = 4)) -> a




png("examples_vignettes/outputs/ESA_2022/dry_mass_carbon_partioned_height.png", height = 1000, width = 2000, res = 150)
a
dev.off()




output_mutated %>% 
  select(total_assim_colimited_, height, trait_value) %>%
  pivot_longer(-c(height,trait_value))%>%
  mutate(name = factor(name, levels= c("total_assim_colimited_"), labels = c("Assimilated carbon"))) %>%
  ggplot() +
  geom_area(aes(x = height, y = value, fill = name, col = name), linewidth = 0.5) + 
  theme_classic()  +
  facet_wrap(~trait_value) +
  labs(x = "Height", fill = "Budget", col = "Budget", y = expression(paste(Dry~mass~carbon, " (kg"~yr^{-1},")"))) +
  geom_text(data = output_mutated %>% distinct(trait_value), aes(x = 10, y = 150, label = paste('SA:LA = ',trait_value)), size = 8)+
  theme(strip.text = element_blank(), text = element_text(size = 25)) +
  scale_color_manual(values= wes_palette("Cavalcanti1", n = 4)) +
  scale_fill_manual(values= wes_palette("Cavalcanti1", n = 4)) -> c




png("examples_vignettes/outputs/ESA_2022/dry_mass_carbon_partioned_carbon_only_height.png", height = 1000, width = 2000, res = 150)
c
dev.off()


output_mutated %>% 
  select(maintenance_sapwood, leftover_after_sapwood_only, height, trait_value) %>%
  pivot_longer(-c(height,trait_value))%>%
  ggplot(aes(x = height, y = value, fill = name, col = name)) +
  geom_area() + 
  theme_classic() +
  facet_wrap(~trait_value) +
  labs(x = "Height", fill = "Budget", col = "Budget", y = expression(paste(Dry~mass~carbon, " (kg"~yr^{-1},")")))

  x^2 -1 = 0
  tibble(trait = c(seq(-1, 1, length.out = 100), seq(-1, 1, length.out = 100)), environment = c(rep("A",100), rep("B",100))) %>%
    mutate(y = ifelse(environment == "A", -trait^2 + 1, -trait^2 + 1)) %>%
    mutate(trait = ifelse(environment == "A", trait, trait+ 1)) %>%
    filter(environment == "A") %>%
    ggplot(aes(x= trait, y= y, col = environment, group = environment)) +
    geom_line(linewidth = 2) +
    ylab(expression(paste("Individual growth rate (", m~yr^{-1},")"))) +
    xlab("Trait")+
    theme_classic()+
    labs(col = "Environment") + 
    theme(text = element_text(size = 16))-> null_ploot
  
  tibble(trait = c(seq(-1, 1, length.out = 100), seq(-1, 1, length.out = 100)), environment = c(rep("A",100), rep("B",100))) %>%
    mutate(y = ifelse(environment == "A", -trait^2 + 1, -trait^2 + 1)) %>%
    mutate(trait = ifelse(environment == "A", trait, trait+ 1)) %>%
    # filter(environment == "A") %>%
    ggplot(aes(x= trait, y= y, col = environment, group = environment)) +
    geom_line(linewidth = 2) +
    ylab(expression(paste("Fitness"))) +
    xlab("Trait")+
    theme_classic()+
    labs(col = "Environment") + 
    theme(text = element_text(size = 16))-> null_ploot

  png("examples_vignettes/outputs/ESA_2022/null_ploot_two_fitness.png", res = 300, height = 1100, width = 1500)
  null_ploot
  dev.off()
      
  
tibble(x = seq(0,5,length.out =5), y =seq(-1,4,length.out =5)) %>%
    ggplot() +
      geom_line(aes(x = x, y = y), linewidth = 2) +
    ylab(expression(paste("Optimum trait"))) +
    xlab("Environment")+
    theme_classic()+
    labs(col = "Environment") + 
    theme(text = element_text(size = 16), axis.text.x = element_blank())-> null_ploot
  png("examples_vignettes/outputs/ESA_2022/null_ploot_two_fitness.png", res = 300, height = 1000, width = 1200)
  null_ploot
  dev.off()
  
  
  tibble(trait = c(seq(-1, 1, length.out = 100), seq(-1, 1, length.out = 100), seq(-1, 1, length.out = 100)), environment = c(rep("A",100), rep("B",100), rep("C",100))) %>%
    mutate(y = ifelse(environment == "A", -trait^2 + 1, -trait^2 + 1)) %>%
    mutate(trait = ifelse(environment == "A", trait, trait+ 0.5)) %>%
    mutate(trait = ifelse(environment %in% c("A","B"), trait, trait+ 0.5)) %>%
    mutate(environment = factor(environment, levels= c("C","B","A"), labels = c("C","B","A"))) %>%
    ggplot() +
    geom_line(aes(x= trait, y= y, alpha = environment, group = environment), linewidth = 2) +
    geom_point(aes(x = c(0), y=c(1)), size =4) +
    geom_point(aes(x = c(0.5), y=c(1)), size =4, alpha = 0.6) +
    geom_point(aes(x = c(1), y=c(1)), size =4, alpha = 0.2) +
    ylab(expression(paste("Indidual growth rate (", m~yr^{-1},")"))) +
    xlab("Trait")+
    theme_classic()+
    labs(col = "Environment") + 
    theme(text = element_text(size = 16), legend.position = "none")-> workflow_1
  

  png("examples_vignettes/outputs/ESA_2022/workflow_1.png", res = 300, height = 1000, width = 1200)
  workflow_1
  dev.off()  
  
  tibble(psi = seq(0,5)) %>%
    mutate(trait= psi-1) %>%
    mutate(environment = "A") %>%
    ggplot(aes(x = psi, y = trait)) +
    geom_line(aes(colour = environment), linewidth = 2) +
    geom_point(aes(x = 1, y = 0, colour = environment), size =4) +
    geom_point(aes(x = 2, y = 1, colour = environment), size =4) +
    geom_point(aes(x = 3, y = 2, colour = environment), size =4) +
    geom_point(aes(x = 4, y = 3, colour = environment), size =4) +
    geom_point(aes(x = 5, y = 4, colour = environment), size =4) +
    xlab(expression(paste(psi[soil]))) +
    ylab("Optimum trait") +
    theme_classic() +
    theme(text = element_text(size = 16), legend.position = "none") -> workflow_2
  
  
  png("examples_vignettes/outputs/ESA_2022/workflow_2.png", res = 300, height = 1000, width = 1200)
  workflow_2
  dev.off()  
  
  
  
  mutate(total_maintenance_no_sapwood = total_maintenance - total_maintenance_sapwood_mol_yr)
         total_maintenance = total_respiration + total_turnover + total_hydraulic_cost,
         total_maintenance_no_sapwood = total_maintenance - total_maintenance_sapwood_mol_yr) %>%
    mutate(total_assim_colimited_ = total_assim_colimited_ - total_hydraulic_cost)
  select(total_assim_colimited_, total_maintenance_no_sapwood, total_maintenance_sapwood_mol_yr, height, trait_value) %>%
  pivot_longer(-c(height,trait_value))%>%
  ggplot(aes(x = height, y = value, fill = name, col = name)) +
  geom_area() + 
  theme_classic() +
  facet_wrap(~trait_value)

  select(total_assim_colimited_, total_maintenance_sapwood_mol_yr, height, trait_value) %>%
  pivot_longer(-c(height,trait_value)) %>%
  ggplot(aes(x = height, y = value, fill = name, col = name)) +
  geom_area() + 
  theme_classic() +
  facet_wrap(~trait_value)


output_states %>%
  mutate(all_stem_costs = total_maintenance_sapwood_mol_yr + total_hydraulic_cost) %>%
  mutate(all_other_respiration_turnover = 
           all_stem_costs + 
           total_respiration_bark_mol_yr + total_turnover_bark_mol_yr +
           total_respiration_leaf_mol_yr + total_turnover_leaf_mol_yr +
           total_respiration_root_mol_yr + total_turnover_root_mol_yr) %>%
  select(total_assim_colimited_, total_maintenance_sapwood_mol_yr, height, trait_value) %>%
  mutate(sapwood_frac = total_maintenance_sapwood_mol_yr/total_assim_colimited_) %>%
  ggplot(aes(x = height,  y= sapwood_frac))+
  geom_line(aes(group = trait_value, colour = trait_value))
```

```{r}

trait_by_height <- function(...){

inputs <- tibble(...)

env <- FF16w_make_environment(vpd = inputs$vpd)
env$set_soil_water_state(env$soil_moist_from_psi(inputs$psi*1e06)) 
env$set_fixed_environment(inputs$E, 150)
  
p0 <- scm_base_parameters("FF16w")

f <- function(x){
s <- strategy(trait_matrix(exp(x),  inputs$trait_name), p0, birth_rate_list = 1)
s$hmat <- 50
indv <- FF16w_Individual(s)
res <- plant::grow_individual_to_height(indv, heights = inputs$height, env, time_max =100)
res <- res$rate[colnames(res$rate) == "height"]
if(is.na(res)){
res <-  0
}
return(res)
}
# 
# ret <- optim(par= log(0.000157), f, method="Brent",
#       control=list(fnscale=-1, trace = 1, ndeps=5), lower = log(1e-07), upper = log(0.1))
# tibble(trait = ret$par, growth = ret$value)

ret <- optim(par= log(1), f, method="Brent",
      control=list(fnscale=-1, trace = 1, ndeps=5), lower = log(1e-05), upper = log(10))
tibble(trait = ret$par, growth = ret$value)
}

```

```{r}
future::plan(multisession, workers = 8)
```

```{r}
expand_grid(trait_name = "theta", E = c(0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1), psi = seq(0.1,5,length.out =50), height = c(0.5,1,2,5,10), vpd = c(1)) %>%
  mutate(results = pmap(., trait_by_height)) -> outputs


expand_grid(trait_name = "K_s", E = c(0.2,0.4,0.6,0.8,1), psi = seq(0.1,5,length.out=25), height = c(0.5), vpd = c(1)) %>%
  mutate(results = pmap(., trait_by_height)) -> outputs

expand_grid(trait_name = "K_s", E = c(0.2,0.4,0.6,0.8,1), psi = seq(0.1,5,length.out =50), height = c(0.5,1,2,5,10), vpd = c(1)) %>%
  mutate(results = pmap(., trait_by_height)) -> outputs


expand_grid(trait_name = "K_s", E = seq(0.4,1,length.out = 20), psi = seq(0.1,5,length.out=25), height = c(0.5,1,2,5,10), vpd = c(1)) %>%
  mutate(results = future_pmap(., trait_by_height)) -> outputsKS

expand_grid(trait_name = "theta", E = seq(0.4,1,length.out = 20), psi = seq(0.1,5,length.out=25), height = c(0.5,1,2,5,10), vpd = c(1)) %>%
  mutate(results = future_pmap(., trait_by_height)) -> outputs


expand_grid(trait_name = "K_s", E = seq(0.4, 1,length.out = 4), psi = seq(0.1,5,length.out=100), height = c(1), vpd = c(1)) %>%
  mutate(results = pmap(., trait_by_height)) -> outputsKS


expand_grid(trait_name = "theta", E = seq(0.4, 1,length.out = 4), psi = seq(0.1,5,length.out=100), height = c(1), vpd = c(1)) %>%
  mutate(results = pmap(., trait_by_height)) -> outputstheta
```

```{r}

f<-function(x){
p0 <- scm_base_parameters("FF16w")

vcmax = 100;
c = 2.04;
K_s = x;
p_50 = 1.731347*(K_s/2)^-0.7246377
b = p_50 / (-log(1 - 50.0 / 100.0))^(1/ c)
psi_crit = b*(log(1/0.05)^(1/c))
epsilon_leaf = 0.001;
beta1 = 20000;
beta2 = 1.5;

leaf <- Leaf(vcmax, p_50, c, b, psi_crit, K_s,p0$strategy_default$epsilon_leaf, beta1, beta2)
k_l_max = K_s * p0$strategy_default$theta / 1
sapwood_volume_per_leaf_area = p0$strategy_default$theta * 1
leaf$set_physiology(1000, 0, k_l_max, 1, 40,sapwood_volume_per_leaf_area)
tibble(psi_stem = seq(0, psi_crit, length.out = 100))%>%
  rowwise() %>%
  mutate(prop_cond = leaf$proportion_of_conductivity(psi_stem))
}


f<-function(x){
p0 <- scm_base_parameters("FF16w")

vcmax = 100;
c = 2.04;
K_s = 5;
p_50 = 1.731347*(K_s/2)^-0.7246377
b = p_50 / (-log(1 - 50.0 / 100.0))^(1/ c)
psi_crit = b*(log(1/0.05)^(1/c))
epsilon_leaf = 0.001;
beta1 = 20000;
beta2 = 1.5;

leaf <- Leaf(vcmax, p_50, c, b, psi_crit, K_s,p0$strategy_default$epsilon_leaf, beta1, beta2)
k_l_max = K_s * p0$strategy_default$theta / 1
sapwood_volume_per_leaf_area = p0$strategy_default$theta * 1
leaf$set_physiology(1000, x, k_l_max, 1, 40,sapwood_volume_per_leaf_area)
leaf$set_leaf_states_rates_from_psi_stem(x + 1)
leaf$assim_colimited_
}
tibble(psi_soil = seq(0, 0.75, length.out =10)) %>%
  rowwise() %>%
  mutate(asd = f(psi_soil)) -> two


tibble(k_s = seq(2, 5, length.out = 2)) %>%
  mutate(prop_cond = map(k_s, f)) %>%
  unnest(prop_cond) %>%
  mutate(k_s = factor(k_s)) %>%
  mutate(psi_stem = -psi_stem) %>%
  ggplot(aes(x = psi_stem, y =prop_cond)) +
  geom_line(aes(colour = k_s, group = k_s), size = 1.5) +
  xlim(c(0,-5)) +
  ylab(expression(paste(Conductance, " (kg ",H[2]~O~m^{-2}~s^{-1}~MPa^{-1}, ")"))) +
  xlab(expression(paste(psi[leaf]))) + 
  theme_classic() +
  theme(text = element_text(size = 16)) +
  labs(colour = "Sapwood conductivity") -> output
  

tibble(k_s = seq(2, 5, length.out = 2)) %>%
  mutate(prop_cond = map(k_s, f)) %>%
  unnest(prop_cond) %>%
  mutate(prop_cond = 1 - prop_cond) %>%
  mutate(k_s = factor(k_s)) %>%
  mutate(psi_stem = -psi_stem) %>%
  ggplot(aes(x = psi_stem, y =prop_cond)) +
  geom_line(aes(colour = k_s, group = k_s), size = 1.5) +
  xlim(c(0,-5)) +
  ylim(c(0,1)) +
  ylab(expression(paste("% xylem damaged"))) +
  xlab(expression(paste(psi[leaf]))) + 
  theme_classic() +
  theme(text = element_text(size = 16)) +
  labs(colour = "Sapwood conductivity") -> output
  

png("examples_vignettes/outputs/ESA_2022/Sapwoodconductivity_nontransformed.png", height= 1000, width =1700, res = 200)
output
dev.off()


leaf$set_physiology()


outputs %>% 
  unnest(results) %>% 
  filter(growth !=0) %>% 
  mutate(trait = exp(trait)) %>% View()
  ggplot(aes(x = psi, y = trait, group = E, colour = E)) +
  geom_line()



env <- FF16w_make_environment(vpd = 1)
env$set_soil_water_state(env$soil_moist_from_psi(0.4*1e06)) 
env$set_fixed_environment(0.4, 150)

p0 <- scm_base_parameters("FF16w")

f <- function(x){
s <- strategy(trait_matrix(exp(x),  "theta"), p0, birth_rate_list = 1)
s$hmat <- 50
indv <- FF16w_Individual(s)
res <- plant::grow_individual_to_height(indv, heights = 5, env, time_max =100)
res <- res$rate[colnames(res$rate) == "height"]
if(is.na(res)){
res <-  0
}
return(res)
}

tibble(x= seq(log(1e-05), log(2e-04), length.out = 100)) %>%
  rowwise() %>%
  mutate(growth = f(x)) %>% View()

  ggplot(aes(x = exp(x), y = growth)) +
  geom_line()

1.731347*(10/2)^-0.7246377

outputs %>%
  filter(vpd == 1) %>%
  unnest(results) %>%
  filter(growth != 0) %>%
  mutate(trait = exp(trait)) %>%
  # filter(E == 0.6) %>%
  ggplot() +
  geom_line(aes(x= psi, y = trait, col = E, group = E)) +
  theme_classic() +
  theme(text = element_text(size = 16)) +
  labs(x = expression(paste(psi[soil], " (-MPa)")),
       col = "Canopy openness",
       y = expression(paste(K[s], " (kg ",m^{-1}~s^{-1}~MPa^{-1}, ")"))) +
  scale_y_log10()+
  scale_x_log10() +
  facet_wrap(~height) -> output


```


```{r}
outputs %>%
  unnest(results)

outputs %>%
  unnest(results) %>%
  mutate(trait = ifelse(is.na(growth), NA, trait)) %>% 
  mutate(trait = exp(trait)) %>%
  filter(growth != 0) %>%
  ggplot(aes(x = psi, y = height, fill = trait)) +
  geom_tile() +
  facet_grid(E~vpd) +
  scale_fill_continuous(trans = "log", 
                        label = function(x) sprintf("%.5f", x)) +
  ylab("Height (m)") +
  xlab(expression(paste(psi[soil]," (",-MPa,")"))) +
  labs(fill = "SA:LA") +
  theme(text = element_text(size = 12))-> d
  
png("examples_vignettes/outputs/ESA_2022/huber_value_environment.png", height = 2000, width= 2000, res = 300)
d
dev.off()

  outputs %>%
  unnest(results) %>%
  mutate(trait = ifelse(is.na(growth), NA, trait)) %>% 
  mutate(trait = exp(trait)) %>%
  filter(growth != 0)  %>%
  ggplot(aes(x = vpd, y = trait)) +
  geom_point()



outputs %>%
  unnest(results) %>%
  mutate(trait = ifelse(is.na(growth), NA, trait)) %>% 
  mutate(trait = exp(trait)) %>%
  filter(growth != 0)  %>%
  ggplot(aes(x = E, y = trait)) +
  geom_point()


outputs %>%
  unnest(results) %>%
  mutate(trait = ifelse(is.na(growth), NA, trait)) %>% 
  mutate(trait = exp(trait)) %>%
  filter(growth != 0)  %>%
  ggplot(aes(x = psi, y = trait)) +
  geom_line(aes(group = interaction(vpd, E, height)))
  
```

```{r}

trait_by_height <- function(...){
inputs <- tibble(...)

env <- FF16w_make_environment(vpd = inputs$vpd)
env$set_soil_water_state(env$soil_moist_from_psi(inputs$psi*1e06)) 
env$set_fixed_environment(inputs$E, 150)
  
p0 <- scm_base_parameters("FF16w")

s <- strategy(trait_matrix((inputs$x),  inputs$trait_name), p0, birth_rate_list = 1)
s$hmat <- 50
indv <- FF16w_Individual(s)
res <- plant::grow_individual_to_height(indv, heights = inputs$height, env, time_max =100)
res <- res$rate[colnames(res$rate) == "height"]
# if(is.na(res)){
# res <-  0
# }
}



expand_grid(trait_name = "K_s", E = seq(0.4, 1,length.out = 4), psi = seq(0.1,5,length.out=5), height = c(1), vpd = c(1), x = (1)) %>%
  mutate(results = pmap(., trait_by_height)) -> outputsKS_no_variation

outputsKS_no_variation %>%
  filter(height == 1) %>%
  filter(vpd == 1) %>%
  unnest(results) %>%
  filter(!is.na(results)) %>%
  mutate(x = exp(x)) %>% 
  mutate(psi = -psi) %>%
  ggplot() +
  geom_line(aes(x= psi, y = results, col = E, group = E)) +
  theme_classic() +
  theme(text = element_text(size = 16)) +
  theme(legend.position = "none") +
  labs(x = expression(paste(psi[soil], " (-MPa)")),
       col = "Canopy openness",
       y = expression(paste("Maximum height growth rate (",m~yr^{-1},")")))












outputstheta %>%
  filter(height == 1) %>%
  # filter(E == 1) %>%
  filter(vpd == 1) %>%
  unnest(results) %>%
  filter(growth != 0) %>%
  mutate(trait = exp(trait)) %>%
  mutate(psi = -psi) %>%
  ggplot() +
  geom_line(aes(x= psi, y = trait, col = E, group = E)) +
  geom_point(aes(x= psi, y = trait, col = E, group = E)) +
  scale_y_log10() +
  theme_classic() +
theme(text = element_text(size = 16)) +
  # theme(legend.position = "none") +
  labs(x = expression(paste(psi[soil], " (-MPa)")),
       col = "Canopy openness",
       y = expression(paste("Optimum SA:LA")))-> output

outputsKS %>%
  filter(height == 1) %>%
  filter(vpd == 1) %>%
  unnest(results) %>%
  filter(growth != 0) %>%
  mutate(trait = exp(trait)) %>% 
  mutate(psi = -psi) %>%
  ggplot() +
  geom_line(aes(x= psi, y = growth, col = E, group = E)) +
  theme_classic() +
  theme(text = element_text(size = 16)) +
  theme(legend.position = "none") +
  labs(x = expression(paste(psi[soil], " (-MPa)")),
       col = "Canopy openness",
       y = expression(paste("Maximum height growth rate (",m~yr^{-1},")")))

outputstheta %>%
  filter(height == 1) %>%
  filter(vpd == 1) %>%
  unnest(results) %>%
  filter(growth != 0) %>%
  mutate(trait = exp(trait)) %>% 
  mutate(psi = -psi) %>%
  ggplot() +
  geom_line(aes(x= psi, y = trait, col = E, group = E)) +
  theme_classic() +
  theme(text = element_text(size = 16)) +
  theme(legend.position = "none") +
  labs(x = expression(paste(psi[soil], " (-MPa)")),
       col = "Canopy openness",
       y = expression(paste("Optimum SA:LA"))) +
  scale_y_log10()+
  facet_wrap(~height) -> output

png("examples_vignettes/outputs/ESA_2022/SA_LA_psi_single.png", height= 1000, width =1600, res = 200)
output
dev.off()


png("examples_vignettes/outputs/ESA_2022/SA_LA_psi_multiple.png", height= 1000, width =2000, res = 180)
output
dev.off()


outputsKS %>%
  # filter(height == 1) %>%
  # filter(E == 1) %>%
  filter(vpd == 1) %>%
  unnest(results) %>%
  filter(growth != 0) %>%
  mutate(trait = exp(trait)) %>%
  mutate(psi = -psi) %>%
  ggplot() +
  geom_line(aes(x= psi, y = trait, col = E, group = E)) +
  geom_point(aes(x= psi, y = trait, col = E, group = E)) +
  scale_y_log10() +
  # scale_x_log10() +
  theme_classic() +
  theme(text = element_text(size = 14)) +
  # theme(legend.position = "none") +
  labs(x = expression(paste(psi[soil], " (MPa)")),
       col = "Canopy openness",
       y = expression(paste(Optimum~sapwood~conductivity, " (kg ",m^{-1}~s^{-1}~MPa^{-1}, ")")))-> output



outputsKS %>%
  # filter(height == 1) %>%
  # filter(E == 1) %>%
  filter(vpd == 1) %>%
  unnest(results) %>%
  filter(growth != 0) %>%
  mutate(trait = exp(trait)) %>%
  filter(E %in% c(0.4,1)) %>%
  group_by(trait_name, psi, height, vpd) %>%
  mutate(diff = diff(trait)) %>%
  ggplot(aes(x=psi, y = diff)) +
  geom_line()



png("examples_vignettes/outputs/ESA_2022/K_s_psi_single.png", height= 1000, width =1600, res = 200)
output
dev.off()-> output


png("examples_vignettes/outputs/ESA_2022/K_s_psi_multiple.png", height= 1000, width =2000, res = 180)
output
dev.off()

```


