---
title: "ensemble_runner"
author: "Isaac Towers"
date: "2023-02-22"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(plant)
```

#Make parameters function

```{r}
p0 <- FF16w_Parameters()


make_parameters <- function(p0 = FF16w_Parameters(),
                            lma = p0$strategy_default$lma,
                            rho = p0$strategy_default$rho,
                            hmat = p0$strategy_default$hmat,
                            omega = p0$strategy_default$omega,
                            theta = p0$strategy_default$theta,
                            a_l1 = p0$strategy_default$a_l1,
                            a_l2 = p0$strategy_default$a_l2,
                            a_r1 = p0$strategy_default$a_r1,
                            a_b1 = p0$strategy_default$a_b1,
                            r_r = p0$strategy_default$r_r,
                            a_y = p0$strategy_default$a_y,
                            a_bio = p0$strategy_default$a_bio,
                            k_b = p0$strategy_default$k_b,
                            k_r = p0$strategy_default$k_r,
                            a_p1 = p0$strategy_default$a_p1,
                            a_p2 = p0$strategy_default$a_p2,
                            a_f1 = p0$strategy_default$a_f1,
                            a_f2 = p0$strategy_default$a_f2,
                            S_D = p0$strategy_default$S_D,
                            a_d0 = p0$strategy_default$a_d0,
                            a_dG1 = p0$strategy_default$a_dG1,
                            k_I = p0$strategy_default$k_I,
                            vcmax = p0$strategy_default$vcmax,
                            K_s = p0$strategy_default$K_s,
                            c = p0$strategy_default$c,
                            beta1 = p0$strategy_default$beta1,
                            beta2 = p0$strategy_default$beta2){
  params <- tibble(lma = lma,
                            rho = rho,
                            hmat = hmat,
                            omega = omega,
                            theta = theta,
                            a_l1 = a_l1,
                            a_l2 = a_l2,
                            a_r1 = a_r1,
                            a_b1 = a_b1,
                            r_r = r_r,
                            a_y = a_y,
                            a_bio = a_bio,
                            k_b = k_b,
                            k_r = k_r,
                            a_p1 = a_p1,
                            a_p2 = a_p2,
                            a_f1 = a_f1,
                            a_f2 = a_f2,
                            S_D = S_D,
                            a_d0 = a_d0,
                            a_dG1 = a_dG1,
                            k_I = k_I,
                            vcmax = vcmax,
                            K_s = K_s,
                            c = c,
                            beta1 = beta1,
                            beta2 = beta2)
}
```

```{r}
hyperpar_fn <- make_FF16w_hyperpar(B_ks2 = 1)
```


```{r}
trait_data <- expand_grid() %>%
  mutate(param_set = seq(1:n())) %>%
  group_by(param_set) %>%
  nest(trait_data = -param_set) %>% 
  mutate(expanded_trait_data = map(trait_data, ~ .x %>%unlist() %>% as.list())) %>%
  mutate(expanded_trait_data = map(trait_data, ~do.call(make_parameters, .x))) %>%
  unnest(expanded_trait_data)
```


```{r}
trait_data %>%
  pivot_longer(cols = c(-param_set, -trait_data)) %>%
  nest(expanded_trait_data = c(-param_set, -trait_data)) %>%
  mutate(trait_matrix = map(expanded_trait_data, ~trait_matrix(.x$value, .x$name))) %>%
  mutate(strategy_type = "FF16w") %>%
  mutate(p0 = map(strategy_type, ~scm_base_parameters(.x))) %>%
  mutate(p1 = map2(.x = trait_matrix, .y = p0, ~expand_parameters(.x, .y, hyperpar = hyperpar_fn, birth_rate_list = 2)))-> trait_data
```

```{r}
trait_data %>%
  mutate(env = map(strategy_type, ~make_environment(.x))) %>%
  expand_grid(soil_moist = seq(0.1,1,0.1)) -> trait_data_environment
```
