---
title: "growth_rate_trait_water"
output: html_document
date: "2022-10-24"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
rm(list=ls())

devtools::load_all(".")
library(tidyverse)
```

Define a number of hyper-parameterisations

```{r}
get_dt <- function(y,x) {
  c(NA, diff(y)/diff(x))
}
```

```{r}
height_names <- c(
  "0.5" = expression(paste("H = 0.5m")),
  "2" = expression(paste("H = 2m")),
  "10" = expression(paste("H = 10m")),
  "15" = expression(paste("H = 15m"))
)

psi_names <- c(
  "0.08" = expression(paste(psi[soil], " = ", 1.59, " (-MPa)", sep = "")),
  "0.09" = expression(paste(psi[soil], " = ", 0.91, " (-MPa)", sep = "")),
  "0.1" = expression(paste(psi[soil], " = ", 0.55, " (-MPa)", sep = "")),
  "0.2" = expression(paste(psi[soil], " = ", 0.02, " (-MPa)", sep = ""))
)
```


```{r}
p_50_2_K_s <- function(p50){
  1.638999*(p50/2)^(-1.38)
}

narea_lma_2_vcmax <- function(narea, lma){
(narea - 0.535 - .009*lma)/0.007
  }
```


```{r}
run_individual <- function(...){
  params <- tibble(...) %>% 
    unnest(data)
  p0 <- scm_base_parameters("FF16w")
  
  s1 <- strategy(trait_matrix(params$value,  params$name), p0, birth_rate_list = 1)
  s1$hmat <- 50

  indv1 <- FF16w_Individual(s1)
  
  params %>%
    group_by(taxon_name, E, psi, height) %>%
    nest() %>%
    ungroup() -> params 
  
  env <- FF16w_make_environment()
  env$set_soil_water_state(env$soil_moist_from_psi(params$psi*1e06)) 
  env$set_fixed_environment(params$E, 150)

  res <- plant::grow_individual_to_height(indv1, heights = params$height, env, time_max =100)
    }
```

```{r}
library(tidyverse)
austraits <- readRDS("examples_vignettes/data/austraits_develop_recent.rds")
austraits$traits %>%
  filter(grepl("Eucalyptus", taxon_name)) %>%
  drop_na(value, trait_name, taxon_name) %>%
  mutate(value = as.numeric(value)) %>%
  group_by(taxon_name, trait_name) %>%
  summarise(value = mean(value, na.rm = T)) %>%
  ungroup() %>% 
  filter(taxon_name %in% c("Eucalyptus blakelyi",
                           "Eucalyptus camaldulensis",
                           "Eucalyptus crebra",
                           "Eucalyptus dunnii",
                           "Eucalyptus globulus",
                           "Eucalyptus grandis",
                           "Eucalyptus largiflorens",
                           "Eucalyptus macrorhyncha",
                           "Eucalyptus melliodora",
                           "Eucalyptus obliqua",
                           "Eucalyptus populnea",
                           "Eucalyptus saligna",
                           "Eucalyptus sideroxylon",
                           "Eucalyptus tereticornis",
                           "Eucalyptus viminalis")) %>% 
  filter(trait_name %in% c("huber_value",
                           "leaf_N_per_dry_mass",
                           "leaf_N_per_area",
                           "seed_mass",
                           "specific_leaf_area",
                           "wood_density"
  )) %>%
  pivot_wider(names_from = trait_name, values_from = value) %>%
  mutate(leaf_N_per_area = if_else(is.na(leaf_N_per_area), leaf_N_per_dry_mass/specific_leaf_area, leaf_N_per_area)) %>%
  select(-leaf_N_per_dry_mass) %>%
  drop_na() %>%
  mutate(p_50 = c(4.90, 4.01, 5.64),
         b = c(5.52, 4.40, 6.41),
         c = c(3.08, 3.95, 2.86)) %>%
  mutate(K_s = map_dbl(p_50, p_50_2_K_s)) %>%
  mutate(vcmax = map2_dbl(.x = leaf_N_per_area, .y = 1/(specific_leaf_area*1000), narea_lma_2_vcmax))-> eucalypt_data
```

```{r}
eucalypt_data %>%
  mutate(lma = 1/specific_leaf_area) %>%
  select(-p_50, - b, -leaf_N_per_area, -specific_leaf_area) %>%
  rename(rho = wood_density,
         theta = huber_value) %>%
  pivot_longer(cols = -(taxon_name)) %>% 
  group_by(taxon_name) %>%
  nest() %>%
  ungroup() %>%
  expand_grid(E = c(0.1, 0.25, 0.5, 1), psi = seq(0.1, 10, length.out = 15), height = c(0.5, 2, 5, 10)) %>%
  mutate(growth = pmap(., run_individual)) -> growth_rates
```

```{r}
growth_rates %>%
  mutate(run = seq(1:nrow(.))) %>%
  rename(to_height = height) %>%
  mutate(rate= map(growth, ~pluck(.x, "rate")%>% as_tibble())) %>%
  unnest(rate) %>%
  ggplot(aes(x = psi, y= height)) +
  geom_line(aes(group = taxon_name, colour = taxon_name)) + 
  facet_grid(to_height~E) +
  theme_classic()
```






```{r}
env <- FF16w_make_environment()

env$calc_psi(0.08)
env$calc_psi(0.2)

expand_grid(theta=c(0.0772, 0.0773, 0.0774, 0.0775, 0.08,0.09,0.1,0.2), E=c(0.5,1), height = c(0.5), trait = "vcmax", trait_value = seq(30,100,10)) %>%
  mutate(results= pmap(., run_individual)) -> N_area_output
  s1 <- strategy(trait_matrix(c(1,1), c("lma","hmat")), p0, birth_rate_list = 1)

  

  env <- FF16w_make_environment(soil_initial_state = 0.1)
  env$set_fixed_environment(1, 150)

    
  p0 <- scm_base_parameters("FF16w")
  s1 <- strategy(trait_matrix(0.09, "lma"), p0, birth_rate_list = 1)
  indv1 <- FF16w_Individual(s1)  
  
  indv1$state("height")
  
#beers law for light extinction not yet included
#growth rate at minimum 
resource_compensation_individual <- function(indivdual, env, size_name){
  
  f <- function(x, indivdual, env, size_name){
    indivdual$set_state(size_name, x)
    return(indivdual$net_mass_production_dt(env))
  }
  
  min_size <- indivdual$state(size_name)
  indivdual$set_state(size_name, min_size)
  
  if(indivdual$net_mass_production_dt(env) < 0){
  return(NA_real_)
  } else{
  uniroot(f = f,interval = c(min_size,150),indivdual, env, size_name, extendInt = 'no', tol = 1e-8)$root
  }
  }    

calculate_resource_compensation_point <- function(size_name = "height", ...){
  data <- tibble(...)
  
  env <- FF16w_make_environment()
  env$set_soil_water_state(env$soil_moist_from_psi(data$psi*1e06)) 
  env$set_fixed_environment(data$E, 150)
  
  p0 <- scm_base_parameters("FF16w")
  s1 <- strategy(trait_matrix(data$trait_value, data$trait_name), p0, birth_rate_list = 1)
  individual <- FF16w_Individual(s1)  
  
  resource_compensation_individual(individual, env, size_name)
}


expand_grid(psi = seq(0,5,length.out = 20), E = seq(0,1,length.out = 20), trait_name = "vcmax", trait_value = seq(30, 100, 10)) %>%
  mutate(rcp = pmap_dbl(., calculate_resource_compensation_point)) -> output
  

output %>%
  ggplot +
  geom_tile(aes(x = psi, y = E, fill = rcp)) +
  facet_wrap(~trait_value) +
  theme_classic() +
  labs(y = "Canopy openness", x = "Soil moisture", fill = "Height at WPRCP") +
  theme(text = element_text(size = 15))

expand_grid(psi = seq(0,5,length.out = 20), E = seq(0,1,length.out = 20), trait_name = "lma", trait_value = seq(0.05, 0.5, length.out = 6)) %>%
  mutate(rcp = pmap_dbl(., calculate_resource_compensation_point)) -> output
  

output %>%
  ggplot +
  geom_tile(aes(x = psi, y = E, fill = rcp)) +
  facet_wrap(~trait_value) +
  theme_classic() +
  labs(y = "Canopy openness", x = "Soil moisture", fill = "Height at WPRCP") +
  theme(text = element_text(size = 15))
```

```{r}
run_individual <- function(...){
  params <- tibble(...)
  p0 <- scm_base_parameters("FF16w")
  
  s1 <- strategy(trait_matrix(params$trait_value,  params$trait), p0, birth_rate_list = 1)
  s1$hmat <- 50

  indv1 <- FF16w_Individual(s1)
  env <- FF16w_make_environment()
  env <- FF16w_make_environment(soil_initial_state = env$soil_moist_from_psi(params$psi*1e06))
  env$set_fixed_environment(params$E, 150)
  res <- plant::grow_individual_to_height(indv1, heights = params$height, env, time_max =100)
    }
```


```{r}
root_strategy <- function(x){
  expand_grid(psi = 1, E= 0.5, height = 2, trait_value = x, trait = "vcmax") %>%
  mutate(results= pmap(., run_individual)) %>%
  mutate(rate= map(results, ~pluck(.x, "rate")%>% as_tibble() %>% select(height))) %>%
  rename(to_height = height) %>%
  unnest(rate) %>% pull(height)
}


tibble(x = seq(50, 300, 1)) %>%
  rowwise() %>%
  mutate(height_growth = root_strategy(x)) -> data

data %>%
  ggplot(aes(x = x, y = height_growth)) +
  geom_line()


suniroot(root_strategy, interval = c(300, 301), extendInt = "yes", trace = 1)
```


```{r}
expand_grid(psi = seq(0, 5, 1), E=c(0.25,0.5,0.75,1), height = c(0.5, 2, 10, 15,20), trait_value = seq(30,200,10), trait = "vcmax") %>%
  mutate(results= pmap(., run_individual)) -> leaf_mass_area_output

leaf_mass_area_output %>%
  mutate(run = seq(1:nrow(.))) %>%
  rename(to_height = height) %>%
  mutate(rate= map(results, ~pluck(.x, "rate")%>% as_tibble())) %>%
  unnest(rate) -> data_to_plot

data_to_plot%>%
  drop_na(height) %>%
  mutate_at(.vars = "to_height", .funs = factor) %>%
  mutate_at(.vars = "psi", .funs = factor) %>%
  ggplot(aes(x= trait_value, y = height)) +
  geom_line(aes(group = E, colour = E))+
  # scale_x_log10() +
  # facet_grid(to_height~theta, labeller = label_parsed) +
  facet_grid(to_height~psi) +
  ylab(expression(paste(Delta~Height," /", Delta~Time, "(m/yr)"))) + 
  xlab(expression(paste(V[{cmax25}], " (", mu,"mol ",m^2~s^{-1},")"))) +
  # theme_classic() +
  theme(text = element_text(size = 18))-> a

```


```{r}
N_area_output %>%
  mutate(run = seq(1:nrow(.))) %>%
  rename(to_height = height) %>%
  mutate(rate= map(results, ~pluck(.x, "rate")%>% as_tibble())) %>%
  unnest(rate) -> data_to_plot
```

```{r}
data_to_plot %>%
  drop_na(height) %>%
  mutate_at(.vars = "to_height", .funs = factor) %>%
  mutate_at(.vars = "theta", .funs = factor) %>%
  ggplot(aes(x= trait_value, y = height)) +
  geom_line(aes(group = E, colour = E)) +
  # scale_x_log10() +
  # facet_grid(to_height~theta, labeller = label_parsed) +
  facet_grid(to_height~theta) +
  ylab(expression(paste(Delta~Height," /", Delta~Time, "(m/yr)"))) + 
  xlab(expression(paste(Sapwood~specific~conducitivity~(kg~m^{-1}~s^{-1}~MPa^{-1})))) +
  # theme_classic() +
  theme(text = element_text(size = 18))-> a
```





```{r}
%>%
  mutate(run = seq(1:nrow(.))) %>%
  rename(target_height = height) %>%
  mutate(rate = map(results, ~pluck(.x$"rate")%>% as_tibble())) %>% 
  unnest(rate) %>%
  drop_na(height) %>%
  select(-height, -mortality, -fecundity, -area_heartwood, -mass_heartwood) %>%
  filter(target_height == 15) %>%
  filter(run %in% c(1114, 1594)) %>%
  mutate(trajectory = map(results, ~pluck(.x$"trajectory")%>% as_tibble())) %>%
  unnest(trajectory) %>%
  mutate(cost_ = assim_colimited_ - profit_) -> plot_data
```



```{r}
K_s_output%>%
  mutate(run = seq(1:nrow(.))) %>%
  rename(target_height = height) %>%
  mutate(rate = map(results, ~pluck(.x$"rate")%>% as_tibble())) %>% 
  unnest(rate) %>%
  drop_na(height) %>%
  select(-height, -mortality, -fecundity, -area_heartwood, -mass_heartwood) %>%
  filter(target_height == 15) %>%
  filter(run %in% c(1114, 1594)) %>%
  mutate(trajectory = map(results, ~pluck(.x$"trajectory")%>% as_tibble())) %>%
  unnest(trajectory) %>%
  mutate(cost_ = assim_colimited_ - profit_) -> plot_data

plot_data %>%
  mutate(K_s = as_factor(round(K_s, 2))) %>%
  ggplot(aes(x = time, y = height)) +
  geom_line(aes(linetype = K_s, group = K_s)) +
  theme_classic() +
  theme_classic() + 
  xlab("Time (yr)") +
  ylab(expression(paste(Height, " (m)"))) +
  theme(text = element_text(size = 18))+
  scale_linetype_discrete(name = expression(paste(K[s], " (kg ", m^{-2}~s^{-1}~MPa^{-1}, ")"))) -> a

economic_names <- c(
  "assim_colimited_" = "Assimilation",
  "cost_" = "Xylem cost",
  "profit_" = "Profit"
)

plot_data %>%
  select(K_s, time, profit_, cost_, assim_colimited_) %>%
  pivot_longer(-c(time, K_s)) %>%
  mutate(K_s = as_factor(round(K_s, 2))) %>%
  mutate_at(.vars = "name", .funs = factor, label=economic_names) %>%
  ggplot(aes(x = time, y = value)) +
  geom_line(aes(group = interaction(name, K_s), linetype = K_s, colour = name)) +
  theme_classic() + 
  xlab("Time (yr)") +
  ylab(expression(paste(Economic~unit, " (",mu, "mol ",m^{-2}~s^{-1},")"))) +
  theme(text = element_text(size = 18)) +
  scale_color_discrete(name = NULL) +
  scale_linetype_discrete(name = expression(paste(K[s], " (kg ", m^{-2}~s^{-1}~MPa^{-1}, ")"))) -> b


plot_data %>%
  mutate(K_s = as_factor(round(K_s, 2))) %>%
  ggplot(aes(x = time, y = opt_psi_stem_)) +
  geom_line(aes(linetype = K_s)) +
  theme_classic() +
  xlab("Time (yr)") +
  ylab(expression(paste(psi[opt], " (-MPa)"))) +
  theme(text = element_text(size = 18)) +
  expand_limits(y = 0) +
  geom_hline(aes(yintercept = 0.02), linetype = "dashed") +
  annotate(geom = "text", x = 17.5, y = 0.04, label = expression(paste(psi[soil])), size = 6) +
  scale_linetype_discrete(name = expression(paste(K[s], " (kg ", m^{-2}~s^{-1}~MPa^{-1}, ")"))) ->c

png("examples_vignettes/outputs/trait_growth_water/example_of_profitmax.png", height = 1000, width = 600, res = 100)
cowplot::plot_grid(a,b,c, nrow =3)
dev.off()



K_s_output%>%
  mutate(run = seq(1:nrow(.))) %>%
  rename(target_height = height) %>%
  mutate(rate = map(results, ~pluck(.x$"rate")%>% as_tibble())) %>% 
  unnest(rate) %>%
  drop_na(height) %>%
  select(-height, -mortality, -fecundity, -area_heartwood, -mass_heartwood) %>%
  filter(target_height == 15) %>%
  filter(run %in% c(1114)) %>%
  mutate(trajectory = map(results, ~pluck(.x$"trajectory")%>% as_tibble())) %>%
  unnest(trajectory) %>%
  mutate(cost_ = assim_colimited_ - profit_) -> plot_data

plot_data %>%
  ggplot(aes(x = time, y = height)) +
  geom_line() +
  theme_classic() +
  theme_classic() + 
  xlab("Time (yr)") +
  ylab(expression(paste(Height, " (m)"))) +
  theme(text = element_text(size = 20)) -> a

economic_names <- c(
  "assim_colimited_" = "Assimilation",
  "cost_" = "Xylem cost",
  "profit_" = "Profit"
)

plot_data %>%
  select(time, profit_, cost_, assim_colimited_) %>%
  pivot_longer(-c(time)) %>%
  mutate_at(.vars = "name", .funs = factor, label=economic_names) %>%
  ggplot(aes(x = time, y = value)) +
  geom_line(aes(colour = name)) +
  theme_classic() + 
  xlab("Time (yr)") +
  ylab(expression(paste(Economic~unit, " (",mu, "mol ",m^{-2}~s^{-1},")"))) +
  theme(text = element_text(size = 20)) +
  scale_color_discrete(name = NULL)  -> b


plot_data %>%
  mutate(K_s = as_factor(round(K_s, 2))) %>%
  ggplot(aes(x = time, y = opt_psi_stem_)) +
  geom_line() +
  theme_classic() +
  xlab("Time (yr)") +
  ylab(expression(paste(psi[opt], " (-MPa)"))) +
  theme(text = element_text(size = 20)) +
  expand_limits(y = 0) +
  geom_hline(aes(yintercept = 0.02), linetype = "dashed") +
  annotate(geom = "text", x = 14, y = 0.06, label = expression(paste(psi[soil])), size = 8) ->c

png("examples_vignettes/outputs/trait_growth_water/example_of_profitmax_one_species.png", height = 1000, width = 1300, res = 100)
cowplot::plot_grid(a,b,c)
dev.off()


```


```{r}
K_s_output %>%
  mutate(run = seq(1:nrow(.))) %>%
  rename(to_height = height) %>%
  mutate(rate= map(results, ~pluck(.x, "rate")%>% as_tibble())) %>%
  unnest(rate) -> data_to_plot
```

```{r}
data_to_plot %>%
  drop_na(height) %>%
  mutate_at(.vars = "to_height", .funs = factor, label=height_names) %>%
  mutate_at(.vars = "theta", .funs = factor, label=psi_names) %>%
  ggplot(aes(x= K_s, y = height)) +
  geom_line(aes(group = E, colour = E)) +
  scale_x_log10() +
  facet_grid(to_height~theta, labeller = label_parsed) +
  ylab(expression(paste(Delta~Height," /", Delta~Time, "(m/yr)"))) + 
  xlab(expression(paste(Sapwood~specific~conducitivity~(kg~m^{-1}~s^{-1}~MPa^{-1})))) +
  theme_classic() +
  theme(text = element_text(size = 18))-> a
```

```{r}
expand_grid(K_s = 2,theta=c(0.08,0.09,0.1,0.2), E=c(0.25,0.5,0.75,1), height = c(0.5, 2, 10, 15,20), huber_value = 0.000157, lma= seq(0.01, 1, length.out = 20)) %>%
  mutate(results= pmap(., run_individual)) -> leaf_mass_area_output

leaf_mass_area_output %>%
  mutate(run = seq(1:nrow(.))) %>%
  rename(to_height = height) %>%
  mutate(rate= map(results, ~pluck(.x, "rate")%>% as_tibble())) %>%
  unnest(rate) -> data_to_plot


data_to_plot %>%
  drop_na(height) %>%
  mutate_at(.vars = "to_height", .funs = factor, label=height_names) %>%
  mutate_at(.vars = "theta", .funs = factor, label=psi_names) %>%
  ggplot(aes(x= lma, y = height)) +
  geom_line(aes(group = E, colour = E)) +
  scale_x_log10() +
  facet_grid(to_height~theta, labeller = label_parsed) +
  ylab(expression(paste(Delta~Height," /", Delta~Time, "(m/yr)"))) + 
  xlab(expression(paste(paste(Leaf~mass~per~area~(kg~m^{-2}~leaf~area))))) +
  theme_classic() +
  theme(text = element_text(size = 18))-> b
  
```


```{r}
expand_grid(K_s = 2, theta=c(0.07,0.075,0.1,0.2), E=c(0.25,0.5,0.75,1), height = c(0.5, 2, 10, 15,20), huber_value = seq(0.000157/5,0.000157*5, length.out = 20), lma= 0.1978791) %>%
  mutate(results= pmap(., run_individual)) -> Hv_output

Hv_output %>%
  mutate(run = seq(1:nrow(.))) %>%
  rename(to_height = height) %>%
  mutate(rate= map(results, ~pluck(.x, "rate")%>% as_tibble())) %>%
  unnest(rate) -> data_to_plot
```


```{r}

data_to_plot %>%
  drop_na(height) %>%
  mutate_at(.vars = "to_height", .funs = factor, label=height_names) %>%
  mutate_at(.vars = "theta", .funs = factor, label=psi_names) %>%
  ggplot(aes(x= huber_value, y = height)) +
  geom_line(aes(group = E, colour = E)) +
  scale_x_log10() +
  facet_grid(to_height~theta, labeller = label_parsed) +
  ylab(expression(paste(Delta~Height," /", Delta~Time, "(m/yr)"))) + 
  xlab(expression(paste(Huber~value~(m^{2}~sapwood~area~m^{-2}~leaf~area)))) +
  theme_classic() +
  theme(text = element_text(size = 18)) -> c

png("traits_growth_rate_soil_WP_canopy_openness_Ks.png", height = 1000, width = 1000, res = 100)
a
dev.off()

png("traits_growth_rate_soil_WP_canopy_openness_lma.png", height = 1000, width = 1000, res = 100)
b
dev.off()

png("traits_growth_rate_soil_WP_canopy_openness_HV.png", height = 1000, width = 1000, res = 100)
c
dev.off()


```

```{r}
K_s_output$results[[1]]$individual[[1]]$rate()
```


```{r}
set_leaf_states_rates_analytical <- function(psi_stem, psi_soil){
  leaf <- Leaf(vcmax= 100, p_50 = 2, c = 2.04, b = calc_vul_b(2, 2.04), psi_crit = calc_psi_crit(calc_vul_b(2, 2.04), 2.04), huber_value = 0.000157, K_s = 2, epsilon_leaf = 0.0001)
  
  PPFD = 1000
  atm_vpd = 2
  k_l_max = calc_k_l_max(K_s = 2, h_v = 0.000157, h =15)
  psi_soil = psi_soil 
  ca =40
  
  leaf$set_physiology(PPFD, psi_soil = psi_soil, k_l_max, atm_vpd, ca)
  
  leaf$set_leaf_states_rates_from_psi_stem_analytical(psi_stem)
  
  cost= leaf$hydraulic_cost_Sperry(psi_stem)
  
  tibble(Benefit = leaf$assim_colimited_, ci_ = leaf$ci_, E = leaf$transpiration_, gc = leaf$stom_cond_CO2_, lambda_ = leaf$lambda_, cost = cost)
  }
```


```{r}
library(tidyverse)

facet_names <- c(
  alim = expression(paste("A (", mu, "mol ", m^{-2}~s^{-1}, ")", sep ="")),
  ci_ = expression(C[i]~(Pa)),
  E = expression(ET~(kg~m^{-2}~s^{-1})),
  gc = expression(paste(G[c], " (", mol~H[2], "O", m^{-2}~s^{-1}, ")", sep = ""))
)
expand_grid(psi_stem = seq(0, calc_psi_crit(calc_vul_b(2, 2.04), 2.04), length.out=50), psi_soil = c(0,1)) %>%
  mutate(states_rates = map2(psi_stem, psi_soil, set_leaf_states_rates_analytical)) %>%
  unnest(states_rates) %>%
  filter(psi_stem >= psi_soil) %>%
  mutate(psi_soil = as_factor(psi_soil)) %>%
  select(-c(lambda_, cost)) %>%
  pivot_longer(-c(psi_stem, psi_soil)) %>%
  mutate_at(.vars = "name", .funs = factor, labels = facet_names) %>%
  ggplot(aes(x= psi_stem, y =value)) +
  geom_line(aes(colour = psi_soil, group = psi_soil)) +
  expand_limits(y = 0) +
  facet_wrap(~name, scales = "free", labeller = label_parsed) +
  xlab(expression(psi[leaf]~(-MPa))) +
  theme_classic() + 
  ylab("") +
  scale_color_discrete(name = expression(psi[soil]~(-MPa))) +
  theme(text = element_text(size = 18))-> d

png("states_rates_psi_stem.png", height=1000, width = 1000, res =100)
d
dev.off()
```


```{r}
facet_names <- c(
  "0" = expression(paste(psi[soil]," = ",0)),
  "1" = expression(paste(psi[soil]," = ",1))
)

names_facets <- c(
  "Assimilation" = "Assimilation",
    "Cost" = "Xylem cost",
  "Profit" = "Profit"
 )


expand_grid(psi_stem = seq(0, calc_psi_crit(calc_vul_b(2, 2.04), 2.04), length.out=50), psi_soil = c(0,1)) %>%
  mutate(states_rates = map2(psi_stem, psi_soil, set_leaf_states_rates_analytical)) %>%
  unnest(states_rates) %>%
  mutate(Cost = cost*lambda_) %>%
  mutate(Profit = Benefit - Cost)%>%
  filter(psi_stem >= psi_soil) %>%
  mutate(psi_soil = as_factor(psi_soil)) %>%
  mutate_at(.vars = "psi_soil", .funs = factor, labels = facet_names) %>%
  select(psi_stem, psi_soil, Benefit, Cost, Profit) %>%
  pivot_longer(-c(psi_stem, psi_soil)) %>%
  mutate_at(.vars = "name", .funs = factor, labels = names_facets) %>%
  ggplot(aes(x= psi_stem, y = value)) +
  geom_line(aes(colour = name, group = name)) +
  facet_wrap(~psi_soil, scales = "free", labeller = label_parsed)+
  xlab(expression(psi[leaf]~(-MPa))) +
  theme_classic() + 
  ylab(expression(paste("Economic unit (",mu,"mol "~m^{-2}~s^{-1},")"))) +
  scale_color_discrete(name = "") +
  theme(text = element_text(size = 18)) +
  expand_limits(x = 0 )-> e

png("economics.png", height=500, width = 1000, res =100)
e
dev.off()
```

```{r}
plot_conductivity <- function(psi_stem, psi_soil){
  leaf <- Leaf(vcmax= 100, p_50 = 2, c = 2.04, b = calc_vul_b(2, 2.04), psi_crit = calc_psi_crit(calc_vul_b(2, 2.04), 2.04), huber_value = 0.000157, K_s = 2, epsilon_leaf = 0.0001)
  
  PPFD = 1000
  atm_vpd = 2
  k_l_max = calc_k_l_max(K_s = 2, h_v = 0.000157, h =15)
  psi_soil = psi_soil 
  ca =40
  
  leaf$set_physiology(PPFD, psi_soil = psi_soil, k_l_max, atm_vpd, ca)
  
  return(leaf$proportion_of_conductivity(psi_stem))
    }
```

```{r}
tibble(psi = seq(0,4,0.01), psi_soil=0) %>%
  rowwise() %>%
  mutate(conductivity = map2_dbl(psi, psi_soil, plot_conductivity)) -> data_for_plot
  

data_for_plot %>%
  ggplot(aes(x = psi, y = conductivity)) +
  geom_line()+
  geom_ribbon(data = data_for_plot %>% filter(psi > 0 & psi <2), aes(ymax = conductivity, ymin= 0, xmin = 1, xmax =  2), fill="red",colour=NA,alpha=0.2) +
  xlab(expression(psi~(-MPa))) +
  ylab(expression(paste(Leaf~specific~conductance, " (", kg~m^{-2}~s^{-1}~MPa^{-1}, ")"))) +
  theme_classic() +
  geom_vline(xintercept = 0, linetype = "dashed") +
  geom_vline(xintercept = 2, linetype = "dashed") +
  annotate("text", x = 0.15, y = 1.1, label = expression(psi[soil])) + 
  annotate("text", x = 2.15, y = 1.1, label = expression(psi[leaf])) +
  annotate("text", x = 0.9, y = 0.5, label = expression(E[supply]), col = "red", size = 12) +
  theme(text= element_text(size = 18)) -> f

png("economics.png", height=500, width = 1000, res =100)
f
dev.off()
```

