---
title: "R Notebook"
output: html_notebook
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r warning=FALSE}
rm(list=ls())

library(dplyr)
library(tidyr)
library(ggplot2)
library(purrr)
library(deSolve)


source("R/solar_model.R")
source("R/reference_leaf.R")
source("R/reference_soil.R")
```

```{r}
trapezium <- function(x, y) sum(diff(x) * (y[-length(y)] + y[-1])/2)
```


```{r}

params <- set_params_soil(evap_routine = NULL, vcmax = c(100))
  bind_rows() %>%
  mutate(daily_data = pmap(., ~tibble(calc_PPFD_instant(day, latitude))))


met <- map(.x = seq(1), ~calc_PPFD_instant(latitude = -23, .x)) %>%
  bind_rows()
```

```{r}
params <- set_params_soil(evap_routine = NULL, vcmax = c(100)) %>%
  bind_rows() %>%
  select() %>%
  expand_grid(day = seq(1,180)) %>%
  right_join(met)
```

```{r}
params_outputs <- params %>%
  rowwise() %>%
  mutate(profit = find_opt_psi_stem_bartlett(1, k_l_max, vcmax, PPFD_umol_m2_s_instant, b, c, psi_crit, VPD, ca, beta1, beta2, h_v, h)$profit_root)
```

```{r}
max <- params_outputs %>% 
  pull(profit) %>%
  .[ggpmisc:::find_peaks(.)]

max_times <- params_outputs %>%
  filter(profit %in% max) %>%
  pull(instant_of_day)

min <- params_outputs %>% 
  filter(between(instant_of_day, max_times[1], max_times[2])) %>%
  mutate(profit = -1*profit) %>%
  pull(profit) %>%
  .[ggpmisc:::find_peaks(.)]

params_outputs %>%
  

$instant_of_day[ggpmisc:::find_peaks(params_outputs$profit)]


max <- params_outputs$instant_of_day[ggpmisc:::find_peaks(params_outputs$profit)]
min <- params_outputs %>%
  filter(between(instant_of_day, max[1], max[2]))

$instant_of_day[ggpmisc:::find_peaks(params_outputs$profit)]


limits <- params_outputs$instant_of_day[ggpmisc:::find_peaks(params_outputs$profit)]
params_outputs %>% 
  filter(between(instant_of_day, limits[1], limits[2])) -> minimum



minimum$instant_of_day[ggpmisc:::find_peaks(-minimum$profit)]

]


[1] 4 7
y[ggpmisc:::find_peaks(y)]
[1] 0.9082078 0.9446753
# Minima
x[ggpmisc:::find_peaks(-y)]
[1] 5
y[ggpmisc:::find_peaks(-y)]
[1] 0.2016819    

```



```{r}
params_outputs %>%
ggplot(aes(x = instant_of_day, y = profit)) +
  geom_line(aes(col = day, group = day)) +
  theme_classic() +
  facet_wrap(~vcmax)

params_outputs %>%
  filter(PPFD_umol_m2_s_instant != 0) %>%
  group_by(day) %>%
  summarise(day_length = max(instant_of_day) - min(instant_of_day)) %>%
  mutate(night_length = 1 - day_length) -> day_length
  
params_outputs %>%
  left_join(day_length) %>%
  group_by(day) %>%
  summarise(integrated_profit = trapezium(instant_of_day, profit),
            multiplied = min(profit)*unique(night_length) + max(profit)*unique(day_length)) %>%
  ggplot(aes(x = integrated_profit, y = multiplied)) +
  geom_point() +
  geom_abline(intercept = 0, slope = 1)


params_outputs %>%
  group_by(day) %>%
  summarise(integrated_profit = trapezium(instant_of_day, profit))

trapezium(params_outputs$instant_of_day, params_outputs$profit)
```

