---
title: "temperature_forcing"
author: "Isaac Towers"
date: "06/06/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r warning=FALSE}
rm(list=ls())

library(dplyr)
library(tidyr)
library(ggplot2)
library(purrr)
library(deSolve)


source("R/solar_model.R")
source("R/reference_leaf.R")
source("R/reference_soil.R")
```

```{r}
day <- 1
latitude <- -23

PPFD <- calc_PPFD_instant(day,latitude)
```


```{r}
max_temp <- 35
min_temp <- 15
```


```{r}
# Parton and Logan (1981) A model for dirunal variation in soil and
#        air temperature. Agricultural Meteorology, 23, 205--216.

# get_chunk_and_distribute_subdaily

a_t = 1.86;
b_t = 2.2;     #nighttime coeffcient
c_t = -0.17;   #lag of the min temp from the time of runrise

day_length = unique(PPFD$day_length) * 24
night_length = 24 - day_length

sun_up = unique(PPFD$sun_up)*24 
sun_down= unique(PPFD$sun_down)*24
 
m = sun_down - sun_up + c_t
tset = (max_temp - min_temp) * sin(pi * m / (day_length + 2.0 * a_t)) + min_temp

PPFD$instant_of_day <- PPFD$instant_of_day*24
PPFD$sun_up <- PPFD$sun_up*24
PPFD$sun_down <- PPFD$sun_down*24
PPFD$day_length <- PPFD$day_length*24

calc_temp <- function(instant_of_day, sun_up, sun_down, day_length){
  
m = instant_of_day - sun_up + c_t
  
  if(instant_of_day >= sun_up & instant_of_day <= sun_down){
    min_temp + (max_temp - min_temp) * sin(pi * m / (day_length + 2.0 * a_t)) 
  }
  else{
    if(instant_of_day > sun_down){
      n = instant_of_day - sun_down
    }
    else if(instant_of_day < sun_up){
      n = 24 + instant_of_day - sun_down
    }
  d = (tset - min_temp)/(exp(b_t)-1)
  
  (min_temp - d) + (tset - min_temp - d) * exp(-b_t*n/(24 -day_length + c_t))
  }
}

PPFD %>%
  rowwise() %>%
  mutate(temp = calc_temp(instant_of_day, sun_up, sun_down, day_length)) %>%
  ggplot(aes(x = instant_of_day, y = temp)) + 
  geom_point()

```


```{r}
calc_temp_func <- function(T_n, a, instant_of_day, H_n, H_x, T_o, b, H_o, H_p, Ra){
  if(H_n <= instant_of_day & instant_of_day <= H_x){
    temp = calc_1(T_n, a, instant_of_day, H_n, H_x)
      browser()
  }
  if(H_x < instant_of_day & instant_of_day <= H_o){
    temp = calc_2(T_o, R, instant_of_day, H_x)
  }
  if(H_o < instant_of_day & instant_of_day <= H_p){
    temp = calc_3(T_o, b, instant_of_day, H_o)
  }
  
  return(temp)

  }

calc_1 <- function(T_n, a, instant_of_day, H_n, H_x){
  T_n + a*((instant_of_day - H_n)/(H_x - H_n)) *(pi/2)
}

calc_2 <- function(T_o, Ra, instant_of_day, H_x){
  T_o + Ra*sin(pi/2 + ((instant_of_day - H_x)/4)*(pi/2))
}

calc_3 <- function(T_o, b, instant_of_day, H_o){
  T_o + b * sqrt(instant_of_day - H_o)
}

```


```{r}
# Carla Cesaraccio · Donatella Spano · Pierpaolo Duce
# Richard L. Snyder
# An improved model for determining degree-day values
# from daily temperature data

tibble(T_x = max_temp, T_n = min_temp, H_n = PPFD$sun_up[1]*24, H_o = PPFD$sun_down[1]*24, c = 0.39) %>%
  mutate(H_p = H_n + 24, H_x = H_o - 4, T_p = T_n) %>%
  mutate(T_o = T_x - c*(T_x - T_p)) %>%
  mutate(a = T_x - T_n,
         Ra = T_x - T_o,
         b = (T_p - T_o) / sqrt(H_p - H_o)) %>%
  expand_grid(instant_of_day = PPFD$instant_of_day * 24) %>%
  mutate(instant_of_day = if_else(instant_of_day <= H_n, instant_of_day + 24, instant_of_day)) %>%
  rowwise() %>% 
  mutate(temp = (calc_temp_func(T_n, a, instant_of_day, H_n, H_x, T_o, b, H_o, H_p, Ra))) -> ASD

  split(., 1:nrow(.)) %>%
  map_dbl(., ~calc_temp_func(.x$T_n, .x$a, .x$instant_of_day, .x$H_n, .x$H_x, .x$T_o, .x$b, .x$H_o, .x$H_p)) %>%
  bind_rows() -> asd
  
  


```

```{r}

```


