---
title: "R Notebook"
output: html_notebook
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r warning=FALSE}
rm(list=ls())

library(dplyr)
library(tidyr)
library(ggplot2)
library(purrr)
library(deSolve)
library(lhs)
library(furrr)
```

```{r}
devtools::load_all(".")
# devtools::install(".")

# library(plant)
```


```{r warning=FALSE}
source("R/solar_model.R")
# source("water_bucket_submodel/R/reference_soil.R")
source("tests/leaf_functions.R")
source("examples_vignettes/R/testing_integration.R")
```

```{r}
#vpsat in kPa
calc_vpsat <- function(air_temp_c){
  
    A = 17.27;
    T_star = 273.0; #K
    T_dash = 36.0;  #K
    es_T_star = 0.611; #kPa
  
  
  air_temp_K <- air_temp_c + 273.15
  
  esat = es_T_star * exp(A * (air_temp_K - T_star) / (air_temp_K - T_dash))
  esat
}
```


```{r}
p_50_2_K_s <- function(p50){
  1.638999*(p50/2)^(-1.38)
}

calc_vul_b <- function(p_50, c){
  num <- p_50
  den <- (-log(1-50/100))^(1/c)
  num/den
}


calc_psi_crit <- function(b,c) {
  b*(log(1/0.05))^(1/c)
}


```


```{r}
calc_temp <- function(instant_of_day, day_length, mean_temp, temp_diff, sun_rise, sun_down){

# Parton and Logan (1981) A model for dirunal variation in soil and
#        air temperature. Agricultural Meteorology, 23, 205--216.


a_t = 1.86;
b_t = 2.2;     #nighttime coeffcient
c_t = -0.17;   #lag of the min temp from the time of runrise

min_temp = mean_temp - temp_diff/2
max_temp = mean_temp + temp_diff/2

sun_rise = sun_rise
sun_down = sun_down

m = instant_of_day - sun_rise + c_t

if(instant_of_day >= sun_rise & instant_of_day <= sun_down){
  min_temp + (max_temp - min_temp) * sin((pi * m) / (day_length + 2.0 * a_t))
} else {
    NA
  }
}

```

```{r}
LHS <- randomLHS(100, 12)

params <- tibble(mean_temp = 20, temp_diff = qunif(LHS[,1], min = 5, max = 20), latitude = qunif(LHS[,2], min = 0, max = 60), VP = qunif(LHS[,3], 0.5, 2),
                   vcmax = qunif(LHS[,4], 30, 100), p_50 = qunif(LHS[,5], min = 1, max = 10), huber_value = qunif(LHS[,6], min = 0.000157/2, max =  0.000157*2),
                   day = qunif(LHS[,7], min = 0, 180), h = qunif(LHS[,8], min = 5, max = 80), E = qunif(LHS[,9], min = 0, max = 1), psi_soil = qunif(LHS[,10], 0, 10), ca = qunif(LHS[,11], 30, 45), c = qunif(LHS[,12], 1, 10))

```


```{r}
future::plan("multisession", workers = 8)
```

```{r}
params %>%
  future_pmap(expand_input_data) %>%
  bind_rows() %>%
  mutate(param_set = seq(1:n())) %>%
  expand_grid(focal_points = c(1,2,3,4,5,6,7,8,9,10,60)) %>%
  mutate(instant_through_day_hr = future_pmap(., create_mult_point)) %>%
  unnest(instant_through_day_hr) %>%
  mutate(instant_through_day_dec = instant_through_day_hr/24,
         dec_day_time = day_floor+ instant_through_day_dec) %>%
  mutate(solar_angle = solar_angle(dec_day_time, latitude),
         PAR = PAR_given_solar_angle(solar_angle) * 1e6 /24/ 60/60) %>%
  rowwise() %>%
  mutate(temp = calc_temp(instant_through_day_hr, day_length, mean_temp, temp_diff, sun_rise, sun_down)) %>%
  mutate(VPD_hr = max(0.05, calc_vpsat(temp) - VP)) -> expanded_input_data

```

```{r}
expanded_input_data %>% 
  ungroup() %>%
  mutate(leaf = pmap(., make_leaf)) %>%
  mutate(leaf_states_rate = map(leaf, leaf_states_rates_from_leaf)) %>%
  unnest(leaf_states_rate) %>% 
  nest(outputs = c(leaf, instant_through_day_hr, instant_through_day_dec, dec_day_time, solar_angle, PAR, temp, VPD_hr, profit, transpiration, psi_stem, g_c)) -> expanded_output
```


```{r}
expanded_output %>%
  unnest(outputs) %>%
  mutate(profit_hr = profit*60*60/1e6) %>%
  mutate(transpiration_hr = transpiration*60*60) %>% 
  mutate(profit_integrated = profit_hr* day_length/focal_points) %>%
  mutate(transpiration_integrated = transpiration_hr * day_length/focal_points) %>%
  group_by(focal_points, param_set) %>%
  nest()  %>%
  mutate(daily_profit_integrated = map_dbl(data, ~sum(.x$profit_integrated))) %>%
  mutate(daily_transpiraiton_integrated = map_dbl(data, ~sum(.x$transpiration_integrated))) -> expanded_output_integrated
```

```{r}


set.seed(124)

expanded_output_integrated %>%
  filter(focal_points == "60") %>%
  unnest(data) %>%
  filter(psi_soil < psi_crit) %>%
  group_by(param_set) %>%
  nest() %>%
  ungroup() %>%
  sample_n(4) -> data_for_plot
  

data_for_plot %>%
  unnest(data) %>%
  ggplot(aes(x = instant_through_day_hr, y = profit)) +
  geom_line() + 
  scale_x_continuous(breaks = seq(0,24,4), labels = seq(0,24,4), limits = c(0,24)) +
  facet_wrap(~param_set, scales = "free_x") +
  theme_classic() +
  theme(strip.background = element_blank(),
  strip.text.x = element_blank(),
  text = element_text(size=16),
  axis.title = element_text(size=18)
  ) +
  ylab(expression(paste("Profit (",mu,"mol C ", m^{-2}~s^{-1},")"))) +
  xlab("Time (hr)") -> a

  
data_for_plot %>%
  unnest(data) %>%
  ggplot() +
  geom_line(aes(x = instant_through_day_hr, y = transpiration)) + 
  scale_x_continuous(breaks = seq(0,24,4), labels = seq(0,24,4), limits = c(0,24)) +
  facet_wrap(~param_set, scales = "free_x") +
  theme_classic() +
  theme(strip.background = element_blank(),
  strip.text.x = element_blank(),
  text = element_text(size=16),
  axis.title = element_text(size=18)
  ) +
  ylab(expression(paste("Evapotranspiration (kg ",H[2],"O ", m^{-2}~s^{-1},")"))) +
  xlab("Time (hr)")-> b
png("examples_vignettes/outputs/testing_integration/Fig_1.png", height = 1000, width = 1500, res = 100)
cowplot::plot_grid(a,b, labels = c("a", "b"))
dev.off()
```


```{r}
set.seed(136)

expanded_output_integrated %>%
  ungroup() %>%
  unnest(data) %>%
  filter(focal_points %in% c(1,2,3, 60)) %>%
  group_by(param_set, focal_points) %>%
  mutate(run = seq(1:n())) %>%
  select(-leaf) %>%
  ungroup() %>%
  group_by(param_set) %>%
  nest(outputs = -param_set) %>%
  ungroup() %>%
  sample_n(1) %>%
  unnest(outputs) %>%
  mutate(coords= pmap(., make_polygon_coordinates2)) %>%
  group_by(param_set) %>%
  nest(params = -param_set) %>%
  ungroup() -> data_for_plot
  
data_for_plot %>%
  {map(.$params, visualise_integrals, variable = "profit")} -> a

data_for_plot %>%
  {map(.$params, visualise_integrals, variable = "transpiration")} -> b
  

a[[1]] +
  scale_x_continuous(breaks = seq(0,24,4), labels = seq(0,24,4), limits = c(0,24)) +
  theme_classic() +
  theme(strip.background = element_blank(),
  strip.text.x = element_blank(),
  text = element_text(size=16),
  axis.title = element_text(size=18)
  ) +
  ylab(expression(paste("Profit (",mu,"mol C ", m^{-2}~s^{-1},")"))) +
  xlab("Time (hr)") -> a

b[[1]] +
  scale_x_continuous(breaks = seq(0,24,4), labels = seq(0,24,4), limits = c(0,24)) +
  theme_classic() +
  theme(strip.background = element_blank(),
  strip.text.x = element_blank(),
  text = element_text(size=16),
  axis.title = element_text(size=18)
  ) +
  ylab(expression(paste("Evapotranspiration (kg ",H[2],"O ", m^{-2}~s^{-1},")"))) +
  xlab("Time (hr)") +
  expand_limits(y = data_for_plot %>% unnest(params) %>% pull(transpiration) %>% max()*1.1)-> b
  
png("examples_vignettes/outputs/testing_integration/Fig_2.png", height = 1200, width = 2000, res = 175)
cowplot::plot_grid(a,b, labels = c("a", "b"))
dev.off()
```

```{r}
expanded_output_integrated %>%
  unnest(data) %>%
  select(-leaf) %>%
  saveRDS("examples_vignettes/expanded_output_integrated2.RDS")

expanded_output_integrated <- readRDS("examples_vignettes/expanded_output_integrated2.RDS")


expanded_output_integrated %>%
  select(-c(data, daily_transpiraiton_integrated)) %>%
  pivot_wider(names_from = focal_points, values_from =  c(daily_profit_integrated)) %>%
  pivot_longer(cols = c( "1","2","3","4","5","6","7","8","9","10"), names_to = "focal_points", values_to = "focal_point_integration") %>%
  rename(high_resolution_integration = `60`)%>%
  filter(high_resolution_integration != 0) %>%
  mutate(focal_point_integration2 = focal_point_integration^2) %>%
  group_by(focal_points) %>%
  nest() %>%
  mutate(linear_model = map(data, ~lm(.x$high_resolution_integration~.x$focal_point_integration +0))) %>%
  mutate(linear_pred = map(linear_model, ~predict(.x))) %>%
  mutate(linear_cor = map_dbl(linear_model, ~summary(.x)$r.squared)) %>%
  mutate(linear_coefficient = map_dbl(linear_model, ~.x$coefficients)) %>%
  mutate(linear_MD = map_dbl(linear_model, ~mean(.x$residuals))) %>%
  mutate(linear_RMSE = map_dbl(linear_model, ~sqrt(mean(.x$residuals^2)))) %>%
  mutate(linear_AIC = map_dbl(linear_model, ~AIC(.x))) %>%
  mutate(linear_BIC = map_dbl(linear_model, ~BIC(.x))) %>%
  mutate(quad_model = map(data, ~lm(.x$high_resolution_integration~.x$focal_point_integration + .x$focal_point_integration2 +0))) %>%
  mutate(quad_pred = map(quad_model, ~predict(.x))) %>%
  mutate(quad_cor = map_dbl(quad_model, ~summary(.x)$r.squared)) %>%
  mutate(quad_coefficient1 = map_dbl(quad_model, ~.x$coefficients[1])) %>%
  mutate(quad_coefficient2 = map_dbl(quad_model, ~.x$coefficients[2])) %>%
  mutate(quad_MD = map_dbl(quad_model, ~mean(.x$residuals))) %>%
  mutate(quad_RMSE = map_dbl(quad_model, ~sqrt(mean(.x$residuals^2)))) %>%
  mutate(quad_AIC = map_dbl(quad_model, ~AIC(.x))) %>%
  mutate(quad_BIC = map_dbl(quad_model, ~BIC(.x))) %>%
  unnest(data, linear_pred, quad_pred) %>%
  group_by(focal_points) %>%
  nest() %>%
  mutate(linear_pred_model = map(data, ~lm(.x$high_resolution_integration~.x$linear_pred))) %>%
  mutate(quad_pred_model = map(data, ~lm(.x$high_resolution_integration~.x$quad_pred))) %>%
  mutate(bias_linear = map_dbl(linear_pred_model, ~.x$coefficients[1])) %>%
  mutate(offset_linear = map_dbl(linear_pred_model, ~.x$coefficients[2])) %>%
  mutate(linear_pred_MD = map_dbl(linear_pred_model, ~mean(.x$residuals))) %>%
  mutate(linear_pred_RMSE = map_dbl(linear_pred_model, ~sqrt(mean(.x$residuals^2)))) %>%
  mutate(bias_quad = map_dbl(quad_pred_model, ~.x$coefficients[1])) %>%
  mutate(offset_quad = map_dbl(quad_pred_model, ~.x$coefficients[2])) %>%
  mutate(quad_pred_MD = map_dbl(quad_pred_model, ~mean(.x$residuals))) %>%
  mutate(quad_pred_RMSE = map_dbl(quad_pred_model, ~sqrt(mean(.x$residuals^2))))  %>%
  ungroup() -> data_for_table_profit

data_for_table_profit %>%
  select(focal_points, linear_cor, linear_coefficient, linear_MD, linear_RMSE, linear_AIC, linear_BIC, quad_cor, quad_coefficient1, quad_coefficient2, quad_MD, quad_RMSE, quad_AIC, quad_BIC) %>%
  mutate(across(.cols = -(focal_points), .fns = ~round(.x,5)))%>%
  write.csv("examples_vignettes/outputs/testing_integration/data_for_table_profit.csv")


expanded_output_integrated %>%
  select(-c(data, daily_profit_integrated)) %>%
  pivot_wider(names_from = focal_points, values_from =  c(daily_transpiraiton_integrated)) %>%
  pivot_longer(cols = c( "1","2","3","4","5","6","7","8","9","10"), names_to = "focal_points", values_to = "focal_point_integration") %>%
  rename(high_resolution_integration = `60`)%>%
  filter(high_resolution_integration != 0) %>%
  mutate(focal_point_integration2 = focal_point_integration^2) %>%
  group_by(focal_points) %>%
  nest() %>%
  mutate(linear_model = map(data, ~lm(.x$high_resolution_integration~.x$focal_point_integration +0))) %>%
  mutate(linear_pred = map(linear_model, ~predict(.x))) %>%
  mutate(linear_cor = map_dbl(linear_model, ~summary(.x)$r.squared)) %>%
  mutate(linear_coefficient = map_dbl(linear_model, ~.x$coefficients)) %>%
  mutate(linear_MD = map_dbl(linear_model, ~mean(.x$residuals))) %>%
  mutate(linear_RMSE = map_dbl(linear_model, ~sqrt(mean(.x$residuals^2)))) %>%
  mutate(linear_AIC = map_dbl(linear_model, ~AIC(.x))) %>%
  mutate(linear_BIC = map_dbl(linear_model, ~BIC(.x))) %>%
  mutate(quad_model = map(data, ~lm(.x$high_resolution_integration~.x$focal_point_integration + .x$focal_point_integration2 +0))) %>%
  mutate(quad_pred = map(quad_model, ~predict(.x))) %>%
  mutate(quad_cor = map_dbl(quad_model, ~summary(.x)$r.squared)) %>%
  mutate(quad_coefficient1 = map_dbl(quad_model, ~.x$coefficients[1])) %>%
  mutate(quad_coefficient2 = map_dbl(quad_model, ~.x$coefficients[2])) %>%
  mutate(quad_MD = map_dbl(quad_model, ~mean(.x$residuals))) %>%
  mutate(quad_RMSE = map_dbl(quad_model, ~sqrt(mean(.x$residuals^2)))) %>%
  mutate(quad_AIC = map_dbl(quad_model, ~AIC(.x))) %>%
  mutate(quad_BIC = map_dbl(quad_model, ~BIC(.x))) %>%
  unnest(data, linear_pred, quad_pred) %>%
  group_by(focal_points) %>%
  nest() %>%
  mutate(linear_pred_model = map(data, ~lm(.x$high_resolution_integration~.x$linear_pred))) %>%
  mutate(quad_pred_model = map(data, ~lm(.x$high_resolution_integration~.x$quad_pred))) %>%
  mutate(bias_linear = map_dbl(linear_pred_model, ~.x$coefficients[1])) %>%
  mutate(offset_linear = map_dbl(linear_pred_model, ~.x$coefficients[2])) %>%
  mutate(linear_pred_MD = map_dbl(linear_pred_model, ~mean(.x$residuals))) %>%
  mutate(linear_pred_RMSE = map_dbl(linear_pred_model, ~sqrt(mean(.x$residuals^2)))) %>%
  mutate(bias_quad = map_dbl(quad_pred_model, ~.x$coefficients[1])) %>%
  mutate(offset_quad = map_dbl(quad_pred_model, ~.x$coefficients[2])) %>%
  mutate(quad_pred_MD = map_dbl(quad_pred_model, ~mean(.x$residuals))) %>%
  mutate(quad_pred_RMSE = map_dbl(quad_pred_model, ~sqrt(mean(.x$residuals^2))))  %>%
  ungroup() -> data_for_table_transpiration
  
data_for_table_transpiration %>%
  select(focal_points, linear_cor, linear_coefficient, linear_MD, linear_RMSE,linear_AIC,linear_BIC, quad_cor, quad_coefficient1, quad_coefficient2, quad_MD, quad_RMSE,quad_AIC,quad_BIC) %>%
  mutate(across(.cols = -(focal_points), .fns = ~round(.x,5)))%>%
  write.csv("examples_vignettes/outputs/testing_integration/data_for_table_transpiration.csv")
```


```{r}

data_for_table_profit %>%
  mutate(focal_points_f = factor(focal_points, levels = c("1","2","3","4","5","6","7","8","9","10"))) %>%
  unnest(data) -> data_for_fit_testing_profit_plot

data_for_table_transpiration %>%
  mutate(focal_points_f = factor(focal_points, levels = c("1","2","3","4","5","6","7","8","9","10"))) %>%
  unnest(data) -> data_for_fit_testing_transpiration_plot


data_for_fit_testing_profit_plot %>%
  ggplot(aes(x = focal_point_integration, y = high_resolution_integration)) +
  geom_hex(bins = 30, aes(colour = after_stat(count))) +
  facet_wrap(~focal_points_f) +
  theme_classic() +
  geom_line(aes(x = focal_point_integration, y = linear_pred), linetype = "solid", size = 1.1) +
  geom_line(aes(x = focal_point_integration, y = focal_point_integration), linetype = "dotted", size = 1.1) +
  theme(strip.text = element_blank(), text = element_text(size = 18)) +
  ylab(expression(paste(Total~daily~profit~(60~sample~points), " [mol C ",m^{-2},"]", sep=""))) +
  xlab(expression(paste(Total~daily~profit~(n~sample~points), " [mol C ",m^{-2},"]", sep=""))) +
  geom_text(data = data_for_fit_testing_profit_plot %>% distinct(focal_points_f), aes(x = 0, y = Inf, label = paste("n = ",focal_points_f, sep = "")), vjust = 1.5, hjust = -0.0625, size = 6)+ 
  labs(fill = "count", colour = "count") +
  scale_color_viridis_b() +
  scale_fill_viridis_b()  -> a_linear

data_for_fit_testing_profit_plot %>%
  ggplot(aes(x = focal_point_integration, y = high_resolution_integration)) +
  geom_hex(bins = 30, aes(colour = after_stat(count))) +
  facet_wrap(~focal_points_f) +
  theme_classic() +
  geom_line(aes(x = focal_point_integration, y = quad_pred), linetype = "solid", size = 1.1) +
  theme(strip.text = element_blank(), text = element_text(size = 18)) +
  ylab(expression(paste(Total~daily~profit~(60~sample~points), " [mol C ",m^{-2},"]", sep=""))) +
  xlab(expression(paste(Total~daily~profit~(n~sample~points), " [mol C ",m^{-2},"]", sep=""))) +
  geom_text(data = data_for_fit_testing_profit_plot %>% distinct(focal_points_f), aes(x = 0, y = Inf, label = paste("n = ",focal_points_f, sep = "")), vjust = 1.5, hjust = -0.0625, size = 6) + 
  labs(fill = "count", colour = "count") +
  scale_color_viridis_b() +
  scale_fill_viridis_b() -> a_quad


data_for_fit_testing_transpiration_plot %>%
  ggplot(aes(x = focal_point_integration, y = high_resolution_integration)) +
  geom_hex(bins = 30, aes(colour = after_stat(count))) +
  facet_wrap(~focal_points_f) +
  theme_classic() +
  geom_line(aes(x = focal_point_integration, y = linear_pred), linetype = "solid", size = 1.1) +
  geom_line(aes(x = focal_point_integration, y = focal_point_integration), linetype = "dotted", size = 1.1) +
  theme(strip.text = element_blank(), text = element_text(size = 18)) +
  ylab(expression(paste(Total~daily~transpiration~(60~sample~points), " [kg ",H[2],"O ",m^{-2},"]", sep=""))) +
  xlab(expression(paste(Total~daily~transpiration~(n~sample~points), " [kg ",H[2],"O ",m^{-2},"]", sep=""))) +
  geom_text(data = data_for_fit_testing_transpiration_plot %>% distinct(focal_points_f), aes(x = 0, y = Inf, label = paste("n = ",focal_points_f, sep = "")), vjust = 1.5, hjust = -0.0625, size = 6) + 
  labs(fill = "count", colour = "count") +
  scale_color_viridis_b() +
  scale_fill_viridis_b() -> b_linear


data_for_fit_testing_transpiration_plot %>%
  ggplot(aes(x = focal_point_integration , y = high_resolution_integration)) +
  geom_hex(bins = 30, aes(colour = ..count..)) +
  facet_wrap(~focal_points_f) +
  theme_classic() +
  geom_line(aes(x = focal_point_integration, y = quad_pred), linetype = "solid", size = 1.1) +
  theme(strip.text = element_blank(), text = element_text(size = 18)) +
  ylab(expression(paste(Total~daily~transpiration~(60~sample~points), " [kg ",H[2],"O ",m^{-2},"]", sep=""))) +
  xlab(expression(paste(Total~daily~transpiration~(n~sample~points), " [kg ",H[2],"O ",m^{-2},"]", sep=""))) +
  geom_text(data = data_for_fit_testing_transpiration_plot %>% distinct(focal_points_f), aes(x = 0, y = Inf, label = paste("n = ",focal_points_f, sep = "")), vjust = 1.5, hjust = -0.0625, size = 6) + 
  labs(fill = "count", colour = "count") +
  scale_color_viridis_b() +
  scale_fill_viridis_b() -> b_quad

png("examples_vignettes/outputs/testing_integration/Fig_3.png", height = 800, width = 1600, res = 70)
cowplot::plot_grid(a_linear, b_linear, labels = "auto")
dev.off()

png("examples_vignettes/outputs/testing_integration/Fig_S1.png", height = 800, width = 1600, res = 70)
cowplot::plot_grid(a_quad, b_quad, labels = "auto")
dev.off()
```

```{r}
data_for_fit_testing_profit_plot %>%
  ggplot() +
  geom_hex(bins = 30, aes(x = linear_pred, y = high_resolution_integration, colour = after_stat(count))) +
  facet_wrap(~focal_points_f) +
  theme_classic() +
  geom_abline(aes(slope = 1, intercept = 0), linetype = "dashed", size = 1.1) +
  theme(strip.text = element_blank(), text = element_text(size = 18)) +
  ylab(expression(paste(Total~daily~profit~(60~sample~points), " [mol C ",m^{-2},"]", sep=""))) +
  xlab(expression(paste(Total~daily~profit~(n~sample~points), " [mol C ",m^{-2},"]", sep=""))) +
  geom_text(data = data_for_fit_testing_profit_plot %>% distinct(focal_points_f), aes(x = 0, y = Inf, label = paste("n = ",focal_points_f, sep = "")), vjust = 1.5, hjust = -0.0625, size = 6)+ 
  labs(fill = "count", colour = "count") +
  scale_color_viridis_b() +
  scale_fill_viridis_b()  -> a_linear_pred

data_for_fit_testing_profit_plot %>%
  ggplot() +
  geom_hex(bins = 30, aes(x = quad_pred, y = high_resolution_integration, colour = after_stat(count))) +
  facet_wrap(~focal_points_f) +
  theme_classic() +
  geom_abline(aes(slope = 1, intercept = 0), linetype = "dashed", size = 1.1) +
  theme(strip.text = element_blank(), text = element_text(size = 18)) +
  ylab(expression(paste(Total~daily~profit~(60~sample~points), " [mol C ",m^{-2},"]", sep=""))) +
  xlab(expression(paste(Total~daily~profit~(n~sample~points), " [mol C ",m^{-2},"]", sep=""))) +
  geom_text(data = data_for_fit_testing_profit_plot %>% distinct(focal_points_f), aes(x = 0, y = Inf, label = paste("n = ",focal_points_f, sep = "")), vjust = 1.5, hjust = -0.0625, size = 6)+ 
  labs(fill = "count", colour = "count") +
  scale_color_viridis_b() +
  scale_fill_viridis_b()  -> a_quad_pred


data_for_fit_testing_transpiration_plot %>%
  ggplot() +
  geom_hex(bins = 30, aes(x = linear_pred, y = high_resolution_integration, colour = after_stat(count))) +
  facet_wrap(~focal_points_f) +
  theme_classic() +
  geom_abline(aes(slope = 1, intercept = 0), linetype = "dashed", size = 1.1) +
  theme(strip.text = element_blank(), text = element_text(size = 18)) +
  ylab(expression(paste(Total~daily~transpiration~(60~sample~points), " [kg ",H[2],"O ",m^{-2},"]", sep=""))) +
  xlab(expression(paste(Total~daily~transpiration~(n~sample~points), " [kg ",H[2],"O ",m^{-2},"]", sep=""))) +
  geom_text(data = data_for_fit_testing_transpiration_plot %>% distinct(focal_points_f), aes(x = 0, y = Inf, label = paste("n = ",focal_points_f, sep = "")), vjust = 1.5, hjust = -0.0625, size = 6) + 
  labs(fill = "count", colour = "count") +
  scale_color_viridis_b() +
  scale_fill_viridis_b() -> b_linear_pred

data_for_fit_testing_transpiration_plot %>%
  ggplot() +
  geom_hex(bins = 30, aes(x = quad_pred, y = high_resolution_integration, colour = after_stat(count))) +
  facet_wrap(~focal_points_f) +
  theme_classic() +
  geom_abline(aes(slope = 1, intercept = 0), linetype = "dashed", size = 1.1) +
  theme(strip.text = element_blank(), text = element_text(size = 18)) +
  ylab(expression(paste(Total~daily~transpiration~(60~sample~points), " [kg ",H[2],"O ",m^{-2},"]", sep=""))) +
  xlab(expression(paste(Total~daily~transpiration~(n~sample~points), " [kg ",H[2],"O ",m^{-2},"]", sep=""))) +
  geom_text(data = data_for_fit_testing_transpiration_plot %>% distinct(focal_points_f), aes(x = 0, y = Inf, label = paste("n = ",focal_points_f, sep = "")), vjust = 1.5, hjust = -0.0625, size = 6) + 
  labs(fill = "count", colour = "count") +
  scale_color_viridis_b() +
  scale_fill_viridis_b() -> b_quad_pred
```


```{r}
focal_parameters <- expand_grid(continuous_parameter = c("ca","VP","day","psi_soil", "temp_diff", "E"), factorial_parameter = c("vcmax", "p_50","huber_value","h","c"))
```

```{r}
set_focal_parameters <- function(length_required, ...){
  
  focal_parameters = tibble(...)
if(focal_parameters$continuous_parameter == "ca") {
  ca = seq(30, 45, length.out =length_required)
} else {
  ca = 40
}
  
if(focal_parameters$continuous_parameter == "E") {
  E = seq(0.01, 1, length.out =length_required)
} else {
  E = 0.7
}

if(focal_parameters$continuous_parameter == "VP") {
  VP = seq(0.5, 3, length.out = length_required)
} else {
  VP = 1.5
}


if(focal_parameters$continuous_parameter == "day") {
  day = seq(0, 180, length.out = length_required)
} else {
  day = 60
}


if(focal_parameters$continuous_parameter == "psi_soil") {
  psi_soil = seq(0, 5, length.out = length_required)
} else {
  psi_soil = 0.5
}

if(focal_parameters$continuous_parameter == "temp_diff") {
  temp_diff = seq(0, 15, length.out = length_required)
} else {
  temp_diff = 5
}  
  
if(focal_parameters$factorial_parameter == "vcmax") {
  vcmax = c(30,100)
} else {
  vcmax = 70
}

if(focal_parameters$factorial_parameter == "p_50") {
  p_50 = c(1, 6)
} else {
  p_50 = 3
}


if(focal_parameters$factorial_parameter == "huber_value") {
  huber_value = c(0.000157/2, 0.000157*2)
} else {
  huber_value = 0.000157
}


if(focal_parameters$factorial_parameter == "h") {
  h = c(5, 50)
} else {
  h = 10
}
  
if(focal_parameters$factorial_parameter == "c") {
  c = c(1, 3)
} else {
  c = 2.04
}

expand_grid(mean_temp = 20, temp_diff = temp_diff, latitude = 27, VP = VP,
                   vcmax = vcmax, p_50 = p_50, huber_value = huber_value,
                   day = day, h = h, E = E, psi_soil = psi_soil, ca = ca, c=c)  
}
```


```{r}
focal_parameters %>%
  mutate(parameters = pmap(., set_focal_parameters, 20)) %>%
  mutate(run = 1:nrow(.)) %>%
  unnest(parameters) %>%
  group_by(run) %>%
  mutate(param_set = 1:n()) %>%
  ungroup() %>%
  pmap(expand_input_data) %>%
  bind_rows() %>%
  expand_grid(focal_points = c(1,60))%>%
  mutate(instant_through_day_hr = pmap(., create_mult_point)) %>%
  unnest(instant_through_day_hr) %>%
  mutate(instant_through_day_dec = instant_through_day_hr/24,
         dec_day_time = day_floor+ instant_through_day_dec) %>%
  mutate(solar_angle = solar_angle(dec_day_time, latitude),
         PAR = PAR_given_solar_angle(solar_angle)) %>%
  rowwise() %>%
  mutate(temp = calc_temp(instant_through_day_hr, day_length, mean_temp, temp_diff, sun_rise, sun_down)) %>%
  mutate(VPD_hr = max(0.05, calc_vpsat(temp) - VP)) -> expanded_input_data_sensitivity


expanded_input_data_sensitivity %>%
  ungroup() %>%
  mutate(leaf = pmap(., make_leaf)) %>%
  mutate(leaf_states_rate = map(leaf, leaf_states_rates_from_leaf)) %>%
  unnest(leaf_states_rate) %>% 
  nest(outputs = c(leaf, instant_through_day_hr, instant_through_day_dec, dec_day_time, solar_angle, PAR, temp, VPD_hr, profit, transpiration, psi_stem, g_c)) -> expanded_output_sensitivity

# need to put this on the right scale
expanded_output_sensitivity %>%
  unnest(outputs) %>%
  mutate(profit_mol_hr = profit * 60 * 60 * 1e-06) %>%
  mutate(profit_integrated = profit_mol_hr * day_length/focal_points) %>%
  mutate(transpiration_hr = transpiration * 60 * 60) %>%
  mutate(profit_integrated = profit_mol_hr * day_length/focal_points) %>%
  mutate(transpiration_integrated = transpiration_hr * day_length/focal_points) %>%
  group_by(param_set, run, focal_points) %>%
  nest() %>%
  mutate(daily_profit_integrated = map_dbl(data, ~sum(.x$profit_integrated))) %>%
  mutate(daily_transpiration_integrated = map_dbl(data, ~sum(.x$transpiration_integrated))) -> expanded_output_sensitivity_for_plotting

expanded_output_sensitivity_for_plotting %>%
  unnest(data) %>%
  ungroup() %>%
  mutate(continuous_parameter2= case_when(continuous_parameter == "VP"~ "Vapour pressure (kPa)",
                                          continuous_parameter == "day"~ "Day",
                                          continuous_parameter == "E" ~ "Canopy openness",
                                          TRUE ~ as.character(continuous_parameter)),
         factorial_parameter2 = case_when(factorial_parameter == "h" ~ "Height (m)",
                                          TRUE ~ as.character(factorial_parameter))
  ) %>%
  mutate(factorial_parameter = as.character(factorial_parameter)) %>%
  group_by(run) %>%
  nest(outputs = -run) %>%
  ungroup() %>%
  mutate(plots = map(outputs, plotting_function, variable = "profit"))-> profit_plots



expanded_output_sensitivity_for_plotting %>%
  unnest(data) %>%
  ungroup() %>%
  mutate(continuous_parameter2= case_when(continuous_parameter == "VP"~ "Vapour pressure (kPa)",
                                          continuous_parameter == "day"~ "Day",
                                          continuous_parameter == "E" ~ "Canopy openness",
                                          TRUE ~ as.character(continuous_parameter)),
         factorial_parameter2 = case_when(factorial_parameter == "h" ~ "Height (m)",
                                          TRUE ~ as.character(factorial_parameter))
  ) %>%
  mutate(factorial_parameter = as.character(factorial_parameter)) %>%
  group_by(run) %>%
  nest(outputs = -run) %>%
  ungroup() %>%
  mutate(plots = map(outputs, plotting_function, variable = "transpiration"))-> transpiration_plots


png("examples_vignettes/outputs/testing_integration/Fig_4.png", width = 2000, height = 2000, res = 160)
plots <- cowplot::plot_grid(plotlist = profit_plots$plots, nrow = n_distinct(expanded_output_sensitivity$continuous_parameter), align = "vh", labels =c(letters, "aa","ab","ac","ad"))
y.grob <- grid::textGrob(expression(paste("Integrated daily profit (","mol C ", m^{-2}~d^{-1},")")),
                   gp=grid::gpar(fontface="bold", fontsize=15), rot=90)

gridExtra::grid.arrange(gridExtra::arrangeGrob(plots, left = y.grob))

dev.off()

png("examples_vignettes/outputs/testing_integration/Fig_S2.png", width = 2000, height = 2000, res = 160)
plots <- cowplot::plot_grid(plotlist = transpiration_plots$plots, nrow = n_distinct(expanded_output_sensitivity$continuous_parameter), align = "vh", labels =c(letters, "aa","ab","ac","ad"))
y.grob <- grid::textGrob(expression(paste("Integrated daily transpiration (","kg ",H[2],"O ", m^{-2}~d^{-1},")")),
                   gp=grid::gpar(fontface="bold", fontsize=15), rot=90)

gridExtra::grid.arrange(gridExtra::arrangeGrob(plots, left = y.grob))

dev.off()
```

```{r}
species_LHS <- randomLHS(50, 12)

species_params <- tibble(vcmax = qunif(LHS[,4], 30, 100), p_50 = qunif(LHS[,5], min = 1, max = 10), huber_value = qunif(LHS[,6], min = 0.000157/2, max =  0.000157*2), c = qunif(LHS[,12], 1, 10))


env_LHS <- randomLHS(100, 12)

env_params
```





LHS <- randomLHS(100, 12)

params <- tibble(mean_temp = 20, temp_diff = qunif(LHS[,1], min = 5, max = 20), latitude = qunif(LHS[,2], min = 0, max = 60), VP = qunif(LHS[,3], 0.5, 2),
                   vcmax = qunif(LHS[,4], 30, 100), p_50 = qunif(LHS[,5], min = 1, max = 10), huber_value = qunif(LHS[,6], min = 0.000157/2, max =  0.000157*2),
                   day = qunif(LHS[,7], min = 0, 180), h = qunif(LHS[,8], min = 5, max = 80), E = qunif(LHS[,9], min = 0, max = 1), psi_soil = qunif(LHS[,10], 0, 10), ca = qunif(LHS[,11], 30, 45), c = qunif(LHS[,12], 1, 10))

