---
title: "reference_soil"
author: "Isaac Towers"
date: "03/05/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(tidyr)
library(ggplot2)
library(purrr)
library(deSolve)

source("R/solar_model.R")
source("R/reference_leaf.R")
source("R/reference_soil.R")
```

```{r}
calc_PPFD_instant <- function(latitude, day, length.out = 86400) {
  given_day_start <- floor(day)
  instant_through_time <- seq(given_day_start, given_day_start+1, length.out = length.out)
  PPFD_instant_mol_m2_day <- PAR_given_solar_angle(solar_angle = solar_angle(latitude = (latitude), decimal_day_time = instant_through_time))
  tibble(PPFD_umol_m2_s_instant = PPFD_instant_mol_m2_day /(60*60*24) * 1E6, instant_of_day = instant_through_time - given_day_start, day = given_day_start, latitude = latitude)
}
```

```{r}
calc_PPFD_instant(-23, 1)
```


```{r warning=FALSE}
#set time period and time step
t <- seq(0,200, by = 1)

#how many soil depths should be monitored
n=1

#set depth of points, can be customised. N-1 in this case accounts for one customsied point, all others are the same
standard_depth = 0.5
z <- c(0.022, rep(standard_depth, n-1))

i=1

#set vector to collect gradients 
dtheta_dt <- vector(length = n)

#set initial soil moisture content for each layer (boundary z[i] - z[i-1]) as well as the amount of water lost to deep drainage and runoff and the total amount of rainfall falling in period for sanity check, particulary important for when inclduing temporal variation
theta_init <- c(theta=rep(0.05, n), runoff = 0, cumulative_rain=0, evaporation = 0)


#set parameter values
params <- list(
  c(
    R=3/365/24/60/60, #m^3 m^2 s^-1
    dsat = 1.4,
    nd = 6.5,
    theta_sat = 0.482,
    b=8,
    ksat=292.8,
    nk=11.9,
    I_constant = 1,
    lambda = 2.45, #MJ kg^-1
    slp = 145, #Pa K^-1
    gamma = 66.1, #Pa K^-1
    theta_fc = 0.3,
    theta_wp = 0.05,
    swf = 1, # sensitivity power factor on empirical soil wetness curve
    r_soil = 0.6, #soil resistance to water infil
    LAI = 3,
    starting_day = 1,
    latitude = -23
    ))
```


```{r warning=FALSE}
#soil moisture drainage model

    net_rad = calc_PPFD_instant(-23, 1)$PPFD_umol_m2_s_instant *umol_2_J


theta_rates <- function(t, theta, params) {
  with(as.list(c(theta, params)), {
    I = (1-I_constant*(theta[i]/theta_sat)^b)
    
    
    E_bare_soil_pot = (1-r_soil)*net_rad[t]*slp/((slp+gamma)*lambda)
    E_bare_soil = max(0,E_bare_soil_pot)
    Ev = E_bare_soil^(-0.398*LAI)
    soil_wetness = ((theta[1] - theta_wp)/(theta_fc - theta_wp)) ^swf
    Ev = max (0, Ev * soil_wetness)
                      

    inflow = R*I
    runoff = (R)*(1-I)
    outflow = Ev
    
    dtheta_dt[i] = (inflow - outflow)/z[i]
    runoff = runoff
    cumulative_rain = R
    evaporation = Ev
    
    
    return(list(c(dtheta_dt, runoff, cumulative_rain, evaporation)))
  })
}



```
```{r}
#number of soil layers
n =2

#number of times steps (s)
times <- seq(0,86400*3, by = 1)

theta <- matrix(nrow = length(times), ncol = n)
theta[1,] <- 0.3

runoff <- rep(NA, length(times))
runoff[1] <- 0

cumulative_rain <- rep(NA, length(times))
cumulative_rain[1] <- 0


evaporation <- rep(NA, length(times))
evaporation[1] <- 0


#set depth of points, can be customised. N-1 in this case accounts for one customsied point, all others are the same
standard_depth = 0.5
z <- c(0.2, rep(standard_depth, n-1))

i=1

(2.501e6 - 2.365e3 * 25) * 18.02 * 1e-3)


#set parameter values
params <-
  tibble(
    R=3/365/24/60/60, #m^3 m^2 s^-1
    dsat = 1.4,
    nd = 6.5,
    theta_sat = 0.482,
    b=8,
    ksat=292.8,
    nk=11.9,
    I_constant = 1,
    lambda = 2450, #MJ kg^-1
    slp = 145, #Pa K^-1
    gamma = 66.1, #Pa K^-1
    theta_fc = 0.3,
    theta_wp = 0.05,
    swf = 1, # sensitivity power factor on empirical soil wetness curve
    r_soil = 0.6, #soil resistance to water infil
    LAI = 4,
    starting_day = 1,
    latitude = -23)

net_rad = map(c(1:3), ~calc_PPFD_instant(-23, .x)) %>%
  bind_rows() %>%
  mutate(PPFD_umol_m2_s_instant = PPFD_umol_m2_s_instant *umol_2_J) %>%
  pull(PPFD_umol_m2_s_instant)

for(t in times){
 
  I = (1-params$I_constant*(theta[t,1]/params$theta_sat)^params$b)
# 
  E_bare_soil_pot = (1-params$r_soil)*net_rad[t]*params$slp/((params$slp+params$gamma)*params$lambda)
  E_bare_soil = max(0,E_bare_soil_pot)
  Ev =  if_else(E_bare_soil == 0, 0, E_bare_soil*exp(-0.398*params$LAI))
  soil_wetness = ((theta[t,1] - params$theta_wp)/(params$theta_fc - params$theta_wp)) ^params$swf
  Ev = max (0, Ev * soil_wetness)

  inflow = params$R*I
  runoff_state = (params$R)*(1-I)
  drainage = 8.05e-6
  outflow = Ev
  
  theta[t+1,1] = (inflow - outflow)/z + theta[t,1]
 
  
  runoff[t+1] = runoff_state + runoff[t]
  cumulative_rain[t+1]= params$R + cumulative_rain[t]
  evaporation[t+1] = Ev + evaporation[t]
    
}

plot(theta~times)
data <- tibble(theta, runoff, cumulative_rain, evaporation)
```

```{r}

logistic_solution <-
  map_dfr(
    params,
    ~ode(
    y = theta_init,
    times = t,
    func = theta_rates,
    parms = .x) %>%
  as.data.frame())
```
