---
title: "water_bucket_model"
author: "Isaac Towers"
date: "19/05/2021"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r warning=FALSE}
rm(list=ls())

library(dplyr)
library(tidyr)
library(ggplot2)
library(purrr)
library(deSolve)


source("R/solar_model.R")
source("R/reference_leaf.R")
source("R/reference_soil.R")
```

```{r}
calc_PPFD_instant <- function(latitude, day, length.out = 86400) {
  given_day_start <- floor(day)
  instant_through_time <- seq(given_day_start, given_day_start+1, length.out = length.out)
  PPFD_instant_mol_m2_day <- PAR_given_solar_angle(solar_angle = solar_angle(latitude = (latitude), decimal_day_time = instant_through_time))
  tibble(PPFD_umol_m2_s_instant = PPFD_instant_mol_m2_day /(60*60*24) * 1E6, instant_of_day = instant_through_time - given_day_start, day = given_day_start, latitude = latitude)
}
```


```{r warning=FALSE}
#set time period and time step
t <- seq(0,8, by = 1)

#how many soil depths should be monitored
n=2

#set depth of points, can be customised. N-1 in this case accounts for one customsied point, all others are the same
standard_depth = 0.5
z <- c(0.022, rep(standard_depth, n-1))

i=1

species <- 5

#set vector to collect gradients 
dtheta_dt <- vector(length = n)
plant_water_use <- vector(length = n)
dLAI_dt <- vector(length = species)
E_supply_m_h <- vector(length = species)
a_i <- vector(length = species)
LAI_state <- vector(length = species)
E_supply_m_h <- vector(length = species)
theta_input <- 0.485
theta_fc = 0.321#field capacity of soil
theta_wp = 0.137#wilting point of soil
theta_sat <- 0.485                       

#set initial soil moisture content for each layer (boundary z[i] - z[i-1]) as well as the amount of water lost to deep drainage and runoff and the total amount of rainfall falling in period for sanity check, particulary important for when inclduing temporal variation

theta_init <- c(theta=rep(theta_input, n), runoff = 0, deep_drainage=0, cumulative_rain=0, evaporation = 0, drainage = 0, plant_water_use = rep(0,n), LAI_state = rep(0.1, species), a_i = rep(0, species), avg_theta = theta_input, avg_psi = calc_abs_psi(theta_input, theta_fc, theta_wp, theta_sat), total_E_supply_m_h = 0, E_supply_m_h = rep(0,species))

```

```{r warning=FALSE}
#soil moisture drainage model

theta_rates <- function(t, theta, params) {
  with(as.list(c(theta, params)), {

   
    
    I = (1-I_constant*(theta[1]/theta_sat)^b_infil)
    S = R*sin(t*2*pi/frequency)

    #umol/m2/s
    PPFD = mean_PPFD*sin(t/12*pi-8) + mean_PPFD
    
    avg_theta <- calc_avg_theta(theta)
    avg_psi <- calc_abs_psi(avg_theta, theta_fc, theta_wp, theta_sat)
    avg_psi_MPa <- avg_psi*Pa_2_MPa
    
    p50 <- seq(from = 2, to = 8, length.out = 5)
    
    K_s = p_50_2_K_s(p50) #kg m^-1 s^-1 MPa ^-1 Liu et al. 2010 
    b = calc_vul_b(p_50 = p50, c = c)
    k_l_max = calc_k_l_max(K_s, h_v, h)
    psi_crit = calc_psi_crit(b, c)
        
    for(j in 1:species){

    opt_psi_stem <- find_opt_psi_stem_bartlett(psi_soil = avg_psi_MPa, k_l_max=  k_l_max[j], vcmax =vcmax, PPFD = PPFD, b = b[j], c= c, psi_crit = psi_crit[j],atm_vpd =  VPD,ca = ca, beta = beta1, beta_2 = beta2, huber_value = h_v, height= h)
    
    
    LAI_state_5 <- c(LAI_state1, LAI_state2, LAI_state3, LAI_state4, LAI_state5)

    
    E_supply_kg_m2_s <- opt_psi_stem$E_root
    
    E_supply_m_h[j] <- E_supply_kg_m2_s * sec_2_hr * kg_2_m3 * LAI_state_5[j]
    
    a_i_umol_m2_s <- opt_psi_stem$profit_root
    a_i_mol_m2_h <- a_i_umol_m2_s *sec_2_hr * umol_2_mol
    a_i[j] <- a_i_mol_m2_h
    
    
    dLAI_dt[j] <- calc_LAI(LAI = LAI_state_5[j], lma = lma, r_l = r_l, fr_l = fr_l, a_bio = a_bio, k_l = k_l, a_i = a_i[j])

    }
    total_E_supply_m_h <- sum(E_supply_m_h)
    
    
    for(i in 1:n){
    
    #top layer. Non-infiltrating rainfall is stored in runoff, but leaves the plant-accessible water budget forever. 
      if(i == 1) {
    
    if(evap_routine == 1){
    
    #mol/m2/s  
    E_bare_soil_pot_mol = (1-r_soil)*PPFD*PAR_2_SW*slp/((slp+gamma)*lh)
    
    #m3/m2/s
    E_bare_soil_pot_m = E_bare_soil_pot_mol*MH2O*g_2_kg*kg_2_m3
    E_bare_soil_pot_m = max(0,E_bare_soil_pot_m)
    
    #m3/m2/s
    Ev = E_bare_soil_pot_m*exp(-0.398*LAI_state)
    soil_wetness = ((theta[i] - theta_wp)/(theta_fc - theta_wp)) ^swf
    
    #m3/m2/h
    Ev = max (0, Ev * soil_wetness) * sec_2_hr
    }
    
    if(evap_routine == 2){
    #m/s
    gc = gc_max * (theta[1]/theta_sat)
    
    #m3/m2/h
    Ev = (slp*PPFD*PAR_2_SW + gb*1.204*1004*VPD)/(slp+gamma*(1+gb/gc))/(2.45e6)*kg_2_m3*sec_2_hr
    }

    inflow = (R+S)*I
    runoff = (R+S)*(1-I)
    drainage = (-d_sat*(theta[i]/theta_sat)^(npsi+2))*((theta[i+1]-theta[i])/(z[i]/2 + z[i+1]/2))*sec_2_hr
    outflow = drainage + Ev +total_E_supply_m_h *(z[i]/sum(z))
    
      }
    
    #middle layers  
      if(!i %in% c(1, n)) {
     inflow = (-dsat*(theta[i-1]/theta_sat)^nd)*((theta[i]-theta[i-1])/z[i])
     outflow= (-dsat*(theta[i]/theta_sat)^nd)*((theta[i+1]-theta[i])/z[i+1])
      }
      
    # last layer - water that outflows from this layer is gone forever. Values are stored in deep_drainage.
      if(i == (n)) {
    inflow = drainage
    deep_drainage = ((ksat)*(theta[i]/theta_sat)^(2*npsi+3)) *sec_2_hr
    outflow = deep_drainage + total_E_supply_m_h *(z[i]/sum(z))
    
      }
    
       
    dtheta_dt[i] = (inflow - outflow)/z[i]
    runoff = runoff
    deep_drainage = deep_drainage
    cumulative_rain = R+S
    evaporation = Ev
    plant_water_use[i] = total_E_supply_m_h *(z[i]/sum(z))

    }
    
    return(list(c(dtheta_dt, runoff, deep_drainage, cumulative_rain, evaporation, drainage, plant_water_use, dLAI_dt, a_i, avg_theta, avg_psi,total_E_supply_m_h, E_supply_m_h)))
    
  })
}



```


```{r}
params <- set_params_soil(R = c(0.5, 3)/365/24, mean_PPFD = 1000, evap_routine = "1")
```

```{r}
t <- seq(0,8640, by = 1)

logistic_solution2<-
  map_dfr(
    params,
    ~ode(
    y = theta_init,
    times = t,
    func = theta_rates,
    parms = .x)  %>%
      as.data.frame()%>%
      mutate(evap_routine = if_else(.x$evap_routine == 1, "Sabot", "Landsberg_Sands"),
             day = rep(seq(1:ceiling(nrow(.)/24)), each = 24)[1:nrow(.)],
             evap_diff = c(0, diff(evaporation)),
             plant_water_use1_diff = c(0, diff(plant_water_use1)),
             plant_water_use2_diff = c(0, diff(plant_water_use2)),
             rain_diff = c(0, diff(cumulative_rain)),
             avg_psi_diff = c(0, diff(avg_psi)),
             avg_theta_diff = c(0, diff(avg_theta)),
             drainage_diff = c(0, diff(drainage)),
             deep_drainage_diff = c(0, diff(deep_drainage)),
             theta_sat = .x$theta_sat,
             a_i1_diff = c(0, diff(a_i1)),
             a_i2_diff = c(0, diff(a_i2)),
             E_supply_m_h1_diff = c(0, diff(E_supply_m_h1)),
             E_supply_m_h2_diff = c(0, diff(E_supply_m_h2)))
  )
```

```{r}
png("example_plot.png", height = 400, width = 400)

logistic_solution2$rainfall <- rep(c("0.5 m/yr", "3 m/yr"), each = 8641)

logistic_solution2 %>%
  filter(time != 0) %>%
  select(time, contains("LAI_state"), rainfall) %>% 
  rename(Rainfall = rainfall) %>%
  pivot_longer(contains("LAI"), names_to = "p50")%>%
  ggplot(aes(x = time)) +
  geom_line(aes(y=value, col =p50, linetype = Rainfall)) + 
  ylab("LAI") +
  xlab("Hours") + 
  theme_classic()

logistic_solution2 %>%
  filter(time != 0) %>%
  select(time, avg_psi_diff, rainfall) %>%
  ggplot() +
  geom_line(aes(x=time, y=avg_psi_diff, linetype = rainfall))


```


```{r}


pivot_longer(contains("MPa"), names_to = "p50") %>%
  ggplot(aes(x = time)) +
  geom_line(aes(y=value, col =name, linetype = rainfall))
  geom_line(aes(y=rain_diff*10000), linetype = "dashed") +
  xlab("Time (hrs)") +
  theme_classic() +
  scale_y_continuous(
  name = (expression(LAI~(m^2~leaf~"/"~m^2~ground))),
  sec.axis = sec_axis(~./10000, name = expression(Rainfall~(m/"hr;"~dashed)))
  )



logistic_solution1 %>%
  filter(time != 0) %>%
  select(time, contains("LAI_state"), rain_diff) %>% 
  pivot_longer(contains("LAI_state")) %>%
  ggplot(aes(x = time)) +
  geom_line(aes(y=value, col =name))
  geom_line(aes(y=rain_diff*10000), linetype = "dashed") +
  xlab("Time (hrs)") +
  theme_classic() +
  scale_y_continuous(
  name = (expression(LAI~(m^2~leaf~"/"~m^2~ground))),
  sec.axis = sec_axis(~./10000, name = expression(Rainfall~(m/"hr;"~dashed)))
  )




logistic_solution1 %>%
  filter(time != 0) %>%
  select(time, LAI_state, rain_diff) %>% 
  ggplot(aes(x = time)) +
  geom_line(aes(y=LAI_state)) +
  geom_line(aes(y=rain_diff*10000), linetype = "dashed") +
  xlab("Time (hrs)") +
  theme_classic() +
  scale_y_continuous(
  name = (expression(LAI~(m^2~leaf~"/"~m^2~ground))),
  sec.axis = sec_axis(~./10000, name = expression(Rainfall~(m/"hr;"~dashed)))
  )

logistic_solution1 %>%
  filter(time != 0) %>%
  select(time, LAI_state, rain_diff) %>% 
  ggplot(aes(x = time)) +
  geom_line(aes(y=LAI_state)) +
  geom_line(aes(y=rain_diff*10000), linetype = "dashed") +
  xlab("Time (hrs)") +
  theme_classic() +
  scale_y_continuous(
  name = (expression(LAI~(m^2~leaf~"/"~m^2~ground))),
  sec.axis = sec_axis(~./10000, name = expression(Rainfall~(m/"hr;"~dashed)))
  )

png("example_plot_gradient.png", height = 400, width = 400)

logistic_solution1 %>%
  filter(time != 0) %>%
  select(time, LAI_state, rain_diff,evap_routine) %>% 
  ggplot(aes(x = time)) +
  geom_line(aes(y=LAI_state, colour= rain_diff, group = evap_routine), size =3) +
  scale_colour_gradient2(low = "red", mid = "yellow" , high = "blue", 
                         midpoint=median(logistic_solution1$rain_diff)) +
  xlab("Time (hrs)") +
  theme_classic() +
  scale_y_continuous(
  name = (expression(LAI~(m^2~leaf~"/"~m^2~ground)))) +
    labs(colour = expression(Rainfall~(m/"hr")))

dev.off()

 



dev.off()

logistic_solution1 %>%
  mutate(PPFD = 1079.901*sin(0:8640/12*pi-8) + 1079.901) -> logistic_solution1

logistic_solution1 %>%
  filter(time %in% 1:500) %>%
  filter(time != 0) %>%
  mutate(PPFD_diff = c(0, diff(PPFD))) %>%
  select(time, LAI_state, PPFD) %>% 
  ggplot(aes(x = time)) +
  geom_line(aes(y=LAI_state)) +
  geom_line(aes(y=PPFD/2000), linetype = "dashed") +
  xlab("Time (hrs)") +
  theme_classic() +
  scale_y_continuous(
  name = (expression(LAI~(m^2~leaf~"/"~m^2~ground))),
  sec.axis = sec_axis(~., name = expression(PPFD~(m/"hr;"~dashed)))
  )

logistic_solution1 %>%
  select(time, LAI_variable) %>% 
  ggplot(aes(x = time)) +
  geom_line(aes(y=LAI_variable))


logistic_solution1 %>%
  select(time, theta1, theta2, evap_routine, LAI, -theta_sat) %>%
  pivot_longer(.,c(theta1, theta2))  %>%
  ggplot(aes(x = time)) +
  geom_line(aes(y=value, col=name, linetype = evap_routine)) +
  scale_y_log10() +
  facet_wrap(~LAI)

logistic_solution1 %>%
  select(time, plant_water_use1_diff, plant_water_use2_diff) %>%
  pivot_longer(., c(plant_water_use1_diff, plant_water_use2_diff))  %>%
  ggplot(aes(x = time)) +
  geom_line(aes(y=value, col=name))


logistic_solution1 %>%
  select(time, psi1, psi2, evap_routine, LAI, -theta_sat) %>%
  pivot_longer(., c(psi1, psi2))  %>%
  mutate(value = -value) %>%
  ggplot(aes(x = time)) +
  geom_line(aes(y=value, col=name, linetype = evap_routine)) +
  scale_y_log10() +
  facet_wrap(~LAI)


logistic_solution1 %>%
  select(day, contains("psi"), evap_routine, LAI) %>%
  group_by(day, evap_routine, LAI) %>%
  summarise(psi1 = mean(psi1), psi2 = mean(psi2)) %>%
  mutate(psi1 = -psi1,
         psi2 = -psi2) %>%
  pivot_longer(., contains("psi"))  %>%
  ggplot(aes(x = day)) +
  geom_line(aes(y=value, col=name, linetype = evap_routine)) +
  scale_y_log10() +
  facet_wrap(~LAI)
 

logistic_solution1 %>%
  select(time, evap_diff, evap_routine, rain_diff) %>%
  ggplot(aes(x = time)) +
  geom_line(aes(y=evap_diff, col = evap_routine)) +
  geom_line(aes(y=rain_diff))

logistic_solution1 %>%
  mutate(z1 = z[1], z2= z[2]) %>%
  mutate(avg_theta = (theta1*z1 + theta2*z2)/(z1 + z2)) %>%
  mutate(avg_psi = a_psi*(avg_theta/theta_sat)^(-n_psi)) %>%
  select(time, avg_psi, evap_routine) %>%
  ggplot(aes(x = time)) +
  geom_line(aes(y=avg_psi, col = evap_routine)) +
  theme_classic()

logistic_solution1 %>%
  mutate(z1 = z[1], z2= z[2]) %>%
  mutate(avg_theta = (theta1*z1 + theta2*z2)/(z1 + z2)) %>%
  select(time, LAI, avg_theta, evap_routine) %>%
  ggplot(aes(x = time)) +
  geom_line(aes(y=avg_theta, col = evap_routine)) +
  theme_classic() +
  facet_wrap(~LAI)

logistic_solution1 %>%
  select(contains("theta"), day, evap_routine, -theta_sat) %>%
  pivot_longer(contains("theta")) %>%
  group_by(day, evap_routine, name) %>%
  summarise(value = mean(value)) %>%
  ggplot(aes(x = day)) +
  geom_line(aes(y=value, col = evap_routine, linetype = name)) +
  theme_classic()

logistic_solution1 %>%
  select(time, runoff, evap_routine, LAI) %>%
  ggplot(aes(x = time)) +
  geom_line(aes(y=runoff, col = evap_routine)) +
  theme_classic() +
  facet_wrap(~LAI)

logistic_solution1 %>%
  select(time, evaporation, evap_routine, LAI) %>%
  ggplot(aes(x = time)) +
  geom_line(aes(y=evaporation, col = evap_routine)) +
  theme_classic() +
  facet_wrap(~LAI)


logistic_solution1 %>%
  select(time, deep_drainage_diff, drainage_diff, evap_routine) %>%
  ggplot(aes(x = time)) +
  geom_line(aes(y=drainage_diff, col = evap_routine)) +
  geom_line(aes(y=deep_drainage_diff, linetype = evap_routine)) +
  theme_classic()
 

logistic_solution1 %>%
  filter(time %in% 1:1000) %>%
  select(contains("theta"), time, evap_routine, -theta_sat) %>%
  pivot_longer(contains("theta")) %>%
  ggplot(aes(x = time)) +
  geom_line(aes(y=value, col = evap_routine, linetype = name)) +
  theme_classic()

logistic_solution1 %>%
  filter(time %in% 1:(8760*2)) %>%
  select(evap_diff, evap_routine, day) %>%
  group_by(day, evap_routine) %>%
  summarise(evap_diff_avg = mean(evap_diff)) -> logistic_solution1_avg


logistic_solution1 %>%
  left_join(logistic_solution1_avg) %>%
  filter(time %in% 1:(8760*2)) %>%
  select(evap_diff, time, evap_routine, evap_diff_avg) %>%
  ggplot(aes(x = time)) +
  geom_line(aes(y=evap_diff, col = evap_routine)) +
  geom_line(aes(y=evap_diff_avg, col = evap_routine))+
  theme_classic()
 
```
