---
title: "Modelling the demography of plants, patches, and metacommunities"
author:
- Daniel Falster
- Ake Brannstrom
- Ulf Dieckmann
date: 2016
bibliography: assets/refs.bib
csl: assets/methods-in-ecology-and-evolution.csl
output:
  bookdown::html_document2:
    toc: yes
---

# Introduction

This document outlines methods used to model demography in the `plant`
package. We first outline the system of equations being solved. These equations were primarily
developed elsewhere, in particular in @Falster-2011 and
@Falster-2015, following general principles laid out in
@Deroos-1997, @Kohyama-1993, and @Moorcroft-2001. They are presented here so that
users can understand the full system of equations being solved within `plant`.
We then describe the numerical techniques used to solve the equations.
Table \@ref(tab:definitions) provides a list of names and definitions used
throughout this document.


```{r definitions, echo=FALSE, results='asis'}
x <- read.csv("assets/demography-vars.csv")
knitr::kable(x,  align = "l",
  caption = 'Variable names and definitions in the demographic model of the `plant` package.'
)
```

# Metacommunity dynamics {#system-dynamics}

The following material is written assuming there exists a physiological sub-model
that takes as inputs a plant's traits $x$, height $H$, and light environment $E_a$,
and returns rates of growth, mortality, and fecundity. The physiological model must
describe how much leaf area the plant contributes to shading other plants in the patch.
Specifically, the physiological model is responsible for calculating the following
variables from Table \@ref(tab:definitions):
$A_{\rm l}(H)$, $Q(z, H)$, $H_0(x)$, $g(x, H, E_a)$, $f(x, H, E_a)$, $d(x, H, E_a)$, and
$S_{\rm G} (x, H_0, E_{{\rm a}0})$.
All are other variables in Table \@ref(tab:definitions) are calculated in the
demographic model using the equations provided below.

## Individual plants {#individual-plants}

We first consider the dynamics of an individual plant. Throughout, we refer to a
plant as having traits $x$ and size $H$, with the latter given by its height. The
plant grows in a light environment $E$, a function describing the distribution
of light with respect to height within a patch. Ultimately, $E$ depends on the
composition of plants in a patch, and thus on the patch age $a$. To indicate this dependence, we
write $E_a$. Further, let $a_0$be the age in which the plant germinated, and $H_0(x)$ its initial height. The functions $g(x, H, E_a)$, $f(x, H, E_a)$, and
$d(x, H, E_a)$ denote the growth, death, and fecundity rates of the
plant. Then,
\begin{equation}
H(x, a_0, a) = H_0(x) + \int_{a_0}^{a} g(x, H(x, a_0, a^\prime), E_{a^\prime}) \, {\rm d}a^\prime
(\#eq:size)
\end{equation}
is the trajectory of plant height,
\begin{equation}
S_{\rm I} (x, a_0, a) = S_{\rm G} (x, H_0, E_{{\rm a}0}) \, \exp\left(- \int_{a_0}^{a} d(x, H(x, a_0, a^\prime), E_{a^\prime}) \, {\rm d} a^\prime \right)
(\#eq:survivalIndividual)
\end{equation}
is the probability of plant survival within the patch, where $S_{\rm G} (x, H_0, E_{{\rm a}0})$
is the probability a seed germinates successfully, and
\begin{equation}
\tilde{R}(x, a_0, a) = \int_{a_0}^{a} f(x, H(x, a_0, a^\prime), E_{a^\prime}) \, S_{\rm I} (x, a_0, a^\prime) \, {\rm d} a^\prime
(\#eq:tildeR1)
\end{equation}
is the plant's cumulative seed output, from its birth at patch age
$a = a_0$ until patch age $a$.

The notational complexity required in Eqs. \@ref(eq:size)-\@ref(eq:tildeR1) potentially obscures an important point: these equations are simply the general, non-linear solutions to
integrating growth, mortality, and fecundity over time.

## Patches of competing plants {#patches-of-competing-plants-size-structured-populations}

We now consider a patch of competing plants. At any age $a$, the
patch is described by the size-density distribution $N(H | x, a)$ of plants
with traits $x$ and height $H$. In a finite-sized patch, $N$ is described by a
collection of points, each indicating the height of one individual, whereas in a very (infinitely) large patch,
$N$ is a continuous function. In either case, the demographic
behaviour of the plants within the patch is given by Eqs. \@ref(eq:size)-\@ref(eq:tildeR1). Integrating the dynamics over time is complicated by-
two other factors: (i) plants interact, thereby altering $E_a$ with
age, and (ii) new individuals may establish, expanding the system of
equations.

In the current version of `plant`, plants interact by shading one another.
Following standards biophysical principles, we let the canopy openness
$E_a(z)$ at height $z$ in a patch of age $a$ decline exponentially
with the total amount of leaf area above $z$,
\begin{equation}
E_a(z) = \exp \left(-k_{\rm I} \sum_{i = 1}^{K} \int_{0}^{\infty} A_{\rm l}(H) \, Q(z, H) \, N(H | x_i, a) \, {\rm d}H \right),
(\#eq:light)
\end{equation}
where $A_{\rm l}(H)$ is the total leaf area of a plant with height $H$, $Q(z, H)$ is the fraction of
this leaf area situated above height $z$ for plants of height $H$,
$k_{\rm I}$ is the light extinction coefficient, and $K$ is the number
of species in the metacommunity.

Assuming patches are sufficiently large, the dynamics of $N$ can be modelled
deterministically via the following partial differential equation (PDE)
[@Kohyama-1993, @Deroos-1997, @Moorcroft-2001],
\begin{equation}
\frac{\partial}{\partial a} N(H | x, a) = - d(x, H, E_a) \, N(H | x, a) - \frac{\partial}{\partial H} \left[g(x, H, E_a) \, N(H | x, a)\right].
(\#eq:PDE)
\end{equation}
See section [derivation-of-pde-describing-size-structured-dynamics](#derivation-of-pde-describing-size-structured-dynamics) for the derivation of this PDE.

Eq. \@ref(eq:PDE) has two boundary conditions. The first links the
flux of individuals across the lower bound $(H_0(x))$ of the size-density
distribution to the rate $Y_{x}$ at which seeds arrive in the patch,
\begin{equation}
N(H_0 | x, a_0) = \left\{
\begin{array}{ll} \frac{Y_{x} \, S_{\rm G} (x, H_0, E_{{\rm a}0}) }{ g(x, H_0, E_{{\rm a}0}) } & \textrm{if } g(x, H_0, E_{{\rm a}0}) > 0 \\
0 & \textrm{otherwise.}
\end{array} \right.
(\#eq:BC1)
\end{equation}
The function $S_{\rm G} (x, H_0, E_{{\rm a}0})$ denotes survival through
germination and must be chosen such that
$S_{\rm G} (x, H_0, E_{{\rm a}0}) / g(x, H_0, E_{{\rm a}0}) \rightarrow 0$ as
$g(x, H_0, E_{{\rm a}0}) \rightarrow 0$, to ensure a smooth decline in
initial density as conditions deteriorate [@Falster-2011].

The second boundary condition of Eq. \@ref(eq:PDE) specifies the initial size-density
distribution in patches right after a disturbance, i.e., for $a = 0$. Throughout, we consider only
situations starting with an empty patch,
\begin{equation}
N\left(H|x,0\right) = 0,
(\#eq:BC2)
\end{equation}
although non--zero distributions could alternatively be specified
[e.g. @Kohyama-1993, @Moorcroft-2001].

## Age structure of patches {#age-structured-distribution-of-patches}

We now consider the distribution of patch age $a$ in the metacommunity.
With $a$ denoting the time since last disturbance, $P(a)$ denotes the
frequency-density of patch age $a$ and $d_{\rm P}(a)$ is the
age-dependent probability that a patch of age $a$ is transformed into
a patch of age 0 by a disturbance event. Here we focus on situations
where the age structure has reached an equilibrium. See section
[derivation-of-pde-describing-age-structured-dynamics](#derivation-of-pde-describing-age-structured-dynamics) for the derivation and
non-equilibrium situations. The dynamics of $P$ are given by
[@Mckendrick-1926, @Vonfoerster-1959]
\begin{equation}
\frac{{\rm d}}{{\rm d} a} P(a) = - d_{\rm P}(a) \, P(a) ,
(\#eq:agepde)
\end{equation}
with the boundary condition
\begin{equation}
P(0) = \int_0^\infty d_{\rm P}(a) \, P(a) \, {\rm d} a.
(\#eq:agepd2)
\end{equation}
The probability that a patch remains undisturbed from patch age $a_0$ to patch age $a$ is
then given by
\begin{equation}
S_{\rm P} (a_0, a) = \exp\left( - \int_{a_0}^{a} d_{\rm P}(a^\prime) \, {\rm d} a^\prime \right).
(\#eq:survivalPatch)
\end{equation}
These equations lead to an equilibrium distribution of patch ages,
\begin{equation}
P(a) = P(0) S_{\rm P} (0, a),
(\#eq:agepde3)
\end{equation}
where
\begin{equation}
P(0) = \frac1{\int_0^\infty S_{\rm P} (0, a) {\rm d}a}
(\#eq:agepde4)
\end{equation}
is the average disturbance frequency of a patch and, at the same time, the frequency-density of patches of
age $0$.

The default approach in `plant` is to assume that $d_{\rm P}(a)$
increases linearly with patch age, which leads to a Weibull distribution for $P$,
specified by a single parameter $\bar{a}$
measuring the mean interval between disturbances (see section [derivation-of-pde-describing-age-structured-dynamics](#derivation-of-pde-describing-age-structured-dynamics) for details).

## Trait-, size-, and patch-structured metacommunities {#trait--size--and-patch-structured-metapopulations}

We consider a large area of habitat where: (i) disturbances (such as fires,
storms, landslides, floods, or disease outbreaks) strike patches of the
habitat on a stochastic basis, killing all individuals within the affected
patches; (ii) individuals compete for resources within patches, with a
spatial scale of competitive interactions that renders negligible such interactions between
individuals in adjacent patches; and (iii) there is high
connectivity via dispersal between all patches in the habitat, allowing
empty patches to be quickly re-colonised. Such a system can be modelled
as a metapopulation (for a single species) or metacommunity (for multiple
species). The dynamics of such a metacommunity are described by the
PDEs in Eqs. \@ref(eq:PDE)-\@ref(eq:agepde4).

The seed rain of each species in the metacommunity is given by the rate at which seeds are produced across all patches,
\begin{equation}
Y_x  = \int_0^{\infty} \int_0^{\infty} P(a) \, S_{\rm D} \, f(x, H, E_a) \, N(H | x, a) \, {\rm d} H \, {\rm d} a,
(\#eq:seed-rain)
\end{equation}
where $S_{\rm D}$ is the survival probability of seeds during dispersal.

A convenient feature of Eqs. \@ref(eq:PDE) - \@ref(eq:agepde4) is that
the dynamics of a single patch scale up to give the dynamics of the
entire metacommunity. Note that the rate $Y_x$ at which offspring of individuals with traits $x$ arrive from the
disperser pool is constant when the metacommunity is at
equilibrium. Combined with the assumption that all patches have the same
initial (empty) size-density distribution after a disturbance, the assumption of constant seed rains
ensures that all patches show the same temporal behaviour, the only
difference between them being their ages.

To model the temporal dynamics of an archetypal patch, we need only a
value for $Y_x$. The numerical challenge is therefore to find the
right value for $Y_x$, by solving Eqs. \@ref(eq:BC1)-\@ref(eq:seed-rain) simultaneously, for all species with traits $x$ in the metacommunity.

## Emergent properties of metacommunities {#emergent-properties-of-metapopulation}

Summary statistics of a metacommunity are obtained by integrating
over the size-density distribution, weighting by the frequency-density $P(a)$.
In particular, the average density of individuals per unit ground area across the metacommunity is
\begin{equation}
\hat{N}(x) = \int_{0}^{\infty} \int_{0}^{\infty} P(a) \, N(H | x, a) \, {\rm d}a \, {\rm d}H,
(\#eq:Nav)
\end{equation}
and the average size-density of plants with height $H$ is
\begin{equation}
\bar{N}(x, H) = \int_{0}^{\infty}P(a) \, N(H | x, a) \, {\rm d}a.
(\#eq:NDav)
\end{equation}

Averages for other individual-level quantities can also be calculated.
Denoting by
$w(x, H, E_a)$ a quantity of interest, either a demographic rate
(growth, mortality) or a state (plant height, leaf area, light environment),
the average of $w$ for plants with height $H$ and traits $x$ is
\begin{equation}\bar{w}(x, H) = \frac1{\bar{N}(x, H)}\int_{0}^{\infty}P(a) \, N(H | x, a) \, w(x, H, E_a) \, {\rm d}a.
(\#eq:Wav1)
\end{equation}
The average of $w$ across all individuals of the species is
\begin{equation}
\hat{w}(x) = \frac1{\hat{N}(x) }\int_{0}^{\infty} \int_{0}^{\infty}P(a) \, N(H | x, a) \, w(x, H, E_a) \, {\rm d}a \, {\rm d}H.
(\#eq:Wav2)
\end{equation}
When calculating the average mortality rate, one must decide whether
mortality due to patch disturbance is included. Non-disturbance mortality
is obtained by setting $w(x, H, E_a) = d(x, H, E_a)$, while the total
mortality due to growth processes and disturbance is obtained by setting
$w(x, H, E_a) = d(x, H, E_a) + d_{\rm P}(a) S_{\rm P}(0, a).$

Similarly, we can integrate over the size-density distribution to extract aggregate
features of the vegetation within a patch,
\begin{equation}
W(a) = \sum_{i = 1}^{N} \int_{0}^{\infty} N(H | x_i, a)\, w(x_i, H, E_a) \, {\rm d}H,
(\#eq:Wa-a)
\end{equation}
and across the entire metacommunity,
\begin{equation}
\hat{W} = \int_{0}^{\infty} P(a) \, W(a) \, {\rm d}a.
(\#eq:Wa-b)
\end{equation}

## Invasion fitness {#invasion-fitness}

We now consider how to estimate the fitness of a rare mutant individual
with traits $x^\prime$ growing in the light environment of a resident
community with traits $x$. We focus on phenotype-dependent components
of fitness -- describing the aggregate consequences of a given set of traits for growth,
fecundity, and mortality -- taking into account the non-linear effects of
competition, but ignoring the underlying genetic
basis for trait inheritance and expression. We also adhere to standard
conventions in such analyses by assuming that the mutant phenotype is sufficiently
rare to have a negligible effect on the light environment where it is growing [@Geritz-1998].
The approach for calculating fitness implemented here follows the approach
described by @Falster-2015.

In general, invasion fitness is defined as the long-term per capita
growth rate of a rare mutant phenotype in the environment
determined by a resident phenotype [@Metz-1992]. Calculating
per capita growth rates, however, is particularly challenging in a
structured metacommunity model [@Gyllenberg-2001, @Metz-2001]. As
an alternative measure of invasion fitness in metacommunities, we can use the basic reproduction
ratio measuring the expected number of new dispersers arising from a
single dispersal event. For metacommunities at demographic equilibrium, evolutionary inferences made using basic
reproduction ratios are equivalent to those made using per capita growth
rates
[@Gyllenberg-2001, @Metz-2001].

We denote by $R\left(x^\prime, x\right)$ the basic reproduction ratio of
individuals with traits $x^\prime$ growing in the competitive
light environment of the resident traits $x$. Recalling that patches of age
$a$ have frequency-density $P(a)$ in the landscape, it follows that any seed
with traits $x^\prime$ has a probability of $P(a)$ of landing in a patch of age
$a$. The basic reproduction ratio for individuals with traits
$x^\prime$ is then
\begin{equation}
R\left(x^\prime,x\right) = \int _0^{\infty} P\left(a\right) \, \tilde{R}\left(x^\prime, a, \infty \right) \, {\rm d}a ,
(\#eq:InvFit)
\end{equation}
where $\tilde{R}\left(x^\prime, a_0, a \right)$ is the expected number
of dispersing offspring produced by a single dispersing seed with traits $x^\prime$ arriving in
a patch of age $a_0$ up until age $a$
[@Gyllenberg-2001, @Metz-2001].
In turn, $\tilde{R}\left(x^\prime, a,\infty\right)$ is calculated by integrating
an individual's fecundity over the expected lifetime of a patch, taking
into account competitive shading from residents with traits $x$, the
individual's probability of surviving, and its traits,
\begin{equation}
\tilde{R}(x^\prime, a_0, \infty) = \int_{a_0}^{\infty} S_{\rm D} \, f(x^\prime, H(x^\prime, a_0, a), E_{a}) \, S_{\rm I} (x^\prime, a_0, a) \, S_{\rm P} (a_0, a) \, {\rm d} a.
(\#eq:tildeR)
\end{equation}

# Numerical methods for solving metacommunity dynamics

The equations below describe how we solve the trait-, size-, and patch-structured
population dynamics specified in the previous section.
Our approach to solving for the size-density distribution is based on the characteristic method [@Angulo-2004, @Angulo-2014, @Angulo-2016]. The characteristic method is related to
the Escalator Boxcar Train technique
[@Deroos-1988, @Deroos-1997, @Deroos-1992], but not identical to it.

When simulating an individual plant, or the development of a
patch, we need to solve for the size, survival, and seed
output of individual plants. When solving for the size-density distribution
in a large patch, we also need to estimate the average abundance of individuals.
Each of these problems is formulated as an initial-value ODE problem
(IVP), which can be solved using an ODE stepper.

## Approach {#approach}

### Size {#size}

The size of an individual is obtained via Eq. \@ref(eq:size) which is solved via the IVP
\begin{equation}
\frac{dy}{dt} = g(x, y, t) ,
(\#eq:size-y)
\end{equation}

\begin{equation}
 y(0) = H_0(x).
(\#eq:size-y0)
\end{equation}

### Survival {#survival}

The probability of an individual surviving from patch age
$a_0$ to patch age $a$ is obtained via Eq. \@ref(eq:survivalIndividual),
which is solved via the IVP
\begin{equation}
\frac{dy}{dt} = d(x, H_i(t) , E_t),
(\#eq:surv-y)
\end{equation}

\begin{equation}
 y(0) = - \ln\left(S_{\rm G} (x, H_0, E_{a0})\right) .
(\#eq:surv-y0)
\end{equation}

Survival is then
\begin{equation}
 S_{\rm I} (x, a_0, a) = \exp\left( - y(a) \right).
(\#eq:surv-SI)
\end{equation}

### Seed production {#seed-production}

The lifetime seed production of individuals is
obtained via Eq. \@ref(eq:tildeR1), which is solved via the IVP
\begin{equation}
\frac{dy}{dt} = S_{\rm D} \, f(x, H_i(t), E_t) \, S_{\rm I} (x, a_0,t) \, S_{\rm P} (a_0, t),
(\#eq:dy)
\end{equation}

\begin{equation}
 y(0) = 0,
(\#eq:y0)
\end{equation}
where $S_{\rm I}$ is calculated as described
above and $S_{\rm P}$ is calculated as in Eq. \@ref(eq:survivalPatch)$.

### Size-density of individuals {#density-of-individuals}

By integrating along the characteristics of Eq. \@ref(eq:PDE),
the size-density of individuals born with height $H_0$ and traits $x$ at patch age $a_{0}$ is given by
[@Deroos-1997, @Angulo-2004]
\begin{equation}
N(H | x, a) = N(H_0 | x, a_0)
\exp \left( - \int _{a_0}^{a} \left[\frac{\partial g(x, H(x, a_0, a^\prime), E_{a^\prime})}{\partial H} + d(x, H(x, a_0, a^\prime), E_{a^\prime})\right] {\rm d} a^\prime \right).
(\#eq:boundN)
\end{equation}
Eq. \@ref(eq:boundN) states that the size-density $N$ at a specific patch age $a$ is
the product of the size-density at patch age $a_{0}$ adjusted for changes through
growth and mortality. Size-density decreases through time because of
mortality, as in a typical survival equation, but also changes
because of growth. If growth is slowing with size, (i.e.,
$\partial g / \partial H < 0$), size-density will increase since the
characteristics compress. Conversely, size-density will increases if
$\partial g / \partial H > 0$.

Denoting by $\left[H_0, H_{ + } \right)$ the range of heights
attainable by any individual, our algorithm for solving metacommunity dynamics proceeds by sub-dividing
this interval into a series of cohorts with heights
$H_0 < H_1 < \ldots < H_k$ at the initial points of the characteristic curves. These cohorts are then transported along
the characteristics of Eq. \@ref(eq:PDE). The placement of cohorts
is controlled indirectly, via the schedule of patch ages at which
new cohorts are introduced into the metacommunity. We then track the
demography of each such cohort.

The integral in Eq. \@ref(eq:boundN) is solved via the IVP
\begin{equation}
\frac{dy}{dt} = \frac{\partial g(x, H_i(t), E_t)}{\partial H} + d(x, H_i(t), E_t),
(\#eq:dy-N)
\end{equation}

\begin{equation}
 y(0) = - \ln\left(N(H_0 | x, a_0) \, S_{\rm G} (x, H_0, E_{{\rm a}0}) \right),
(\#eq:y0-N)
\end{equation}
from which we obtain the size-density
\begin{equation}
N(H_0 | x, a_0) = \exp( - y(a)).
(\#eq:N-H0)
\end{equation}

## Controls on approximation error

We now outline how to control the error of the approximate solutions
to the system of equations described above. In our algorithm, numerical solutions are required to address a variety of problems:

- To estimate the amount of light at a given height in a patch requires
numerically integrating over the size-density distribution within that patch.
- To calculate the
assimilation of a plant requires numerically integrating
photosynthesis over this light profile.
- To simulate patch dynamics
requires numerically identifying a vector of patch ages at which new cohorts are
introduced, and then numerically stepping the equations for each cohort forward in time to
estimate their size, survival, and fecundity at different subsequent patch ages.
- To solve for the initial height of a plant given
its seed mass, and for the equilibrium seed rains across the
metacommunity, requires numerical root finding.


As with all numerical techniques, solutions to each of these problems are
accurate only up to a specified level. These levels are controlled
via parameters in the `plant` code. Below, we
provide a brief overview of the different numerical techniques being
applied and outline how error tolerance can be increased or decreased.
We refer to various control parameters that can be found within the
`control` object. For a worked example illustrating how to modify these control parameters,
see the section `parameters` of Appendix S3.

### Initial plant heights {#initial-height-of-plants}

When a seed germinates, it produces a seedling of given height. The
height of these seedlings is assumed to vary with the seed mass.
Because there is no analytical solution relating seedling height to seed
mass -- at least when using the default `FF16` physiological model -- we must solve
for this height numerically. The calculation is performed by the function
`height_seed` within the physiological model, using the Boost
library's one-dimensional `bisect` routine
[@Schaling-2014, @Eddelbuettel-2015]. The accuracy of the solution
is controlled by the parameter `plant_seed_tol`.

### Stepping of ODEs

All of the IVPs outlined above (in section [approach](#approach)) must be stepped through time.
For this, `plant` uses
the embedded Runge-Kutta Cash-Karp 4-5 algorithm [@Cash-1990], with
code ported directly from the [GNU Scientific Library](http://www.gnu.org/software/gsl/)
[@Galassi-2009]. The accuracy of the solver is controlled by two
control parameters for relative and absolute accuracy,
`ode_tol_rel` and `ode_tol_abs`.

### Approximation of size-density distribution via the characteristic method  {#approximation-of-size-density-distribution-via-the-scm}

Errors in the approximation of the size-density distribution arise from two sources:
(i) coarse stepping of cohorts through time and
(ii) poor spacing of cohorts across the attainable size range.

As described above, the stepping of the ODE solver is controlled by two
control parameters for relative and absolute accuracy,
`ode_tol_rel` and `ode_tol_abs`.

A second factor controlling the accuracy with which cohorts are stepped
through time is the accuracy of the derivative calculation according to Eq. \@ref(eq:boundN), calculated via standard finite differencing
[@Abramowitz-2012]. When the parameter
`cohort_gradient_richardson` is `TRUE` a Richardson extrapolation
[@Stoer-2002] is used to refine the estimate, up to depth
`cohort_gradient_richardson`. The overall accuracy of the
derivative is controlled by `cohort_gradient_eps`.

The primary factor controlling the spacing of cohorts is the schedule of
cohort introduction times. Because the system of equations to be integrated is deterministic, the
schedule of cohort introduction times determines the spacing of cohorts
throughout the entire development of a patch. Poor cohort spacing
introduces error because various emergent properties -- such as total
leaf area, biomass, or seed output -- are estimated by integrating over
the size-density distribution. The accuracy of these integrations declines
directly with the inappropriate spacing of cohorts. Thus, our algorithm aims to build an
appropriately refined schedule, which allows the required integrations to be
performed with the desired accuracy at every time point. At the same
time, for reasons of computational efficiency, we want as few cohorts as possible.
The general idea of adaptively refining cohort spacing times was first applied
by @Falster-2011, and was described further by @Falster-2015.

For a worked example illustrating the `build_schedule` function,
see the [cohort scheduling vignette](https://traitecoevo.github.io/plant/articles/cohort_spacing.html).

### Calculation of light environment and influence on assimilation {#calculation-of-light-environment-and-influence-on-assimilation}

To progress with solving the system of ODEs requires that we calculate the amount of
shading on each of the cohorts, from all other plants in the
patch.

Calculating the canopy openness $E_a(z)$ at a given height $z$ in a patch of age $a$ requires that
we integrate over the size-density distribution (Eq. \@ref(eq:light). This
integration is performed using the trapezium rule, within the function
`area_leaf_above` in [species.h](https://github.com/traitecoevo/plant/blob/master/inst/include/plant/species.h). The main factor
controlling the accuracy of the integration is the spacing of cohorts.
The cohort introduction times determining the
spacing of cohorts are adaptively refined as described above. This implies that also the trapezium integration
within the `area_leaf_above` function is adaptively refined
via the `build_schedule` function.

The cost of calculating $E_a(z)$ linearly increases with the number of
cohorts in the metacommunity. Since the same calculation must be repeated
for every cohort, the overall computational cost
of a step increases as $O(k^2 )$, where $k$ is the
total number of cohorts across all species. This disproportionate
increase in computational cost with the number of cohorts is highly undesirable.

We reduce the computational cost
from $O(k^2)$ to $O(k)$ by approximating $E_a(z)$ with a
spline. Eq. \@ref(eq:light) describes a function monotonically
increasing with size. This function is easily
approximated using a piecewise continuous spline fitted to a limited
number of points. Once fitted, the spline can be used to estimate any
additional evaluations of competitive effect. Since spline
evaluations are computationally cheaper than integrating over the size-density distribution,
this approach reduces the overall cost of stepping the resident
population. A new spline is constructed for each time step.

The accuracy of the spline interpolation depends on the number of points
used in its construction and on their placement along the size axis. We
select the number and locations of points via an adaptive algorithm.
Starting with an initial set of 33 points, we assess how much each point
contributes to the accuracy of the spline fit at the location of each
cohort, first via exact calculation, and second by linearly interpolating
from adjacent cohorts. The absolute difference in these values is
compared to the control parameter `environment_light_tol`. If
the error is greater than this tolerance, the interval is bisected and the is
process repeated (see [adaptive_interpolator.h](https://github.com/traitecoevo/plant/blob/master/inst/include/plant/adaptive_interpolator.h) for details).

### Integration over light environment {#integrating-over-light-environment}

Plants have leaf area distributed over a range of heights. Estimating
a plant's assimilation at each time step thus requires integrating
leaf-level rates over the plant. The integration is performed using
Gaussian quadrature, using the QUADPACK routines [@Piessens-1983]
adapted from the [GNU Scientific Library](http://www.gnu.org/software/gsl/) [@Galassi-2009]; see [qag.h](https://github.com/traitecoevo/plant/blob/master/inst/include/plant/qag.h) for details.
If the control parameter `plant_assimilation_adaptive` is `TRUE`,
the integration is performed using adaptive refinement with an accuracy
controlled by the parameter `plant_assimilation_tol`.

### Solving for seed rains {#solving-demographic-seed-rain}

For a single species, solving for $Y_x$ is a straightforward
one-dimensional root-finding problem, which can be solved with accuracy
`equilibrium_eps` via a simple bisection algorithm (see
[equlibrium.R](https://github.com/traitecoevo/plant/blob/master/R/equilibrium.R) for details).

Solving for seed rains in metacommunities with multiple species is significantly harder,
because there is no generally applicable method for multi-dimensional root finding. In `plant`, we
have therefore implemented several different approaches (see
[equlibrium.R](https://github.com/traitecoevo/plant/blob/master/R/equilibrium.R) for details).

# Appendices {#appendices}

## Derivation of PDE describing age-structured dynamics {#derivation-of-pde-describing-age-structured-dynamics}

We consider patches of habitat that are subject to an intermittent
disturbance, with the age of a patch measuring the time
since the last disturbance. Denoting by $P(a, t)$ the frequency-density of
patch age $a$ at time $t$ and by $d_{\rm P}(a)$ the
age-dependent probability that a patch of age $a$ is transformed into
a patch of age $0$ through disturbance, the dynamics of $P(a, t)$ are given by
\begin{equation}
 \frac{\partial}{\partial t} P(a, t) = -\frac{\partial}{\partial a} P(a, t)-d_{\rm P}(a, t) P(a, t),
(\#eq:dp-a)
\end{equation}
with boundary condition
\begin{equation}
 P(0, t) = \int^{\infty}_{0}d_{\rm P}(a, t) P(a, t) \, {\rm d}a.
(\#eq:p0)
\end{equation}

The frequency-density of patches of age $a < a^{\prime}$ is given by
$\int_{0}^{a^{\prime}}P(a, t) \, {\rm d}a$, with
$\int_{0}^{\infty} P(a, t) \, {\rm d}a = 1$. If
$\frac{\partial}{\partial t}d_{\rm P}(a, t) = 0$, then $P(a)$ will
approach an equilibrium solution given by \begin{equation}
P(a) = P(0) \, S_{\rm P}(0, a),
(\#eq:pa)
\end{equation}

where
\begin{equation}
S_{\rm P}(0, a) = \exp \left( - \int_{0}^{a} d_{\rm P}(a^\prime) \, {\rm d}a^\prime\right)
(\#eq:S-P)
\end{equation}
is the probability that a patch remains undisturbed for
duration $a$, and
\begin{equation}
P(0) = \frac1{ \int_{0}^{\infty}S_{\rm P}(0, a) \, {\rm d}a}
(\#eq:p0-eq)
\end{equation}

is the
frequency-density of patches of age $0$. The rate of disturbance for patches
of age $a$ is given by
$\frac{\partial (1-S_{\rm P}(0, a))}{\partial a} = - \frac{\partial S_{\rm P}(0, a)}{\partial a}$,
while the expected lifetime of patches is
$- \int_0^\infty a \frac{\partial}{\partial a} S_{\rm P}(0, a) \, {\rm d} a = \int_0^\infty S_{\rm P}(0, a) \, {\rm d} a = \frac1{P(0)}$
(first step made using integration by parts).

An equilibrium distribution of patch ages may be achieved under a variety of
conditions, for example, if $d_{\rm P}(a, t)$ depends on patch age $a$ but
not on time $t$. The rate of disturbance
may also depend on features of the vegetation in the patch, rather than on patch age directly, in which case an equilibrium distribution of patch ages can still arise, provided the
vegetation is also assumed to be at equilibrium.

### Exponential distribution {#exponential-distribution}

If the rate $d_{\rm P}$ of patch disturbance is constant with respect to
patch age, then the rates at which patches of age $a$ are
disturbed follow an exponential distribution,
$-\partial S_{\rm P}(0, a)/ \partial a = d_{\rm P} \, \exp(-d_{\rm P} a)$. The
distribution of patch ages is then given by
\begin{equation}
 S_{\rm P}(0, a) = \exp\left(-d_{\rm P} a\right), \, P(0) = d_{\rm P}.
(\#eq:S-P0a1)
\end{equation}

### Weibull distribution {#weibull-distribution}

If the rate of patch disturbance changes with patch age according to
$d_{\rm P}(a) = \lambda \psi a^{\psi-1}$, then the rates at which
patches of age $a$ are disturbed follow a Weibull distribution,
$-\partial S_{\rm P}(0, a)/ \partial a = \lambda \psi a^{\psi -1}e^{-\lambda a^\psi}$.
$\psi>1$ implies that the probability of disturbance increases with
patch age, while $\psi<1$ implies that it decreases with
patch age. For $\psi = 1$, we obtain the exponential distribution, a special
case of the Weibull distribution. The Weibull distribution results in the following
distribution of patch ages,
\begin{equation}
S_{\rm P}(0, a) = \exp(-\lambda a^\psi), \, P(0) = \frac{\psi \lambda^{\frac1{\psi}}}{\Gamma\left(\frac1{\psi}\right)},
(\#eq:S-P0a2)
\end{equation}
where $\Gamma(x) = \int_{0}^{\infty}e^{-t}t^{x-1} \, dt$ is the gamma function. We can
also specify this distribution by the mean  disturbance interval
$\bar{a} = \frac1{P(0)}$. From this, we can calculate the relevant value for
$\lambda = \left(\frac{\Gamma\left(\frac1{\psi}\right)}{\psi \bar{a}}\right)^{\psi}$.

The default in `plant` is to assume $\psi=2$, such that $d_{\rm P}$ increases as
a linear function of patch age. The distribution of patch ages is then specified by a
single parameter, $\bar{a}$.


## Derivation of PDE describing size-structured dynamics {#derivation-of-pde-describing-size-structured-dynamics}

To model the metacommunity, we use a PDE describing the dynamics for a thin
slice $\Delta H$. This PDE can be derived as follows, following
@Deroos-1997. Note that in this sub-section the dependencies on the traits $x$ are deliberately not made explicit. Assuming that all rates are constant within the
interval $\Delta H$, the total number of individuals within the
interval spanned by $[H - 0.5\Delta H, H + 0.5\Delta H)$ is
$N(H, a)\Delta H$. The flux of individuals in and out of this size
interval can be expressed as
\begin{equation}\begin{array}{ll} &g(H - 0.5 \Delta H, a) \, N(H - 0.5 \Delta H, a) - g(H + 0.5 \Delta H, a) \, N(H + 0.5 \Delta H, a) \\ & - d (H, a) \, N(H, a)\Delta H\\ \end{array}.
(\#eq:flux-1)
\end{equation}
The first two terms describe the flux in and out of the considered size interval
through growth, while the last term describes losses through mortality.
The change in the density of individuals within this size interval during a time
step $\Delta $a is thus
\begin{equation}
\begin{array}{ll} N(H, a + \Delta a)\Delta H - N(H, a)\Delta H = &g(H - 0.5 \Delta H, a) \, N(H - 0.5 \Delta H, a)\Delta a \\ & - g(H + 0.5 \Delta H, a) \, N(H + 0.5 \Delta H, a)\Delta a\\& - d (H, a) \, N(H, a)\Delta H\Delta a.
\end{array}
(\#eq:flux-2)
\end{equation}
By rearranging, we obtain
\begin{equation}
\begin{array}{ll}
\frac{N(H, a + \Delta a) - N(H, a)}{\Delta a} = & - d (H, a) \, N(H, a) \\
& - \frac{g(H + 0.5 \Delta H, a) \, N(H + 0.5 \Delta H, a) - g(H - 0.5 \Delta H, a) \, N(H - 0.5 \Delta H, a)}{\Delta H}.
\end{array}
(\#eq:flux-3)
\end{equation}
The left-hand side above corresponds to the derivative of $N$ as $\Delta a\to 0$.
For thin slices, $\Delta H \to 0$, this yields
\begin{equation}
\frac{\partial}{\partial a} N(H, a) = - d (H, a) \, N(H, a) - \frac{\partial}{\partial H} (g(H, a) \, N(H, a)).
(\#eq:PDE-app)
\end{equation}

To complete the model, this PDE must be supplemented with boundary
conditions that specify the density at the lower end of heights
for all $a$, as well as the initial distribution
$N(H,0)$. The former is derived by integrating the PDE with respect to
$H$ over the interval $(H_{0}, H_{\infty} )$, yielding
\begin{equation}\frac{\partial}{\partial a} \int _{H_{0} }^{H_{\infty}}N(H, a) \, {\rm d} H = g(H_{0} , a) \, N(H_{0} , a) - g(H_{\infty}, a) \, N(H_{\infty}, a) - \int _{H_{0} }^{H_{\infty}}d (H, a) \, N(H, a) \, {\rm d} H.
(\#eq:partial-a)
\end{equation}
The left-hand size above is evidently the rate of change of the total
density of individuals in the population, while the right-hand side is
the population's total death rate. Further, we can assume that $N(H_{\infty}, a) = 0$. Thus,
to balance total births and deaths, $g(H_{0} , a) \, N(H_{0} , a)$ must
equal the population's total birth rate $B$, yielding the boundary condition
\begin{equation}g(H_{0} , a) \, N(H_{0} , a) = B.
(\#eq:g0)
\end{equation}

## Converting density from one size unit to another {#converting-density-from-one-size-unit-to-another}

The quantification of size-density depends on the chosen size
unit (Eq. \@ref(eq:PDE)). Thus, what if we want to express size-density with respect to
another size unit? A relation between the two corresponding values of size-density can be derived
by noting that the total density of individuals within a given size range
must be equal. We consider a situation in which size-density is expressed in units of size $M$,
but we want it in units of size $H$. First, we require a
one-to-one function that translates the first size unit into the second, $H = \hat{H}(M)$. Then
the following must hold
\begin{equation}
\int_{M_1}^{M_2} N(M | x, a) \, {\rm d}M = \int_{\hat{H}(M_1)}^{\hat{H}(M_2)} N^\prime(H | x, a) \, {\rm d}H .
(\#eq:n-conversion)
\end{equation}
For very small size intervals, this equation is equivalent to
\begin{equation}\left(M_2 - M_1 \right) \, N(M_1 | x, a) = \left( \hat{H}(M_2) - \hat{H}(M_1)\right) \, N^\prime(\hat{H}(M_1) | x, a).
(\#eq:n-conversion2)
\end{equation}
Rearranging gives
\begin{equation}N^\prime(\hat{H}(M_1) | x, a) = N(M_1 | x, a) \, \frac{M_2 - M_1}{\hat{H}(M_2) - \hat{H}(M_1)}.
(\#eq:n-conversion3)
\end{equation}
Noting that the second term on the right-hand side is simply the definition of
$\frac{{\rm d} M}{{\rm d} H}$ evaluated at $M_1$, we have
\begin{equation}
N^\prime(H | x, a) = N(M | x, a) \, \frac{{\rm d} M}{{\rm d} H}.
(\#eq:n-conversion4)
\end{equation}

# References
