\newcommand{\ud}{\mathrm{d}}
\newcommand{\tm}{\textrm}

```{r, results="hide", echo=FALSE, message=FALSE}
library(methods)
library(tree)
s <- new(Strategy)
tree_p <- s$parameters
```

# Equations

For the sake of brevity, dependencies of functions are shown only in the Symbol column. The variable $x$ refers to a vector of four traits that are varied in the model: $x = (\phi, \rho, h_m, s)$. Subscripts for size variables are: l = leaves, s = sapwood, b = bark and phloem, h = heartwood, r = fine roots. All mass measurements are in terms of dry mass.

## Traits

### Leaf mass per unit area (LMA)

Symbol: $\varphi$

Units: kg m$^{-2}$

Description: Mass cost for constructing a unit of leaf area

Default value: $\varepsilon$ = `r tree_p[["lma"]]`

### Stem tissue density
Symbol: $\rho$

Units: kg m$^{-3}$

Description: Mass cost for constructing a unit of stem volume

Default value: $\rho$ = `r tree_p[["rho"]]`

### Leaf nitrogen content
Symbol: $N$

Units: kg m$^{-2}$

Description: leaf nitrogen per unit leaf area

Default value: $N$ = `r tree_p[["n_area"]]`

### Height at maturation

Symbol: $h_m$

Units: m

Description: Height at which plants allocate 50% of surplus energy to reproduction.

Default value: $h_m$ = `r tree_p[["hmat"]]`

### Seed size

Symbol: $s$

Units: kg

Description: Mass of individual seeds dispersing from parent.

Default value: $s$ = `r tree_p[["s"]]`

## Individual size

### Height

Symbol: $h(x, a)$

Units: m

Description: Height of plant with traits $x$ at and age $a$. Height is the key size variable tracked during plant growth. With exception of any variable combination involving heartwood area or heartwood mass, the remaining size metrics are tied directly to height, so knowing height means you also know the other variables.

Determination: Plants begin with initial height at germination $h_{0}$, obtained by finding a value that satisfies the equation
\begin{equation} s = m_\tm{t}(x, h_0(x)). \end{equation}

Height growth rate $g(x, h(x, a^\prime))$ is calculated as

\begin{equation} \label{eq:dhdt}
g = \frac{\textrm{d}h}{\textrm{d}t}=\frac{\textrm{d}h}{\textrm{d}a_\textrm{l}}
\times \frac{\textrm{d}a_\textrm{l}}{\textrm{d}m_\textrm{t}}
\times \frac{\textrm{d}m_\textrm{t}}{\textrm{d}B}
\times \strut\frac{\textrm{d}B}{\textrm{d}t}.
 \end{equation}

Each element on the RHS of eq. \ref{eq:dhdt} is also a function of current traits and height. Height at given age is then obtained by integrating eq. \ref{eq:dhdt} with the initial conditions:
\begin{equation} h(x, 0) = h_0(x), \end{equation}
such that
\begin{equation} h(x, a) = h_0(x) + \int_{0}^{a} g(x, h(x, a^\prime)) \, \rm{d}a^\prime. \end{equation}

### Leaf area

Symbol: $a_\tm{l}(h)$

Units: m$^2$

Description: Total leaf area of plant with traits $x$ and height $h$

Determination: Leaf area is calculated directly from plant height as
\begin{equation} a_\tm{l} = \alpha_1 \, h^{\beta_1}. \end{equation}

Useful derivatives: The growth rate of leaf area is given by
\begin{equation} \label{eq:dhdt}
\frac{\textrm{d}a_\textrm{l}}{\textrm{d}t} = \frac{\textrm{d}h}{\textrm{d}a_\textrm{l}}
\times \frac{\textrm{d}a_\textrm{l}}{\textrm{d}m_\textrm{t}}
\times \frac{\textrm{d}m_\textrm{t}}{\textrm{d}B}
\times \frac{\textrm{d}B}{\textrm{d}t}
 \end{equation}

To solve equation \ref{eq:dhdt} , the following derivative is also required:

\begin{equation} \frac{\ud h}{\ud a_\tm{l}} = -\beta_1\big(\frac{a_\tm{l}}{\alpha_1}\big)^{-(\beta_1 + 1)}. \end{equation}

Parameter values: $\alpha_1$ = `r tree_p[["a1"]]`, $\beta_1$ = `r tree_p[["B1"]]`

### Area of sapwood

Symbol: $a_{ss}(x, a_\tm{l})$

Units: $m^2$

Description: Area of live sapwood in stem at base of a plant with traits $x$ and leaf area $a_\tm{l}$.

Determination: Sapwood area is assumed to be in functional balance with leaf area (i.e. the pipe model), such that:
\begin{equation} a_\tm{ss} = \theta^{-1} \, a_\tm{l}. \end{equation}

Useful derivatives:
\begin{equation} \frac{\ud a_\tm{ss}}{\ud a_\tm{l}} = \theta^{-1} \end{equation}

\begin{equation} \frac{\ud a_\tm{ss}}{\ud t} = \theta^{-1} \, \frac{\ud a_\tm{l}}{\ud t} \end{equation}

Parameter values: $\theta$ = `r tree_p[["theta"]]`

### Mass of sapwood

Symbol: $m_{ss}(x, h)$

Units: kg

Description: Total mass of sapwood in a plant with traits $x$ and height $h$.

Determination: Calculated from leaf area and height, by XXXX.

\begin{equation} m_\tm{ss} = \theta^{-1} \, \rho \, \eta_c \, a_\tm{l}(x,h) \, h \end{equation}

Useful derivatives:
\begin{equation} \frac{\ud m_\tm{ss}}{\ud a_\tm{l}} = \theta^{-1} \, \rho \, \eta_c \, \big( h + a_\tm{l} \, \frac{\ud h}{\ud a_\tm{l}} \big) \end{equation}

Parameter values: $\eta$ = `r tree_p[["eta"]]`

### Area of bark

Symbol: $a_{sb}(x, a_\tm{l})$

Units: kg

Description: Area of live bark area in stem at base of a plant with traits $x$ and leaf area $a_\tm{l}$.

Determination: Bark cross-sectional area is treated analogously to sapwood area. We assume a constant ratio $b$ between bark and sapwood area so that:

\begin{equation} a_\tm{sb} = b \, \theta^{-1} \, a_\tm{l} \end{equation}

Useful derivatives:
\begin{equation} \frac{\ud a_\tm{sb}}{\ud t} = b \, \theta^{-1} \, \frac{\ud a_\tm{l}}{\ud t} \end{equation}

\begin{equation} \frac{\textrm{d}a_\textrm{sb}}{\textrm{d}t}=b \, \theta^{-1} \, \frac{\textrm{d}a_\textrm{l}}{\textrm{d}t} \end{equation}

Parameter values: $\eta$ = `r tree_p[["b"]]`

### Mass of bark

Symbol: $m_{sb}(x, a_\tm{l})$

Units: kg

Description: Total mass of bark in a plant with traits $x$ and height $h$.

Determination: As for $m_{ss}$, calculated from leaf area and height such that:
\begin{equation} m_\tm{sb} = \theta^{-1} \, \rho \, \eta_c \, a_\tm{l} \, h \end{equation}

Useful derivatives:
\begin{equation} \frac{\ud m_\tm{sb}}{\ud a_\tm{l}} = \theta^{-1} \, \rho \, \eta_c \, \big( h + a_\tm{l} \, \frac{\ud h}{\ud a_\tm{l}} \big) \end{equation}

\begin{equation} \frac{\textrm{d}m_\textrm{b}}{\textrm{d}a_\textrm{l}}=b \, \theta^{-1} \, \rho \, \eta_c\big( h + a_\textrm{l} \, \frac{\textrm{d}h}{\textrm{d}A} \big) \end{equation}

### Area of heartwood

Symbol: $a_\tm{sh}(x, h, a)$

Units: kg

Description: Area of dead sapwood in stem at base of a plant with traits $x$, height $h$ and age $a$.

Determination: Heartwood area is created by the turnover of sapwood. As such area of heartwood is obtained by integrating the IVP with initial conditions:
\begin{equation} a_\tm{sh} = 0, \end{equation}
and rates of change
\begin{equation} \frac{\ud a_\tm{sh}}{\ud t} = k_\tm{s} \, a_\tm{ss}(x, a_\tm{l}(h)). \end{equation}
Thus,
\begin{equation} a_\tm{sh} = \int_0^t \frac{\ud a_\tm{sh}}{\ud t}(t^\prime) \, dt^\prime. \end{equation}

Parameter values: $k_\tm{s}$ = `r tree_p[["k_s"]]`

### Mass of heartwood

Symbol: $m_\tm{sh}(x, h, a)$

Units: kg

Description: Mass of dead sapwood in stem for a plant with traits $x$, height $h$ and age $a$.

Determination: Heartwood mass is created by the turnover of sapwood. As such mass of heartwood is obtained by integrating the IVP with initial conditions:
\begin{equation} m_\tm{sh} = 0, \end{equation}
and rates of change
\begin{equation} \frac{\ud m_\tm{sh}}{\ud t} = k_\tm{s} \, m_\tm{ss}(x,h). \end{equation}
Thus,
\begin{equation} m_\tm{sh} = \int_0^t \frac{\ud m_\tm{sh}}{\ud t}(t^\prime) \, dt^\prime. \end{equation}

### Mass of fine roots

Symbol: $m_\tm{r}(x, a_\tm{l})$

Units: kg

Description: Mass of fine roots on a plant with traits $x$ and leaf area $a_l$.

Determination: root mass is assumed to be in functional balance with leaf area (i.e. the pipe model), such that:
\begin{equation} m_\tm{r} = \alpha_3 a_\tm{l}(h) \end{equation}

Useful derivatives:
\begin{equation} \frac{\ud m_\tm{r}}{\ud a_\tm{l}} = \alpha_3 \end{equation}
\begin{equation} \frac{\ud m_\tm{r}}{\ud t} = \alpha_3 \frac{\ud a_\tm{l}}{\ud t} \end{equation}

Parameter values: $\alpha_3$ = `r tree_p[["a3"]]`

### Total live mass

Symbol: $m_\tm{t}(x, h, a)$

Units: kg

Description: Total mass of live tissue on a plant with traits $x$ and height $h$.

Determination: Calculated from sum of mass in leaves, sapwood, bark and root.

\begin{equation} m_\tm{t} = m_\tm{l} + m_\tm{ss} + m_\tm{sb} + m_\tm{r} \end{equation}

## Mass production

All rates are per plant.

### Net production

Symbol: $\frac{\textrm{d}B}{\textrm{d}t}(x, h, E)$

Units: kg yr$^{-1}$

Description: Rate of biomass production, after replacing parts lost via turnover, for plant with traits $x$, height $h$ and growing in environment $E$.

Determination: Calculated as the difference between income (photosynthesis) and losses (respiration and turnover):
\begin{equation} \frac{\textrm{d}B}{\textrm{d}t} = \underbrace{\strut c_{\tm{bio}} Y}_\textrm{yield} \big(\underbrace{\strut \, A_\tm{p}\left(x, h, E_a\right)}_\textrm{photosynthesis} - \underbrace{\strut \, R(x, h)}_\textrm{respiration}\big) - \underbrace{\strut T(x, h)}_\textrm{turnover}. \end{equation}

Parameter values: $c_{\tm{bio}}$ = `r tree_p[["c_bio"]]`, $Y$ = `r tree_p[["Y"]]`

### Total photosynthesis (= gross primary production)

Symbol: $A_\tm{p}(x, h_\tm{l}, E)$

Units: mol yr$^{-1}$

Description:

Determination: Calculated by integrating assimilation per unit leaf area over the plant:

\begin{equation} A_\tm{p} = a_\tm{l}(h) \int_0^{h} A(x, E_a(z)) \, q(z, h) \; \ud z \end{equation}

### Photosynthesis per leaf area

Symbol: $A(x, E)$

Units: mol yr$^{-1}$

Description: $A(x, E)$ is the gross annual CO2 assimilation per unit leaf area at canopy openness $E$ for a leaf with traits $x$.

Determination: Calculated by using the approximation, which was derived by integrating instantaneous rates of assimilation (described by a rectangular hyperbola) over the diurnal solar cycles throughout the year:

\begin{equation} A = \frac{c_\tm{p1}}{c_\tm{p2}+ E} \end{equation}

Parameter values: $c_\tm{p2}$ = `r tree_p[["c_p1"]]`, $c_\tm{p2}$ = `r tree_p[["c_p2"]]`

### Maintenance respiration

Symbol: $R(x, h)$

Units: mol yr$^{-1}$

Description:

Determination: Calculated from sum of respiration in leaves, sapwood, bark and root. Leaf respiration is calculated per unit area, while sapwood and bark respiration are calculated per unit volume.

\begin{equation} R = c_\tm{R,l} \, N \, a_\tm{l} + c_\tm{R,ss} \, \frac{m_\tm{ss}}{\rho} + c_\tm{R,sb} \, \frac{m_\tm{sb}}{\rho}  +  c_\tm{R,r} \, m_\tm{r} \end{equation}

Parameter values: $c_\tm{R,l}$ = `r tree_p[["c_Rl"]]` mol CO2 / kgN / yr, $c_\tm{R,ss}$ = `r tree_p[["c_Rs"]]` mol CO2 / m3 / yr, $c_\tm{R,sb}$ = `r tree_p[["c_Rb"]]` mol CO2 / m3 / yr, $c_\tm{R,r}$ = `r tree_p[["c_Rr"]]` mol CO2 / kg / yr.

### Total turnover

Symbol: $T(x, h)$

Units: kg yr$^{-1}$

Description:

Determination:
\begin{equation} T = \sum_\textrm{i=l,ss,sb,r}{k_i \, m_i} \end{equation}

### Leaf turnover rate

Symbol: $k_\tm{l}$

Units: yr$^{-1}$

Description: Rate at which leaf mass dies and is lost.

Determination: Assumed proportional to leaf mass per area, as per scaling relationship observed in large datasets:

\begin{equation} k_\tm{l} = \alpha_4 \phi^{\beta_4} \end{equation}

Parameter values: $\alpha_4$ = `r tree_p[["a4"]]`, $\beta_4$ = `r tree_p[["B4"]]`,

### Sapwood turnover rate

Symbol: $k_\tm{ss}$

Units: yr$^{-1}$

Description: Rate at which sapwood mass dies and becomes heartwood.

Parameter values: $k_\tm{ss}$ = `r tree_p[["k_s"]]`,

### Bark turnover rate

Symbol: $k_\tm{sb}$

Units: yr$^{-1}$

Description: Rate at which bark mass dies and is lost.

Determination: Set to be same as sapwood turnover rate
\begin{equation} k_\tm{sb} = k_\tm{ss} \end{equation}

Parameter values: $k_\tm{sb}$ = `r tree_p[["k_b"]]`,

### Root turnover rate

Symbol: $k_\tm{r}$

Units: yr$^{-1}$

Description: Rate at which root mass dies and is lost.

Parameter values: $k_\tm{r}$ = `r tree_p[["k_r"]]`,

### Reproductive allocation

Symbol: $r(x, h)$

Units: Dimensionless (0 to 1)

Determination: Fraction of surplus production ($allocated to reproduction

Determination:
\begin{equation} r = c_{\tm{r}, 1}\left(1 + \exp\left(c_{\tm{r}, 2} \left(1-\frac{h(x, m_l)}{h_m}\right)\right)\right)^{-1} \end{equation}

Parameter values: $c_{\tm{r}, 1}$ = `r tree_p[["c_r1"]]`, $c_{\tm{r}, 2}$ = `r tree_p[["c_r2"]]`

### Leaf deployment rate
Symbol: $\frac{\ud a_\tm{l}}{\ud m_\tm{t}} (x, h)$

Units: Dimensionless (0 to 1)

Determination: $\textrm{d}a_\textrm{l} / \textrm{d}m_\textrm{t}$ accounts for the cost of deploying a unit of leaf area, including construction of the leaf itself and various support structures. As such, $\textrm{d}a_\textrm{l} / \textrm{d}m_\textrm{t}$ can itself be decomposed into a sum of construction costs per unit leaf area:

\begin{equation} \label{eq:daldmt}
\frac{\textrm{d}a_\textrm{l}}{\textrm{d}m_\textrm{t}}
= \big(\phi
 + \frac{\textrm{d}m_\textrm{s}}{\textrm{d}a_\textrm{l}} + \frac{\textrm{d}m_\textrm{b}}{\textrm{d}a_\textrm{l}} + \frac{\textrm{d}m_\textrm{r}}{\textrm{d}a_\textrm{l}}\big)^{-1}.
 \end{equation}

### Fraction of production allocated to growth

Symbol: $\frac{\textrm{d}m_\textrm{t}}{\textrm{d}B}$

Units: Dimensionless (0 to 1)

Determination:
\begin{equation} \frac{\textrm{d}m_\textrm{t}}{\textrm{d}B} = 1- r(x, h) \end{equation}

### Fecundity

Symbol: $f(x, h, E)$

Units: yr$^{-1}$

Description: Rate of offspring production for plant with traits $x$, height $h$ and growing in environment $E$.

Determination:
\begin{equation} f = \frac{r(x, h) \;\frac{\textrm{d}B}{\textrm{d}t}(x, h, E)}{c_{\tm{acc}}s} \end{equation}
if $\frac{\textrm{d}B}{\textrm{d}t}(x, h_0(x), E)>0$, otherwise 0

Parameter values: $c_{\tm{acc}}$ = `r tree_p[["c_acc"]]`

### Probability density of leaf area at height z for an individual of height h

Symbol: $q(z, h)$

Units: m$^{-1}$

Description: Fraction of plant's leaf area at height $z$, for plant of height $h$.

Determination:
\begin{equation} q = 2\eta(1-z^\eta h^{-\eta}) z^{\eta-1} h^{-\eta} \end{equation}
if $z \leq h$, otherwise 0.

## Mortality

### Survival of seedlings during germination

Symbol: $\Pi_1(x, m_{\tm{l}, 0}, E)$

Units: Dimensionless (0 to 1)

Description: Gives probability of plant suriving germination. Is a function of biomass growth rate for seedlings, such that seedlings unable to grow die.

Determination:
\begin{equation} \Pi_1 = \left(1 + \left(\frac{c^2_{\tm{s}, 0}}{\frac{\frac{\textrm{d}B}{\textrm{d}t}(x, h_0(x), E)}{a_\tm{l}(x, h_0(x))}} \right)^{2} \right)^{-1} \end{equation}
if $\frac{\textrm{d}B}{\textrm{d}t}(x, h_0(x), E) > 0$, otherwise 0

Parameter values: $c_{\tm{s}, 0}$ = `r tree_p[["c_s0"]]`

### Mortality rate

Symbol: $d_\tm{t}(x, h, E)$

Units: yr$^{-1}$

Description: Instantaneous mortality rate for a plant with traits $x$, height $h$ and growing in environment $E$. Given as sum of growth-dependent and growth-independent hazards.

Determination:
\begin{equation} d_\tm{t} = d_\tm{i}(x, h) + d_\tm{d}(x, h, E) \end{equation}

### Growth-independent mortality rate

Symbol: $d_\tm{i}(x, h)$

Units: yr$^{-1}$

Description: Mortality rate for a plant with traits $x$ and height $h$ due to growth-independent factors.

Determination:
\begin{equation} d_\tm{i} = c_{\ud 0}\exp\left(-c_{\ud 1}\rho\right) \end{equation}

Parameter values: $c_{\ud 0}$ = `r tree_p[["c_d0"]]`, $c_{\ud 1}$ = `r tree_p[["c_d1"]]`

### Growth-dependent mortality rate

Symbol: $d_\tm{d}(x, h)$

Units: yr$^{-1}$

Description: Mortality rate for a plant with traits $x$, height $h$ and growing in environment $E$ due to growth-dependent factors.

Determination:
\begin{equation} d_\tm{d} = c_{\ud 2} \exp\left(-c_{\ud 3} \frac{\frac{\textrm{d}B}{\textrm{d}t}(x, h, E)}{a_\tm{l}(h)} \right) \end{equation}

Parameter values: $c_{\ud 2}$ = `r tree_p[["c_d2"]]`, $c_{\ud 3}$ = `r tree_p[["c_d3"]]`

\newpage

# Appendix 1: Moving from leaf mass to height as key variable

The focus on leaf mass as the key variable in @falster_influence_2011 is fairly arbitrary.
Instead, consider a change of variables to use "height" as the key
size variable. This is useful because we need to know about plant
height elsewhere, and it's a common measuring stick that is fairly
independent of the key traits.

To convert from leaf mass ($m_l$) to height ($h$), use equations 3 and
4 in @falster_influence_2011:

\begin{equation}
h = \alpha_1 \left(\frac{m_l}{\phi}\right)^{\beta_1}
 \end{equation}

where $\phi$ is the leaf mass per unit area (\textsc{lma}) and
$\alpha_1$ and $\beta_1$ are scaling parameters relating leaf area
($m_l/\phi$) to height.

What we need for the main calculations is the derivative of height $h$
with respect to time. Because $m_l$ is a function of time, we have

\begin{equation}
\frac{\ud h}{\ud t} = \frac{\ud}{\ud t}[m_l(t)]
\frac{\alpha_1 \beta_1}{\phi} \left(\frac{m_l(t)}{\phi}\right)^{\beta_1 - 1}
 \end{equation}

where $\frac{\ud}{\ud t}[m_l(t)]$ comes from equation 19:

\begin{equation}
\frac{\ud}{\ud t}[m_l(t)] = (1 - r)P\frac{\ud m_l}{\ud m_t}
 \end{equation}

where $P$ is total production, $r$ is allocation to reproduction and
$\ud m_l/\ud m_t$ is the fraction of whole plant growth that is leaf.

So overall, we have

\begin{equation}
\frac{\ud h}{\ud t} =
\frac{\ud m_t}{\ud t} \frac{\ud m_l}{\ud m_t} \frac{\ud h}{\ud m_l}
 \end{equation}

---

Here, I'm just explicitly writing down the derivations of the pieces
needed for this equation, and for the equivalent equation used in the
R version of the growth model.

From equation (18) we have

\begin{equation}
\frac{\ud m_l}{\ud m_t} =
\frac{1}{1 +
	\frac{\ud m_s}{\ud m_l} +
	\frac{\ud m_b}{\ud m_l} +
	\frac{\ud m_h}{\ud m_l} +
	\frac{\ud m_r}{\ud m_l}}
 \end{equation}

(because $m_t = m_l + m_s + m_b + mh + m_r$, and $\ud m_l/\ud m_t = 1
/(\ud m_t / \ud m_l)$).

Using appendix S2 of Falster et al. (2010).

\begin{equation}
\frac{\ud m_s}{\ud m_l} = \frac{\ud}{\ud m_l}\left[
\frac{\rho \eta_c}{\theta} \omega(m_l) h(m_l)\right] =
\frac{\ud}{\ud m_l}\left[
\frac{\rho \eta_c}{\theta} \frac{m_l}{\phi}
\alpha_1\left(\frac{m_l}{\phi}\right)^{\beta_1}\right] =
\frac{\ud}{\ud m_l}\left[
\frac{\rho \eta_c}{\theta}
\alpha_1\left(\frac{m_l}{\phi}\right)^{\beta_1 + 1}\right] =
% r n / t (m/p) a (m/p) ^ b
% D[r n / t (m/p) a (m/p) ^ b, m] // Simplify
\frac{\rho \eta_c}{\theta\phi}\alpha_1(\beta_1 + 1)
\left(\frac{m_l}{\phi}\right)^{\beta_1}
 \end{equation}
and
\begin{equation}
\frac{\ud m_b}{\ud m_l} = \frac{\ud}{\ud m_l}[b m_s] =
b \frac{\ud m_s}{\ud m_l} =
b \frac{\rho \eta_c}{\theta\phi}\alpha_1(\beta_1 + 1)
\left(\frac{m_l}{\phi}\right)^{\beta_1}
 \end{equation}
and
\begin{equation}
\frac{\ud m_h}{\ud m_l} =
\frac{\ud}{\ud m_l}\left[
\rho\eta_c\alpha_2 \omega(m_l)^{\beta_2}
\right] =
\frac{\ud}{\ud m_l}\left[
\rho\eta_c\alpha_2 \left(\frac{m_l}{\phi}\right)^{\beta_2}
\right] =
\frac{\rho\eta_c\alpha_2}{\phi}\beta_2
\left(\frac{m_l}{\phi}\right)^{\beta_2-1} =
% D[r n a (m / p)^b, m]
% D[r n a (m / p)^b, m] // Simplify
\frac{\rho\eta_c\alpha_2}{m_l}\beta_2
\left(\frac{m_l}{\phi}\right)^{\beta_2}
 \end{equation}
and
\begin{equation}
\frac{\ud m_r}{\ud m_l} =
\frac{\ud}{\ud m_l}\left[\alpha_3 \omega(m_l)\right] =
\frac{\ud}{\ud m_l}\left[\alpha_3 \frac{m_l}{\phi}\right] =
\frac{\alpha_3}{\phi}
 \end{equation}

So, the denomininator of $\ud m_l / \ud m_t$ looks like:

\begin{equation}
1 +
% d m_s / d m_l
\frac{\rho \eta_c}{\theta\phi}\alpha_1(\beta_1 + 1)
\left(\frac{m_l}{\phi}\right)^{\beta_1} +
% d m_b / d m_l
b \frac{\rho \eta_c}{\theta\phi}\alpha_1(\beta_1 + 1)
\left(\frac{m_l}{\phi}\right)^{\beta_1} +
% d m_h / d m_l
\frac{\rho\eta_c\alpha_2}{m_l}\beta_2
\left(\frac{m_l}{\phi}\right)^{\beta_2} +
% d m_r / d m_l
\frac{\alpha_3}{\phi}
 \end{equation}

\begin{equation}
1 +
% d m_s / d m_l + d m_b / d m_l
(1 + b) \frac{\rho \eta_c}{\theta\phi}\alpha_1(\beta_1 + 1)
\left(\frac{m_l}{\phi}\right)^{\beta_1} +
% d m_h / d m_l
\frac{\rho\eta_c\alpha_2}{m_l}\beta_2
\left(\frac{m_l}{\phi}\right)^{\beta_2} +
% d m_r / d m_l
\frac{\alpha_3}{\phi}
 \end{equation}

Repeating this with the version in the R verison, working in terms of
leaf area.
\begin{equation}
\frac{\ud \omega}{\ud m_t} =
\frac{1}{
	\frac{\ud m_l}{\ud \omega} +
	\frac{\ud m_s}{\ud \omega} +
	\frac{\ud m_b}{\ud \omega} +
	\frac{\ud m_h}{\ud \omega} +
	\frac{\ud m_r}{\ud \omega}}
 \end{equation}

\begin{equation}
\frac{\ud m_l}{\ud \omega} =
\frac{\ud}{\ud \omega}\left[\omega\phi\right] =
\phi
 \end{equation}
and
\begin{equation}
\frac{\ud m_s}{\ud \omega} =
\frac{\ud}{\ud \omega}\left[
\frac{\rho \eta_c}{\theta} \omega h(\omega)\right] =
\frac{\ud}{\ud \omega}\left[
\frac{\rho \eta_c}{\theta} \alpha_1 \omega^{\beta_1 + 1}\right] =
\frac{\rho \eta_c}{\theta}\alpha_1(\beta_1 + 1)\omega^{\beta_1}
 \end{equation}
and
\begin{equation}
\frac{\ud m_b}{\ud \omega} =
\frac{\ud}{\ud \omega}\left[b m_s\right] =
b \frac{\ud m_s}{\ud \omega} =
b \frac{\rho \eta_c}{\theta}\alpha_1(\beta_1 + 1)\omega^{\beta_1}
 \end{equation}
and
\begin{equation}
\frac{\ud m_h}{\ud \omega} =
\frac{\ud}{\ud \omega}\left[\rho\eta_c\alpha_2 \omega^{\beta_2}
\right] =
\rho\eta_c\alpha_2\beta_2\omega^{\beta_2 - 1}
 \end{equation}
and
\begin{equation}
\frac{\ud m_r}{\ud \omega} =
\frac{\ud}{\ud \omega}\left[\alpha_3 \omega\right] = \alpha_3
 \end{equation}

Other useful derivatives:

Because
\begin{equation}
h = \alpha_1 \left(\frac{m_l}{\phi}\right)^{\beta_1}
\qquad
m_l = \phi\left(\frac{h}{\alpha_1}\right)^{1/\beta_1}
 \end{equation}

we have

\begin{equation}
\frac{\ud h}{\ud m_l} = \frac{\alpha_1 \beta_1}{\phi}
\left(\frac{m_l}{\phi}\right)^{\beta_1 - 1}
\qquad
\frac{\ud m_l}{\ud h} =
\frac{\phi}{\alpha_1 \beta_1}\left(\frac{h}{\alpha_1}\right)^
{\frac{1}{\beta_1} - 1}
 \end{equation}

# References
