---
title: "ci_over_ca_water_gradient"
author: "Isaac Towers"
date: "27/07/2022"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```

```{r}
p_50_2_K_s <- function(p50){
  1.638999*(p50/2)^(-1.38)
}

calc_vul_b <- function(p_50, c){
  num <- p_50
  den <- (-log(1-50/100))^(1/c)
  num/den
}


calc_psi_crit <- function(b,c) {
  b*(log(1/0.05))^(1/c)
}

calc_k_l_max <- function(K_s, h_v, h){
  K_s * h_v / h
}
```



```{r}
c <- 2.04

h_v = 0.000157 #huber value (m^2 sapwood area m^-2 leaf area)
h = 5 #height/path length (m)
eta <- 12.0
eta_c <- 1 - 2 / (1 + eta) + 1 / (1 + 2 * eta)

```

```{r}
calc_opt_ci <- function(p50, PPFD, psi_soil){
  K_s = p_50_2_K_s(p50)
  b = calc_vul_b(p50, c)
  psi_crit = calc_psi_crit(b, c)
  k_l_max = calc_k_l_max(K_s, h_v, h*eta_c)

  l <- Leaf(vcmax = 30, p_50 = p50, c = 2.04, b = b, psi_crit = psi_crit, beta=15000, beta_2 = 1, huber_value = 0.000157, K_s = K_s)
  l$set_physiology(PPFD = PPFD, psi_soil = psi_soil, k_l_max = k_l_max)
  
  l$optimise_psi_stem_Sperry_Newton_recall_one_line(psi_soil+0.2)
  
  return(l$ci)
}
```

```{r}
expand_grid(p50 = c(0.5,4), PPFD = 1000, psi_soil = seq(0,10,length.out = 100)) %>%
  slice(1) %>%
    mutate(ci = calc_opt_ci(p50 = p50, PPFD = PPFD, psi_soil = psi_soil)) -> output

```


```{r}
expand_grid(p50 = c(0.5,4), PPFD = 1000, psi_soil = seq(0,10,length.out = 100)) %>%
  rowwise() %>%
  mutate(ci = calc_opt_ci(p50 = p50, PPFD = PPFD, psi_soil = psi_soil)) -> output
```

```{r}
output %>%
  ggplot(aes(x = psi_soil, y = ci/40)) +
  geom_line(aes(group = as_factor(p50), colour=as_factor(p50))) +
  theme_classic() +
  ylab("ci/ca") +
  xlab("psi soil (-MPa)") +
  scale_color_discrete(name = "p_50 (-MPa)")
```



