---
title: "optimisation_speed"
author: "Isaac Towers"
date: "18/07/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
devtools::load_all(".")
```


```{r}
l <- Leaf(vcmax = 100, p_50 = 1.731347, c = 2.04, b = 2.072101, psi_crit = 3.548059, beta=15000, beta_2 = 1, huber_value = 0.000157, K_s = 2)
```

```{r}
calc_k_l_max <- function(K_s, h_v, h){
  K_s * h_v / h
}
```

```{r}
K_s = 2 #stem-specific conductivity (kg h2o m^-1 stem s^-1 MPa^-1)
h_v = 0.000157 #huber value (m^2 sapwood area m^-2 leaf area)
h = 5 #height/path length (m)
eta <- 12.0
eta_c <- 1 - 2 / (1 + eta) + 1 / (1 + 2 * eta)
  

k_l_max = calc_k_l_max(K_s, h_v, h*eta_c)

PPFD = 900 #umol m^-2 s^-1
psi_soil = 0 #-MPa
```


```{r}
l$optimise_psi_stem_Sperry_Newton_recall(PPFD, psi_soil, k_l_max)

l <- Leaf(vcmax = 100, p_50 = 1.731347, c = 2.04, b = 2.072101, psi_crit = 3.548059, beta=15000, beta_2 = 1, huber_value = 0.000157, K_s = 2)

l$optimise_psi_stem_Sperry_Newton(PPFD, psi_soil, k_l_max)

l$optimise_ci_Sperry_Newton_recall()


library(tidyverse)
expand_grid(PPFD = seq(0,900,100), psi_soil = seq(0, 5, 0.1), k_l_max = seq(0.000001, k_l_max, k_l_max/10)) -> data


expand_grid(PPFD = 75, psi_soil = (0), k_l_max =  k_l_max) %>%
  rowwise() %>%
  mutate(ci = l$optimise_ci_Sperry_Newton_recall(PPFD, psi_soil, k_l_max))


expand_grid(PPFD = 100, psi_soil = 0, k_l_max = k_l_max, ci = seq(l$calc_min_psi(100, 0, k_l_max), 38.3693, length.out = 100)) %>%
  rowwise() %>%
  mutate(profit = l$calc_profit_Sperry_ci(PPFD, psi_soil, c_i = ci, k_l_max)) %>%
  ggplot(aes(x = ci, y = profit)) +
  geom_line()


l$optimise_ci_Sperry_Newton_recall(900, 0, k_l_max)



l$calc_A_lim(300, 5.59)
l$calc_cond_vuln(-1)

expand_grid(PPFD = 900, psi_soil = 0, c_i= seq(0.1, 40, length.out =100), k_l_max = k_l_max) -> data

data %>%
  rowwise() %>%
mutate(ci = l$calc_profit_Sperry_ci(PPFD, psi_soil, c_i, k_l_max))

l$calc_co



l$calc_profit_Sperry_ci()

atm_kpa = 101.3
kPa_to_Pa = 1000
ca = 40
atm_vpd = 2
kg_to_mol_h2o = 55.4939

benefit_ = l$calc_A_lim(900, 0.1)
g_c_ci = (benefit_ * 1e-6 * atm_kpa * kPa_to_Pa)/(ca - 0.1); 
E_ci = g_c_ci * 1.6 * atm_vpd / kg_to_mol_h2o / atm_kpa;

expand_grid(PPFD = 100, psi_soil = 0, c_i = seq(7.72, 38.315, length.out = 100)) %>%
  rowwise() %>%
  mutate(profit = l$calc_profit_Sperry_ci(100, 0, c_i = c_i, k_l_max)) %>%
  ggplot(aes(y = profit, x = c_i)) +
  geom_line()


expand_grid(PPFD = 100, psi_soil = 0, c_i = seq(7.72, 38.315, length.out = 100)) %>%
  rowwise() %>%
  mutate(profit = l$calc_profit_Sperry_ci(100, 0, c_i = c_i, k_l_max))


expand_grid(PPFD = 900, psi_soil = 1, psi_stem = seq(1, 5, length.out = 100)) %>%
  rowwise() %>%
  mutate(cost = l$calc_hydraulic_cost_Bartlett(psi_soil, psi_stem = psi_stem, k_l_max)) %>%
  mutate(benefit = l$calc_assim_gross(PPFD, psi_soil, psi_stem = psi_stem, k_l_max)) %>%
  ggplot(aes(x = psi_stem, y = benefit-cost)) + geom_line()


expand_grid(PPFD = 900, psi_soil = c(0,1), psi_stem = seq(0, 5, length.out = 100)) %>%
  filter(!(psi_soil == 1 & psi_stem < 1)) %>%
  rowwise() %>%
  mutate(profit = l$calc_profit_Sperry(PPFD, psi_soil, psi_stem = psi_stem, k_l_max)) %>%
  ggplot(aes(x = psi_stem, y = profit)) + geom_line(aes(group = psi_soil, colour = psi_soil))


l$calc_profit_Sperry()


l$calc_hydraulic_cost_Bartlett(0,4,k_)
```




```{r}
expand_grid(ci = seq(0,40,1), PPFD = c(0, 200, 1000, 2000)) %>%
  mutate(a_c = map_dbl(ci, ~l$calc_A_c(.x)) , a_j = map2_dbl(.x = ci, .y = PPFD , ~l$calc_A_j(.y, .x)), a_lim = map2_dbl(.x = ci, .y = PPFD , ~l$calc_A_lim(.y, .x) + 0.015*100)) %>%
  ggplot(aes(x = ci)) +
  geom_line(aes(y = a_c), col = "blue") +
  geom_line(aes(y = a_j), col = "red") +
  geom_line(aes(y = a_lim), col = "purple") +
  facet_wrap(~PPFD)

l$calc_A_lim(42.75*101.3*1000*1e-6, PPFD = 900)

```
```{r}

l <- Leaf(vcmax = 100, p_50 = 1.731347, c = 2.04, b = 2.072101, psi_crit = 3.548059, beta=15000, beta_2 = 1, huber_value = 0.000157, K_s = 2)

l$find_max_ci(900, 0, k_l_max)


system.time(l$optimise_ci_Sperry_Newton_recall(10, 0, k_l_max))
l$optimise_ci_Sperry_Newton_recall(10, 0, k_l_max)
l$optimise_psi_stem_Sperry_Newton_recall(10, 0, k_l_max)
l$optimise_ci_Sperry_Newton_recall()
```

```{r}
l$calc_profit_Sperry_ci(900, 0, 32.0832, k_l_max)

tibble(ci = seq(42.75 * 101.3*1000*1e-6, l$find_max_ci(900, 0, k_l_max), length.out=100), psi_soil= 0, PPFD = 900, k_l_max = k_l_max) %>%
  rowwise() %>%
  mutate(profit = l$calc_profit_Sperry_ci(PPFD, psi_soil, ci, k_l_max)) %>%
  ggplot(aes(x= ci, y = profit)) + geom_line()



```
```{r}

p0 <- scm_base_parameters("FF16w")
p0$disturbance_mean_interval <- 2
p0$max_patch_lifetime <- 2

p50_1 <- 2
p50_2 <- 4
p50_3 <- 5

p1 <- expand_parameters(trait_matrix(c(p50_1,p50_2,p50_3), "p_50"), p0, mutant=FALSE, birth_rate_list = c(1,1,1))
env <- make_environment("FF16w", soil_initial_state = rep(0.2, 1), rainfall = 1)


p_50_2_K_s <- function(p50){
  1.638999*(p50/2)^(-1.38)
}

calc_vul_b <- function(p_50, c){
  num <- p_50
  den <- (-log(1-50/100))^(1/c)
  num/den
}


calc_psi_crit <- function(b,c) {
  b*(log(1/0.05))^(1/c)
}


p1$strategies[[1]]$K_s <- p_50_2_K_s(p50_1)
p1$strategies[[2]]$K_s <- p_50_2_K_s(p50_2)
p1$strategies[[3]]$K_s <- p_50_2_K_s(p50_3)

p1$strategies[[1]]$b <- calc_vul_b(p50_1, p1$strategies[[1]]$c)
p1$strategies[[2]]$b <- calc_vul_b(p50_2, p1$strategies[[2]]$c)
p1$strategies[[3]]$b <- calc_vul_b(p50_2, p1$strategies[[3]]$c)

p1$strategies[[1]]$psi_crit <- calc_psi_crit(p1$strategies[[1]]$b, p1$strategies[[1]]$c)
p1$strategies[[2]]$psi_crit <- calc_psi_crit(p1$strategies[[2]]$b, p1$strategies[[2]]$c)
p1$strategies[[3]]$psi_crit <- calc_psi_crit(p1$strategies[[3]]$b, p1$strategies[[3]]$c)

# 
# test_low5 <- c(1,2)
# saveRDS(test_low5, "plant/test_low5.RDS")


ctrl = scm_base_control()
# 
ctrl$ode_tol_abs <- ctrl$ode_tol_rel <- 1e-3
ctrl$ode_step_size_initial <- ctrl$ode_step_size_min <- 1e-5
ctrl$schedule_eps <- 0.01
#time take for recall optimiser
result_update <- system.time(run_scm_collect(p1, env, ctrl))
```

