---
title: "testing_GSS"
author: "Isaac Towers"
date: "2022-09-06"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```

```{r}
devtools::load_all(".")
```

```{r}
p_50_2_K_s <- function(p50){
    1.638999*(p50/2)^(-1.38)
  }
  
  calc_vul_b <- function(p_50, c){
    num <- p_50
    den <- (-log(1-50/100))^(1/c)
    num/den
  }
  
  
  calc_psi_crit <- function(b,c) {
    b*(log(1/0.05))^(1/c)
  }
  
  calc_k_l_max <- function(K_s, h_v, h){
  K_s * h_v / h
}
```


```{r}
vcmax = 100 #maximum carboxylation rate, defined by leaf nitrogen (umol m^-2 s^-1) 
  p_50 = 1.731347 #stem water potential at 50% loss of conductivity
  b = 2.072101 #shape parameter for vulnerability curve, point of 37% conductance (-MPa) 
  c = 2.04 #shape parameter for hydraulic vulnerability curve (unitless) estimated from trait data in Austraits from Choat et al. 2012
  psi_crit = calc_psi_crit(b, c) #stem water potential at which conductance is 95%
  huber_value = 0.000157 #huber value (m^2 sapwood area m^-2 leaf area)
  K_s = 2 #stem-specific conductivity (kg h2o m^-1 stem s^-1 MPa^-1)
  h = 5 #height or path length (m)
  

  l <- Leaf(vcmax = vcmax, p_50 = p_50, c = c, b = b, psi_crit = psi_crit, beta=15000, beta_2 = 1, huber_value = huber_value, K_s = K_s, epsilon_leaf = 0.0001)
  
 
  #now set physiology, PPFD_, k_l_max_, and psi_soil_ should be not NA
  
  PPFD = 900
  k_l_max = calc_k_l_max(K_s, huber_value, 5)
  psi_soil = 2
  
  l$set_physiology(PPFD, psi_soil = psi_soil, k_l_max = k_l_max)
```

```{r}
max_ci <- l$find_max_ci_one_line()
```



```{r}
GSS <- function(){
  gr = (sqrt(5) + 1) / 2;

bound_a = NA  
bound_b = NA
bound_c = NA
bound_d = NA
  
bound_a = 42.75*0.1013;
bound_b = max_ci;

delta_crit = 0.01;

bound_c = bound_b - (bound_b - bound_a) / gr;
bound_d = bound_a + (bound_b - bound_a) / gr;
count = 0
  
while (abs(bound_b - bound_a) > delta_crit) {
  
  profit_at_c = l$calc_profit_Sperry_ci_one_line(bound_c);
  profit_at_d = l$calc_profit_Sperry_ci_one_line(bound_d);
  
  if (profit_at_c > profit_at_d) {
        bound_b = bound_d;
      } else {
        bound_a = bound_c;
      }

      bound_c = bound_b - (bound_b - bound_a) / gr;
      bound_d = bound_a + (bound_b - bound_a) / gr;
    
        count = count + 1

      }

    opt_ci = ((bound_b + bound_a) / 2);
    profit = l$calc_profit_Sperry_ci_one_line(opt_ci);
    
    return(tibble(opt_ci = opt_ci, profit = profit, count = count))
}

GSS()

```


```{r}
tibble(ci = seq(42.75*0.1013, max_ci, length.out = 100)) %>%
  rowwise() %>%
mutate(profit = l$calc_profit_Sperry_ci_one_line(ci)) %>%
  ggplot(aes(x = ci, y = profit)) +
  geom_line() +
  geom_point(aes(x=31.2, y = 21.3))
```

```{r}
  l <- Leaf(vcmax = vcmax, p_50 = p_50, c = c, b = b, psi_crit = psi_crit, beta=15000, beta_2 = 1, huber_value = huber_value, K_s = K_s, epsilon_leaf = 0.0001)
  
 
  #now set physiology, PPFD_, k_l_max_, and psi_soil_ should be not NA
  
  PPFD = 900
  k_l_max = calc_k_l_max(K_s, huber_value, 5)
  psi_soil = 3.548
  
  l$set_physiology(PPFD, psi_soil = psi_soil, k_l_max = k_l_max)

l$optimise_ci_Sperry_Newton_recall_one_line(NA)
l$profit
l$opt_ci
```


