---
title: "testing_newton_derivative"
author: "Isaac Towers"
date: "01/08/2022"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
devtools::load_all()
```

```{r}
p_50_2_K_s <- function(p50){
  1.638999*(p50/2)^(-1.38)
}

calc_vul_b <- function(p_50, c){
  num <- p_50
  den <- (-log(1-50/100))^(1/c)
  num/den
}


calc_psi_crit <- function(b,c) {
  b*(log(1/0.05))^(1/c)
}

calc_k_l_max <- function(K_s, h_v, h){
  K_s * h_v / h
}
```

```{r}
c <- 2.04

h_v = 0.000157 #huber value (m^2 sapwood area m^-2 leaf area)
h = 5 #height/path length (m)
eta <- 12.0
eta_c <- 1 - 2 / (1 + eta) + 1 / (1 + 2 * eta)

```

```{r}
calc_profit <- function(p50, PPFD, psi_soil,psi_stem){
  K_s = p_50_2_K_s(p50)
  b = calc_vul_b(p50, c)
  psi_crit = calc_psi_crit(b, c)
  k_l_max = calc_k_l_max(K_s, h_v, h*eta_c)

  l <- Leaf(vcmax = 100, p_50 = p50, c = 2.04, b = b, psi_crit = psi_crit, beta=15000, beta_2 = 1, huber_value = 0.000157, K_s = K_s)
  l$set_physiology(PPFD = PPFD, psi_soil = psi_soil, k_l_max = k_l_max)
  
  psi_stem_initial = psi_stem;
  
  diff_value = 0.0001

  x_1 = psi_stem_initial - diff_value;
  x_2 = psi_stem_initial + diff_value;
    

  y_0 = l$calc_profit_Sperry_one_line(psi_stem_initial);
    
  y_1 = l$calc_profit_Sperry_one_line(x_1);
    
  y_2 = l$calc_profit_Sperry_one_line(x_2);

  first_dev = (y_2 - y_1)/(2*diff_value);
  sec_dev = (y_2 - 2*y_0 + y_1)/(diff_value^2);
  
  x_diff = psi_stem_initial - first_dev/sec_dev
  
  tibble(a_profit = y_0, first_dev = first_dev, sec_dev = sec_dev, x_diff = x_diff)
}
```

```{r}
library(tidyverse)

expand_grid(p50 = c(4), PPFD = c(30), psi_soil = seq(0,5,length.out = 4)) %>%
  mutate(K_s = p_50_2_K_s(p50),b = calc_vul_b(p50, c),psi_crit = calc_psi_crit(b, c)) %>%
  expand_grid(psi_stem = seq(0,10,0.01)) %>%
  filter(psi_stem > psi_soil) %>%
  filter(psi_stem < psi_crit) %>%
  rowwise() %>%
  mutate(output = calc_profit(p50 = p50, psi_stem = psi_stem, PPFD = PPFD, psi_soil = psi_soil)) -> output

output %>%
  unnest(output) %>%
  mutate(x_diff_log = log(x_diff)) %>%
  select(-x_diff_log, x_diff) %>%
  pivot_longer(cols = c(a_profit,first_dev, sec_dev)) %>%
  mutate(psi_soil = paste("Ps = ", round(psi_soil,2), sep = "")) %>%
  mutate(PPFD = as_factor(PPFD)) %>%
  ggplot(aes(x = psi_stem, y = value)) +
  geom_line(aes(group = p50, colour = p50)) +
  facet_grid(name~psi_soil, scales = "free") +
  ylab("") +
  xlab("Psi stem") +
  scale_x_continuous(limits = c(0,10))-> a

output %>%
  unnest(output) %>%
  mutate(x_diff_log = log(x_diff)) %>%
  select(-c(a_profit,first_dev, sec_dev)) %>%
  rename(new_psi_stem = x_diff) %>%
  pivot_longer(cols = c(new_psi_stem)) %>%
  mutate(psi_soil_LABEL = paste("Ps = ", round(psi_soil,2), sep = "")) %>%
  filter(!(name == "new_psi_stem" & value < -5)) %>%
  filter(!(name == "new_psi_stem" & value > 10)) %>%
  mutate(PPFD = as_factor(PPFD)) %>%
  ggplot(aes(x = psi_stem, y = value)) +
  geom_line(aes(group = p50, colour = p50)) +
  facet_grid(name~psi_soil_LABEL, scales = "free") +
  ylab("") +
  xlab("Psi stem") +
  geom_abline(slope= 1, intercept = 0, linetype = "dashed") +
  geom_abline(aes(slope= 0, intercept = psi_soil))  +
  scale_x_continuous(limits = c(0,10)) -> b

library(cowplot)

# png("plot.png", height = 400 , width = 900)
# b
cowplot::plot_grid(a,b, nrow = 2, rel_heights = c(2,1), align = "v")

dev.off()
```


```{r}
calc_profit_Halley <- function(p50, PPFD, psi_soil,psi_stem){
  K_s = p_50_2_K_s(p50)
  b = calc_vul_b(p50, c)
  psi_crit = calc_psi_crit(b, c)
  k_l_max = calc_k_l_max(K_s, h_v, h*eta_c)

  l <- Leaf(vcmax = 100, p_50 = p50, c = 2.04, b = b, psi_crit = psi_crit, beta=15000, beta_2 = 1, huber_value = 0.000157, K_s = K_s)
  l$set_physiology(PPFD = PPFD, psi_soil = psi_soil, k_l_max = k_l_max)
  
  x_0 = psi_stem;
  
  diff_value = 0.001
  
  x_neg_3 = x_0 - 3*diff_value;
  x_neg_2 = x_0 - 2*diff_value;
  x_neg_1 = x_0 - 1*diff_value;
  x_pos_1 = x_0 + 1*diff_value;
  x_pos_2 = x_0 + 2*diff_value;
  x_pos_3 = x_0 - 3*diff_value;

  y_0 = l$calc_profit_Sperry_one_line(x_0);
  y_neg_3 = l$calc_profit_Sperry_one_line(x_neg_3);
  y_neg_2 = l$calc_profit_Sperry_one_line(x_neg_2);
  y_neg_1 = l$calc_profit_Sperry_one_line(x_neg_1);
  y_pos_1 = l$calc_profit_Sperry_one_line(x_pos_1);
  y_pos_2 = l$calc_profit_Sperry_one_line(x_pos_2);
  y_pos_3 = l$calc_profit_Sperry_one_line(x_pos_3);

  
  first_dev = (y_pos_1 - y_neg_1)/(2*diff_value);

  sec_dev= (y_neg_1 - 2*y_0 + y_pos_1)/(diff_value^2);

  third_dev = (-0.5*y_neg_2 + y_neg_1 - y_pos_1 + 0.5*y_pos_2)/(diff_value^3);

  x_diff_Newton = x_0 - first_dev/sec_dev

  x_diff_Halley = x_0 - (2*first_dev*sec_dev)/(2*sec_dev^2 - first_dev*third_dev)

  tibble(a_profit = y_0, first_dev, sec_dev, third_dev, x_diff_Newton, x_diff_Halley)
}
```

```{r}
expand_grid(p50 = c(4), PPFD = c(900), psi_soil = seq(0,5,length.out = 4)) %>%
  mutate(K_s = p_50_2_K_s(p50),b = calc_vul_b(p50, c),psi_crit = calc_psi_crit(b, c)) %>%
  expand_grid(psi_stem = seq(0,10,0.01)) %>%
  filter(psi_stem > psi_soil) %>%
  filter(psi_stem < psi_crit) %>%
  rowwise() %>%
  mutate(output = calc_profit_Halley(p50 = p50, psi_stem = psi_stem, PPFD = PPFD, psi_soil = psi_soil)) -> output
```


```{r}
output %>%
  unnest(output) %>%
  # select(-c(x_diff_Newton, x_diff_Newton_four, x_diff_Halley, x_diff_Halley_four)) %>%
  # pivot_longer(cols = c(a_profit, first_dev, first_dev_two, sec_dev_two, sec_dev_four, third_dev_two, third_dev_two_wiki)) %>%
  # select(-c(x_diff_Newton, x_diff_Newton_four, x_diff_Halley, x_diff_Halley_four)) %>%
  pivot_longer(cols = c(a_profit, first_dev, sec_dev, third_dev,x_diff_Newton, x_diff_Halley)) %>%
  mutate(psi_soil_LABEL = paste("Ps = ", round(psi_soil,2), sep = "")) %>%
  # filter(!(name == "new_psi_stem" & value < -5)) %>%
  # filter(!(name == "new_psi_stem" & value > 10)) %>%
  mutate(PPFD = as_factor(PPFD)) %>%
  ggplot(aes(x = psi_stem, y = value)) +
  geom_line(aes(group = p50, colour = p50)) +
  facet_grid(name~psi_soil_LABEL, scales = "free") +
  ylab("") +
  xlab("Psi stem") +
  geom_abline(slope= 1, intercept = 0, linetype = "dashed") +
  geom_abline(aes(slope= 0, intercept = psi_soil)) -> a

a
```

```{r}
output %>%
  unnest(output) %>%
  select(-c(a_profit, first_dev, first_dev_two, sec_dev_two, sec_dev_four, third_dev_two)) %>%
  pivot_longer(cols = c(x_diff_Newton, x_diff_Newton_four, x_diff_Halley, x_diff_Halley_four)) %>%
  mutate(psi_soil_LABEL = paste("Ps = ", round(psi_soil,2), sep = "")) %>%
  # filter(!(name == "new_psi_stem" & value < -5)) %>%
  # filter(!(name == "new_psi_stem" & value > 10)) %>%
  mutate(PPFD = as_factor(PPFD)) %>%
  ggplot(aes(x = psi_stem, y = value)) +
  geom_line(aes(group = p50, colour = p50)) +
  facet_grid(name~psi_soil_LABEL, scales = "free") +
  ylab("") +
  xlab("Psi stem") +
  # geom_abline(slope= 1, intercept = 0, linetype = "dashed") +
  geom_abline(aes(slope= 0, intercept = psi_soil))  +
  scale_x_continuous(limits = c(0,10)) -> b
```


```{r}
calc_profit_ci <- function(p50, PPFD, psi_soil,ci){
  K_s = p_50_2_K_s(p50)
  b = calc_vul_b(p50, c)
  psi_crit = calc_psi_crit(b, c)
  # k_l_max = calc_k_l_max(K_s, h_v, h*eta_c)
  k_l_max = 0.000843655

  l <- Leaf(vcmax = 100, p_50 = p50, c = 2.04, b = b, psi_crit = psi_crit, beta=15000, beta_2 = 1, huber_value = 0.000157, K_s = K_s)
  l$set_physiology(PPFD = PPFD, psi_soil = psi_soil, k_l_max = k_l_max)
  
  ci_initial = ci;
  diff_value = 0.001
  # max_ci = l$find_max_ci()
  
  y_0 = NA
  first_dev = NA
  sec_dev = NA
  thrd_dev = NA
  x_diff_Newton = NA
  x_diff_Halley = NA
  
  l$calc_assim_gross_one_line(psi_crit)
  if(ci_initial - diff_value*2 >= 42.75*101.3*1000*1e-6 & ci_initial + diff_value*2 <= l$ci){
  y_0 = l$calc_profit_Sperry_ci_one_line(ci_initial)
  
  x_neg_2 = ci_initial - 2*diff_value;
  x_neg_1 = ci_initial - 1*diff_value;
  x_pos_1 = ci_initial + 1*diff_value;
  x_pos_2 = ci_initial + 2*diff_value;

  y_0 = l$calc_profit_Sperry_ci_one_line(ci_initial);
  y_neg_2 = l$calc_profit_Sperry_ci_one_line(x_neg_2);
  y_neg_1 = l$calc_profit_Sperry_ci_one_line(x_neg_1);
  y_pos_1 = l$calc_profit_Sperry_ci_one_line(x_pos_1);
  y_pos_2 = l$calc_profit_Sperry_ci_one_line(x_pos_2);

  
  first_dev = (y_pos_1 - y_neg_1)/(2*diff_value);

  sec_dev = (y_neg_1 - 2*y_0 + y_pos_1)/(diff_value^2);
  
  thrd_dev = (-0.5*y_neg_2 + y_neg_1 - y_pos_1 + 0.5*y_pos_2) / (diff_value^3)
  
  x_diff_Newton = ci_initial - first_dev/sec_dev

  x_diff_Halley = ci_initial - (2*first_dev*sec_dev)/(2*sec_dev^2 - first_dev*thrd_dev)
  }
  
  tibble(a_profit = y_0, first_dev, sec_dev,thrd_dev, x_diff_Newton, x_diff_Halley)
  
}

```

```{r}
expand_grid(p50 = c(2), PPFD = c(30), psi_soil = seq(0,5,length.out = 4)) %>%
  mutate(K_s = p_50_2_K_s(p50),b = calc_vul_b(p50, c),psi_crit = calc_psi_crit(b, c)) %>%
  expand_grid(ci = seq(42.75*101.3*1000*1e-6,40,0.1)) %>%
  rowwise() %>%
  mutate(output = calc_profit_ci(p50 = p50, ci = ci, PPFD = PPFD, psi_soil = psi_soil)) -> output
```

```{r}
output %>%
  unnest(output) %>%
  pivot_longer(cols = c(a_profit, first_dev, sec_dev, x_diff_Newton, x_diff_Halley)) %>%
  ggplot(aes(x = ci, y = value)) +
  geom_line(aes(colour = p50, group = p50)) +
  facet_grid(name~psi_soil, scales = "free") +
  geom_abline(slope = 1, intercept = 0)
```



```{r}
expand_grid(p50 = c(2), PPFD = c(500), psi_soil = seq(0.020171, length.out = 1)) %>%
  mutate(K_s = p_50_2_K_s(p50),b = calc_vul_b(p50, c),psi_crit = calc_psi_crit(b, c)) %>%
  expand_grid(ci = seq(42.75*101.3*1000*1e-6,45,0.1)) %>%
  rowwise() %>%
  mutate(output = calc_profit_ci(p50 = p50, ci = ci, PPFD = PPFD, psi_soil = psi_soil)) -> output
```

```{r}
output %>%
  unnest(output) %>%
  pivot_longer(cols = c(a_profit, first_dev, sec_dev, thrd_dev, x_diff_Newton, x_diff_Halley)) %>%
  ggplot(aes(x = ci, y = value)) +
  geom_line(aes(colour = p50, group = p50)) +
  facet_grid(name~psi_soil, scales = "free") +
  geom_abline(slope = 1, intercept = 0)
```



```{r}
PPFD <- 900

psi_soil <- 0.5

p50 <- 2

K_s = p_50_2_K_s(p50)
b = calc_vul_b(p50, c)
psi_crit = calc_psi_crit(b, c)
k_l_max = calc_k_l_max(K_s, h_v, h*eta_c)

l <- Leaf(vcmax = 10, p_50 = p50, c = 2.04, b = b, psi_crit = psi_crit, beta=15000, beta_2 = 1, huber_value = 0.000157, K_s = K_s)
l$set_physiology(PPFD = PPFD, psi_soil = psi_soil, k_l_max = k_l_max)

l$optimise_ci_Sperry_Newton_recall_one_line(20)


```


```{r}
p50 <- 2
K_s = p_50_2_K_s(p50)
  b = calc_vul_b(p50, c)
  psi_crit = calc_psi_crit(b, c)
  k_l_max = calc_k_l_max(K_s, h_v, h*eta_c)

PPFD = 499.544  
psi_soil   = 4.0983
k_l_max = 7.53293e-05

l <- Leaf(vcmax = 100, p_50 = p50, c = 2.04, b = b, psi_crit = psi_crit, beta=15000, beta_2 = 1, huber_value = 0.000157, K_s = K_s)
l$set_physiology(PPFD = PPFD, psi_soil = psi_soil, k_l_max = k_l_max)


tibble(ci = seq(42.75*101.3*1000*1e-6 , l$find_max_ci_one_line(), length.out = 100)) %>%
  rowwise() %>%
  mutate(profit = l$calc_profit_Sperry_ci_one_line(ci))%>%
  ggplot() +
  geom_line(aes(x = ci ,y =profit))



l$calc_A_lim_one_line(42.75*101.3*1000*1e-6)
l$find_max_ci_one_line()  
  42.75*101.3*1000*1e-6
tibble(ci = seq(4.33,4.330998, length.out = 100)) %>%
rowwise() %>%
  mutate(profit = l$calc_profit_Sperry_ci_one_line(ci)) %>%
  ggplot() +
  geom_line(aes(x = ci ,y =profit))
  
  
  l$calc_A_lim_one_line(4.33)
  -0.0009846407 * 1e-6 * 101.3 * 1000/(40 - 4.33) * 1.6*2/55.4939/101.3
  l$calc_psi_stem_ci(-1.591767e-09)
  l$optimise_ci_Sperry_Newton_recall_one_line(NA)  
  
```

```{r}
l$find_max_ci_one_line()
42.75 * 101.3 * 1000 * 1e-6
tibble(ci = seq(4.330575,8.772588, length.out= 100)) %>%
  rowwise() %>%
  mutate(profit = l$calc_profit_Sperry_ci_one_line(ci)) %>%
  ggplot() +
  geom_line(aes(x = ci, y = profit))

```

```{r}
 
  ci_initial = 6.50914;
  diff_value = 0.001
  # max_ci = l$find_max_ci()
  ci_initial = x_diff_Newton
  
  # y_0 = NA
  # first_dev = NA
  # sec_dev = NA
  # x_diff_Newton = NA
  # 
  # l$calc_assim_gross_one_line(psi_crit)
  # if(ci_initial - diff_value*2 >= 42.75*101.3*1000*1e-6 & ci_initial + diff_value*2 <= l$ci)
  # y_0 = l$calc_profit_Sperry_ci_one_line(ci_initial)
  # 
  x_neg_2 = ci_initial - 2*diff_value;
  x_neg_1 = ci_initial - 1*diff_value;
  x_pos_1 = ci_initial + 1*diff_value;
  x_pos_2 = ci_initial + 2*diff_value;

  y_0 = l$calc_profit_Sperry_ci_one_line(ci_initial);
  y_neg_2 = l$calc_profit_Sperry_ci_one_line(x_neg_2);
  y_neg_1 = l$calc_profit_Sperry_ci_one_line(x_neg_1);
  y_pos_1 = l$calc_profit_Sperry_ci_one_line(x_pos_1);
  y_pos_2 = l$calc_profit_Sperry_ci_one_line(x_pos_2);

  
  first_dev = (y_pos_1 - y_neg_1)/(2*diff_value);

  sec_dev = (y_neg_1 - 2*y_0 + y_pos_1)/(diff_value^2);
  
  x_diff_Newton = ci_initial - first_dev/sec_dev
ci_initial - x_diff_Newton < ci_initial*1/1000
```


```{r}

  l$calc_hydraulic_cost_Sperry(psi_soil)
  
  ci_initial = 4.33157;
  diff_value = 0.001
  # max_ci = l$find_max_ci()
  ci_initial = x_diff_Newton
  
  # y_0 = NA
  # first_dev = NA
  # sec_dev = NA
  # x_diff_Newton = NA
  # 
  # l$calc_assim_gross_one_line(psi_crit)
  # if(ci_initial - diff_value*2 >= 42.75*101.3*1000*1e-6 & ci_initial + diff_value*2 <= l$ci)
  # y_0 = l$calc_profit_Sperry_ci_one_line(ci_initial)
  # 
  x_neg_2 = ci_initial - 2*diff_value;
  x_neg_1 = ci_initial - 1*diff_value;
  x_pos_1 = ci_initial + 1*diff_value;
  x_pos_2 = ci_initial + 2*diff_value;

  y_0 = l$calc_profit_Sperry_ci_one_line(ci_initial);
  y_neg_2 = l$calc_profit_Sperry_ci_one_line(x_neg_2);
  y_neg_1 = l$calc_profit_Sperry_ci_one_line(x_neg_1);
  y_pos_1 = l$calc_profit_Sperry_ci_one_line(x_pos_1);
  y_pos_2 = l$calc_profit_Sperry_ci_one_line(x_pos_2);

  
  first_dev = (y_pos_1 - y_neg_1)/(2*diff_value);

  sec_dev = (y_neg_1 - 2*y_0 + y_pos_1)/(diff_value^2);
  
  x_diff_Newton = ci_initial - first_dev/sec_dev

```



```{r}
p_50_2_K_s <- function(p50){
  1.638999*(p50/2)^(-1.38)
}

calc_vul_b <- function(p_50, c){
  num <- p_50
  den <- (-log(1-50/100))^(1/c)
  num/den
}


calc_psi_crit <- function(b,c) {
  b*(log(1/0.05))^(1/c)
}

calc_k_l_max <- function(K_s, h_v, h){
  K_s * h_v / h
}
```

```{r}
c <- 2.04

h_v = 0.000157 #huber value (m^2 sapwood area m^-2 leaf area)
h = 5 #height/path length (m)
eta <- 12.0
eta_c <- 1 - 2 / (1 + eta) + 1 / (1 + 2 * eta)

```


```{r}
diff_value = 0.001

p50 <- 2
K_s = p_50_2_K_s(p50)
  b = calc_vul_b(p50, c)
  psi_crit = calc_psi_crit(b, c)
  k_l_max = calc_k_l_max(K_s, h_v, h*eta_c)

PPFD = 500  
psi_soil   = 0.020171
k_l_max = 0.000843655

l <- Leaf(vcmax = 100, p_50 = 2, c = 2.04, b = 2, psi_crit = 3.5, beta=15000, beta_2 = 1, huber_value = 0.000157, K_s = 2)

l$set_physiology(PPFD = PPFD, psi_soil = psi_soil, k_l_max = k_l_max)

l$optimise_psi_stem_Sperry_Newton_recall_one_line(NA)
l$optimise_ci_Sperry_Newton_recall_one_line(NA)

l$calc_E_supply(3.5)

l$calc_A_lim_one_line(40+0.001)*1e-6 * 101.3 *1000
l$profit
l$opt_ci

library(ggplot2)
library(tidyverse)

tibble(c_i = seq(20, 39, 0.01)) %>%
  rowwise() %>%
  mutate(profit = l$calc_profit_Sperry_ci_one_line(c_i)) %>%
  ggplot(aes( x= c_i, y = profit)) +
  geom_line() +
  geom_vline(xintercept = 35.5638)


```

Testing what the deal is with the much faster small diff value

```{r}
calc_profit_ci <- function(p50, PPFD, psi_soil,ci){
  K_s = p_50_2_K_s(p50)
  b = calc_vul_b(p50, c)
  psi_crit = calc_psi_crit(b, c)
  # k_l_max = calc_k_l_max(K_s, h_v, h*eta_c)
  k_l_max = 0.000843655

  l <- Leaf(vcmax = 100, p_50 = p50, c = 2.04, b = b, psi_crit = psi_crit, beta=15000, beta_2 = 1, huber_value = 0.000157, K_s = K_s)
  l$set_physiology(PPFD = PPFD, psi_soil = psi_soil, k_l_max = k_l_max)
  
  ci_initial = ci;
  diff_value = 0.001
  # max_ci = l$find_max_ci()
  
  y_0 = NA
  first_dev = NA
  sec_dev = NA
  thrd_dev = NA
  x_diff_Newton = NA
  x_diff_Halley = NA
  
  l$calc_assim_gross_one_line(psi_crit)
  y_0 = l$calc_profit_Sperry_ci_one_line(ci_initial)
  
  x_neg_1 = ci_initial - 1*diff_value;
  x_pos_1 = ci_initial + 1*diff_value;

  y_0 = l$calc_profit_Sperry_ci_one_line(ci_initial);
  y_neg_1 = l$calc_profit_Sperry_ci_one_line(x_neg_1);
  y_pos_1 = l$calc_profit_Sperry_ci_one_line(x_pos_1);

  
  first_dev = (y_pos_1 - y_neg_1)/(2*diff_value);

  sec_dev = (y_neg_1 - 2*y_0 + y_pos_1)/(diff_value^2);
  

  x_diff_Newton = ci_initial - first_dev/sec_dev
  
  tibble(a_profit = y_0, first_dev, sec_dev, x_diff_Newton)
}
  
```

```{r}

```

