// Generated by RcppR6 (0.1): do not edit by hand
#include <tree2.h>

// [[Rcpp::export]]
ode::test::Lorenz Lorenz__ctor(double sigma, double R, double b) {
  return ode::test::Lorenz(sigma, R, b);
}
// [[Rcpp::export]]
size_t Lorenz__size__get(tree2::RcppR6::RcppR6<ode::test::Lorenz> obj_) {
  return obj_->size();
}

// [[Rcpp::export]]
std::vector<double> Lorenz__ode_values__get(tree2::RcppR6::RcppR6<ode::test::Lorenz> obj_) {
  return obj_->ode_values();
}
// [[Rcpp::export]]
void Lorenz__ode_values__set(tree2::RcppR6::RcppR6<ode::test::Lorenz> obj_, std::vector<double> value) {
  obj_->set_ode_values(value);
}

// [[Rcpp::export]]
std::vector<double> Lorenz__ode_rates__get(tree2::RcppR6::RcppR6<ode::test::Lorenz> obj_) {
  return obj_->r_ode_rates();
}

// [[Rcpp::export]]
Rcpp::NumericVector Lorenz__pars__get(tree2::RcppR6::RcppR6<ode::test::Lorenz> obj_) {
  return obj_->r_get_pars();
}


// [[Rcpp::export]]
ode::OdeSystem<ode::test::Lorenz> OdeRunner___Lorenz__ctor(ode::test::Lorenz obj) {
  return ode::OdeSystem<ode::test::Lorenz>(obj);
}
// [[Rcpp::export]]
ode::test::Lorenz OdeRunner___Lorenz__obj__get(tree2::RcppR6::RcppR6<ode::OdeSystem<ode::test::Lorenz> > obj_) {
  return obj_->obj;
}
// [[Rcpp::export]]
void OdeRunner___Lorenz__obj__set(tree2::RcppR6::RcppR6<ode::OdeSystem<ode::test::Lorenz> > obj_, ode::test::Lorenz value) {
  obj_->obj = value;
}

