// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/tree2.h"
#include <Rcpp.h>

using namespace Rcpp;

// Lorenz__ctor
ode::test::Lorenz Lorenz__ctor(double sigma, double R, double b);
RcppExport SEXP tree2_Lorenz__ctor(SEXP sigmaSEXP, SEXP RSEXP, SEXP bSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP );
        Rcpp::traits::input_parameter< double >::type R(RSEXP );
        Rcpp::traits::input_parameter< double >::type b(bSEXP );
        ode::test::Lorenz __result = Lorenz__ctor(sigma, R, b);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// Lorenz__size__get
size_t Lorenz__size__get(tree2::RcppR6::RcppR6<ode::test::Lorenz> obj_);
RcppExport SEXP tree2_Lorenz__size__get(SEXP obj_SEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< tree2::RcppR6::RcppR6<ode::test::Lorenz> >::type obj_(obj_SEXP );
        size_t __result = Lorenz__size__get(obj_);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// Lorenz__ode_values__get
std::vector<double> Lorenz__ode_values__get(tree2::RcppR6::RcppR6<ode::test::Lorenz> obj_);
RcppExport SEXP tree2_Lorenz__ode_values__get(SEXP obj_SEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< tree2::RcppR6::RcppR6<ode::test::Lorenz> >::type obj_(obj_SEXP );
        std::vector<double> __result = Lorenz__ode_values__get(obj_);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// Lorenz__ode_values__set
void Lorenz__ode_values__set(tree2::RcppR6::RcppR6<ode::test::Lorenz> obj_, std::vector<double> value);
RcppExport SEXP tree2_Lorenz__ode_values__set(SEXP obj_SEXP, SEXP valueSEXP) {
BEGIN_RCPP
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< tree2::RcppR6::RcppR6<ode::test::Lorenz> >::type obj_(obj_SEXP );
        Rcpp::traits::input_parameter< std::vector<double> >::type value(valueSEXP );
        Lorenz__ode_values__set(obj_, value);
    }
    return R_NilValue;
END_RCPP
}
// Lorenz__ode_rates__get
std::vector<double> Lorenz__ode_rates__get(tree2::RcppR6::RcppR6<ode::test::Lorenz> obj_);
RcppExport SEXP tree2_Lorenz__ode_rates__get(SEXP obj_SEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< tree2::RcppR6::RcppR6<ode::test::Lorenz> >::type obj_(obj_SEXP );
        std::vector<double> __result = Lorenz__ode_rates__get(obj_);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// Lorenz__pars__get
Rcpp::NumericVector Lorenz__pars__get(tree2::RcppR6::RcppR6<ode::test::Lorenz> obj_);
RcppExport SEXP tree2_Lorenz__pars__get(SEXP obj_SEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< tree2::RcppR6::RcppR6<ode::test::Lorenz> >::type obj_(obj_SEXP );
        Rcpp::NumericVector __result = Lorenz__pars__get(obj_);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// OdeRunner___Lorenz__ctor
ode::OdeSystem<ode::test::Lorenz> OdeRunner___Lorenz__ctor(ode::test::Lorenz obj);
RcppExport SEXP tree2_OdeRunner___Lorenz__ctor(SEXP objSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< ode::test::Lorenz >::type obj(objSEXP );
        ode::OdeSystem<ode::test::Lorenz> __result = OdeRunner___Lorenz__ctor(obj);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// OdeRunner___Lorenz__obj__get
ode::test::Lorenz OdeRunner___Lorenz__obj__get(tree2::RcppR6::RcppR6<ode::OdeSystem<ode::test::Lorenz> > obj_);
RcppExport SEXP tree2_OdeRunner___Lorenz__obj__get(SEXP obj_SEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< tree2::RcppR6::RcppR6<ode::OdeSystem<ode::test::Lorenz> > >::type obj_(obj_SEXP );
        ode::test::Lorenz __result = OdeRunner___Lorenz__obj__get(obj_);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// OdeRunner___Lorenz__obj__set
void OdeRunner___Lorenz__obj__set(tree2::RcppR6::RcppR6<ode::OdeSystem<ode::test::Lorenz> > obj_, ode::test::Lorenz value);
RcppExport SEXP tree2_OdeRunner___Lorenz__obj__set(SEXP obj_SEXP, SEXP valueSEXP) {
BEGIN_RCPP
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< tree2::RcppR6::RcppR6<ode::OdeSystem<ode::test::Lorenz> > >::type obj_(obj_SEXP );
        Rcpp::traits::input_parameter< ode::test::Lorenz >::type value(valueSEXP );
        OdeRunner___Lorenz__obj__set(obj_, value);
    }
    return R_NilValue;
END_RCPP
}
