---
title: "comparing_stomatal_optimisation"
author: "Isaac Towers"
date: "2023-04-19"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Install and load packages

```{r}
rm(list=ls())
```


```{r}
devtools::install("/Users/z3533545/Documents/GitHub/plant")
devtools::load_all("/Users/z3533545/Documents/GitHub/plant")
```

```{r}
library(tidyverse)
library(furrr)
library(future)
library(wesanderson)
```

```{r}
library(plant)
```

```{r}
source("R/individual_growth_rate_func.R")
```

```{r}
future::plan("multisession", workers = 16)
```

```{r}
tibble(make_parameters(vcmax = 100, jmax = 167, theta = 0.000157,hmat = 75, beta2 = 1.5, a = 0.24, curv_fact_elec_trans = 0.7, curv_fact_colim = 0.99)) %>%
  mutate(trait_set = 1:n()) %>%
  # group_by(param_set) %>%
  nest(trait_matrix = c(-trait_set)) %>%
  expand_grid(environment = expand_grid(PPFD = 1000, psi_soil = seq(0.01, 4, length.out = 10), atm_vpd = seq(0.01, 4, length.out = 10), ca = 40)) %>%
  unnest(environment) %>%
  mutate(param_set = 1:n()) %>%
  group_by(param_set) %>%
  expand_grid(height = c(1)) %>%
  expand_grid(B_ks1 = c(0.2), B_ks2 = c(2),B_hks1 = c(2), B_hks2 = c(2)) %>%
  mutate(focal_hyperpar = pmap(list(B_ks1 = B_ks1,B_ks2 = B_ks2,B_hks1 = B_hks1, B_hks2 =B_hks2), .f = function(B_ks1, B_ks2, B_hks1, B_hks2) list(B_ks1 = B_ks1,B_ks2 = B_ks2, B_hks1 = B_hks1, B_hks2 = B_hks2))) %>%
  nest(environment = -c(trait_set, trait_matrix, param_set, focal_hyperpar, height)) %>%
  mutate(B_rs1_ = 4012, B_lf2_ = 0.004, B_lf3_ = 8e-04, B_lf5_ = 200000) %>% 
  mutate(leaf = pmap(.l = list(trait_matrix, environment, height, focal_hyperpar, B_rs1_, B_lf2_, B_lf3_, B_lf5_), .f = make_leaf)) -> leaf
```

```{r}
find_states_null <- function(leaf, psi_stem){
  leaf$set_leaf_states_rates_from_psi_stem(psi_stem)
  ci_ <- leaf$ci_  
  
  tibble(ci_ = ci_)
}
```

```{r}
leaf %>%
  unnest(leaf) %>%
  unnest(environment) %>%
  mutate(psi_stem = psi_crit) %>%
  mutate(res = map2(.x = leaf, .y = psi_stem, ~find_states_null(.x, .y))) %>%
  unnest(res) %>%
  unnest(trait_matrix) -> output

output %>%
  filter(psi_soil == 0.01) %>%
  ggplot() +
  geom_point(aes(x = atm_vpd, y = ci_), col = "red") +
  labs(y = expression(paste("Intracellular C", O[2]," (Pa)")), x = "VPD (kPa)") + 
  theme_classic() +
  theme(text = element_text(size = 16))-> a

output %>%
  filter(atm_vpd == 0.01) %>%
  ggplot() +
  geom_point(aes(x = psi_soil, y = ci_), col = "red") +
  labs(y = expression(paste("Intracellular C", O[2]," (Pa)")), x = expression(psi[soil]~(-MPa))) + 
  theme_classic()+
  theme(text = element_text(size = 16))-> b

null_opt <- cowplot::plot_grid(plotlist = list(a,b)) 

png("output/comparing_stomatal_conductance_models/null_model.png", height = 12.8, width = 32, units = "cm", res = 1000)
null_opt
dev.off()
```



```{r}
find_states <- function(leaf, psi_stem){
  cost <- leaf$calculate_cost_LCT(psi_stem)
  ci_ <- leaf$ci_  
  assim_colimited_ <- leaf$assim_colimited_
  stom_cond_CO2_ <- leaf$stom_cond_CO2_
  
  tibble(cost = cost, ci_ = ci_, opt_assim_colimited_ = assim_colimited_, stom_cond_CO2_ = stom_cond_CO2_)
}
```



```{r}
source("R/individual_growth_rate_func.R")

target_traits <- tibble(target_traits = c("jmax","vcmax"), bounds = (tibble(lower = c(100,100), upper = c(100,100)))) 

bounds <- matrix(data = c(target_traits %>% unnest(bounds) %>% pull(lower), target_traits %>% unnest(bounds) %>% pull(upper)), nrow=length(target_traits$target_traits), dimnames = list(target_traits$target_traits, c("lower", "upper")))

  expand_grid(environment = expand_grid(PPFD = 1000, psi_soil = seq(0.01, 4, length.out = 5), atm_vpd = seq(0.01, 4, length.out = 5), ca = 40)) %>%
    unnest(environment) %>%
  mutate(param_set = 1:n()) %>%
  group_by(param_set) %>%
  nest(environment = -param_set) %>%
  mutate(bounds = list(bounds)) %>% ungroup() %>%
  mutate(cost = pmap(.l = list(environment = environment, focal_bounds = bounds, optimise_theta = FALSE), .f = find_lowest_cost)) %>%
  mutate(attr = map(cost, ~attr(.x, "outcome"))) %>%
  unnest(attr)-> output

output %>%
  mutate(names = names(attr)) %>%
  pivot_wider(names_from = "names", values_from = "attr") %>%
  mutate(parameters = map2(vcmax, jmax, ~make_parameters(vcmax = exp(.x), jmax = exp(.y)))) %>%
  select(-bounds, -cost, -jmax, -vcmax) %>% 
  mutate(trait_set = 1:n()) %>%
  # group_by(param_set) %>%
  # nest(trait_matrix = c(-trait_set, -bounds, -cost, -environment, -param_set,-jmax, -vcmax)) %>%
  # unnest(environment) %>%
  mutate(param_set = 1:n()) %>%
  group_by(param_set) %>%
  expand_grid(height = c(1)) %>%
  expand_grid(B_ks1 = c(0.2), B_ks2 = c(2),B_hks1 = c(2), B_hks2 = c(2)) %>%
  mutate(focal_hyperpar = pmap(list(B_ks1 = B_ks1,B_ks2 = B_ks2,B_hks1 = B_hks1, B_hks2 =B_hks2), .f = function(B_ks1, B_ks2, B_hks1, B_hks2) list(B_ks1 = B_ks1,B_ks2 = B_ks2, B_hks1 = B_hks1, B_hks2 = B_hks2))) %>%
  # nest(environment = -c(trait_set, trait_matrix, param_set, focal_hyperpar, height)) %>%
  mutate(B_rs1 = 4012, B_lf2 = 0.004, B_lf3 = 8e-04, B_lf5 = 200000) %>% 
  mutate(leaf = pmap(.l = list(parameters, environment, height, focal_hyperpar, B_rs1, B_lf2, B_lf3, B_lf5), .f = make_leaf)) -> leaf
```


```{r}
leaf %>%
  unnest(leaf) %>%
  unnest(environment) %>%
  mutate(psi_stem = psi_crit) %>%
  mutate(res = map2(.x = leaf, .y = 4, ~find_states(.x, .y))) %>%
  unnest(res) -> output

output %>%
  filter(psi_soil == 0.01) %>%
  ggplot() +
  geom_point(aes(x = atm_vpd, y = ci_), col = "red") +
  labs(y = expression(paste("Intracellular C", O[2]," (Pa)")), x = "VPD (kPa)") + 
  theme_classic() +
  theme(text = element_text(size = 16))-> a

output %>%
  filter(atm_vpd == 0.01) %>%
  ggplot() +
  geom_point(aes(x = psi_soil, y = ci_), col = "red") +
  labs(y = expression(paste("Intracellular C", O[2]," (Pa)")), x = expression(psi[soil]~(-MPa))) + 
  theme_classic()+
  theme(text = element_text(size = 16))-> b

vcmax_jmax_LCT_opt <- cowplot::plot_grid(plotlist = list(a,b)) 

png("output/comparing_stomatal_conductance_models/vcmax_jmax_LCT_opt.png", height = 12.8, width = 32, units = "cm", res = 1000)
vcmax_jmax_LCT_opt
dev.off()
```


```{r}
source("R/individual_growth_rate_func.R")

target_traits <- tibble(target_traits = c("jmax","vcmax","theta"), bounds = (tibble(lower = c(100,100, 0.000157), upper = c(100,100, 0.000157)))) 

bounds <- matrix(data = c(target_traits %>% unnest(bounds) %>% pull(lower), target_traits %>% unnest(bounds) %>% pull(upper)), nrow=length(target_traits$target_traits), dimnames = list(target_traits$target_traits, c("lower", "upper")))

  expand_grid(environment = expand_grid(PPFD = 1000, psi_soil = seq(0.01, 4, length.out = 5), atm_vpd = seq(0.01, 4, length.out = 5), ca = 40)) %>%
    unnest(environment) %>%
  mutate(param_set = 1:n()) %>%
  group_by(param_set) %>%
  nest(environment = -param_set) %>%
  mutate(bounds = list(bounds)) %>% ungroup() %>%
  mutate(cost = pmap(.l = list(environment = environment, focal_bounds = bounds, optimise_theta = TRUE), .f = find_lowest_cost)) %>%
  mutate(attr = map(cost, ~attr(.x, "outcome"))) %>%
  unnest(attr)-> output

output %>%
  mutate(names = names(attr)) %>%
  pivot_wider(names_from = "names", values_from = "attr") %>%
  mutate(vcmax = exp(vcmax), jmax = exp(jmax), theta = exp(theta)) %>% 
  rowwise() %>%
  mutate(parameters = pmap(list(vcmax, jmax, theta), ~make_parameters(vcmax = vcmax, jmax = jmax, theta = theta))) %>%
  ungroup() %>%
  select(-bounds, -cost, -jmax, -vcmax, -theta) %>% 
  # unnest(parameters) %>% 
  mutate(trait_set = 1:n()) %>%
  # group_by(param_set) %>%
  # nest(trait_matrix = c(-trait_set, -bounds, -cost, -environment, -param_set,-jmax, -vcmax)) %>%
  # unnest(environment) %>%
  mutate(param_set = 1:n()) %>%
  group_by(param_set) %>%
  expand_grid(height = c(1)) %>%
  expand_grid(B_ks1 = c(0.2), B_ks2 = c(2),B_hks1 = c(2), B_hks2 = c(2)) %>%
  mutate(focal_hyperpar = pmap(list(B_ks1 = B_ks1,B_ks2 = B_ks2,B_hks1 = B_hks1, B_hks2 =B_hks2), .f = function(B_ks1, B_ks2, B_hks1, B_hks2) list(B_ks1 = B_ks1,B_ks2 = B_ks2, B_hks1 = B_hks1, B_hks2 = B_hks2))) %>%
  # nest(environment = -c(trait_set, trait_matrix, param_set, focal_hyperpar, height)) %>%
  mutate(B_rs1 = 4012, B_lf2 = 0.004, B_lf3 = 8e-04, B_lf5 = 200000) %>% 
  mutate(leaf = pmap(.l = list(parameters, environment, height, focal_hyperpar, B_rs1, B_lf2, B_lf3, B_lf5), .f = make_leaf)) -> leaf
```


```{r}
leaf %>%
  unnest(leaf) %>%
  unnest(environment) %>%
  mutate(psi_stem = psi_crit) %>%
  mutate(res = map2(.x = leaf, .y = psi_crit, ~find_states(.x, .y))) %>%
  unnest(res) -> output

output %>%
  filter(psi_soil == 0.01) %>%
  ggplot() +
  geom_point(aes(x = atm_vpd, y = ci_), col = "red") +
  labs(y = expression(paste("Intracellular C", O[2]," (Pa)")), x = "VPD (kPa)") + 
  theme_classic() +
  theme(text = element_text(size = 16))-> a

output %>%
  filter(atm_vpd == 0.01) %>%
  ggplot() +
  geom_point(aes(x = psi_soil, y = ci_), col = "red") +
  labs(y = expression(paste("Intracellular C", O[2]," (Pa)")), x = expression(psi[soil]~(-MPa))) + 
  theme_classic()+
  theme(text = element_text(size = 16))-> b

vcmax_jmax_LCT_theta_opt <- cowplot::plot_grid(plotlist = list(a,b)) 

png("output/comparing_stomatal_conductance_models/vcmax_jmax_LCT_theta_opt.png", height = 12.8, width = 32, units = "cm", res = 1000)
vcmax_jmax_LCT_theta_opt
dev.off()
```



```{r}
tibble(make_parameters(vcmax = 100, jmax = 167, theta = 0.000157,hmat = 75, beta2 = 1.5, a = 0.24, curv_fact_elec_trans = 0.7, curv_fact_colim = 0.99)) %>%
  mutate(trait_set = 1:n()) %>%
  # group_by(param_set) %>%
  nest(trait_matrix = c(-trait_set)) %>%
  expand_grid(environment = expand_grid(PPFD = 1000, psi_soil = seq(0.01, 4, length.out = 10), atm_vpd = seq(0.01, 4, length.out = 10), ca = 40)) %>%
  unnest(environment) %>%
  mutate(param_set = 1:n()) %>%
  group_by(param_set) %>%
  expand_grid(height = c(1)) %>%
  expand_grid(B_ks1 = c(0.2), B_ks2 = c(2),B_hks1 = c(2), B_hks2 = c(2)) %>%
  mutate(focal_hyperpar = pmap(list(B_ks1 = B_ks1,B_ks2 = B_ks2,B_hks1 = B_hks1, B_hks2 =B_hks2), .f = function(B_ks1, B_ks2, B_hks1, B_hks2) list(B_ks1 = B_ks1,B_ks2 = B_ks2, B_hks1 = B_hks1, B_hks2 = B_hks2))) %>%
  nest(environment = -c(trait_set, trait_matrix, param_set, focal_hyperpar, height)) %>%
  mutate(B_rs1_ = 4012, B_lf2_ = 0.004, B_lf3_ = 8e-04, B_lf5_ = 200000) %>% 
  mutate(leaf = pmap(.l = list(trait_matrix, environment, height, focal_hyperpar, B_rs1_, B_lf2_, B_lf3_, B_lf5_), .f = make_leaf)) -> leaf
```

```{r}
find_states_profit <- function(leaf){
  leaf$optimise_psi_stem_TF()
  ci_ <- leaf$ci_  
  
  tibble(ci_ = ci_)
}
```


```{r}
leaf %>%
  unnest(leaf) %>%
  unnest(environment) %>%
  mutate(psi_stem = psi_crit) %>%
  mutate(res = map2(.x = leaf, .y = psi_stem, ~find_states_profit(.x))) %>%
  unnest(res) %>%
  unnest(trait_matrix) -> output

output %>%
  filter(psi_soil == 0.01) %>%
  ggplot() +
  geom_point(aes(x = atm_vpd, y = ci_), col = "red") +
  labs(y = expression(paste("Intracellular C", O[2]," (Pa)")), x = "VPD (kPa)") + 
  theme_classic() +
  theme(text = element_text(size = 16))-> a

output %>%
  filter(atm_vpd == 0.01) %>%
  ggplot() +
  geom_point(aes(x = psi_soil, y = ci_), col = "red") +
  labs(y = expression(paste("Intracellular C", O[2]," (Pa)")), x = expression(psi[soil]~(-MPa))) + 
  theme_classic()+
  theme(text = element_text(size = 16))-> b

optimise_profit <- cowplot::plot_grid(plotlist = list(a,b)) 

png("output/comparing_stomatal_conductance_models/optimise_profit.png", height = 12.8, width = 32, units = "cm", res = 1000)
optimise_profit
dev.off()
```


#optimise jmax and vcmax

```{r}
target_traits <- tibble(target_traits = c("vcmax","jmax"), bounds = (tibble(lower = c(100,100), upper = c(100,100)))) %>%
  nest(target_traits = everything())
```

```{r}
target_heights <- tibble(target_heights = c(1))
```

#params
```{r}
trait_data <- expand_grid(hmat = 75, beta2 = 1.5, a = 0.24, curv_fact_elec_trans = 0.7, curv_fact_colim = 0.99) %>%
  mutate(param_set = seq(1:n())) %>%
  group_by(param_set) %>%
  nest(trait_data = -param_set) %>% 
  mutate(expanded_trait_data = map(trait_data, ~ .x %>%unlist() %>% as.list())) %>%
  mutate(expanded_trait_data = map(trait_data, ~do.call(make_parameters, .x))) %>%
  unnest(expanded_trait_data)
```


```{r}
trait_data %>%
  pivot_longer(cols = c(-param_set, -trait_data)) %>%
  nest(expanded_trait_data = c(-param_set, -trait_data)) %>%
  mutate(trait_matrix = map(expanded_trait_data, ~trait_matrix(.x$value, .x$name))) %>%
  expand_grid(strategy_type = c("FF16w")) %>%
  mutate(p0 = map(strategy_type, ~scm_base_parameters(.x))) %>%
  expand_grid(B_ks1 = c(0.2), B_ks2 = c(2),B_hks1 = c(2), B_hks2 = c(2), B_lf2=0.004, B_lf3=0.0008, B_lf4=2100, B_lf5=200000) %>%
  mutate(focal_hyperpar = pmap(list(B_ks1 = B_ks1,B_hks1 = B_hks1, B_ks2 = B_ks2, B_hks2 = B_hks2, B_lf2=B_lf2, B_lf3=B_lf3, B_lf4 = B_lf4, B_lf5 = B_lf5), .f = function(B_ks1, B_hks1, B_ks2, B_hks2, B_lf2, B_lf3, B_lf4,B_lf5) list(B_ks1 = B_ks1, B_hks1 = B_hks1, B_ks2 = B_ks2, B_hks2 = B_hks2, B_lf2 = B_lf2, B_lf3 = B_lf3, B_lf4 = B_lf4, B_lf5 = B_lf5))) -> trait_data_expanded
```

```{r}
trait_data_expanded %>%
  mutate(env = map(strategy_type, ~make_environment(.x))) %>%
  # expand_grid(soil_moist = exp(c(log(0.1), seq(log(0.01),log(1),length.out = 10)))) -> trait_data_environment
 expand_grid(
    psi_soil = seq(0.01, 4, length.out = 10),
    ca = 40,
    atm_vpd = 0.1,
    canopy_openess = 1) -> trait_data_environment_soil_moist

trait_data_expanded %>%
  mutate(env = map(strategy_type, ~make_environment(.x))) %>%
  # expand_grid(soil_moist = exp(c(log(0.1), seq(log(0.01),log(1),length.out = 10)))) -> trait_data_environment
 expand_grid(
   psi_soil = 0.1,
    ca = 40,
    atm_vpd = seq(0.10, 4, length.out = 10), 
   canopy_openess = 1) -> trait_data_environment_vpd

trait_data_environment <- bind_rows(trait_data_environment_soil_moist, trait_data_environment_vpd)
```

```{r}
trait_data_environment %>%
  expand_grid(target_traits, target_heights)-> trait_data_environment_bounds
```


```{r}
trait_data_environment_bounds %>%
  mutate(res = future_pmap(., find_max_growth, use_default_strategy = FALSE, use_optim = TRUE)) -> growth_outcome
```

```{r}
growth_outcome %>%
  mutate(ret = map(res, ~.x$res)) %>% 
  mutate(attr = map(ret, ~attr(.x, "height"))) %>%
  unnest(attr, target_traits) %>% 
  mutate(attr = exp(attr)) %>%
  select(-bounds) %>%
  pivot_wider(names_from = target_traits, values_from = attr) %>%
  filter(ret != 0) %>%
  select(ca, atm_vpd, canopy_openess, psi_soil, vcmax, jmax, target_heights, trait_data, focal_hyperpar) -> optimum_traits
```


```{r}
indv_growth_trait_data <- tibble(trait_data = optimum_traits$trait_data[1], vcmax = optimum_traits$vcmax, jmax = optimum_traits$jmax) %>%
  unnest(trait_data) %>%
  mutate(param_set = seq(1:n())) %>%
  group_by(param_set) %>%
  nest(trait_data = -param_set) %>% 
  mutate(expanded_trait_data = map(trait_data, ~ .x %>%unlist() %>% as.list())) %>%
  mutate(expanded_trait_data = map(trait_data, ~do.call(make_parameters, .x))) %>%
  unnest(expanded_trait_data)
```

```{r}
indv_growth_trait_data %>%
  pivot_longer(cols = c(-param_set, -trait_data)) %>%
  nest(expanded_trait_data = c(-param_set, -trait_data)) %>%
  mutate(trait_matrix = map(expanded_trait_data, ~trait_matrix(.x$value, .x$name))) %>%
  expand_grid(strategy_type = c("FF16w")) %>%
  mutate(p0 = map(strategy_type, ~scm_base_parameters(.x))) %>%
  mutate(focal_hyperpar = optimum_traits[1,]$focal_hyperpar) -> indv_growth_trait_data_expanded
```

```{r}
indv_growth_trait_data_expanded %>%
  mutate(env = map(strategy_type, ~make_environment(.x))) %>%
  # expand_grid(soil_moist = exp(c(log(0.1), seq(log(0.01),log(1),length.out = 10)))) -> trait_data_environment
 tibble(
    psi_soil = optimum_traits$psi_soil,
    ca = optimum_traits$ca,
    atm_vpd = optimum_traits$atm_vpd,
              canopy_openess = optimum_traits$canopy_openess) -> trait_data_environment 
```

```{r}
trait_data_environment %>%bind_cols(target_heights = optimum_traits$target_heights)-> trait_data_environment_bounds
```

```{r}
trait_data_environment_bounds %>% 
  mutate(param_set = 1:n()) %>%
  group_by(param_set) %>%
  nest(environment = c(psi_soil, ca, atm_vpd, canopy_openess)) %>%
  mutate(res = pmap(.l = list(trait_matrix, environment, target_heights, focal_hyperpar), .f = run_individual_through_height)) -> outcome_optimised
```

```{r}
tibble(outcome_optimised = outcome_optimised %>% ungroup() %>% nest()) %>%
  pivot_longer(cols = c(outcome_optimised), names_to = "outcome_type") %>%
  unnest(value) %>%
  unnest(data) -> outcome
```

```{r}
outcome %>% 
  unnest(trait_data) %>%
  filter(target_heights == 1) %>%
  ungroup() %>%
  unnest(environment) %>%
  filter(ca == 40) %>%
  filter(canopy_openess == 1) %>%
  filter(psi_soil == 0.1) %>%
  unnest(trait_matrix) %>%
  ungroup()   %>% 
  unnest_wider(res) %>%
  unnest(ode_rates, ode_state, ode_names) %>%
  pivot_wider(names_from = "ode_names", values_from = c("ode_rates", "ode_state")) %>% 
  unnest(aux_names, aux) %>%
  pivot_wider(names_from = "aux_names", values_from = "aux") %>% 
  ggplot() +
  geom_point(aes(x = atm_vpd, y = ci_), col = "red") +
  labs(y = expression(paste("Intracellular C", O[2]," (Pa)")), x = "VPD (kPa)") + 
  theme_classic() -> a


outcome %>% 
  unnest(trait_data) %>%
  filter(target_heights == 1) %>%
  ungroup() %>%
  unnest(environment) %>%
  filter(ca == 40) %>%
  filter(canopy_openess == 1) %>%
  filter(atm_vpd == 0.1) %>%
  unnest(trait_matrix) %>%
  ungroup()   %>% 
  unnest_wider(res) %>%
  unnest(ode_rates, ode_state, ode_names) %>%
  pivot_wider(names_from = "ode_names", values_from = c("ode_rates", "ode_state")) %>% 
  unnest(aux_names, aux) %>%
  pivot_wider(names_from = "aux_names", values_from = "aux") %>% 
  ggplot() +
  geom_point(aes(x = psi_soil, y = ci_), col = "red") +
  labs(y = expression(paste("Intracellular C", O[2]," (Pa)")), x = expression(psi[soil]~(-MPa))) + 
  theme_classic() -> b

optimise_growth <- cowplot::plot_grid(plotlist = list(a,b))

png("output/comparing_stomatal_conductance_models/optimise_growth.png", height = 12.8, width = 32, units = "cm", res = 1000)
optimise_growth
dev.off()
```



#optimise jmax and vcmax and theta

```{r}
target_traits <- tibble(target_traits = c("vcmax","jmax","theta"), bounds = (tibble(lower = c(100,100, 0.000157), upper = c(100,100, 0.000157)))) %>%
  nest(target_traits = everything())
```

```{r}
target_heights <- tibble(target_heights = c(1))
```

#params
```{r}
trait_data <- expand_grid(hmat = 75, beta2 = 1.5, a = 0.24, curv_fact_elec_trans = 0.7, curv_fact_colim = 0.99) %>%
  mutate(param_set = seq(1:n())) %>%
  group_by(param_set) %>%
  nest(trait_data = -param_set) %>% 
  mutate(expanded_trait_data = map(trait_data, ~ .x %>%unlist() %>% as.list())) %>%
  mutate(expanded_trait_data = map(trait_data, ~do.call(make_parameters, .x))) %>%
  unnest(expanded_trait_data)
```


```{r}
trait_data %>%
  pivot_longer(cols = c(-param_set, -trait_data)) %>%
  nest(expanded_trait_data = c(-param_set, -trait_data)) %>%
  mutate(trait_matrix = map(expanded_trait_data, ~trait_matrix(.x$value, .x$name))) %>%
  expand_grid(strategy_type = c("FF16w")) %>%
  mutate(p0 = map(strategy_type, ~scm_base_parameters(.x))) %>%
  expand_grid(B_ks1 = c(0.2), B_ks2 = c(2),B_hks1 = c(2), B_hks2 = c(2), B_lf2=0.004, B_lf3=0.0008, B_lf4=2100, B_lf5=200000) %>%
  mutate(focal_hyperpar = pmap(list(B_ks1 = B_ks1,B_hks1 = B_hks1, B_ks2 = B_ks2, B_hks2 = B_hks2, B_lf2=B_lf2, B_lf3=B_lf3, B_lf4 = B_lf4, B_lf5 = B_lf5), .f = function(B_ks1, B_hks1, B_ks2, B_hks2, B_lf2, B_lf3, B_lf4,B_lf5) list(B_ks1 = B_ks1, B_hks1 = B_hks1, B_ks2 = B_ks2, B_hks2 = B_hks2, B_lf2 = B_lf2, B_lf3 = B_lf3, B_lf4 = B_lf4, B_lf5 = B_lf5))) -> trait_data_expanded
```

```{r}
trait_data_expanded %>%
  mutate(env = map(strategy_type, ~make_environment(.x))) %>%
  # expand_grid(soil_moist = exp(c(log(0.1), seq(log(0.01),log(1),length.out = 10)))) -> trait_data_environment
 expand_grid(
    psi_soil = seq(0.01, 4, length.out = 10),
    ca = 40,
    atm_vpd = 0.1,
    canopy_openess = 1) -> trait_data_environment_soil_moist

trait_data_expanded %>%
  mutate(env = map(strategy_type, ~make_environment(.x))) %>%
  # expand_grid(soil_moist = exp(c(log(0.1), seq(log(0.01),log(1),length.out = 10)))) -> trait_data_environment
 expand_grid(
   psi_soil = 0.1,
    ca = 40,
    atm_vpd = seq(0.1, 4, length.out = 10), 
   canopy_openess = 1) -> trait_data_environment_vpd

trait_data_environment <- bind_rows(trait_data_environment_soil_moist, trait_data_environment_vpd)
```

```{r}
trait_data_environment %>%
  expand_grid(target_traits, target_heights)-> trait_data_environment_bounds
```


```{r}
trait_data_environment_bounds %>%
  mutate(res = future_pmap(., find_max_growth, use_default_strategy = FALSE, use_optim = TRUE)) -> growth_outcome
```

```{r}
growth_outcome %>%
  mutate(ret = map(res, ~.x$res)) %>% 
  mutate(attr = map(ret, ~attr(.x, "height"))) %>%
  unnest(attr, target_traits) %>% 
  mutate(attr = exp(attr)) %>%
  select(-bounds) %>%
  pivot_wider(names_from = target_traits, values_from = attr) %>%
  filter(ret != 0) %>%
  select(ca, atm_vpd, canopy_openess, psi_soil, vcmax, jmax, theta, target_heights, trait_data, focal_hyperpar) -> optimum_traits
```


```{r}
indv_growth_trait_data <- tibble(trait_data = optimum_traits$trait_data[1], vcmax = optimum_traits$vcmax, jmax = optimum_traits$jmax, theta = optimum_traits$theta) %>%
  unnest(trait_data) %>%
  mutate(param_set = seq(1:n())) %>%
  group_by(param_set) %>%
  nest(trait_data = -param_set) %>% 
  mutate(expanded_trait_data = map(trait_data, ~ .x %>%unlist() %>% as.list())) %>%
  mutate(expanded_trait_data = map(trait_data, ~do.call(make_parameters, .x))) %>%
  unnest(expanded_trait_data)
```

```{r}
indv_growth_trait_data %>%
  pivot_longer(cols = c(-param_set, -trait_data)) %>%
  nest(expanded_trait_data = c(-param_set, -trait_data)) %>%
  mutate(trait_matrix = map(expanded_trait_data, ~trait_matrix(.x$value, .x$name))) %>%
  expand_grid(strategy_type = c("FF16w")) %>%
  mutate(p0 = map(strategy_type, ~scm_base_parameters(.x))) %>%
  mutate(focal_hyperpar = optimum_traits[1,]$focal_hyperpar) -> indv_growth_trait_data_expanded
```

```{r}
indv_growth_trait_data_expanded %>%
  mutate(env = map(strategy_type, ~make_environment(.x))) %>%
  # expand_grid(soil_moist = exp(c(log(0.1), seq(log(0.01),log(1),length.out = 10)))) -> trait_data_environment
 tibble(
    psi_soil = optimum_traits$psi_soil,
    ca = optimum_traits$ca,
    atm_vpd = optimum_traits$atm_vpd,
              canopy_openess = optimum_traits$canopy_openess) -> trait_data_environment 
```

```{r}
trait_data_environment %>%bind_cols(target_heights = optimum_traits$target_heights)-> trait_data_environment_bounds
```

```{r}
trait_data_environment_bounds %>% 
  mutate(param_set = 1:n()) %>%
  group_by(param_set) %>%
  nest(environment = c(psi_soil, ca, atm_vpd, canopy_openess)) %>%
  mutate(res = pmap(.l = list(trait_matrix, environment, target_heights, focal_hyperpar), .f = run_individual_through_height)) -> outcome_optimised
```

```{r}
tibble(outcome_optimised = outcome_optimised %>% ungroup() %>% nest()) %>%
  pivot_longer(cols = c(outcome_optimised), names_to = "outcome_type") %>%
  unnest(value) %>%
  unnest(data) -> outcome
```

```{r}
outcome %>% 
  unnest(trait_data) %>%
  filter(target_heights == 1) %>%
  ungroup() %>%
  unnest(environment) %>%
  filter(ca == 40) %>%
  filter(canopy_openess == 1) %>%
  filter(psi_soil == 0.1) %>%
  unnest(trait_matrix) %>%
  ungroup()   %>% 
  unnest_wider(res) %>%
  unnest(ode_rates, ode_state, ode_names) %>%
  pivot_wider(names_from = "ode_names", values_from = c("ode_rates", "ode_state")) %>% 
  unnest(aux_names, aux) %>%
  pivot_wider(names_from = "aux_names", values_from = "aux") %>% 
  ggplot() +
  geom_point(aes(x = atm_vpd, y = ci_), col = "red") +
  labs(y = expression(paste("Intracellular C", O[2]," (Pa)")), x = "VPD (kPa)") + 
  theme_classic() -> a


outcome %>% 
  unnest(trait_data) %>%
  filter(target_heights == 1) %>%
  ungroup() %>%
  unnest(environment) %>%
  filter(ca == 40) %>%
  filter(canopy_openess == 1) %>%
  filter(atm_vpd == 0.1) %>%
  unnest(trait_matrix) %>%
  ungroup()   %>% 
  unnest_wider(res) %>%
  unnest(ode_rates, ode_state, ode_names) %>%
  pivot_wider(names_from = "ode_names", values_from = c("ode_rates", "ode_state")) %>% 
  unnest(aux_names, aux) %>%
  pivot_wider(names_from = "aux_names", values_from = "aux") %>% 
  ggplot() +
  geom_point(aes(x = psi_soil, y = ci_), col = "red") +
  labs(y = expression(paste("Intracellular C", O[2]," (Pa)")), x = expression(psi[soil]~(-MPa))) + 
  theme_classic() -> b

optimise_growth_theta <- cowplot::plot_grid(plotlist = list(a,b))

png("output/comparing_stomatal_conductance_models/optimise_growth_theta.png", height = 12.8, width = 32, units = "cm", res = 1000)
optimise_growth_theta
dev.off()
```

```{r}
outcome %>% 
  unnest(trait_data) %>%
  filter(target_heights == 1) %>%
  ungroup() %>%
  unnest(environment) %>%
  filter(ca == 40) %>%
  filter(canopy_openess == 1) %>%
  filter(psi_soil == 0.1) %>%
  unnest(trait_matrix) %>%
  ungroup()   %>% 
  unnest_wider(res) %>%
  unnest(ode_rates, ode_state, ode_names) %>%
  pivot_wider(names_from = "ode_names", values_from = c("ode_rates", "ode_state")) %>% 
  unnest(aux_names, aux) %>%
  pivot_wider(names_from = "aux_names", values_from = "aux") %>%
  mutate(assim_gs_D = assim_colimited_/(ca*sqrt(atm_vpd))) %>%
  ggplot(aes(y = stom_cond_CO2_, x= assim_gs_D)) +
  geom_point()
```


#optimise jmax and vcmax and theta

```{r}
target_traits <- tibble(target_traits = c("vcmax","jmax","theta"), bounds = (tibble(lower = c(100,100, 0.000157), upper = c(100,100, 0.000157)))) %>%
  nest(target_traits = everything())
```

```{r}
target_heights <- tibble(target_heights = c(1))
```

#params
```{r}
trait_data <- expand_grid(hmat = 75, beta2 = 1.5, a = 0.24, curv_fact_elec_trans = 0.7, curv_fact_colim = 0.99) %>%
  mutate(param_set = seq(1:n())) %>%
  group_by(param_set) %>%
  nest(trait_data = -param_set) %>% 
  mutate(expanded_trait_data = map(trait_data, ~ .x %>%unlist() %>% as.list())) %>%
  mutate(expanded_trait_data = map(trait_data, ~do.call(make_parameters, .x))) %>%
  unnest(expanded_trait_data)
```


```{r}
trait_data %>%
  pivot_longer(cols = c(-param_set, -trait_data)) %>%
  nest(expanded_trait_data = c(-param_set, -trait_data)) %>%
  mutate(trait_matrix = map(expanded_trait_data, ~trait_matrix(.x$value, .x$name))) %>%
  expand_grid(strategy_type = c("FF16w")) %>%
  mutate(p0 = map(strategy_type, ~scm_base_parameters(.x))) %>%
  expand_grid(B_ks1 = c(0.2), B_ks2 = c(2),B_hks1 = c(2), B_hks2 = c(2), B_lf2=0.004, B_lf3=0.0008, B_lf4=2100, B_lf5=200000) %>%
  mutate(focal_hyperpar = pmap(list(B_ks1 = B_ks1,B_hks1 = B_hks1, B_ks2 = B_ks2, B_hks2 = B_hks2, B_lf2=B_lf2, B_lf3=B_lf3, B_lf4 = B_lf4, B_lf5 = B_lf5), .f = function(B_ks1, B_hks1, B_ks2, B_hks2, B_lf2, B_lf3, B_lf4,B_lf5) list(B_ks1 = B_ks1, B_hks1 = B_hks1, B_ks2 = B_ks2, B_hks2 = B_hks2, B_lf2 = B_lf2, B_lf3 = B_lf3, B_lf4 = B_lf4, B_lf5 = B_lf5))) -> trait_data_expanded
```


```{r}
future::plan("multisession", workers = 16)
```


```{r}
trait_data_expanded %>%
  mutate(env = map(strategy_type, ~make_environment(.x))) %>%
  # expand_grid(soil_moist = exp(c(log(0.1), seq(log(0.01),log(1),length.out = 10)))) -> trait_data_environment
 expand_grid(
    psi_soil = seq(0.01, 4, length.out = 3),
    ca = seq(30,50, length.out = 3),
    atm_vpd = seq(0.1, 2, length.out = 3),
    canopy_openess = seq(0.5, 1, length.out = 3)) -> trait_data_environment
```

```{r}
trait_data_environment %>%
  expand_grid(target_traits, target_heights)-> trait_data_environment_bounds
```


```{r}
trait_data_environment_bounds %>%
  mutate(res = future_pmap(., find_max_growth, use_default_strategy = FALSE, use_optim = TRUE)) -> growth_outcome
```

```{r}
growth_outcome %>%
  mutate(ret = map(res, ~.x$res)) %>% 
  mutate(attr = map(ret, ~attr(.x, "height"))) %>%
  unnest(attr, target_traits) %>% 
  mutate(attr = exp(attr)) %>%
  select(-bounds) %>%
  pivot_wider(names_from = target_traits, values_from = attr) %>%
  filter(ret != 0) %>%
  select(ca, atm_vpd, canopy_openess, psi_soil, vcmax, jmax, theta, target_heights, trait_data, focal_hyperpar) -> optimum_traits
```


```{r}
indv_growth_trait_data <- tibble(trait_data = optimum_traits$trait_data[1], vcmax = optimum_traits$vcmax, jmax = optimum_traits$jmax, theta = optimum_traits$theta) %>%
  unnest(trait_data) %>%
  mutate(param_set = seq(1:n())) %>%
  group_by(param_set) %>%
  nest(trait_data = -param_set) %>% 
  mutate(expanded_trait_data = map(trait_data, ~ .x %>%unlist() %>% as.list())) %>%
  mutate(expanded_trait_data = map(trait_data, ~do.call(make_parameters, .x))) %>%
  unnest(expanded_trait_data)
```

```{r}
indv_growth_trait_data %>%
  pivot_longer(cols = c(-param_set, -trait_data)) %>%
  nest(expanded_trait_data = c(-param_set, -trait_data)) %>%
  mutate(trait_matrix = map(expanded_trait_data, ~trait_matrix(.x$value, .x$name))) %>%
  expand_grid(strategy_type = c("FF16w")) %>%
  mutate(p0 = map(strategy_type, ~scm_base_parameters(.x))) %>%
  mutate(focal_hyperpar = optimum_traits[1,]$focal_hyperpar) -> indv_growth_trait_data_expanded
```

```{r}
indv_growth_trait_data_expanded %>%
  mutate(env = map(strategy_type, ~make_environment(.x))) %>%
  # expand_grid(soil_moist = exp(c(log(0.1), seq(log(0.01),log(1),length.out = 10)))) -> trait_data_environment
 tibble(
    psi_soil = optimum_traits$psi_soil,
    ca = optimum_traits$ca,
    atm_vpd = optimum_traits$atm_vpd,
              canopy_openess = optimum_traits$canopy_openess) -> trait_data_environment 
```

```{r}
trait_data_environment %>%bind_cols(target_heights = optimum_traits$target_heights)-> trait_data_environment_bounds
```

```{r}
trait_data_environment_bounds %>% 
  mutate(param_set = 1:n()) %>%
  group_by(param_set) %>%
  nest(environment = c(psi_soil, ca, atm_vpd, canopy_openess)) %>%
  mutate(res = pmap(.l = list(trait_matrix, environment, target_heights, focal_hyperpar), .f = run_individual_through_height)) -> outcome_optimised
```

```{r}
tibble(outcome_optimised = outcome_optimised %>% ungroup() %>% nest()) %>%
  pivot_longer(cols = c(outcome_optimised), names_to = "outcome_type") %>%
  unnest(value) %>%
  unnest(data) -> outcome
```



```{r}
outcome %>% 
  unnest(trait_data) %>%
  filter(target_heights == 1) %>%
  ungroup() %>%
  unnest(environment) %>%
  filter(ca == 40) %>%
  filter(canopy_openess == 1) %>%
  filter(psi_soil == 0.1) %>%
  unnest(trait_matrix) %>%
  ungroup()   %>% 
  unnest_wider(res) %>%
  unnest(ode_rates, ode_state, ode_names) %>%
  pivot_wider(names_from = "ode_names", values_from = c("ode_rates", "ode_state")) %>% 
  unnest(aux_names, aux) %>%
  pivot_wider(names_from = "aux_names", values_from = "aux") %>% 
  ggplot() +
  geom_point(aes(x = atm_vpd, y = ci_), col = "red") +
  labs(y = expression(paste("Intracellular C", O[2]," (Pa)")), x = "VPD (kPa)") + 
  theme_classic() -> a


outcome %>% 
  unnest(trait_data) %>%
  filter(target_heights == 1) %>%
  ungroup() %>%
  unnest(environment) %>%
  filter(ca == 40) %>%
  filter(canopy_openess == 1) %>%
  filter(atm_vpd == 0.1) %>%
  unnest(trait_matrix) %>%
  ungroup()   %>% 
  unnest_wider(res) %>%
  unnest(ode_rates, ode_state, ode_names) %>%
  pivot_wider(names_from = "ode_names", values_from = c("ode_rates", "ode_state")) %>% 
  unnest(aux_names, aux) %>%
  pivot_wider(names_from = "aux_names", values_from = "aux") %>% 
  ggplot() +
  geom_point(aes(x = psi_soil, y = ci_), col = "red") +
  labs(y = expression(paste("Intracellular C", O[2]," (Pa)")), x = expression(psi[soil]~(-MPa))) + 
  theme_classic() -> b

optimise_growth_theta <- cowplot::plot_grid(plotlist = list(a,b))

png("output/comparing_stomatal_conductance_models/optimise_growth_theta.png", height = 12.8, width = 32, units = "cm", res = 1000)
optimise_growth_theta
dev.off()
```

```{r}
outcome %>% 
  unnest(trait_data) %>%
  ungroup() %>%
  unnest(environment) %>%
  unnest(trait_matrix) %>%
  ungroup()   %>% 
  unnest_wider(res) %>%
  unnest(ode_rates, ode_state, ode_names) %>%
  pivot_wider(names_from = "ode_names", values_from = c("ode_rates", "ode_state")) %>% 
  unnest(aux_names, aux) %>%
  pivot_wider(names_from = "aux_names", values_from = "aux") %>%
  mutate(assim_ca_D = assim_colimited_/(ca*sqrt(atm_vpd))) %>%
  ggplot(aes(y = stom_cond_CO2_, x= assim_ca_D)) +
  geom_point(aes(colour = atm_vpd)) +
  labs(y = expression(paste(g[s]~(mu~mol~m^{-2}~s^{-1}))),
       x = expression(A/(C[a]~sqrt(D)))) +
  theme_classic() + 
  theme(text = element_text(size = 16)) -> medlyn_model

png("output/comparing_stomatal_conductance_models/medlyn_model.png", height = 16, width = 24, units = "cm", res = 1000)
medlyn_model
dev.off()
```





















```{r}
source("R/individual_growth_rate_func.R")

target_traits <- tibble(target_traits = c("jmax","vcmax"), bounds = (tibble(lower = c(100,100), upper = c(100,100)))) 

bounds <- matrix(data = c(target_traits %>% unnest(bounds) %>% pull(lower), target_traits %>% unnest(bounds) %>% pull(upper)), nrow=length(target_traits$target_traits), dimnames = list(target_traits$target_traits, c("lower", "upper")))

  expand_grid(environment = expand_grid(PPFD = 1000, psi_soil = seq(0.01, 4, length.out = 5), atm_vpd = seq(0.01, 4, length.out = 5), ca = 40)) %>%
    unnest(environment) %>%
  mutate(param_set = 1:n()) %>%
  group_by(param_set) %>%
  nest(environment = -param_set) %>%
  mutate(bounds = list(bounds)) %>% ungroup() %>%
  mutate(cost = pmap(.l = list(environment = environment, focal_bounds = bounds, optimise_theta = FALSE), .f = find_highest_profit)) %>%
  mutate(attr = map(cost, ~attr(.x, "outcome"))) %>%
  unnest(attr)-> output

output %>%
  mutate(names = names(attr)) %>%
  pivot_wider(names_from = "names", values_from = "attr") %>%
  mutate(parameters = map2(vcmax, jmax, ~make_parameters(vcmax = exp(.x), jmax = exp(.y)))) %>%
  select(-bounds, -cost, -jmax, -vcmax) %>% 
  mutate(trait_set = 1:n()) %>%
  # group_by(param_set) %>%
  # nest(trait_matrix = c(-trait_set, -bounds, -cost, -environment, -param_set,-jmax, -vcmax)) %>%
  # unnest(environment) %>%
  mutate(param_set = 1:n()) %>%
  group_by(param_set) %>%
  expand_grid(height = c(1)) %>%
  expand_grid(B_ks1 = c(0.2), B_ks2 = c(2),B_hks1 = c(2), B_hks2 = c(2)) %>%
  mutate(focal_hyperpar = pmap(list(B_ks1 = B_ks1,B_ks2 = B_ks2,B_hks1 = B_hks1, B_hks2 =B_hks2), .f = function(B_ks1, B_ks2, B_hks1, B_hks2) list(B_ks1 = B_ks1,B_ks2 = B_ks2, B_hks1 = B_hks1, B_hks2 = B_hks2))) %>%
  # nest(environment = -c(trait_set, trait_matrix, param_set, focal_hyperpar, height)) %>%
  mutate(B_rs1 = 4012, B_lf2 = 0.004, B_lf3 = 8e-04, B_lf5 = 200000) %>% 
  mutate(leaf = pmap(.l = list(parameters, environment, height, focal_hyperpar, B_rs1, B_lf2, B_lf3, B_lf5), .f = make_leaf)) -> leaf
```


```{r}
leaf %>%
  unnest(leaf) %>%
  unnest(environment) %>%
  mutate(psi_stem = psi_crit) %>%
  mutate(res = map2(.x = leaf, .y = 4, ~find_states(.x, .y))) %>%
  unnest(res) -> output

output %>%
  filter(psi_soil == 0.01) %>%
  ggplot() +
  geom_point(aes(x = atm_vpd, y = ci_), col = "red") +
  labs(y = expression(paste("Intracellular C", O[2]," (Pa)")), x = "VPD (kPa)") + 
  theme_classic() +
  theme(text = element_text(size = 16))-> a

output %>%
  filter(atm_vpd == 0.01) %>%
  ggplot() +
  geom_point(aes(x = psi_soil, y = ci_), col = "red") +
  labs(y = expression(paste("Intracellular C", O[2]," (Pa)")), x = expression(psi[soil]~(-MPa))) + 
  theme_classic()+
  theme(text = element_text(size = 16))-> b

vcmax_jmax_LCT_opt <- cowplot::plot_grid(plotlist = list(a,b)) 

png("output/comparing_stomatal_conductance_models/vcmax_jmax_LCT_opt.png", height = 12.8, width = 32, units = "cm", res = 1000)
vcmax_jmax_LCT_opt
dev.off()
```




















#one point


```{r}
source("R/individual_growth_rate_func.R")

target_traits <- tibble(target_traits = c("jmax","vcmax","theta"), bounds = (tibble(lower = c(100,100, 0.000157), upper = c(100,100, 0.000157)))) 

bounds <- matrix(data = c(target_traits %>% unnest(bounds) %>% pull(lower), target_traits %>% unnest(bounds) %>% pull(upper)), nrow=length(target_traits$target_traits), dimnames = list(target_traits$target_traits, c("lower", "upper")))

  expand_grid(environment = expand_grid(PPFD = 1000, psi_soil = seq(0.01, 0.9, length.out = 1), atm_vpd = seq(0.01, 4, length.out = 1), ca = 40)) %>%
    unnest(environment) %>%
  mutate(param_set = 1:n()) %>%
  group_by(param_set) %>%
  nest(environment = -param_set) %>%
  mutate(bounds = list(bounds)) %>% ungroup() %>%
  mutate(cost = pmap(.l = list(environment = environment, focal_bounds = bounds, optimise_theta = TRUE), .f = find_lowest_cost)) %>%
  mutate(attr = map(cost, ~attr(.x, "outcome"))) %>%
  unnest(attr)-> output

  output %>%
  mutate(names = names(attr)) %>%
  pivot_wider(names_from = "names", values_from = "attr") %>%View()
  expand_grid(theta_expanded = seq(-17, theta+3, length.out = 100)) %>%
  mutate(parameters = pmap(.l = list(jmax = exp(jmax), vcmax = exp(vcmax), theta = exp(theta_expanded)), .f = make_parameters)) %>% select(-c(theta, vcmax, jmax))%>%    
  select(-bounds, -cost) %>% 
  mutate(trait_set = 1:n()) %>%
  # group_by(param_set) %>%
  # nest(trait_matrix = c(-trait_set, -bounds, -cost, -environment, -param_set,-jmax, -vcmax)) %>%
  # unnest(environment) %>%
  mutate(param_set = 1:n()) %>%
  group_by(param_set) %>%
  expand_grid(height = c(1)) %>%
  expand_grid(B_ks1 = c(0.2), B_ks2 = c(2),B_hks1 = c(2), B_hks2 = c(2)) %>%
  mutate(focal_hyperpar = pmap(list(B_ks1 = B_ks1,B_ks2 = B_ks2,B_hks1 = B_hks1, B_hks2 =B_hks2), .f = function(B_ks1, B_ks2, B_hks1, B_hks2) list(B_ks1 = B_ks1,B_ks2 = B_ks2, B_hks1 = B_hks1, B_hks2 = B_hks2))) %>%
  # nest(environment = -c(trait_set, trait_matrix, param_set, focal_hyperpar, height)) %>%
  mutate(B_rs1_ = 4012, B_lf2_ = 0.004, B_lf3_ = 8e-04, B_lf5_ = 200000) %>% 
  mutate(leaf = pmap(.l = list(parameters, environment, height, focal_hyperpar, B_rs1_, B_lf2_, B_lf3_, B_lf5_), .f = make_leaf)) -> leaf

  
leaf %>%
  unnest(leaf) %>%
  unnest(environment) %>%
  mutate(psi_stem = psi_crit) %>%
  mutate(states = map2(.x = leaf, .y = psi_crit, .f = ~find_states(.x, .y))) %>%
  unnest(states) %>% 
  mutate(ci_seq = ci_) %>%
  mutate(electron_transport_ = map_dbl(.x = leaf, .f = ~.x$electron_transport_)) %>% 
  mutate(assim_rubisco_limited = map2_dbl(.x = leaf, .y = ci_seq, .f = ~.x$assim_rubisco_limited(.y))) %>% 
  mutate(assim_electron = map2_dbl(.x = leaf, .y = ci_seq, .f = ~.x$assim_electron_limited(.y))) %>%
    unnest(parameters) %>%
  mutate(assim_colimited_ = map2_dbl(.x = leaf, .y = ci_seq, .f = ~.x$assim_colimited(.y))) %>% 
  # mutate(num_diff_electron_transport_ = c(NA, diff(electron_transport_)/diff(exp(jmax_expanded)))) %>%
  # mutate(num_diff_assim_electron_jmax = c(NA, diff(assim_electron)/diff(exp(jmax_expanded)))) %>%
  # mutate(num_diff_assim_colimited_jmax = c(NA, diff(assim_colimited_)/diff(exp(jmax_expanded)))) %>% 
  
  mutate(Nj_ = (B_lf3_*(jmax))/1000) %>%
  mutate(Rj_ = B_lf5_*Nj_*1e6/365/24/60/60) %>%
  mutate(Nv_ = (B_lf2_*(vcmax))/1000) %>%
  mutate(Rv_ = B_lf5_*Nv_*1e6/365/24/60/60) %>%
  select(-vcmax, -jmax) %>%
  mutate(Rs_ = B_rs1_*theta*1e6/365/24/60/60) %>%
# mutate(num_diff_assim_electron_jmax = c(NA, diff(assim_electron)/diff(exp(jmax_expanded)))) %>%
  # mutate(num_diff_assim_colimited_jmax = c(NA, diff(assim_colimited_)/diff(exp(jmax_expanded)))) %>%
  # pivot_longer(cols = c(Rj_, num_diff_assim_electron_jmax, num_diff_assim_colimited_jmax))
  # mutate(Rj_over_jmax = c(NA, diff(Rj_)/diff(exp(jmax_expanded)))) %>%
  mutate(Rj_over_A = Rj_/assim_colimited_) %>%
  mutate(Rv_over_A = Rv_/assim_colimited_) %>%
  mutate(Rs_over_A = Rs_/assim_colimited_) %>%
  mutate(R_over_A = Rj_over_A + Rv_over_A + Rs_over_A) %>%
  # pivot_longer(cols = c(electron_transport_,assim_rubisco_limited, assim_electron, assim_colimited_)) %>%
  pivot_longer(cols = c(R_over_A, Rj_over_A,Rv_over_A, Rs_over_A, assim_colimited_)) %>%
  filter(name == "R_over_A") %>%
  filter(value == min(value)) %>%
  mutate(e)
  ggplot(aes(x = theta, y =value)) +
  geom_line(aes(group = name, colour = name)) +
  lims(x = c(0,5e-07)) 
  # labs(y = "d assim/ d jmax") +
  ylim(c(0,5))
# 
leaf %>%
  unnest(leaf) %>%
  unnest(environment) %>%
  mutate(psi_stem = psi_crit) %>%
  mutate(states = map2(.x = leaf, .y = 4, .f = ~find_states(.x, .y))) %>%
  unnest(states) %>%
  expand_grid(ci_seq = 39.9) %>%
  mutate(assim_rubisco_limited = map2_dbl(.x = leaf, .y = ci_seq, .f = ~.x$assim_rubisco_limited(.y))) %>% 
  mutate(assim_electron = map2_dbl(.x = leaf, .y = ci_seq, .f = ~.x$assim_electron_limited(.y))) %>% 
  mutate(assim_colimited_ = map2_dbl(.x = leaf, .y = ci_seq, .f = ~.x$assim_colimited(.y))) %>%  
  mutate(num_diff_assim_electron_jmax = c(NA, diff(assim_electron)/diff(exp(jmax_expanded)))) %>%
  mutate(num_diff_assim_colimited_jmax = c(NA, diff(assim_colimited_)/diff(exp(jmax_expanded)))) %>%
  mutate(Nj_ = (B_lf3_*jmax_expanded)/1000) %>%
  mutate(Rj_ = B_lf5_*Nj_*1e6/365/24/60/60) %>%
  # mutate(num_diff_assim_electron_jmax = c(NA, diff(assim_electron)/diff(exp(jmax_expanded)))) %>%
  # mutate(num_diff_assim_colimited_jmax = c(NA, diff(assim_colimited_)/diff(exp(jmax_expanded)))) %>%
  # pivot_longer(cols = c(Rj_, num_diff_assim_electron_jmax, num_diff_assim_colimited_jmax))
  mutate(Rj_over_A = c(NA, diff(Rj_)/diff(exp(jmax_expanded)))) %>%
  pivot_longer(cols = c(num_diff_assim_electron_jmax, num_diff_assim_colimited_jmax,Rj_over_A)) %>%
  ggplot(aes(x = exp(jmax_expanded), y =value)) +
  geom_line(aes(group = name, colour = name)) + 
  # lims(x = c(0,1000)) +
  # labs(y = "d assim/ d jmax") +
  xlim(c(0,10000))
```

```{r}
  output %>%
  mutate(names = names(attr)) %>%
  pivot_wider(names_from = "names", values_from = "attr") %>%
  expand_grid(vcmax_expanded = seq(1, vcmax+1, length.out = 10),
              jmax_expanded = seq(1, jmax+1, length.out = 10)) %>%
  mutate(parameters = map2(vcmax_expanded, jmax_expanded, ~make_parameters(vcmax = exp(.x), jmax = exp(.y)))) %>%
  select(-bounds, -cost) %>% 
  mutate(trait_set = 1:n()) %>%
  # group_by(param_set) %>%
  # nest(trait_matrix = c(-trait_set, -bounds, -cost, -environment, -param_set,-jmax, -vcmax)) %>%
  # unnest(environment) %>%
  mutate(param_set = 1:n()) %>%
  group_by(param_set) %>%
  expand_grid(height = c(1)) %>%
  expand_grid(B_ks1 = c(0.2), B_ks2 = c(2),B_hks1 = c(2), B_hks2 = c(2)) %>%
  mutate(focal_hyperpar = pmap(list(B_ks1 = B_ks1,B_ks2 = B_ks2,B_hks1 = B_hks1, B_hks2 =B_hks2), .f = function(B_ks1, B_ks2, B_hks1, B_hks2) list(B_ks1 = B_ks1,B_ks2 = B_ks2, B_hks1 = B_hks1, B_hks2 = B_hks2))) %>%
  # nest(environment = -c(trait_set, trait_matrix, param_set, focal_hyperpar, height)) %>%
  mutate(B_rs1_ = 4012, B_lf2_ = 0.004, B_lf3_ = 8e-04, B_lf5_ = 200000) %>% 
  mutate(leaf = pmap(.l = list(parameters, environment, height, focal_hyperpar, B_rs1_, B_lf2_, B_lf3_, B_lf5_), .f = make_leaf)) -> leaf


  output %>%
  mutate(names = names(attr)) %>%
  pivot_wider(names_from = "names", values_from = "attr") %>%
  expand_grid(vcmax_expanded = vcmax,
              jmax_expanded = jmax) %>%
  mutate(parameters = map2(vcmax_expanded, jmax_expanded, ~make_parameters(vcmax = exp(.x), jmax = exp(.y)))) %>%
  select(-bounds, -cost) %>% 
  mutate(trait_set = 1:n()) %>%
  # group_by(param_set) %>%
  # nest(trait_matrix = c(-trait_set, -bounds, -cost, -environment, -param_set,-jmax, -vcmax)) %>%
  # unnest(environment) %>%
  mutate(param_set = 1:n()) %>%
  group_by(param_set) %>%
  expand_grid(height = c(1)) %>%
  expand_grid(B_ks1 = c(0.2), B_ks2 = c(2),B_hks1 = c(2), B_hks2 = c(2)) %>%
  mutate(focal_hyperpar = pmap(list(B_ks1 = B_ks1,B_ks2 = B_ks2,B_hks1 = B_hks1, B_hks2 =B_hks2), .f = function(B_ks1, B_ks2, B_hks1, B_hks2) list(B_ks1 = B_ks1,B_ks2 = B_ks2, B_hks1 = B_hks1, B_hks2 = B_hks2))) %>%
  # nest(environment = -c(trait_set, trait_matrix, param_set, focal_hyperpar, height)) %>%
  mutate(B_rs1_ = 4012, B_lf2_ = 0.004, B_lf3_ = 8e-04, B_lf5_ = 200000) %>% 
  mutate(leaf = pmap(.l = list(parameters, environment, height, focal_hyperpar, B_rs1_, B_lf2_, B_lf3_, B_lf5_), .f = make_leaf)) -> leaf


  
leaf %>%
  unnest(leaf) %>%
  unnest(environment) %>%
  mutate(psi_stem = psi_crit) %>%
  mutate(states = map2(.x = leaf, .y = 4, .f = ~find_states(.x, .y))) %>%
  unnest(states) %>% 
  expand_grid(ci_seq = ci_) %>%
  mutate(electron_transport_ = map_dbl(.x = leaf, .f = ~.x$electron_transport_)) %>% 
  mutate(assim_rubisco_limited = map2_dbl(.x = leaf, .y = ci_seq, .f = ~.x$assim_rubisco_limited(.y))) %>% 
  mutate(assim_electron = map2_dbl(.x = leaf, .y = ci_seq, .f = ~.x$assim_electron_limited(.y))) %>% 
  mutate(assim_colimited_ = map2_dbl(.x = leaf, .y = ci_seq, .f = ~.x$assim_colimited(.y))) %>%  
  mutate(num_diff_electron_transport_ = c(NA, diff(electron_transport_)/diff(exp(jmax_expanded)))) %>%
  mutate(num_diff_assim_electron_jmax = c(NA, diff(assim_electron)/diff(exp(jmax_expanded)))) %>%
  mutate(num_diff_assim_colimited_jmax = c(NA, diff(assim_colimited_)/diff(exp(jmax_expanded)))) %>%
  mutate(Nj_ = (B_lf3_*exp(jmax_expanded))/1000) %>%
  mutate(Rj_ = B_lf5_*Nj_*1e6/365/24/60/60) %>%
  mutate(Nv_ = (B_lf2_*exp(vcmax_expanded))/1000) %>%
  mutate(Rv_ = B_lf5_*Nv_*1e6/365/24/60/60) %>%
  select(-vcmax, -jmax) %>%
  unnest(parameters) %>%
  mutate(Rs_ = B_rs1_*theta*1e6/365/24/60/60) %>%
# mutate(num_diff_assim_electron_jmax = c(NA, diff(assim_electron)/diff(exp(jmax_expanded)))) %>%
  # mutate(num_diff_assim_colimited_jmax = c(NA, diff(assim_colimited_)/diff(exp(jmax_expanded)))) %>%
  # pivot_longer(cols = c(Rj_, num_diff_assim_electron_jmax, num_diff_assim_colimited_jmax))
  # mutate(Rj_over_jmax = c(NA, diff(Rj_)/diff(exp(jmax_expanded)))) %>%
  mutate(Rj_over_A = Rj_/assim_colimited_) %>%
  mutate(Rv_over_A = Rv_/assim_colimited_) %>%
  mutate(Rs_over_A = Rs_/assim_colimited_) %>%
  mutate(R_over_A = Rj_over_A + Rv_over_A + Rs_over_A) -> output2
  # pivot_longer(cols = c(electron_transport_,assim_rubisco_limited, assim_electron, assim_colimited_)) %>%
  
output2 %>%
pivot_longer(cols = c(R_over_A, Rj_over_A,Rv_over_A, Rs_over_A, assim_colimited_)) %>%
  filter(name == "R_over_A") %>% 
  filter(value == min(value)) %>% View()
  ggplot(aes(x = exp(vcmax_expanded), y =value)) +
  geom_line(aes(group = jmax_expanded, colour = jmax_expanded))
```







```{r}
source("R/individual_growth_rate_func.R")

target_traits <- tibble(target_traits = c("jmax","vcmax"), bounds = (tibble(lower = c(100,100), upper = c(100,100)))) 

bounds <- matrix(data = c(target_traits %>% unnest(bounds) %>% pull(lower), target_traits %>% unnest(bounds) %>% pull(upper)), nrow=length(target_traits$target_traits), dimnames = list(target_traits$target_traits, c("lower", "upper")))

  expand_grid(environment = expand_grid(PPFD = 1000, psi_soil = seq(0.01, 3, length.out = 1), atm_vpd = seq(0.01, 4, length.out = 1), ca = 40)) %>%
    unnest(environment) %>%
  mutate(param_set = 1:n()) %>%
  group_by(param_set) %>%
  nest(environment = -param_set) %>%
  mutate(bounds = list(bounds)) %>% ungroup() %>%
  mutate(cost = future_pmap(.l = list(environment = environment, focal_bounds = bounds, optimise_theta = FALSE), .f = find_lowest_cost)) %>%
  mutate(attr = map(cost, ~attr(.x, "outcome"))) %>%
  unnest(attr)-> output

  output %>%
  mutate(names = names(attr)) %>%
  pivot_wider(names_from = "names", values_from = "attr") %>%
  expand_grid(jmax_expanded = seq(1, jmax+1, length.out = 100)) %>%
  mutate(parameters = map2(vcmax, jmax_expanded, ~make_parameters(vcmax = exp(.x), jmax = exp(.y)))) %>%
  select(-bounds, -cost) %>% 
  mutate(trait_set = 1:n()) %>%
  # group_by(param_set) %>%
  # nest(trait_matrix = c(-trait_set, -bounds, -cost, -environment, -param_set,-jmax, -vcmax)) %>%
  # unnest(environment) %>%
  mutate(param_set = 1:n()) %>%
  group_by(param_set) %>%
  expand_grid(height = c(1)) %>%
  expand_grid(B_ks1 = c(0.2), B_ks2 = c(2),B_hks1 = c(2), B_hks2 = c(2)) %>%
  mutate(focal_hyperpar = pmap(list(B_ks1 = B_ks1,B_ks2 = B_ks2,B_hks1 = B_hks1, B_hks2 =B_hks2), .f = function(B_ks1, B_ks2, B_hks1, B_hks2) list(B_ks1 = B_ks1,B_ks2 = B_ks2, B_hks1 = B_hks1, B_hks2 = B_hks2))) %>%
  # nest(environment = -c(trait_set, trait_matrix, param_set, focal_hyperpar, height)) %>%
  mutate(B_rs1_ = 4012, B_lf2_ = 0.004, B_lf3_ = 8e-04, B_lf5_ = 200000) %>% 
  mutate(leaf = pmap(.l = list(parameters, environment, height, focal_hyperpar, B_rs1_, B_lf2_, B_lf3_, B_lf5_), .f = make_leaf)) -> leaf

  
leaf %>%
  unnest(leaf) %>%
  unnest(environment) %>%
  mutate(psi_stem = psi_crit) %>%
  mutate(states = map2(.x = leaf, .y = 4, .f = ~find_states(.x, .y))) %>%
  unnest(states) %>%
  expand_grid(ci_seq = 39.9) %>%
  mutate(electron_transport_ = map_dbl(.x = leaf, .f = ~.x$electron_transport_)) %>% 
  mutate(assim_rubisco_limited = map2_dbl(.x = leaf, .y = ci_seq, .f = ~.x$assim_rubisco_limited(.y))) %>% 
  mutate(assim_electron = map2_dbl(.x = leaf, .y = ci_seq, .f = ~.x$assim_electron_limited(.y))) %>% 
  mutate(assim_colimited_ = map2_dbl(.x = leaf, .y = ci_seq, .f = ~.x$assim_colimited(.y))) %>%  
  mutate(num_diff_electron_transport_ = c(NA, diff(electron_transport_)/diff(exp(jmax_expanded)))) %>%
  mutate(num_diff_assim_electron_jmax = c(NA, diff(assim_electron)/diff(exp(jmax_expanded)))) %>%
  mutate(num_diff_assim_colimited_jmax = c(NA, diff(assim_colimited_)/diff(exp(jmax_expanded)))) %>%
  mutate(Nj_ = (B_lf3_*exp(jmax_expanded))/1000) %>%
  mutate(Rj_ = B_lf5_*Nj_*1e6/365/24/60/60) %>%
  # mutate(num_diff_assim_electron_jmax = c(NA, diff(assim_electron)/diff(exp(jmax_expanded)))) %>%
  # mutate(num_diff_assim_colimited_jmax = c(NA, diff(assim_colimited_)/diff(exp(jmax_expanded)))) %>%
  # pivot_longer(cols = c(Rj_, num_diff_assim_electron_jmax, num_diff_assim_colimited_jmax))
  mutate(Rj_over_jmax = c(NA, diff(Rj_)/diff(exp(jmax_expanded)))) %>%
  # pivot_longer(cols = c(electron_transport_,assim_rubisco_limited, assim_electron, assim_colimited_)) %>%
  pivot_longer(cols = c(num_diff_electron_transport_,num_diff_assim_electron_jmax, num_diff_assim_colimited_jmax,Rj_over_jmax)) %>%
  ggplot(aes(x = exp(jmax_expanded), y =value)) +
  geom_line(aes(group = name, colour = name)) + 
  # lims(x = c(0,1000)) +
  # labs(y = "d assim/ d jmax") +
  ylim(c(0,0.01))

leaf %>%
  unnest(leaf) %>%
  unnest(environment) %>%
  mutate(psi_stem = psi_crit) %>%
  mutate(states = map2(.x = leaf, .y = 4, .f = ~find_states(.x, .y))) %>%
  unnest(states) %>%
  expand_grid(ci_seq = 39.9) %>%
  mutate(assim_rubisco_limited = map2_dbl(.x = leaf, .y = ci_seq, .f = ~.x$assim_rubisco_limited(.y))) %>% 
  mutate(assim_electron = map2_dbl(.x = leaf, .y = ci_seq, .f = ~.x$assim_electron_limited(.y))) %>% 
  mutate(assim_colimited_ = map2_dbl(.x = leaf, .y = ci_seq, .f = ~.x$assim_colimited(.y))) %>%  
  mutate(num_diff_assim_electron_jmax = c(NA, diff(assim_electron)/diff(exp(jmax_expanded)))) %>%
  mutate(num_diff_assim_colimited_jmax = c(NA, diff(assim_colimited_)/diff(exp(jmax_expanded)))) %>%
  mutate(Nj_ = (B_lf3_*jmax_expanded)/1000) %>%
  mutate(Rj_ = B_lf5_*Nj_*1e6/365/24/60/60) %>%
  # mutate(num_diff_assim_electron_jmax = c(NA, diff(assim_electron)/diff(exp(jmax_expanded)))) %>%
  # mutate(num_diff_assim_colimited_jmax = c(NA, diff(assim_colimited_)/diff(exp(jmax_expanded)))) %>%
  # pivot_longer(cols = c(Rj_, num_diff_assim_electron_jmax, num_diff_assim_colimited_jmax))
  mutate(Rj_over_A = c(NA, diff(Rj_)/diff(exp(jmax_expanded)))) %>%
  pivot_longer(cols = c(num_diff_assim_electron_jmax, num_diff_assim_colimited_jmax,Rj_over_A)) %>%
  ggplot(aes(x = exp(jmax_expanded), y =value)) +
  geom_line(aes(group = name, colour = name)) + 
  # lims(x = c(0,1000)) +
  # labs(y = "d assim/ d jmax") +
  xlim(c(0,10000))
```


```{r}
output %>%
  mutate(names = names(attr)) %>%
  pivot_wider(names_from = "names", values_from = "attr") %>%
  expand_grid(jmax_expanded = c(jmax - 6, jmax, jmax + 1)) %>%
  mutate(parameters = map2(vcmax, jmax_expanded, ~make_parameters(vcmax = exp(.x), jmax = exp(.y)))) %>%
  select(-bounds, -cost) %>% 
  mutate(trait_set = 1:n()) %>%
  # group_by(param_set) %>%
  # nest(trait_matrix = c(-trait_set, -bounds, -cost, -environment, -param_set,-jmax, -vcmax)) %>%
  # unnest(environment) %>%
  mutate(param_set = 1:n()) %>%
  group_by(param_set) %>%
  expand_grid(height = c(1)) %>%
  expand_grid(B_ks1 = c(0.2), B_ks2 = c(2),B_hks1 = c(2), B_hks2 = c(2)) %>%
  mutate(focal_hyperpar = pmap(list(B_ks1 = B_ks1,B_ks2 = B_ks2,B_hks1 = B_hks1, B_hks2 =B_hks2), .f = function(B_ks1, B_ks2, B_hks1, B_hks2) list(B_ks1 = B_ks1,B_ks2 = B_ks2, B_hks1 = B_hks1, B_hks2 = B_hks2))) %>%
  # nest(environment = -c(trait_set, trait_matrix, param_set, focal_hyperpar, height)) %>%
  mutate(B_rs1_ = 4012, B_lf2_ = 0.004, B_lf3_ = 8e-04, B_lf5_ = 200000) %>% 
  mutate(leaf = pmap(.l = list(parameters, environment, height, focal_hyperpar, B_rs1_, B_lf2_, B_lf3_, B_lf5_), .f = make_leaf)) -> leaf
```



```{r}
leaf %>%
  unnest(leaf) %>%
  unnest(environment) %>%
  mutate(psi_stem = psi_crit) %>%
  mutate(states = map2(.x = leaf, .y = 0.02, .f = ~find_states(.x, .y))) %>%
  unnest(states) %>% 
  # mutate(assim_electron = map2_dbl(.x = leaf, .y = ci_seq, .f = ~.x$assim_electron_limited(.y))) %>% 
  expand_grid(ci_seq_ = seq(5,45, by = 0.01)) %>%
  mutate(assim_colimited_ = map2_dbl(.x = leaf, .y = ci_seq_, .f = ~.x$assim_colimited(.y))) %>%
  mutate(jmax_expanded = exp(jmax_expanded)) %>% 
  mutate(stom_cond_line = stom_cond_CO2_ * 1e6  * (ca - ci_seq_)/101325) %>% 

  pivot_longer(cols = c(stom_cond_line, assim_colimited_)) %>%
  ggplot(aes(x = ci_seq_, y = value)) +
  geom_line(aes(colour = jmax_expanded, group = interaction(jmax_expanded, name)))+
  ylim(c(0,100))


  mutate(Nj_ = (B_lf3_*jmax_expanded)/1000) %>%
  mutate(Rj_ = B_lf5_*Nj_*1e6/365/24/60/60) %>%
  # mutate(num_diff_assim_electron_jmax = c(NA, diff(assim_electron)/diff(exp(jmax_expanded)))) %>%
  # mutate(num_diff_assim_colimited_jmax = c(NA, diff(assim_colimited_)/diff(exp(jmax_expanded)))) %>%
  # pivot_longer(cols = c(Rj_, num_diff_assim_electron_jmax, num_diff_assim_colimited_jmax))
  mutate(Rj_over_A = c(NA, diff(Rj_)/diff(opt_assim_colimited_))) %>% 
  ggplot(aes(x= jmax_expanded, y = Rj_over_A )) +
  geom_line() +
  geom_vline(aes(xintercept = jmax)) +
  ylim(c(0,50))


leaf %>%
  unnest(leaf) %>%
  unnest(environment) %>%
  mutate(psi_stem = psi_crit) %>%
  mutate(states = map2(.x = leaf, .y = 4, .f = ~find_states(.x, .y))) %>%
  unnest(states) %>%
  expand_grid(ci_seq = 38) %>%
  mutate(assim_electron = map2_dbl(.x = leaf, .y = ci_seq, .f = ~.x$assim_electron_limited(.y))) %>% 
  mutate(assim_colimited_ = map2_dbl(.x = leaf, .y = ci_seq, .f = ~.x$assim_colimited(.y))) %>%  
  mutate(num_diff_assim_electron_jmax = c(NA, diff(assim_electron)/diff(exp(jmax_expanded)))) %>%
  mutate(num_diff_assim_colimited_jmax = c(NA, diff(assim_colimited_)/diff(exp(jmax_expanded)))) %>%
  pivot_longer(cols = c(num_diff_assim_electron_jmax, num_diff_assim_colimited_jmax)) %>%
  ggplot(aes(x = exp(jmax_expanded), y =value)) +
  geom_line(aes(group = name, colour = name)) + 
  # lims(x = c(0,1000)) +
  labs(y = "d assim/ d jmax") +
  xlim(c(0,1000))
  
leaf %>%
  unnest(leaf) %>%
  unnest(environment) %>%
  mutate(psi_stem = psi_crit) %>%
  mutate(states = map2(.x = leaf, .y = 4, .f = ~find_states(.x, .y))) %>%
  unnest(states) %>% unnest(parameters) %>% 
  expand_grid(ci_seq = 38) %>%
  mutate(assim_electron = map2_dbl(.x = leaf, .y = ci_seq, .f = ~.x$assim_electron_limited(.y))) %>% 
  mutate(assim_colimited_ = map2_dbl(.x = leaf, .y = ci_seq, .f = ~.x$assim_colimited(.y))) %>% 
  mutate(Nj_ = (B_lf3_*jmax_expanded)/1000) %>%
  mutate(Rj_ = B_lf5_*Nj_*1e6/365/24/60/60) %>%
  mutate(num_diff_assim_electron_jmax = c(NA, diff(assim_electron)/diff(exp(jmax_expanded)))) %>%
  mutate(num_diff_assim_colimited_jmax = c(NA, diff(assim_colimited_)/diff(exp(jmax_expanded)))) %>%
  pivot_longer(cols = c(Rj_, num_diff_assim_electron_jmax, num_diff_assim_colimited_jmax)) %>% 
  ggplot(aes(x = exp(jmax_expanded), y =value)) +
  geom_line(aes(group = name, colour = name)) + 
  # lims(x = c(0,100000)) +
  labs(y = "d assim/ d jmax")




leaf %>%
  unnest(leaf) %>%
  unnest(environment) %>%
  mutate(psi_stem = psi_crit) %>%
  mutate(cost = map2_dbl(.x = leaf, .y = 4, .f = ~.x$calculate_cost_LCT(.y))) %>%
  ggplot(aes(x = exp(jmax_expanded), y = cost)) +
  geom_line()
  
  
  
  # select(-cost) %>%
  mutate(res = map(.x = leaf, .y , ~.x$electron_transport_)) %>%
  unnest(parameters) %>% 
  mutate(elec_trans_deriv = 1 + 0.5 * ((2 * (a * PPFD + jmax) - 4 * curv_fact_elec_trans * 
    a * PPFD) * ((a * PPFD + jmax)^2 - 4 * curv_fact_elec_trans * 
    a * PPFD * jmax)^-0.5)/(2 * curv_fact_elec_trans))  %>%
  unnest(res) -> output



f = expression(a * PPFD + jmax - sqrt((a * PPFD + jmax)^2 - 4 * curv_fact_elec_trans * a * PPFD * jmax) / (2 * curv_fact_elec_trans))
D(f, "jmax")

leaf %>%
  unnest(leaf) %>%
  unnest(environment) %>%
  mutate(psi_stem = psi_crit) %>%
  # select(-cost) %>%
  mutate(res = map2(.x = leaf, .y = psi_stem, ~find_states(.x, .y))) %>%
  unnest(res) -> output

output %>%
  mutate(elec_trans_derive_num = c(NA,diff(res)/diff(jmax))) %>%
  ggplot() +
  geom_line(aes(x = jmax, y = elec_trans_derive_num), col = "red") +
  labs(y = expression(paste("J")), x = "jmax") + 
  theme_classic()
  


output %>%
  ggplot() +
  geom_line(aes(x = jmax, y = res), col = "red") +
  labs(y = expression(paste("J")), x = "jmax") + 
  theme_classic() +
  xlim(c(0,1000))


output %>%
  ggplot() +
  geom_point(aes(x = jmax, y = elec_trans_deriv), col = "red") +
  labs(y = expression(paste("Intracellular C", O[2]," (Pa)")), x = "VPD (kPa)") + 
  theme_classic()


output %>%
  filter(atm_vpd == 0.01) %>%
  ggplot() +
  geom_point(aes(x = psi_soil, y = ci_), col = "red") +
  labs(y = expression(paste("Intracellular C", O[2]," (Pa)")), x = expression(psi[soil]~(-MPa))) + 
  theme_classic() -> b

cowplot::plot_grid(plotlist = list(a,b)) -> lct

png("output/comparing_stomatal_conductance_models/lct.png", height = 12.8, width = 32, units = "cm", res = 1000)
lct
dev.off()
```


```{r}
source("R/individual_growth_rate_func.R")

target_traits <- tibble(target_traits = c("jmax","vcmax","theta"), bounds = (tibble(lower = c(100,100, 0.000157), upper = c(100,100, 0.000157)))) 

bounds <- matrix(data = c(target_traits %>% unnest(bounds) %>% pull(lower), target_traits %>% unnest(bounds) %>% pull(upper)), nrow=length(target_traits$target_traits), dimnames = list(target_traits$target_traits, c("lower", "upper")))

  expand_grid(environment = expand_grid(PPFD = 1000, psi_soil = seq(0.01, 3, length.out = 10), atm_vpd = seq(0.01, 4, length.out = 10), ca = 40)) %>%
    unnest(environment) %>%
  mutate(param_set = 1:n()) %>%
  group_by(param_set) %>%
  nest(environment = -param_set) %>%
  mutate(bounds = list(bounds)) %>% ungroup() %>%
  mutate(cost = future_pmap(.l = list(environment = environment, focal_bounds = bounds, optimise_theta = TRUE), .f = find_lowest_cost)) %>%
  mutate(attr = map(cost, ~attr(.x, "outcome"))) %>%
  unnest(attr)-> output
  
output %>%
  mutate(names = names(attr)) %>%
  pivot_wider(names_from = "names", values_from = "attr") %>%
  mutate(parameters = pmap(list(vcmax = vcmax, jmax = jmax, theta = theta),.f = function(vcmax, jmax, theta) make_parameters(vcmax = exp(vcmax), jmax = exp(jmax), theta = exp(theta)))) %>%
  select(-bounds, -cost, -jmax, -vcmax) %>% 
  mutate(trait_set = 1:n()) %>%
  # group_by(param_set) %>%
  # nest(trait_matrix = c(-trait_set, -bounds, -cost, -environment, -param_set,-jmax, -vcmax)) %>%
  # unnest(environment) %>%
  mutate(param_set = 1:n()) %>%
  group_by(param_set) %>%
  expand_grid(height = c(1)) %>%
  expand_grid(B_ks1 = c(0.2), B_ks2 = c(2),B_hks1 = c(2), B_hks2 = c(2)) %>%
  mutate(focal_hyperpar = pmap(list(B_ks1 = B_ks1,B_ks2 = B_ks2,B_hks1 = B_hks1, B_hks2 =B_hks2), .f = function(B_ks1, B_ks2, B_hks1, B_hks2) list(B_ks1 = B_ks1,B_ks2 = B_ks2, B_hks1 = B_hks1, B_hks2 = B_hks2))) %>%
  # nest(environment = -c(trait_set, trait_matrix, param_set, focal_hyperpar, height)) %>%
  mutate(B_rs1_ = 4012, B_lf2_ = 0.004, B_lf3_ = 8e-04, B_lf5_ = 40000) %>% 
  mutate(leaf = pmap(.l = list(parameters, environment, height, focal_hyperpar, B_rs1_, B_lf2_, B_lf3_, B_lf5_), .f = make_leaf)) -> leaf
```


```{r}
leaf %>%
  unnest(leaf) %>%
  unnest(environment) %>%
  mutate(psi_stem = psi_crit) %>%
  # select(-cost) %>%
  mutate(res = map2(.x = leaf, .y = psi_stem, ~find_states(.x, .y))) %>%
  unnest(res) -> output

output %>%
  filter(psi_soil == 0.01) %>%
  ggplot() +
  geom_point(aes(x = atm_vpd, y = ci_), col = "red") +
  labs(y = expression(paste("Intracellular C", O[2]," (Pa)")), x = "VPD (kPa)") + 
  theme_classic() -> a

output %>%
  filter(atm_vpd == 0.01) %>%
  ggplot() +
  geom_point(aes(x = psi_soil, y = ci_), col = "red") +
  labs(y = expression(paste("Intracellular C", O[2]," (Pa)")), x = expression(psi[soil]~(-MPa))) + 
  theme_classic() -> b



cowplot::plot_grid(plotlist = list(a,b)) -> lct_theta

png("output/comparing_stomatal_conductance_models/lct_theta.png", height = 12.8, width = 32, units = "cm", res = 1000)
lct_theta
dev.off()

cowplot::plot_grid(plotlist = list(a,b))
```


```{r}
source("R/individual_growth_rate_func.R")

target_traits <- tibble(target_traits = c("jmax","vcmax"), bounds = (tibble(lower = c(100,100), upper = c(100,100)))) 

bounds <- matrix(data = c(target_traits %>% unnest(bounds) %>% pull(lower), target_traits %>% unnest(bounds) %>% pull(upper)), nrow=length(target_traits$target_traits), dimnames = list(target_traits$target_traits, c("lower", "upper")))

  expand_grid(environment = expand_grid(PPFD = 1000, psi_soil = seq(0.01, 3, length.out = 5), atm_vpd = seq(0.01, 4, length.out = 5), ca = 40)) %>%
    unnest(environment) %>%
  mutate(param_set = 1:n()) %>%
  group_by(param_set) %>%
     expand_grid(height = c(1)) %>%
  expand_grid(B_ks1 = c(0.2), B_ks2 = c(2),B_hks1 = c(2), B_hks2 = c(2)) %>%
  mutate(focal_hyperpar = pmap(list(B_ks1 = B_ks1,B_ks2 = B_ks2,B_hks1 = B_hks1, B_hks2 =B_hks2), .f = function(B_ks1, B_ks2, B_hks1, B_hks2) list(B_ks1 = B_ks1,B_ks2 = B_ks2, B_hks1 = B_hks1, B_hks2 = B_hks2))) %>%
  nest(environment = c(PPFD, psi_soil, atm_vpd, ca)) %>%
  mutate(bounds = list(bounds)) %>% ungroup() %>%
    slice(1:50) %>%
  mutate(cost = future_pmap(.l = list(environment = environment, hyperpar = focal_hyperpar, focal_bounds = bounds, optimise_theta = FALSE), .f = find_highest_profit)) %>%
  mutate(attr = map(cost, ~attr(.x, "outcome"))) %>%
  unnest(attr)-> output
  
output %>%
  mutate(names = names(attr)) %>%
  pivot_wider(names_from = "names", values_from = "attr") %>%
  mutate(parameters = pmap(list(vcmax = vcmax, jmax = jmax),.f = function(vcmax, jmax) make_parameters(vcmax = exp(vcmax), jmax = exp(jmax)))) %>%
  select(-bounds, -cost, -jmax, -vcmax) %>% 
  mutate(trait_set = 1:n()) %>%
  # group_by(param_set) %>%
  # nest(trait_matrix = c(-trait_set, -bounds, -cost, -environment, -param_set,-jmax, -vcmax)) %>%
  # unnest(environment) %>%
  mutate(param_set = 1:n()) %>%
  group_by(param_set) %>%
  mutate(B_rs1_ = 4012, B_lf2_ = 0.004, B_lf3_ = 8e-04, B_lf5_ = 40000) %>% 
  mutate(leaf = pmap(.l = list(parameters, environment, height, focal_hyperpar, B_rs1_, B_lf2_, B_lf3_, B_lf5_), .f = make_leaf)) -> leaf
```


```{r}
leaf %>%
  unnest(leaf) %>%
  unnest(environment) %>%
  mutate(psi_stem = psi_crit) %>%
  mutate(res = map2(.x = leaf, .y = psi_stem, ~find_states(.x, .y))) %>%
  unnest(res) -> output

output %>%
  filter(psi_soil == 0.01) %>%
  ggplot() +
  geom_point(aes(x = atm_vpd, y = ci_), col = "red") +
  labs(y = expression(paste("Intracellular C", O[2]," (Pa)")), x = "VPD (kPa)") + 
  theme_classic() -> a

output %>%
  filter(atm_vpd == 0.01) %>%
  ggplot() +
  geom_point(aes(x = psi_soil, y = ci_), col = "red") +
  labs(y = expression(paste("Intracellular C", O[2]," (Pa)")), x = expression(psi[soil]~(-MPa))) + 
  theme_classic() -> b

cowplot::plot_grid(plotlist = list(a,b))
```


```{r}
source("R/individual_growth_rate_func.R")

target_traits <- tibble(target_traits = c("jmax","vcmax"), bounds = (tibble(lower = c(100,100), upper = c(100,100)))) 

bounds <- matrix(data = c(target_traits %>% unnest(bounds) %>% pull(lower), target_traits %>% unnest(bounds) %>% pull(upper)), nrow=length(target_traits$target_traits), dimnames = list(target_traits$target_traits, c("lower", "upper")))

  expand_grid(environment = expand_grid(PPFD = 1000, psi_soil = seq(0.01, 3, length.out = 5), atm_vpd = seq(0.01, 4, length.out = 5), ca = 40)) %>%
    unnest(environment) %>%
  mutate(param_set = 1:n()) %>%
  group_by(param_set) %>%
     expand_grid(height = c(1)) %>%
  expand_grid(B_ks1 = c(0.2), B_ks2 = c(2),B_hks1 = c(2), B_hks2 = c(2)) %>%
  mutate(focal_hyperpar = pmap(list(B_ks1 = B_ks1,B_ks2 = B_ks2,B_hks1 = B_hks1, B_hks2 =B_hks2), .f = function(B_ks1, B_ks2, B_hks1, B_hks2) list(B_ks1 = B_ks1,B_ks2 = B_ks2, B_hks1 = B_hks1, B_hks2 = B_hks2))) %>%
  nest(environment = c(PPFD, psi_soil, atm_vpd, ca)) %>%
  mutate(bounds = list(bounds)) %>% ungroup() %>%
  mutate(cost = future_pmap(.l = list(environment = environment, hyperpar = focal_hyperpar, focal_bounds = bounds, optimise_theta = FALSE), .f = find_highest_profit)) %>%
  mutate(attr = map(cost, ~attr(.x, "outcome"))) %>%
  unnest(attr)-> output
  
output %>%
  mutate(names = names(attr)) %>%
  pivot_wider(names_from = "names", values_from = "attr") %>%
  mutate(parameters = pmap(list(vcmax = vcmax, jmax = jmax),.f = function(vcmax, jmax) make_parameters(vcmax = exp(vcmax), jmax = exp(jmax)))) %>%
  select(-bounds, -cost, -jmax, -vcmax) %>% 
  mutate(trait_set = 1:n()) %>%
  # group_by(param_set) %>%
  # nest(trait_matrix = c(-trait_set, -bounds, -cost, -environment, -param_set,-jmax, -vcmax)) %>%
  # unnest(environment) %>%
  mutate(param_set = 1:n()) %>%
  group_by(param_set) %>%
  mutate(B_rs1_ = 4012, B_lf2_ = 0.004, B_lf3_ = 8e-04, B_lf5_ = 40000) %>% 
  mutate(leaf = pmap(.l = list(parameters, environment, height, focal_hyperpar, B_rs1_, B_lf2_, B_lf3_, B_lf5_), .f = make_leaf)) -> leaf
```


```{r}
leaf %>%
  unnest(leaf) %>%
  unnest(environment) %>%
  mutate(psi_stem = psi_crit) %>%
  mutate(res = map2(.x = leaf, .y = psi_stem, ~find_states(.x, .y))) %>%
  unnest(res) -> output

output %>%
  filter(psi_soil == 0.01) %>%
  ggplot() +
  geom_point(aes(x = atm_vpd, y = ci_), col = "red") +
  labs(y = expression(paste("Intracellular C", O[2]," (Pa)")), x = "VPD (kPa)") + 
  theme_classic() -> a

output %>%
  filter(atm_vpd == 0.01) %>%
  ggplot() +
  geom_point(aes(x = psi_soil, y = ci_), col = "red") +
  labs(y = expression(paste("Intracellular C", O[2]," (Pa)")), x = expression(psi[soil]~(-MPa))) + 
  theme_classic() -> b

cowplot::plot_grid(plotlist = list(a,b))
```


```{r}
tibble(make_parameters(vcmax = 100, jmax = 167, theta = 0.000157)) %>%
  mutate(trait_set = 1:n()) %>%
  # group_by(param_set) %>%
  nest(trait_matrix = c(-trait_set)) %>%
  expand_grid(environment = expand_grid(PPFD = 1000, psi_soil = seq(0.01, 4, length.out = 10), atm_vpd = seq(0.01, 4, length.out = 10), ca = 40)) %>%
  unnest(environment) %>%
  mutate(param_set = 1:n()) %>%
  group_by(param_set) %>%
  expand_grid(height = c(1)) %>%
  expand_grid(B_ks1 = c(0.2), B_ks2 = c(2),B_hks1 = c(2), B_hks2 = c(2)) %>%
  mutate(focal_hyperpar = pmap(list(B_ks1 = B_ks1,B_ks2 = B_ks2,B_hks1 = B_hks1, B_hks2 =B_hks2), .f = function(B_ks1, B_ks2, B_hks1, B_hks2) list(B_ks1 = B_ks1,B_ks2 = B_ks2, B_hks1 = B_hks1, B_hks2 = B_hks2))) %>%
  nest(environment = -c(trait_set, trait_matrix, param_set, focal_hyperpar, height)) %>%
  mutate(B_rs1_ = 4012, B_lf2_ = 0.004, B_lf3_ = 8e-04, B_lf5_ = 40000) %>% 
  mutate(leaf = pmap(.l = list(trait_matrix, environment, height, focal_hyperpar, B_rs1_, B_lf2_, B_lf3_, B_lf5_), .f = make_leaf)) -> leaf
```

```{r}
find_states_opt_psi_stem <- function(leaf, psi_stem){
  leaf$optimise_psi_stem_TF()
  
  res <- leaf$ci_
  return(res)
}
```

```{r}
leaf %>%
  unnest(leaf) %>%
  unnest(environment) %>%
  mutate(psi_stem = psi_crit) %>%
  mutate(res = map2(.x = leaf, .y = psi_stem, ~find_states_opt_psi_stem(.x, .y))) %>%
  unnest(res) %>%
  unnest(trait_matrix) -> output

output %>%
  filter(psi_soil == 0.01) %>%
  unnest(res) %>%
  ggplot() +
  geom_point(aes(x = atm_vpd, y = res), col = "red") +
  labs(y = expression(paste("Intracellular C", O[2]," (Pa)")), x = "VPD (kPa)") + 
  theme_classic() -> a

output %>%
  filter(atm_vpd == 0.01) %>%
  ggplot() +
  geom_point(aes(x = psi_soil, y = res), col = "red") +
  labs(y = expression(paste("Intracellular C", O[2]," (Pa)")), x = expression(psi[soil]~(-MPa))) + 
  theme_classic() -> b

cowplot::plot_grid(plotlist = list(a,b))

```


#optimise jmax and vcmax

```{r}
target_traits <- tibble(target_traits = c("vcmax","jmax"), bounds = (tibble(lower = c(100,100), upper = c(100,100)))) %>%
  nest(target_traits = everything())
```

```{r}
target_heights <- tibble(target_heights = c(1))
```

#params
```{r}
trait_data <- expand_grid(hmat = 75, beta2 = 1.5, a = 0.24, curv_fact_elec_trans = 0.7, curv_fact_colim = 0.99) %>%
  mutate(param_set = seq(1:n())) %>%
  group_by(param_set) %>%
  nest(trait_data = -param_set) %>% 
  mutate(expanded_trait_data = map(trait_data, ~ .x %>%unlist() %>% as.list())) %>%
  mutate(expanded_trait_data = map(trait_data, ~do.call(make_parameters, .x))) %>%
  unnest(expanded_trait_data)
```


```{r}
trait_data %>%
  pivot_longer(cols = c(-param_set, -trait_data)) %>%
  nest(expanded_trait_data = c(-param_set, -trait_data)) %>%
  mutate(trait_matrix = map(expanded_trait_data, ~trait_matrix(.x$value, .x$name))) %>%
  expand_grid(strategy_type = c("FF16w")) %>%
  mutate(p0 = map(strategy_type, ~scm_base_parameters(.x))) %>%
  expand_grid(B_ks1 = c(0.2), B_ks2 = c(2),B_hks1 = c(2), B_hks2 = c(2), B_lf2=0.004, B_lf3=0.0008, B_lf4=2100, B_lf5=200000) %>%
  mutate(focal_hyperpar = pmap(list(B_ks1 = B_ks1,B_hks1 = B_hks1, B_ks2 = B_ks2, B_hks2 = B_hks2, B_lf2=B_lf2, B_lf3=B_lf3, B_lf4 = B_lf4, B_lf5 = B_lf5), .f = function(B_ks1, B_hks1, B_ks2, B_hks2, B_lf2, B_lf3, B_lf4,B_lf5) list(B_ks1 = B_ks1, B_hks1 = B_hks1, B_ks2 = B_ks2, B_hks2 = B_hks2, B_lf2 = B_lf2, B_lf3 = B_lf3, B_lf4 = B_lf4, B_lf5 = B_lf5))) -> trait_data_expanded
```

```{r}
trait_data_expanded %>%
  mutate(env = map(strategy_type, ~make_environment(.x))) %>%
  # expand_grid(soil_moist = exp(c(log(0.1), seq(log(0.01),log(1),length.out = 10)))) -> trait_data_environment
 expand_grid(
    psi_soil = 4.4-exp(seq(log(0.01), log(4.3), length.out = 1)),
    ca = 40,
    atm_vpd = 0.1,
    canopy_openess = 1) -> trait_data_environment_soil_moist

trait_data_expanded %>%
  mutate(env = map(strategy_type, ~make_environment(.x))) %>%
  # expand_grid(soil_moist = exp(c(log(0.1), seq(log(0.01),log(1),length.out = 10)))) -> trait_data_environment
 expand_grid(
   psi_soil = 0.1,
    ca = 40,
    atm_vpd = seq(0.1,4, length.out = 1),   
   canopy_openess = 1) -> trait_data_environment_vpd

trait_data_environment <- bind_rows(trait_data_environment_soil_moist, trait_data_environment_vpd)
```

```{r}
trait_data_environment %>%
  expand_grid(target_traits, target_heights)-> trait_data_environment_bounds
```


```{r}
trait_data_environment_bounds %>%
  mutate(res = pmap(., find_max_growth, use_default_strategy = FALSE, use_optim = TRUE)) -> growth_outcome
```

```{r}
growth_outcome %>%
  mutate(ret = map(res, ~.x$res)) %>% 
  mutate(attr = map(ret, ~attr(.x, "height"))) %>%
  unnest(attr, target_traits) %>% 
  mutate(attr = exp(attr)) %>% 
  pivot_wider(names_from = target_traits, values_from = attr) %>%
  filter(ret != 0) %>% View()
  select(ca, atm_vpd, canopy_openess, psi_soil, vcmax, jmax, target_heights, trait_data, focal_hyperpar) -> optimum_traits
```

```{r}
indv_growth_trait_data <- tibble(trait_data = optimum_traits$trait_data[1], vcmax = optimum_traits$vcmax, jmax = optimum_traits$jmax) %>%
  unnest(trait_data) %>%
  mutate(param_set = seq(1:n())) %>%
  group_by(param_set) %>%
  nest(trait_data = -param_set) %>% 
  mutate(expanded_trait_data = map(trait_data, ~ .x %>%unlist() %>% as.list())) %>%
  mutate(expanded_trait_data = map(trait_data, ~do.call(make_parameters, .x))) %>%
  unnest(expanded_trait_data)
```

```{r}
indv_growth_trait_data %>%
  pivot_longer(cols = c(-param_set, -trait_data)) %>%
  nest(expanded_trait_data = c(-param_set, -trait_data)) %>%
  mutate(trait_matrix = map(expanded_trait_data, ~trait_matrix(.x$value, .x$name))) %>%
  expand_grid(strategy_type = c("FF16w")) %>%
  mutate(p0 = map(strategy_type, ~scm_base_parameters(.x))) %>%
  mutate(focal_hyperpar = optimum_traits[1,]$focal_hyperpar) -> indv_growth_trait_data_expanded
```

```{r}
indv_growth_trait_data_expanded %>%
  mutate(env = map(strategy_type, ~make_environment(.x))) %>%
  # expand_grid(soil_moist = exp(c(log(0.1), seq(log(0.01),log(1),length.out = 10)))) -> trait_data_environment
 tibble(
    psi_soil = optimum_traits$psi_soil,
    ca = optimum_traits$ca,
    atm_vpd = optimum_traits$atm_vpd,
              canopy_openess = optimum_traits$canopy_openess) -> trait_data_environment 
```

```{r}
trait_data_environment %>%bind_cols(target_heights = optimum_traits$target_heights)-> trait_data_environment_bounds
```

```{r}
trait_data_environment_bounds %>% 
  mutate(param_set = 1:n()) %>%
  group_by(param_set) %>%
  nest(environment = c(psi_soil, ca, atm_vpd, canopy_openess)) %>%
  mutate(res = pmap(.l = list(trait_matrix, environment, target_heights, focal_hyperpar), .f = run_individual_through_height)) -> outcome_optimised
```

```{r}
tibble(outcome_optimised = outcome_optimised %>% ungroup() %>% nest()) %>%
  pivot_longer(cols = c(outcome_optimised), names_to = "outcome_type") %>%
  unnest(value) %>%
  unnest(data) -> outcome
```

```{r}
outcome %>% 
  unnest(trait_data) %>%
  filter(target_heights == 1) %>%
  ungroup() %>%
  unnest(environment) %>%
  filter(ca == 40) %>%
  filter(canopy_openess == 1) %>%
  filter(psi_soil == 0.1) %>%
  unnest(trait_matrix) %>%
  ungroup()   %>% 
  unnest_wider(res) %>%
  unnest(ode_rates, ode_state, ode_names) %>%
  pivot_wider(names_from = "ode_names", values_from = c("ode_rates", "ode_state")) %>% 
  unnest(aux_names, aux) %>%
  pivot_wider(names_from = "aux_names", values_from = "aux") %>% 
  ggplot() +
  geom_point(aes(x = atm_vpd, y = ci_), col = "red") +
  labs(y = expression(paste("Intracellular C", O[2]," (Pa)")), x = "VPD (kPa)") + 
  theme_classic() -> a


outcome %>% 
  unnest(trait_data) %>%
  filter(target_heights == 1) %>%
  ungroup() %>%
  unnest(environment) %>%
  filter(ca == 40) %>%
  filter(canopy_openess == 1) %>%
  filter(atm_vpd == 0.1) %>%
  unnest(trait_matrix) %>%
  ungroup()   %>% 
  unnest_wider(res) %>%
  unnest(ode_rates, ode_state, ode_names) %>%
  pivot_wider(names_from = "ode_names", values_from = c("ode_rates", "ode_state")) %>% 
  unnest(aux_names, aux) %>%
  pivot_wider(names_from = "aux_names", values_from = "aux") %>% 
  ggplot() +
  geom_point(aes(x = psi_soil, y = ci_), col = "red") +
  labs(y = expression(paste("Intracellular C", O[2]," (Pa)")), x = expression(psi[soil]~(-MPa))) + 
  theme_classic() -> b
```


#optimise jmax and vcmax and theta

```{r}
target_traits <- tibble(target_traits = c("vcmax","jmax","theta"), bounds = (tibble(lower = c(100,100, 0.000157), upper = c(100,100, 0.000157)))) %>%
  nest(target_traits = everything())
```

```{r}
target_heights <- tibble(target_heights = c(1))
```

#params
```{r}
trait_data <- expand_grid(hmat = 75, beta2 = 1.5, a = 0.24, curv_fact_elec_trans = 0.7, curv_fact_colim = 0.99) %>%
  mutate(param_set = seq(1:n())) %>%
  group_by(param_set) %>%
  nest(trait_data = -param_set) %>% 
  mutate(expanded_trait_data = map(trait_data, ~ .x %>%unlist() %>% as.list())) %>%
  mutate(expanded_trait_data = map(trait_data, ~do.call(make_parameters, .x))) %>%
  unnest(expanded_trait_data)
```


```{r}
trait_data %>%
  pivot_longer(cols = c(-param_set, -trait_data)) %>%
  nest(expanded_trait_data = c(-param_set, -trait_data)) %>%
  mutate(trait_matrix = map(expanded_trait_data, ~trait_matrix(.x$value, .x$name))) %>%
  expand_grid(strategy_type = c("FF16w")) %>%
  mutate(p0 = map(strategy_type, ~scm_base_parameters(.x))) %>%
  expand_grid(B_ks1 = c(0.2), B_ks2 = c(2),B_hks1 = c(2), B_hks2 = c(2), B_lf2=0.004, B_lf3=0.0008, B_lf4=2100, B_lf5=200000) %>%
  mutate(focal_hyperpar = pmap(list(B_ks1 = B_ks1,B_hks1 = B_hks1, B_ks2 = B_ks2, B_hks2 = B_hks2, B_lf2=B_lf2, B_lf3=B_lf3, B_lf4 = B_lf4, B_lf5 = B_lf5), .f = function(B_ks1, B_hks1, B_ks2, B_hks2, B_lf2, B_lf3, B_lf4,B_lf5) list(B_ks1 = B_ks1, B_hks1 = B_hks1, B_ks2 = B_ks2, B_hks2 = B_hks2, B_lf2 = B_lf2, B_lf3 = B_lf3, B_lf4 = B_lf4, B_lf5 = B_lf5))) -> trait_data_expanded
```

```{r}
trait_data_expanded %>%
  mutate(env = map(strategy_type, ~make_environment(.x))) %>%
  # expand_grid(soil_moist = exp(c(log(0.1), seq(log(0.01),log(1),length.out = 10)))) -> trait_data_environment
 expand_grid(
    psi_soil = 4.4-exp(seq(log(0.01), log(4.3), length.out = 10)),
    ca = 40,
    atm_vpd = 0.1,
    canopy_openess = 1) -> trait_data_environment_soil_moist

trait_data_expanded %>%
  mutate(env = map(strategy_type, ~make_environment(.x))) %>%
  # expand_grid(soil_moist = exp(c(log(0.1), seq(log(0.01),log(1),length.out = 10)))) -> trait_data_environment
 expand_grid(
   psi_soil = 0.1,
    ca = 40,
    atm_vpd = seq(0.1,4, length.out = 10),   
   canopy_openess = 1) -> trait_data_environment_vpd

trait_data_environment <- bind_rows(trait_data_environment_soil_moist, trait_data_environment_vpd)
```

```{r}
trait_data_environment %>%
  expand_grid(target_traits, target_heights)-> trait_data_environment_bounds
```


```{r}
trait_data_environment_bounds %>%
  mutate(res = future_pmap(., find_max_growth, use_default_strategy = FALSE, use_optim = TRUE)) -> growth_outcome
```

```{r}
growth_outcome %>%
  mutate(ret = map(res, ~.x$res)) %>% 
  mutate(attr = map(ret, ~attr(.x, "height"))) %>%
  unnest(attr, target_traits) %>% 
  mutate(attr = exp(attr)) %>% 
  pivot_wider(names_from = target_traits, values_from = attr) %>%
  filter(ret != 0) %>%
  select(ca, atm_vpd, canopy_openess, psi_soil, vcmax, jmax, target_heights, trait_data, focal_hyperpar) -> optimum_traits
```

```{r}
indv_growth_trait_data <- tibble(trait_data = optimum_traits$trait_data[1], vcmax = optimum_traits$vcmax, jmax = optimum_traits$jmax) %>%
  unnest(trait_data) %>%
  mutate(param_set = seq(1:n())) %>%
  group_by(param_set) %>%
  nest(trait_data = -param_set) %>% 
  mutate(expanded_trait_data = map(trait_data, ~ .x %>%unlist() %>% as.list())) %>%
  mutate(expanded_trait_data = map(trait_data, ~do.call(make_parameters, .x))) %>%
  unnest(expanded_trait_data)
```

```{r}
indv_growth_trait_data %>%
  pivot_longer(cols = c(-param_set, -trait_data)) %>%
  nest(expanded_trait_data = c(-param_set, -trait_data)) %>%
  mutate(trait_matrix = map(expanded_trait_data, ~trait_matrix(.x$value, .x$name))) %>%
  expand_grid(strategy_type = c("FF16w")) %>%
  mutate(p0 = map(strategy_type, ~scm_base_parameters(.x))) %>%
  mutate(focal_hyperpar = optimum_traits[1,]$focal_hyperpar) -> indv_growth_trait_data_expanded
```

```{r}
indv_growth_trait_data_expanded %>%
  mutate(env = map(strategy_type, ~make_environment(.x))) %>%
  # expand_grid(soil_moist = exp(c(log(0.1), seq(log(0.01),log(1),length.out = 10)))) -> trait_data_environment
 tibble(
    psi_soil = optimum_traits$psi_soil,
    ca = optimum_traits$ca,
    atm_vpd = optimum_traits$atm_vpd,
              canopy_openess = optimum_traits$canopy_openess) -> trait_data_environment 
```

```{r}
trait_data_environment %>%bind_cols(target_heights = optimum_traits$target_heights)-> trait_data_environment_bounds
```

```{r}
trait_data_environment_bounds %>% 
  mutate(param_set = 1:n()) %>%
  group_by(param_set) %>%
  nest(environment = c(psi_soil, ca, atm_vpd, canopy_openess)) %>%
  mutate(res = pmap(.l = list(trait_matrix, environment, target_heights, focal_hyperpar), .f = run_individual_through_height)) -> outcome_optimised
```

```{r}
tibble(outcome_optimised = outcome_optimised %>% ungroup() %>% nest()) %>%
  pivot_longer(cols = c(outcome_optimised), names_to = "outcome_type") %>%
  unnest(value) %>%
  unnest(data) -> outcome
```

```{r}
outcome %>% 
  unnest(trait_data) %>%
  filter(target_heights == 1) %>%
  ungroup() %>%
  unnest(environment) %>%
  filter(ca == 40) %>%
  filter(canopy_openess == 1) %>%
  filter(psi_soil == 0.1) %>%
  unnest(trait_matrix) %>%
  ungroup()   %>% 
  unnest_wider(res) %>%
  unnest(ode_rates, ode_state, ode_names) %>%
  pivot_wider(names_from = "ode_names", values_from = c("ode_rates", "ode_state")) %>% 
  unnest(aux_names, aux) %>%
  pivot_wider(names_from = "aux_names", values_from = "aux") %>% 
  ggplot() +
  geom_point(aes(x = atm_vpd, y = ci_), col = "red") +
  labs(y = expression(paste("Intracellular C", O[2]," (Pa)")), x = "VPD (kPa)") + 
  theme_classic() -> a


outcome %>% 
  unnest(trait_data) %>%
  filter(target_heights == 1) %>%
  ungroup() %>%
  unnest(environment) %>%
  filter(ca == 40) %>%
  filter(canopy_openess == 1) %>%
  filter(atm_vpd == 0.1) %>%
  unnest(trait_matrix) %>%
  ungroup()   %>% 
  unnest_wider(res) %>%
  unnest(ode_rates, ode_state, ode_names) %>%
  pivot_wider(names_from = "ode_names", values_from = c("ode_rates", "ode_state")) %>% 
  unnest(aux_names, aux) %>%
  pivot_wider(names_from = "aux_names", values_from = "aux") %>% 
  ggplot() +
  geom_point(aes(x = psi_soil, y = ci_), col = "red") +
  labs(y = expression(paste("Intracellular C", O[2]," (Pa)")), x = expression(psi[soil]~(-MPa))) + 
  theme_classic() -> b
```

