# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Lorenz__ctor <- function(sigma, R, b) {
    .Call('tree2_Lorenz__ctor', PACKAGE = 'tree2', sigma, R, b)
}

Lorenz__size__get <- function(obj_) {
    .Call('tree2_Lorenz__size__get', PACKAGE = 'tree2', obj_)
}

Lorenz__ode_values__get <- function(obj_) {
    .Call('tree2_Lorenz__ode_values__get', PACKAGE = 'tree2', obj_)
}

Lorenz__ode_values__set <- function(obj_, value) {
    invisible(.Call('tree2_Lorenz__ode_values__set', PACKAGE = 'tree2', obj_, value))
}

Lorenz__ode_rates__get <- function(obj_) {
    .Call('tree2_Lorenz__ode_rates__get', PACKAGE = 'tree2', obj_)
}

Lorenz__pars__get <- function(obj_) {
    .Call('tree2_Lorenz__pars__get', PACKAGE = 'tree2', obj_)
}

OdeSystem___Lorenz__ctor <- function(obj, abs_tol, rel_tol) {
    .Call('tree2_OdeSystem___Lorenz__ctor', PACKAGE = 'tree2', obj, abs_tol, rel_tol)
}

OdeSystem___Lorenz__do_step <- function(obj_, dt) {
    invisible(.Call('tree2_OdeSystem___Lorenz__do_step', PACKAGE = 'tree2', obj_, dt))
}

OdeSystem___Lorenz__try_step <- function(obj_, dt) {
    .Call('tree2_OdeSystem___Lorenz__try_step', PACKAGE = 'tree2', obj_, dt)
}

OdeSystem___Lorenz__advance <- function(obj_, t, dt) {
    invisible(.Call('tree2_OdeSystem___Lorenz__advance', PACKAGE = 'tree2', obj_, t, dt))
}

OdeSystem___Lorenz__advance_save <- function(obj_, t, dt) {
    .Call('tree2_OdeSystem___Lorenz__advance_save', PACKAGE = 'tree2', obj_, t, dt)
}

OdeSystem___Lorenz__obj__get <- function(obj_) {
    .Call('tree2_OdeSystem___Lorenz__obj__get', PACKAGE = 'tree2', obj_)
}

OdeSystem___Lorenz__t__get <- function(obj_) {
    .Call('tree2_OdeSystem___Lorenz__t__get', PACKAGE = 'tree2', obj_)
}

OdeSystem___Lorenz__t__set <- function(obj_, value) {
    invisible(.Call('tree2_OdeSystem___Lorenz__t__set', PACKAGE = 'tree2', obj_, value))
}

OdeSystem___Lorenz__y__get <- function(obj_) {
    .Call('tree2_OdeSystem___Lorenz__y__get', PACKAGE = 'tree2', obj_)
}

OdeSystem___Lorenz__y__set <- function(obj_, value) {
    invisible(.Call('tree2_OdeSystem___Lorenz__y__set', PACKAGE = 'tree2', obj_, value))
}

CohortScheduleEvent__ctor <- function(introduction, species_index) {
    .Call('tree2_CohortScheduleEvent__ctor', PACKAGE = 'tree2', introduction, species_index)
}

CohortScheduleEvent__species_index__get <- function(obj_) {
    .Call('tree2_CohortScheduleEvent__species_index__get', PACKAGE = 'tree2', obj_)
}

CohortScheduleEvent__times__get <- function(obj_) {
    .Call('tree2_CohortScheduleEvent__times__get', PACKAGE = 'tree2', obj_)
}

CohortScheduleEvent__time_introduction__get <- function(obj_) {
    .Call('tree2_CohortScheduleEvent__time_introduction__get', PACKAGE = 'tree2', obj_)
}

CohortScheduleEvent__time_end__get <- function(obj_) {
    .Call('tree2_CohortScheduleEvent__time_end__get', PACKAGE = 'tree2', obj_)
}

Control__ctor <- function() {
    .Call('tree2_Control__ctor', PACKAGE = 'tree2')
}

Strategy__ctor <- function() {
    .Call('tree2_Strategy__ctor', PACKAGE = 'tree2')
}

