## Generated by RcppR6: do not edit by hand
## Version: 0.2.3
## Hash: a25e20cb376bc7a8c93b175eeedc288f

##' @importFrom Rcpp evalCpp
##' @importFrom R6 R6Class
##' @useDynLib plant
NULL

## This section of code is only included where templated classes are
## included.  Don't rely on the approach taken here, as it may change
## soon.
check_type <- function(type, valid) {
  i <- match(list(type), valid, nomatch=NA)
  if (is.na(i)) {
    choices <- paste(sprintf("\t%s", sapply(valid, paste, collapse=", ")),
                     collapse="\n")
    stop(sprintf("Invalid type '%s'; expected one of:\n%s",
                 paste(type, collapse=", "), choices))
  }
  names(valid)[[i]]
}


`Lorenz` <- function(sigma, R, b) {
  Lorenz__ctor(sigma, R, b)
}
.R6_Lorenz <-
  R6::R6Class(
    "Lorenz",
    inherit=,
    portable=TRUE,
    public=list(
      .ptr=NULL,
      initialize = function(ptr) {
        self$.ptr <- ptr
      }),
    active=list(
      ode_size = function(value) {
        if (missing(value)) {
          Lorenz__ode_size__get(self)
        } else {
          stop("Lorenz$ode_size is read-only")
        }
      },
      ode_state = function(value) {
        if (missing(value)) {
          Lorenz__ode_state__get(self)
        } else {
          Lorenz__ode_state__set(self, value)
        }
      },
      ode_rates = function(value) {
        if (missing(value)) {
          Lorenz__ode_rates__get(self)
        } else {
          stop("Lorenz$ode_rates is read-only")
        }
      },
      pars = function(value) {
        if (missing(value)) {
          Lorenz__pars__get(self)
        } else {
          stop("Lorenz$pars is read-only")
        }
      }))


`OdeR` <- function(derivs, state, time) {
  OdeR__ctor(derivs, state, time)
}
.R6_OdeR <-
  R6::R6Class(
    "OdeR",
    inherit=,
    portable=TRUE,
    public=list(
      .ptr=NULL,
      initialize = function(ptr) {
        self$.ptr <- ptr
      },
      update_state = function() {
        OdeR__update_state(self)
      }),
    active=list())

OdeRunner <- function(T) {
  type <- c(T)
  valid <- list("OdeRunner<Lorenz>"="Lorenz", "OdeRunner<OdeR>"="OdeR", "OdeRunner<PlantRunner>"="PlantRunner")
  constructors <- list("OdeRunner<Lorenz>"=`OdeRunner<Lorenz>`, "OdeRunner<OdeR>"=`OdeRunner<OdeR>`, "OdeRunner<PlantRunner>"=`OdeRunner<PlantRunner>`)
  constructors[[check_type(type, valid)]]
}
.R6_OdeRunner <- R6::R6Class("OdeRunner")



`OdeRunner<Lorenz>` <- function(obj, control=OdeControl()) {
  OdeRunner___Lorenz__ctor(obj, control)
}
.R6_OdeRunner___Lorenz <-
  R6::R6Class(
    "OdeRunner<Lorenz>",
    inherit=.R6_OdeRunner,
    portable=TRUE,
    public=list(
      .ptr=NULL,
      initialize = function(ptr) {
        self$.ptr <- ptr
      },
      advance = function(time) {
        OdeRunner___Lorenz__advance(self, time)
      },
      advance_fixed = function(time) {
        OdeRunner___Lorenz__advance_fixed(self, time)
      },
      step = function() {
        OdeRunner___Lorenz__step(self)
      },
      step_to = function(time) {
        OdeRunner___Lorenz__step_to(self, time)
      },
      set_state = function(y, time) {
        OdeRunner___Lorenz__set_state(self, y, time)
      },
      set_state_from_system = function() {
        OdeRunner___Lorenz__set_state_from_system(self)
      }),
    active=list(
      time = function(value) {
        if (missing(value)) {
          OdeRunner___Lorenz__time__get(self)
        } else {
          stop("OdeRunner<Lorenz>$time is read-only")
        }
      },
      state = function(value) {
        if (missing(value)) {
          OdeRunner___Lorenz__state__get(self)
        } else {
          stop("OdeRunner<Lorenz>$state is read-only")
        }
      },
      times = function(value) {
        if (missing(value)) {
          OdeRunner___Lorenz__times__get(self)
        } else {
          stop("OdeRunner<Lorenz>$times is read-only")
        }
      },
      object = function(value) {
        if (missing(value)) {
          OdeRunner___Lorenz__object__get(self)
        } else {
          stop("OdeRunner<Lorenz>$object is read-only")
        }
      }))


`OdeRunner<OdeR>` <- function(obj, control=OdeControl()) {
  OdeRunner___OdeR__ctor(obj, control)
}
.R6_OdeRunner___OdeR <-
  R6::R6Class(
    "OdeRunner<OdeR>",
    inherit=.R6_OdeRunner,
    portable=TRUE,
    public=list(
      .ptr=NULL,
      initialize = function(ptr) {
        self$.ptr <- ptr
      },
      advance = function(time) {
        OdeRunner___OdeR__advance(self, time)
      },
      advance_fixed = function(time) {
        OdeRunner___OdeR__advance_fixed(self, time)
      },
      step = function() {
        OdeRunner___OdeR__step(self)
      },
      step_to = function(time) {
        OdeRunner___OdeR__step_to(self, time)
      },
      set_state = function(y, time) {
        OdeRunner___OdeR__set_state(self, y, time)
      },
      set_state_from_system = function() {
        OdeRunner___OdeR__set_state_from_system(self)
      }),
    active=list(
      time = function(value) {
        if (missing(value)) {
          OdeRunner___OdeR__time__get(self)
        } else {
          stop("OdeRunner<OdeR>$time is read-only")
        }
      },
      state = function(value) {
        if (missing(value)) {
          OdeRunner___OdeR__state__get(self)
        } else {
          stop("OdeRunner<OdeR>$state is read-only")
        }
      },
      times = function(value) {
        if (missing(value)) {
          OdeRunner___OdeR__times__get(self)
        } else {
          stop("OdeRunner<OdeR>$times is read-only")
        }
      },
      object = function(value) {
        if (missing(value)) {
          OdeRunner___OdeR__object__get(self)
        } else {
          stop("OdeRunner<OdeR>$object is read-only")
        }
      }))


`OdeRunner<PlantRunner>` <- function(obj, control=OdeControl()) {
  OdeRunner___PlantRunner__ctor(obj, control)
}
.R6_OdeRunner___PlantRunner <-
  R6::R6Class(
    "OdeRunner<PlantRunner>",
    inherit=.R6_OdeRunner,
    portable=TRUE,
    public=list(
      .ptr=NULL,
      initialize = function(ptr) {
        self$.ptr <- ptr
      },
      advance = function(time) {
        OdeRunner___PlantRunner__advance(self, time)
      },
      advance_fixed = function(time) {
        OdeRunner___PlantRunner__advance_fixed(self, time)
      },
      step = function() {
        OdeRunner___PlantRunner__step(self)
      },
      step_to = function(time) {
        OdeRunner___PlantRunner__step_to(self, time)
      },
      set_state = function(y, time) {
        OdeRunner___PlantRunner__set_state(self, y, time)
      },
      set_state_from_system = function() {
        OdeRunner___PlantRunner__set_state_from_system(self)
      }),
    active=list(
      time = function(value) {
        if (missing(value)) {
          OdeRunner___PlantRunner__time__get(self)
        } else {
          stop("OdeRunner<PlantRunner>$time is read-only")
        }
      },
      state = function(value) {
        if (missing(value)) {
          OdeRunner___PlantRunner__state__get(self)
        } else {
          stop("OdeRunner<PlantRunner>$state is read-only")
        }
      },
      times = function(value) {
        if (missing(value)) {
          OdeRunner___PlantRunner__times__get(self)
        } else {
          stop("OdeRunner<PlantRunner>$times is read-only")
        }
      },
      object = function(value) {
        if (missing(value)) {
          OdeRunner___PlantRunner__object__get(self)
        } else {
          stop("OdeRunner<PlantRunner>$object is read-only")
        }
      }))


`CohortScheduleEvent` <- function(introduction, species_index) {
  CohortScheduleEvent__ctor(introduction, species_index)
}
.R6_CohortScheduleEvent <-
  R6::R6Class(
    "CohortScheduleEvent",
    inherit=,
    portable=TRUE,
    public=list(
      .ptr=NULL,
      initialize = function(ptr) {
        self$.ptr <- ptr
      }),
    active=list(
      species_index = function(value) {
        if (missing(value)) {
          CohortScheduleEvent__species_index__get(self)
        } else {
          CohortScheduleEvent__species_index__set(self, value)
        }
      },
      times = function(value) {
        if (missing(value)) {
          CohortScheduleEvent__times__get(self)
        } else {
          stop("CohortScheduleEvent$times is read-only")
        }
      },
      time_introduction = function(value) {
        if (missing(value)) {
          CohortScheduleEvent__time_introduction__get(self)
        } else {
          stop("CohortScheduleEvent$time_introduction is read-only")
        }
      },
      time_end = function(value) {
        if (missing(value)) {
          CohortScheduleEvent__time_end__get(self)
        } else {
          stop("CohortScheduleEvent$time_end is read-only")
        }
      },
      species_index_raw = function(value) {
        if (missing(value)) {
          CohortScheduleEvent__species_index_raw__get(self)
        } else {
          stop("CohortScheduleEvent$species_index_raw is read-only")
        }
      }))

##' Schedule of cohort introduction times
##' @param n_species number of species
##' @export
`CohortSchedule` <- function(n_species) {
  CohortSchedule__ctor(n_species)
}
.R6_CohortSchedule <-
  R6::R6Class(
    "CohortSchedule",
    inherit=,
    portable=TRUE,
    public=list(
      .ptr=NULL,
      initialize = function(ptr) {
        self$.ptr <- ptr
      },
      expand = function(n_extra, times) {
        CohortSchedule__expand(self, n_extra, times)
      },
      clear_times = function(species_index) {
        CohortSchedule__clear_times(self, species_index)
      },
      clear_ode_times = function() {
        CohortSchedule__clear_ode_times(self)
      },
      set_times = function(times, species_index) {
        CohortSchedule__set_times(self, times, species_index)
      },
      times = function(species_index) {
        CohortSchedule__times(self, species_index)
      },
      reset = function() {
        CohortSchedule__reset(self)
      },
      pop = function() {
        CohortSchedule__pop(self)
      },
      copy = function() {
        CohortSchedule__copy(self)
      }),
    active=list(
      size = function(value) {
        if (missing(value)) {
          CohortSchedule__size__get(self)
        } else {
          stop("CohortSchedule$size is read-only")
        }
      },
      n_species = function(value) {
        if (missing(value)) {
          CohortSchedule__n_species__get(self)
        } else {
          stop("CohortSchedule$n_species is read-only")
        }
      },
      next_event = function(value) {
        if (missing(value)) {
          CohortSchedule__next_event__get(self)
        } else {
          stop("CohortSchedule$next_event is read-only")
        }
      },
      remaining = function(value) {
        if (missing(value)) {
          CohortSchedule__remaining__get(self)
        } else {
          stop("CohortSchedule$remaining is read-only")
        }
      },
      max_time = function(value) {
        if (missing(value)) {
          CohortSchedule__max_time__get(self)
        } else {
          CohortSchedule__max_time__set(self, value)
        }
      },
      ode_times = function(value) {
        if (missing(value)) {
          CohortSchedule__ode_times__get(self)
        } else {
          CohortSchedule__ode_times__set(self, value)
        }
      },
      use_ode_times = function(value) {
        if (missing(value)) {
          CohortSchedule__use_ode_times__get(self)
        } else {
          CohortSchedule__use_ode_times__set(self, value)
        }
      },
      all_times = function(value) {
        if (missing(value)) {
          CohortSchedule__all_times__get(self)
        } else {
          CohortSchedule__all_times__set(self, value)
        }
      }))

##' Disturbance control object
##' @param mean_interval Mean disturbance interval in years
##' @export
`Disturbance` <- function(mean_interval) {
  Disturbance__ctor(mean_interval)
}
.R6_Disturbance <-
  R6::R6Class(
    "Disturbance",
    inherit=,
    portable=TRUE,
    public=list(
      .ptr=NULL,
      initialize = function(ptr) {
        self$.ptr <- ptr
      },
      density = function(time) {
        Disturbance__density(self, time)
      },
      pr_survival = function(time) {
        Disturbance__pr_survival(self, time)
      },
      pr_survival_conditional = function(time, time_start) {
        Disturbance__pr_survival_conditional(self, time, time_start)
      },
      cdf = function(time) {
        Disturbance__cdf(self, time)
      }),
    active=list(
      mean_interval = function(value) {
        if (missing(value)) {
          Disturbance__mean_interval__get(self)
        } else {
          stop("Disturbance$mean_interval is read-only")
        }
      }))

##' Control parameters that tune various aspects of the numerical solvers.
##' @title Control parameters
##' @param ...,values Values to initialise the struct with (either as
##' variadic arguments, or as a list, but not both).
##' @export
`Control` <- function(..., values=list(...)) {
  ret <- Control__ctor()
  if (length(values) > 0L) {
    if (is.null(names(values)) || any(names(values) == "")) {
      stop("All values must be named")
    }
    if (length(err <- setdiff(names(values), names(ret))) > 0L) {
      stop(sprintf("Unknown fields: %s", paste(err, collapse=", ")))
    }
    to_set <- intersect(names(values), names(ret))
    ret[to_set] <- values[to_set]
  }
  ret
}

##' Control parameters for the ode system
##' @title ODE Control parameters
##' @param ...,values Values to initialise the struct with (either as
##' variadic arguments, or as a list, but not both).
##' @export
`OdeControl` <- function(..., values=list(...)) {
  ret <- OdeControl__ctor()
  if (length(values) > 0L) {
    if (is.null(names(values)) || any(names(values) == "")) {
      stop("All values must be named")
    }
    if (length(err <- setdiff(names(values), names(ret))) > 0L) {
      stop(sprintf("Unknown fields: %s", paste(err, collapse=", ")))
    }
    to_set <- intersect(names(values), names(ret))
    ret[to_set] <- values[to_set]
  }
  ret
}

##' Gauss-Kronrod Quadrature
##' @param rule Degree of the rule; valid sizes are 15, 21, 31, 41, 51, 61.
`QK` <- function(rule) {
  QK__ctor(rule)
}
.R6_QK <-
  R6::R6Class(
    "QK",
    inherit=,
    portable=TRUE,
    public=list(
      .ptr=NULL,
      initialize = function(ptr) {
        self$.ptr <- ptr
      },
      integrate = function(f, a, b) {
        QK__integrate(self, f, a, b)
      },
      integrate_vector_x = function(a, b) {
        QK__integrate_vector_x(self, a, b)
      },
      integrate_vector = function(y, a, b) {
        QK__integrate_vector(self, y, a, b)
      }),
    active=list(
      last_area = function(value) {
        if (missing(value)) {
          QK__last_area__get(self)
        } else {
          stop("QK$last_area is read-only")
        }
      },
      last_error = function(value) {
        if (missing(value)) {
          QK__last_error__get(self)
        } else {
          stop("QK$last_error is read-only")
        }
      },
      last_area_abs = function(value) {
        if (missing(value)) {
          QK__last_area_abs__get(self)
        } else {
          stop("QK$last_area_abs is read-only")
        }
      },
      last_area_asc = function(value) {
        if (missing(value)) {
          QK__last_area_asc__get(self)
        } else {
          stop("QK$last_area_asc is read-only")
        }
      }))


`QAG` <- function(rule, max_iterations, atol, rtol) {
  QAG__ctor(rule, max_iterations, atol, rtol)
}
.R6_QAG <-
  R6::R6Class(
    "QAG",
    inherit=,
    portable=TRUE,
    public=list(
      .ptr=NULL,
      initialize = function(ptr) {
        self$.ptr <- ptr
      },
      integrate = function(f, a, b) {
        QAG__integrate(self, f, a, b)
      },
      integrate_with_intervals = function(f, intervals) {
        QAG__integrate_with_intervals(self, f, intervals)
      },
      integrate_with_last_intervals = function(f, a, b) {
        QAG__integrate_with_last_intervals(self, f, a, b)
      }),
    active=list(
      last_area = function(value) {
        if (missing(value)) {
          QAG__last_area__get(self)
        } else {
          stop("QAG$last_area is read-only")
        }
      },
      last_error = function(value) {
        if (missing(value)) {
          QAG__last_error__get(self)
        } else {
          stop("QAG$last_error is read-only")
        }
      },
      last_iterations = function(value) {
        if (missing(value)) {
          QAG__last_iterations__get(self)
        } else {
          stop("QAG$last_iterations is read-only")
        }
      },
      last_intervals = function(value) {
        if (missing(value)) {
          QAG__last_intervals__get(self)
        } else {
          stop("QAG$last_intervals is read-only")
        }
      },
      is_adaptive = function(value) {
        if (missing(value)) {
          QAG__is_adaptive__get(self)
        } else {
          stop("QAG$is_adaptive is read-only")
        }
      }))

##' Spline interpolation
##' @export
`Interpolator` <- function() {
  Interpolator__ctor()
}
.R6_Interpolator <-
  R6::R6Class(
    "Interpolator",
    inherit=,
    portable=TRUE,
    public=list(
      .ptr=NULL,
      initialize = function(ptr) {
        self$.ptr <- ptr
      },
      init = function(x, y) {
        Interpolator__init(self, x, y)
      },
      eval = function(x) {
        Interpolator__eval(self, x)
      }),
    active=list(
      x = function(value) {
        if (missing(value)) {
          Interpolator__x__get(self)
        } else {
          stop("Interpolator$x is read-only")
        }
      },
      y = function(value) {
        if (missing(value)) {
          Interpolator__y__get(self)
        } else {
          stop("Interpolator$y is read-only")
        }
      },
      xy = function(value) {
        if (missing(value)) {
          Interpolator__xy__get(self)
        } else {
          stop("Interpolator$xy is read-only")
        }
      },
      size = function(value) {
        if (missing(value)) {
          Interpolator__size__get(self)
        } else {
          stop("Interpolator$size is read-only")
        }
      },
      min = function(value) {
        if (missing(value)) {
          Interpolator__min__get(self)
        } else {
          stop("Interpolator$min is read-only")
        }
      },
      max = function(value) {
        if (missing(value)) {
          Interpolator__max__get(self)
        } else {
          stop("Interpolator$max is read-only")
        }
      }))

##' Environment object
##' @param disturbance_mean_interval mean disturbance interval in years
##' @param seed_rain vector of seed rains
##' @param control A Control object
##' @export
`Environment` <- function(disturbance_mean_interval, seed_rain, control) {
  Environment__ctor(disturbance_mean_interval, seed_rain, control)
}
.R6_Environment <-
  R6::R6Class(
    "Environment",
    inherit=,
    portable=TRUE,
    public=list(
      .ptr=NULL,
      initialize = function(ptr) {
        self$.ptr <- ptr
      },
      canopy_openness = function(height) {
        Environment__canopy_openness(self, height)
      },
      patch_survival_conditional = function(time_at_birth) {
        Environment__patch_survival_conditional(self, time_at_birth)
      },
      clear = function() {
        Environment__clear(self)
      },
      set_seed_rain_index = function(x) {
        Environment__set_seed_rain_index(self, x)
      }),
    active=list(
      patch_survival = function(value) {
        if (missing(value)) {
          Environment__patch_survival__get(self)
        } else {
          stop("Environment$patch_survival is read-only")
        }
      },
      seed_rain_dt = function(value) {
        if (missing(value)) {
          Environment__seed_rain_dt__get(self)
        } else {
          stop("Environment$seed_rain_dt is read-only")
        }
      },
      disturbance_regime = function(value) {
        if (missing(value)) {
          Environment__disturbance_regime__get(self)
        } else {
          Environment__disturbance_regime__set(self, value)
        }
      },
      time = function(value) {
        if (missing(value)) {
          Environment__time__get(self)
        } else {
          Environment__time__set(self, value)
        }
      },
      light_environment = function(value) {
        if (missing(value)) {
          Environment__light_environment__get(self)
        } else {
          Environment__light_environment__set(self, value)
        }
      }))

`Plant_internals` <- function(..., values=list(...)) {
  ret <- Plant_internals__ctor()
  if (length(values) > 0L) {
    if (is.null(names(values)) || any(names(values) == "")) {
      stop("All values must be named")
    }
    if (length(err <- setdiff(names(values), names(ret))) > 0L) {
      stop(sprintf("Unknown fields: %s", paste(err, collapse=", ")))
    }
    to_set <- intersect(names(values), names(ret))
    ret[to_set] <- values[to_set]
  }
  ret
}

Plant <- function(T) {
  type <- c(T)
  valid <- list("Plant<FFW16>"="FFW16")
  constructors <- list("Plant<FFW16>"=`Plant<FFW16>`)
  constructors[[check_type(type, valid)]]
}
.R6_Plant <- R6::R6Class("Plant")



`Plant<FFW16>` <- function(s) {
  Plant___FFW16__ctor(s)
}
.R6_Plant___FFW16 <-
  R6::R6Class(
    "Plant<FFW16>",
    inherit=.R6_Plant,
    portable=TRUE,
    public=list(
      .ptr=NULL,
      initialize = function(ptr) {
        self$.ptr <- ptr
      },
      area_leaf_above = function(h) {
        Plant___FFW16__area_leaf_above(self, h)
      },
      compute_vars_phys = function(environment) {
        Plant___FFW16__compute_vars_phys(self, environment)
      },
      germination_probability = function(environment) {
        Plant___FFW16__germination_probability(self, environment)
      },
      reset_mortality = function() {
        Plant___FFW16__reset_mortality(self)
      }),
    active=list(
      height = function(value) {
        if (missing(value)) {
          Plant___FFW16__height__get(self)
        } else {
          Plant___FFW16__height__set(self, value)
        }
      },
      mortality = function(value) {
        if (missing(value)) {
          Plant___FFW16__mortality__get(self)
        } else {
          Plant___FFW16__mortality__set(self, value)
        }
      },
      fecundity = function(value) {
        if (missing(value)) {
          Plant___FFW16__fecundity__get(self)
        } else {
          Plant___FFW16__fecundity__set(self, value)
        }
      },
      strategy = function(value) {
        if (missing(value)) {
          Plant___FFW16__strategy__get(self)
        } else {
          stop("Plant<FFW16>$strategy is read-only")
        }
      },
      internals = function(value) {
        if (missing(value)) {
          Plant___FFW16__internals__get(self)
        } else {
          stop("Plant<FFW16>$internals is read-only")
        }
      },
      ode_size = function(value) {
        if (missing(value)) {
          Plant___FFW16__ode_size__get(self)
        } else {
          stop("Plant<FFW16>$ode_size is read-only")
        }
      },
      ode_state = function(value) {
        if (missing(value)) {
          Plant___FFW16__ode_state__get(self)
        } else {
          Plant___FFW16__ode_state__set(self, value)
        }
      },
      ode_rates = function(value) {
        if (missing(value)) {
          Plant___FFW16__ode_rates__get(self)
        } else {
          stop("Plant<FFW16>$ode_rates is read-only")
        }
      },
      ode_names = function(value) {
        if (missing(value)) {
          Plant___FFW16__ode_names__get(self)
        } else {
          stop("Plant<FFW16>$ode_names is read-only")
        }
      },
      mortality_probability = function(value) {
        if (missing(value)) {
          Plant___FFW16__mortality_probability__get(self)
        } else {
          stop("Plant<FFW16>$mortality_probability is read-only")
        }
      }))


`PlantRunner` <- function(plant, environment) {
  PlantRunner__ctor(plant, environment)
}
.R6_PlantRunner <-
  R6::R6Class(
    "PlantRunner",
    inherit=,
    portable=TRUE,
    public=list(
      .ptr=NULL,
      initialize = function(ptr) {
        self$.ptr <- ptr
      }),
    active=list(
      plant = function(value) {
        if (missing(value)) {
          PlantRunner__plant__get(self)
        } else {
          PlantRunner__plant__set(self, value)
        }
      }))

##' Strategy parameters that tune various aspects of the biological model.
##' @title Strategy parameters
##' @param ...,values Values to initialise the struct with (either as
##' variadic arguments, or as a list, but not both).
##' @export
`FFW16_Strategy` <- function(..., values=list(...)) {
  ret <- FFW16_Strategy__ctor()
  if (length(values) > 0L) {
    if (is.null(names(values)) || any(names(values) == "")) {
      stop("All values must be named")
    }
    if (length(err <- setdiff(names(values), names(ret))) > 0L) {
      stop(sprintf("Unknown fields: %s", paste(err, collapse=", ")))
    }
    to_set <- intersect(names(values), names(ret))
    ret[to_set] <- values[to_set]
  }
  ret
}

Parameters <- function(T) {
  type <- c(T)
  valid <- list("Parameters<FFW16>"="FFW16")
  constructors <- list("Parameters<FFW16>"=`Parameters<FFW16>`)
  constructors[[check_type(type, valid)]]
}


`Parameters<FFW16>` <- function(..., values=list(...)) {
  ret <- Parameters___FFW16__ctor()
  if (length(values) > 0L) {
    if (is.null(names(values)) || any(names(values) == "")) {
      stop("All values must be named")
    }
    if (length(err <- setdiff(names(values), names(ret))) > 0L) {
      stop(sprintf("Unknown fields: %s", paste(err, collapse=", ")))
    }
    to_set <- intersect(names(values), names(ret))
    ret[to_set] <- values[to_set]
  }
  Parameters___FFW16__vdor(ret)
}

##' Plant object
##' @param strategy A \code{FFW16_Strategy} object
##' @export
`FFW16_PlantPlus` <- function(strategy=FFW16_Strategy()) {
  FFW16_PlantPlus__ctor(strategy)
}
.R6_FFW16_PlantPlus <-
  R6::R6Class(
    "FFW16_PlantPlus",
    inherit=,
    portable=TRUE,
    public=list(
      .ptr=NULL,
      initialize = function(ptr) {
        self$.ptr <- ptr
      },
      area_leaf_above = function(h) {
        FFW16_PlantPlus__area_leaf_above(self, h)
      },
      compute_vars_phys = function(environment) {
        FFW16_PlantPlus__compute_vars_phys(self, environment)
      },
      compute_vars_growth = function() {
        FFW16_PlantPlus__compute_vars_growth(self)
      },
      germination_probability = function(environment) {
        FFW16_PlantPlus__germination_probability(self, environment)
      }),
    active=list(
      height = function(value) {
        if (missing(value)) {
          FFW16_PlantPlus__height__get(self)
        } else {
          FFW16_PlantPlus__height__set(self, value)
        }
      },
      mortality = function(value) {
        if (missing(value)) {
          FFW16_PlantPlus__mortality__get(self)
        } else {
          FFW16_PlantPlus__mortality__set(self, value)
        }
      },
      fecundity = function(value) {
        if (missing(value)) {
          FFW16_PlantPlus__fecundity__get(self)
        } else {
          FFW16_PlantPlus__fecundity__set(self, value)
        }
      },
      area_heartwood = function(value) {
        if (missing(value)) {
          FFW16_PlantPlus__area_heartwood__get(self)
        } else {
          FFW16_PlantPlus__area_heartwood__set(self, value)
        }
      },
      mass_heartwood = function(value) {
        if (missing(value)) {
          FFW16_PlantPlus__mass_heartwood__get(self)
        } else {
          FFW16_PlantPlus__mass_heartwood__set(self, value)
        }
      },
      area_leaf = function(value) {
        if (missing(value)) {
          FFW16_PlantPlus__area_leaf__get(self)
        } else {
          stop("FFW16_PlantPlus$area_leaf is read-only")
        }
      },
      strategy = function(value) {
        if (missing(value)) {
          FFW16_PlantPlus__strategy__get(self)
        } else {
          stop("FFW16_PlantPlus$strategy is read-only")
        }
      },
      internals = function(value) {
        if (missing(value)) {
          FFW16_PlantPlus__internals__get(self)
        } else {
          stop("FFW16_PlantPlus$internals is read-only")
        }
      },
      ode_size = function(value) {
        if (missing(value)) {
          FFW16_PlantPlus__ode_size__get(self)
        } else {
          stop("FFW16_PlantPlus$ode_size is read-only")
        }
      },
      ode_state = function(value) {
        if (missing(value)) {
          FFW16_PlantPlus__ode_state__get(self)
        } else {
          FFW16_PlantPlus__ode_state__set(self, value)
        }
      },
      ode_rates = function(value) {
        if (missing(value)) {
          FFW16_PlantPlus__ode_rates__get(self)
        } else {
          stop("FFW16_PlantPlus$ode_rates is read-only")
        }
      },
      ode_names = function(value) {
        if (missing(value)) {
          FFW16_PlantPlus__ode_names__get(self)
        } else {
          stop("FFW16_PlantPlus$ode_names is read-only")
        }
      }))

`FFW16_PlantPlus_internals` <- function(..., values=list(...)) {
  ret <- FFW16_PlantPlus_internals__ctor()
  if (length(values) > 0L) {
    if (is.null(names(values)) || any(names(values) == "")) {
      stop("All values must be named")
    }
    if (length(err <- setdiff(names(values), names(ret))) > 0L) {
      stop(sprintf("Unknown fields: %s", paste(err, collapse=", ")))
    }
    to_set <- intersect(names(values), names(ret))
    ret[to_set] <- values[to_set]
  }
  ret
}

Cohort <- function(T) {
  type <- c(T)
  valid <- list("Cohort<FFW16>"="FFW16")
  constructors <- list("Cohort<FFW16>"=`Cohort<FFW16>`)
  constructors[[check_type(type, valid)]]
}
.R6_Cohort <- R6::R6Class("Cohort")



`Cohort<FFW16>` <- function(strategy) {
  Cohort___FFW16__ctor(strategy)
}
.R6_Cohort___FFW16 <-
  R6::R6Class(
    "Cohort<FFW16>",
    inherit=.R6_Cohort,
    portable=TRUE,
    public=list(
      .ptr=NULL,
      initialize = function(ptr) {
        self$.ptr <- ptr
      },
      area_leaf_above = function(height) {
        Cohort___FFW16__area_leaf_above(self, height)
      },
      growth_rate_gradient = function(environment) {
        Cohort___FFW16__growth_rate_gradient(self, environment)
      },
      compute_vars_phys = function(environment) {
        Cohort___FFW16__compute_vars_phys(self, environment)
      },
      compute_initial_conditions = function(environment) {
        Cohort___FFW16__compute_initial_conditions(self, environment)
      }),
    active=list(
      plant = function(value) {
        if (missing(value)) {
          Cohort___FFW16__plant__get(self)
        } else {
          stop("Cohort<FFW16>$plant is read-only")
        }
      },
      height = function(value) {
        if (missing(value)) {
          Cohort___FFW16__height__get(self)
        } else {
          stop("Cohort<FFW16>$height is read-only")
        }
      },
      log_density = function(value) {
        if (missing(value)) {
          Cohort___FFW16__log_density__get(self)
        } else {
          stop("Cohort<FFW16>$log_density is read-only")
        }
      },
      area_leaf = function(value) {
        if (missing(value)) {
          Cohort___FFW16__area_leaf__get(self)
        } else {
          stop("Cohort<FFW16>$area_leaf is read-only")
        }
      },
      fecundity = function(value) {
        if (missing(value)) {
          Cohort___FFW16__fecundity__get(self)
        } else {
          stop("Cohort<FFW16>$fecundity is read-only")
        }
      },
      ode_size = function(value) {
        if (missing(value)) {
          Cohort___FFW16__ode_size__get(self)
        } else {
          stop("Cohort<FFW16>$ode_size is read-only")
        }
      },
      ode_state = function(value) {
        if (missing(value)) {
          Cohort___FFW16__ode_state__get(self)
        } else {
          Cohort___FFW16__ode_state__set(self, value)
        }
      },
      ode_rates = function(value) {
        if (missing(value)) {
          Cohort___FFW16__ode_rates__get(self)
        } else {
          stop("Cohort<FFW16>$ode_rates is read-only")
        }
      },
      ode_names = function(value) {
        if (missing(value)) {
          Cohort___FFW16__ode_names__get(self)
        } else {
          stop("Cohort<FFW16>$ode_names is read-only")
        }
      }))

Species <- function(T) {
  type <- c(T)
  valid <- list("Species<FFW16>"="FFW16")
  constructors <- list("Species<FFW16>"=`Species<FFW16>`)
  constructors[[check_type(type, valid)]]
}
.R6_Species <- R6::R6Class("Species")



`Species<FFW16>` <- function(strategy) {
  Species___FFW16__ctor(strategy)
}
.R6_Species___FFW16 <-
  R6::R6Class(
    "Species<FFW16>",
    inherit=.R6_Species,
    portable=TRUE,
    public=list(
      .ptr=NULL,
      initialize = function(ptr) {
        self$.ptr <- ptr
      },
      clear = function() {
        Species___FFW16__clear(self)
      },
      compute_vars_phys = function(environment) {
        Species___FFW16__compute_vars_phys(self, environment)
      },
      area_leaf_above = function(height) {
        Species___FFW16__area_leaf_above(self, height)
      },
      add_seed = function() {
        Species___FFW16__add_seed(self)
      },
      cohort_at = function(index) {
        Species___FFW16__cohort_at(self, index)
      },
      area_leafs_error = function(scal=1) {
        Species___FFW16__area_leafs_error(self, scal)
      }),
    active=list(
      size = function(value) {
        if (missing(value)) {
          Species___FFW16__size__get(self)
        } else {
          stop("Species<FFW16>$size is read-only")
        }
      },
      seed = function(value) {
        if (missing(value)) {
          Species___FFW16__seed__get(self)
        } else {
          stop("Species<FFW16>$seed is read-only")
        }
      },
      height_max = function(value) {
        if (missing(value)) {
          Species___FFW16__height_max__get(self)
        } else {
          stop("Species<FFW16>$height_max is read-only")
        }
      },
      heights = function(value) {
        if (missing(value)) {
          Species___FFW16__heights__get(self)
        } else {
          Species___FFW16__heights__set(self, value)
        }
      },
      log_densities = function(value) {
        if (missing(value)) {
          Species___FFW16__log_densities__get(self)
        } else {
          stop("Species<FFW16>$log_densities is read-only")
        }
      },
      cohorts = function(value) {
        if (missing(value)) {
          Species___FFW16__cohorts__get(self)
        } else {
          stop("Species<FFW16>$cohorts is read-only")
        }
      },
      seeds = function(value) {
        if (missing(value)) {
          Species___FFW16__seeds__get(self)
        } else {
          stop("Species<FFW16>$seeds is read-only")
        }
      },
      area_leafs = function(value) {
        if (missing(value)) {
          Species___FFW16__area_leafs__get(self)
        } else {
          stop("Species<FFW16>$area_leafs is read-only")
        }
      },
      ode_size = function(value) {
        if (missing(value)) {
          Species___FFW16__ode_size__get(self)
        } else {
          stop("Species<FFW16>$ode_size is read-only")
        }
      },
      ode_state = function(value) {
        if (missing(value)) {
          Species___FFW16__ode_state__get(self)
        } else {
          Species___FFW16__ode_state__set(self, value)
        }
      },
      ode_rates = function(value) {
        if (missing(value)) {
          Species___FFW16__ode_rates__get(self)
        } else {
          stop("Species<FFW16>$ode_rates is read-only")
        }
      }))

Patch <- function(T) {
  type <- c(T)
  valid <- list("Patch<FFW16>"="FFW16")
  constructors <- list("Patch<FFW16>"=`Patch<FFW16>`)
  constructors[[check_type(type, valid)]]
}
.R6_Patch <- R6::R6Class("Patch")



`Patch<FFW16>` <- function(parameters) {
  Patch___FFW16__ctor(parameters)
}
.R6_Patch___FFW16 <-
  R6::R6Class(
    "Patch<FFW16>",
    inherit=.R6_Patch,
    portable=TRUE,
    public=list(
      .ptr=NULL,
      initialize = function(ptr) {
        self$.ptr <- ptr
      },
      area_leaf_above = function(height) {
        Patch___FFW16__area_leaf_above(self, height)
      },
      canopy_openness = function(height) {
        Patch___FFW16__canopy_openness(self, height)
      },
      add_seed = function(species_index) {
        Patch___FFW16__add_seed(self, species_index)
      },
      compute_light_environment = function() {
        Patch___FFW16__compute_light_environment(self)
      },
      compute_vars_phys = function() {
        Patch___FFW16__compute_vars_phys(self)
      },
      reset = function() {
        Patch___FFW16__reset(self)
      },
      set_ode_state = function(values, time) {
        Patch___FFW16__set_ode_state(self, values, time)
      },
      derivs = function(y, time) {
        Patch___FFW16__derivs(self, y, time)
      },
      set_state = function(time, state, n) {
        Patch___FFW16__set_state(self, time, state, n)
      }),
    active=list(
      time = function(value) {
        if (missing(value)) {
          Patch___FFW16__time__get(self)
        } else {
          stop("Patch<FFW16>$time is read-only")
        }
      },
      size = function(value) {
        if (missing(value)) {
          Patch___FFW16__size__get(self)
        } else {
          stop("Patch<FFW16>$size is read-only")
        }
      },
      height_max = function(value) {
        if (missing(value)) {
          Patch___FFW16__height_max__get(self)
        } else {
          stop("Patch<FFW16>$height_max is read-only")
        }
      },
      parameters = function(value) {
        if (missing(value)) {
          Patch___FFW16__parameters__get(self)
        } else {
          stop("Patch<FFW16>$parameters is read-only")
        }
      },
      environment = function(value) {
        if (missing(value)) {
          Patch___FFW16__environment__get(self)
        } else {
          stop("Patch<FFW16>$environment is read-only")
        }
      },
      species = function(value) {
        if (missing(value)) {
          Patch___FFW16__species__get(self)
        } else {
          stop("Patch<FFW16>$species is read-only")
        }
      },
      ode_size = function(value) {
        if (missing(value)) {
          Patch___FFW16__ode_size__get(self)
        } else {
          stop("Patch<FFW16>$ode_size is read-only")
        }
      },
      ode_time = function(value) {
        if (missing(value)) {
          Patch___FFW16__ode_time__get(self)
        } else {
          stop("Patch<FFW16>$ode_time is read-only")
        }
      },
      ode_state = function(value) {
        if (missing(value)) {
          Patch___FFW16__ode_state__get(self)
        } else {
          stop("Patch<FFW16>$ode_state is read-only")
        }
      },
      ode_rates = function(value) {
        if (missing(value)) {
          Patch___FFW16__ode_rates__get(self)
        } else {
          stop("Patch<FFW16>$ode_rates is read-only")
        }
      }))

EBT <- function(T) {
  type <- c(T)
  valid <- list("EBT<FFW16>"="FFW16")
  constructors <- list("EBT<FFW16>"=`EBT<FFW16>`)
  constructors[[check_type(type, valid)]]
}
.R6_EBT <- R6::R6Class("EBT")



`EBT<FFW16>` <- function(parameters) {
  EBT___FFW16__ctor(parameters)
}
.R6_EBT___FFW16 <-
  R6::R6Class(
    "EBT<FFW16>",
    inherit=.R6_EBT,
    portable=TRUE,
    public=list(
      .ptr=NULL,
      initialize = function(ptr) {
        self$.ptr <- ptr
      },
      run = function() {
        EBT___FFW16__run(self)
      },
      run_next = function() {
        EBT___FFW16__run_next(self)
      },
      reset = function() {
        EBT___FFW16__reset(self)
      },
      seed_rain = function(species_index) {
        EBT___FFW16__seed_rain(self, species_index)
      },
      seed_rain_cohort = function(species_index) {
        EBT___FFW16__seed_rain_cohort(self, species_index)
      },
      area_leaf_error = function(species_index) {
        EBT___FFW16__area_leaf_error(self, species_index)
      },
      set_cohort_schedule_times = function(times) {
        EBT___FFW16__set_cohort_schedule_times(self, times)
      }),
    active=list(
      complete = function(value) {
        if (missing(value)) {
          EBT___FFW16__complete__get(self)
        } else {
          stop("EBT<FFW16>$complete is read-only")
        }
      },
      time = function(value) {
        if (missing(value)) {
          EBT___FFW16__time__get(self)
        } else {
          stop("EBT<FFW16>$time is read-only")
        }
      },
      seed_rains = function(value) {
        if (missing(value)) {
          EBT___FFW16__seed_rains__get(self)
        } else {
          stop("EBT<FFW16>$seed_rains is read-only")
        }
      },
      parameters = function(value) {
        if (missing(value)) {
          EBT___FFW16__parameters__get(self)
        } else {
          stop("EBT<FFW16>$parameters is read-only")
        }
      },
      patch = function(value) {
        if (missing(value)) {
          EBT___FFW16__patch__get(self)
        } else {
          stop("EBT<FFW16>$patch is read-only")
        }
      },
      cohort_schedule = function(value) {
        if (missing(value)) {
          EBT___FFW16__cohort_schedule__get(self)
        } else {
          EBT___FFW16__cohort_schedule__set(self, value)
        }
      },
      ode_times = function(value) {
        if (missing(value)) {
          EBT___FFW16__ode_times__get(self)
        } else {
          stop("EBT<FFW16>$ode_times is read-only")
        }
      },
      state = function(value) {
        if (missing(value)) {
          EBT___FFW16__state__get(self)
        } else {
          stop("EBT<FFW16>$state is read-only")
        }
      },
      use_ode_times = function(value) {
        if (missing(value)) {
          EBT___FFW16__use_ode_times__get(self)
        } else {
          EBT___FFW16__use_ode_times__set(self, value)
        }
      },
      seed_rain_error = function(value) {
        if (missing(value)) {
          EBT___FFW16__seed_rain_error__get(self)
        } else {
          stop("EBT<FFW16>$seed_rain_error is read-only")
        }
      }))

StochasticSpecies <- function(T) {
  type <- c(T)
  valid <- list("StochasticSpecies<FFW16>"="FFW16")
  constructors <- list("StochasticSpecies<FFW16>"=`StochasticSpecies<FFW16>`)
  constructors[[check_type(type, valid)]]
}
.R6_StochasticSpecies <- R6::R6Class("StochasticSpecies")



`StochasticSpecies<FFW16>` <- function(strategy) {
  StochasticSpecies___FFW16__ctor(strategy)
}
.R6_StochasticSpecies___FFW16 <-
  R6::R6Class(
    "StochasticSpecies<FFW16>",
    inherit=.R6_StochasticSpecies,
    portable=TRUE,
    public=list(
      .ptr=NULL,
      initialize = function(ptr) {
        self$.ptr <- ptr
      },
      clear = function() {
        StochasticSpecies___FFW16__clear(self)
      },
      compute_vars_phys = function(environment) {
        StochasticSpecies___FFW16__compute_vars_phys(self, environment)
      },
      area_leaf_above = function(height) {
        StochasticSpecies___FFW16__area_leaf_above(self, height)
      },
      add_seed = function() {
        StochasticSpecies___FFW16__add_seed(self)
      },
      plant_at = function(index) {
        StochasticSpecies___FFW16__plant_at(self, index)
      },
      deaths = function() {
        StochasticSpecies___FFW16__deaths(self)
      },
      germination_probability = function(environment) {
        StochasticSpecies___FFW16__germination_probability(self, environment)
      }),
    active=list(
      size = function(value) {
        if (missing(value)) {
          StochasticSpecies___FFW16__size__get(self)
        } else {
          stop("StochasticSpecies<FFW16>$size is read-only")
        }
      },
      size_plants = function(value) {
        if (missing(value)) {
          StochasticSpecies___FFW16__size_plants__get(self)
        } else {
          stop("StochasticSpecies<FFW16>$size_plants is read-only")
        }
      },
      seed = function(value) {
        if (missing(value)) {
          StochasticSpecies___FFW16__seed__get(self)
        } else {
          stop("StochasticSpecies<FFW16>$seed is read-only")
        }
      },
      height_max = function(value) {
        if (missing(value)) {
          StochasticSpecies___FFW16__height_max__get(self)
        } else {
          stop("StochasticSpecies<FFW16>$height_max is read-only")
        }
      },
      heights = function(value) {
        if (missing(value)) {
          StochasticSpecies___FFW16__heights__get(self)
        } else {
          StochasticSpecies___FFW16__heights__set(self, value)
        }
      },
      plants = function(value) {
        if (missing(value)) {
          StochasticSpecies___FFW16__plants__get(self)
        } else {
          stop("StochasticSpecies<FFW16>$plants is read-only")
        }
      },
      is_alive = function(value) {
        if (missing(value)) {
          StochasticSpecies___FFW16__is_alive__get(self)
        } else {
          stop("StochasticSpecies<FFW16>$is_alive is read-only")
        }
      },
      seeds = function(value) {
        if (missing(value)) {
          StochasticSpecies___FFW16__seeds__get(self)
        } else {
          stop("StochasticSpecies<FFW16>$seeds is read-only")
        }
      },
      ode_size = function(value) {
        if (missing(value)) {
          StochasticSpecies___FFW16__ode_size__get(self)
        } else {
          stop("StochasticSpecies<FFW16>$ode_size is read-only")
        }
      },
      ode_state = function(value) {
        if (missing(value)) {
          StochasticSpecies___FFW16__ode_state__get(self)
        } else {
          StochasticSpecies___FFW16__ode_state__set(self, value)
        }
      },
      ode_rates = function(value) {
        if (missing(value)) {
          StochasticSpecies___FFW16__ode_rates__get(self)
        } else {
          stop("StochasticSpecies<FFW16>$ode_rates is read-only")
        }
      }))

StochasticPatch <- function(T) {
  type <- c(T)
  valid <- list("StochasticPatch<FFW16>"="FFW16")
  constructors <- list("StochasticPatch<FFW16>"=`StochasticPatch<FFW16>`)
  constructors[[check_type(type, valid)]]
}
.R6_StochasticPatch <- R6::R6Class("StochasticPatch")



`StochasticPatch<FFW16>` <- function(parameters) {
  StochasticPatch___FFW16__ctor(parameters)
}
.R6_StochasticPatch___FFW16 <-
  R6::R6Class(
    "StochasticPatch<FFW16>",
    inherit=.R6_StochasticPatch,
    portable=TRUE,
    public=list(
      .ptr=NULL,
      initialize = function(ptr) {
        self$.ptr <- ptr
      },
      area_leaf_above = function(height) {
        StochasticPatch___FFW16__area_leaf_above(self, height)
      },
      canopy_openness = function(height) {
        StochasticPatch___FFW16__canopy_openness(self, height)
      },
      add_seed = function(species_index) {
        StochasticPatch___FFW16__add_seed(self, species_index)
      },
      add_seedling = function(species_index) {
        StochasticPatch___FFW16__add_seedling(self, species_index)
      },
      compute_light_environment = function() {
        StochasticPatch___FFW16__compute_light_environment(self)
      },
      compute_vars_phys = function() {
        StochasticPatch___FFW16__compute_vars_phys(self)
      },
      reset = function() {
        StochasticPatch___FFW16__reset(self)
      },
      set_ode_state = function(values, time) {
        StochasticPatch___FFW16__set_ode_state(self, values, time)
      },
      derivs = function(y, time) {
        StochasticPatch___FFW16__derivs(self, y, time)
      },
      set_state = function(time, state, n) {
        StochasticPatch___FFW16__set_state(self, time, state, n)
      },
      deaths = function() {
        StochasticPatch___FFW16__deaths(self)
      }),
    active=list(
      time = function(value) {
        if (missing(value)) {
          StochasticPatch___FFW16__time__get(self)
        } else {
          stop("StochasticPatch<FFW16>$time is read-only")
        }
      },
      size = function(value) {
        if (missing(value)) {
          StochasticPatch___FFW16__size__get(self)
        } else {
          stop("StochasticPatch<FFW16>$size is read-only")
        }
      },
      height_max = function(value) {
        if (missing(value)) {
          StochasticPatch___FFW16__height_max__get(self)
        } else {
          stop("StochasticPatch<FFW16>$height_max is read-only")
        }
      },
      parameters = function(value) {
        if (missing(value)) {
          StochasticPatch___FFW16__parameters__get(self)
        } else {
          stop("StochasticPatch<FFW16>$parameters is read-only")
        }
      },
      environment = function(value) {
        if (missing(value)) {
          StochasticPatch___FFW16__environment__get(self)
        } else {
          stop("StochasticPatch<FFW16>$environment is read-only")
        }
      },
      species = function(value) {
        if (missing(value)) {
          StochasticPatch___FFW16__species__get(self)
        } else {
          stop("StochasticPatch<FFW16>$species is read-only")
        }
      },
      ode_size = function(value) {
        if (missing(value)) {
          StochasticPatch___FFW16__ode_size__get(self)
        } else {
          stop("StochasticPatch<FFW16>$ode_size is read-only")
        }
      },
      ode_time = function(value) {
        if (missing(value)) {
          StochasticPatch___FFW16__ode_time__get(self)
        } else {
          stop("StochasticPatch<FFW16>$ode_time is read-only")
        }
      },
      ode_state = function(value) {
        if (missing(value)) {
          StochasticPatch___FFW16__ode_state__get(self)
        } else {
          stop("StochasticPatch<FFW16>$ode_state is read-only")
        }
      },
      ode_rates = function(value) {
        if (missing(value)) {
          StochasticPatch___FFW16__ode_rates__get(self)
        } else {
          stop("StochasticPatch<FFW16>$ode_rates is read-only")
        }
      }))

StochasticPatchRunner <- function(T) {
  type <- c(T)
  valid <- list("StochasticPatchRunner<FFW16>"="FFW16")
  constructors <- list("StochasticPatchRunner<FFW16>"=`StochasticPatchRunner<FFW16>`)
  constructors[[check_type(type, valid)]]
}
.R6_StochasticPatchRunner <- R6::R6Class("StochasticPatchRunner")



`StochasticPatchRunner<FFW16>` <- function(parameters) {
  StochasticPatchRunner___FFW16__ctor(parameters)
}
.R6_StochasticPatchRunner___FFW16 <-
  R6::R6Class(
    "StochasticPatchRunner<FFW16>",
    inherit=.R6_StochasticPatchRunner,
    portable=TRUE,
    public=list(
      .ptr=NULL,
      initialize = function(ptr) {
        self$.ptr <- ptr
      },
      run = function() {
        StochasticPatchRunner___FFW16__run(self)
      },
      run_next = function() {
        StochasticPatchRunner___FFW16__run_next(self)
      },
      reset = function() {
        StochasticPatchRunner___FFW16__reset(self)
      },
      set_schedule_times = function(times) {
        StochasticPatchRunner___FFW16__set_schedule_times(self, times)
      }),
    active=list(
      complete = function(value) {
        if (missing(value)) {
          StochasticPatchRunner___FFW16__complete__get(self)
        } else {
          stop("StochasticPatchRunner<FFW16>$complete is read-only")
        }
      },
      time = function(value) {
        if (missing(value)) {
          StochasticPatchRunner___FFW16__time__get(self)
        } else {
          stop("StochasticPatchRunner<FFW16>$time is read-only")
        }
      },
      parameters = function(value) {
        if (missing(value)) {
          StochasticPatchRunner___FFW16__parameters__get(self)
        } else {
          stop("StochasticPatchRunner<FFW16>$parameters is read-only")
        }
      },
      patch = function(value) {
        if (missing(value)) {
          StochasticPatchRunner___FFW16__patch__get(self)
        } else {
          stop("StochasticPatchRunner<FFW16>$patch is read-only")
        }
      },
      schedule = function(value) {
        if (missing(value)) {
          StochasticPatchRunner___FFW16__schedule__get(self)
        } else {
          StochasticPatchRunner___FFW16__schedule__set(self, value)
        }
      },
      state = function(value) {
        if (missing(value)) {
          StochasticPatchRunner___FFW16__state__get(self)
        } else {
          stop("StochasticPatchRunner<FFW16>$state is read-only")
        }
      }))
