## Generated by RcppR6 (0.1): do not edit by hand

## @importFrom Rcpp evalCpp
##' @importFrom R6 R6Class
##' @useDynLib tree2
NULL


`Lorenz` <- function(sigma, R, b) {
  Lorenz__ctor(sigma, R, b)
}
.R6_Lorenz <-
  R6::R6Class("Lorenz",
              portable=TRUE,
              inherit=NULL,
              public=list(
                .ptr=NULL,
                initialize = function(ptr) {
                  self$.ptr <- ptr
                }),
              active=list(
                size = function(value) {
                  if (missing(value)) {
                    Lorenz__size__get(self)
                  } else {
                    stop("Lorenz$size is read-only")
                  }
                },
                ode_values = function(value) {
                  if (missing(value)) {
                    Lorenz__ode_values__get(self)
                  } else {
                    Lorenz__ode_values__set(self, value)
                  }
                },
                ode_rates = function(value) {
                  if (missing(value)) {
                    Lorenz__ode_rates__get(self)
                  } else {
                    stop("Lorenz$ode_rates is read-only")
                  }
                },
                pars = function(value) {
                  if (missing(value)) {
                    Lorenz__pars__get(self)
                  } else {
                    stop("Lorenz$pars is read-only")
                  }
                }))


OdeRunner <- function(T) {
  type <- c(T)
  valid <- list("OdeRunner<Lorenz>"="Lorenz")
  constructors <- list("OdeRunner<Lorenz>"=`OdeRunner<Lorenz>`)
  constructors[[check_type(type, valid)]]
}
.R6_OdeRunner <- R6::R6Class("OdeRunner")


`OdeRunner<Lorenz>` <- function(obj) {
  OdeRunner___Lorenz__ctor(obj)
}
.R6_OdeRunner___Lorenz <-
  R6::R6Class("OdeRunner<Lorenz>",
              portable=TRUE,
              inherit=.R6_OdeRunner,
              public=list(
                .ptr=NULL,
                initialize = function(ptr) {
                  self$.ptr <- ptr
                }),
              active=list(
                obj = function(value) {
                  if (missing(value)) {
                    OdeRunner___Lorenz__obj__get(self)
                  } else {
                    OdeRunner___Lorenz__obj__set(self, value)
                  }
                }))

## This section of code is only included where templated classes are
## included.  Don't rely on the approach taken here, as it may change
## soon.
check_type <- function(type, valid) {
  i <- match(list(type), valid, nomatch=NA)
  if (is.na(i)) {
    choices <- paste(sprintf("\t%s", sapply(valid, paste, collapse=", ")),
                     collapse="\n")
    stop(sprintf("Invalid type '%s'; expected one of:\n%s",
                 paste(type, collapse=", "), choices))
  }
  names(valid)[[i]]
}
