## Generated by RcppR6 (0.1): do not edit by hand

##' @importFrom Rcpp evalCpp
##' @importFrom R6 R6Class
##' @useDynLib tree2
NULL


`Lorenz` <- function(sigma, R, b) {
  Lorenz__ctor(sigma, R, b)
}
.R6_Lorenz <-
  R6::R6Class("Lorenz",
              portable=TRUE,
              inherit=NULL,
              public=list(
                .ptr=NULL,
                initialize = function(ptr) {
                  self$.ptr <- ptr
                }),
              active=list(
                size = function(value) {
                  if (missing(value)) {
                    Lorenz__size__get(self)
                  } else {
                    stop("Lorenz$size is read-only")
                  }
                },
                ode_values = function(value) {
                  if (missing(value)) {
                    Lorenz__ode_values__get(self)
                  } else {
                    Lorenz__ode_values__set(self, value)
                  }
                },
                ode_rates = function(value) {
                  if (missing(value)) {
                    Lorenz__ode_rates__get(self)
                  } else {
                    stop("Lorenz$ode_rates is read-only")
                  }
                },
                pars = function(value) {
                  if (missing(value)) {
                    Lorenz__pars__get(self)
                  } else {
                    stop("Lorenz$pars is read-only")
                  }
                }))


OdeSystem <- function(T) {
  type <- c(T)
  valid <- list("OdeSystem<Lorenz>"="Lorenz")
  constructors <- list("OdeSystem<Lorenz>"=`OdeSystem<Lorenz>`)
  constructors[[check_type(type, valid)]]
}
.R6_OdeSystem <- R6::R6Class("OdeSystem")


`OdeSystem<Lorenz>` <- function(obj, abs_tol=1e-8, rel_tol=1e-8) {
  OdeSystem___Lorenz__ctor(obj, abs_tol, rel_tol)
}
.R6_OdeSystem___Lorenz <-
  R6::R6Class("OdeSystem<Lorenz>",
              portable=TRUE,
              inherit=.R6_OdeSystem,
              public=list(
                .ptr=NULL,
                initialize = function(ptr) {
                  self$.ptr <- ptr
                },
                do_step = function(dt) {
                  OdeSystem___Lorenz__do_step(self, dt)
                },
                try_step = function(dt) {
                  OdeSystem___Lorenz__try_step(self, dt)
                },
                advance = function(t, dt) {
                  OdeSystem___Lorenz__advance(self, t, dt)
                },
                advance_save = function(t, dt) {
                  OdeSystem___Lorenz__advance_save(self, t, dt)
                }),
              active=list(
                obj = function(value) {
                  if (missing(value)) {
                    OdeSystem___Lorenz__obj__get(self)
                  } else {
                    stop("OdeSystem<Lorenz>$obj is read-only")
                  }
                },
                t = function(value) {
                  if (missing(value)) {
                    OdeSystem___Lorenz__t__get(self)
                  } else {
                    OdeSystem___Lorenz__t__set(self, value)
                  }
                },
                y = function(value) {
                  if (missing(value)) {
                    OdeSystem___Lorenz__y__get(self)
                  } else {
                    OdeSystem___Lorenz__y__set(self, value)
                  }
                }))


`CohortScheduleEvent` <- function(introduction, species_index) {
  CohortScheduleEvent__ctor(introduction, species_index)
}
.R6_CohortScheduleEvent <-
  R6::R6Class("CohortScheduleEvent",
              portable=TRUE,
              inherit=NULL,
              public=list(
                .ptr=NULL,
                initialize = function(ptr) {
                  self$.ptr <- ptr
                }),
              active=list(
                species_index = function(value) {
                  if (missing(value)) {
                    CohortScheduleEvent__species_index__get(self)
                  } else {
                    CohortScheduleEvent__species_index__set(self, value)
                  }
                },
                times = function(value) {
                  if (missing(value)) {
                    CohortScheduleEvent__times__get(self)
                  } else {
                    stop("CohortScheduleEvent$times is read-only")
                  }
                },
                time_introduction = function(value) {
                  if (missing(value)) {
                    CohortScheduleEvent__time_introduction__get(self)
                  } else {
                    stop("CohortScheduleEvent$time_introduction is read-only")
                  }
                },
                time_end = function(value) {
                  if (missing(value)) {
                    CohortScheduleEvent__time_end__get(self)
                  } else {
                    stop("CohortScheduleEvent$time_end is read-only")
                  }
                },
                species_index_raw = function(value) {
                  if (missing(value)) {
                    CohortScheduleEvent__species_index_raw__get(self)
                  } else {
                    stop("CohortScheduleEvent$species_index_raw is read-only")
                  }
                }))

##' Schedule of cohort introduction times
##' @param n_species number of species
##' @export
`CohortSchedule` <- function(n_species) {
  CohortSchedule__ctor(n_species)
}
.R6_CohortSchedule <-
  R6::R6Class("CohortSchedule",
              portable=TRUE,
              inherit=NULL,
              public=list(
                .ptr=NULL,
                initialize = function(ptr) {
                  self$.ptr <- ptr
                },
                expand = function(n_extra, times) {
                  CohortSchedule__expand(self, n_extra, times)
                },
                clear_times = function(species_index) {
                  CohortSchedule__clear_times(self, species_index)
                },
                clear_ode_times = function() {
                  CohortSchedule__clear_ode_times(self)
                },
                set_times = function(times, species_index) {
                  CohortSchedule__set_times(self, times, species_index)
                },
                times = function(species_index) {
                  CohortSchedule__times(self, species_index)
                },
                reset = function() {
                  CohortSchedule__reset(self)
                },
                pop = function() {
                  CohortSchedule__pop(self)
                },
                copy = function() {
                  CohortSchedule__copy(self)
                }),
              active=list(
                size = function(value) {
                  if (missing(value)) {
                    CohortSchedule__size__get(self)
                  } else {
                    stop("CohortSchedule$size is read-only")
                  }
                },
                n_species = function(value) {
                  if (missing(value)) {
                    CohortSchedule__n_species__get(self)
                  } else {
                    stop("CohortSchedule$n_species is read-only")
                  }
                },
                next_event = function(value) {
                  if (missing(value)) {
                    CohortSchedule__next_event__get(self)
                  } else {
                    stop("CohortSchedule$next_event is read-only")
                  }
                },
                remaining = function(value) {
                  if (missing(value)) {
                    CohortSchedule__remaining__get(self)
                  } else {
                    stop("CohortSchedule$remaining is read-only")
                  }
                },
                max_time = function(value) {
                  if (missing(value)) {
                    CohortSchedule__max_time__get(self)
                  } else {
                    CohortSchedule__max_time__set(self, value)
                  }
                },
                ode_times = function(value) {
                  if (missing(value)) {
                    CohortSchedule__ode_times__get(self)
                  } else {
                    CohortSchedule__ode_times__set(self, value)
                  }
                },
                use_ode_times = function(value) {
                  if (missing(value)) {
                    CohortSchedule__use_ode_times__get(self)
                  } else {
                    CohortSchedule__use_ode_times__set(self, value)
                  }
                },
                all_times = function(value) {
                  if (missing(value)) {
                    CohortSchedule__all_times__get(self)
                  } else {
                    CohortSchedule__all_times__set(self, value)
                  }
                }))

##' Disturbance control object
##' @param mean_interval Mean disturbance interval in years
##' @export
`Disturbance` <- function(mean_interval) {
  Disturbance__ctor(mean_interval)
}
.R6_Disturbance <-
  R6::R6Class("Disturbance",
              portable=TRUE,
              inherit=NULL,
              public=list(
                .ptr=NULL,
                initialize = function(ptr) {
                  self$.ptr <- ptr
                },
                density = function(time) {
                  Disturbance__density(self, time)
                },
                pr_survival = function(time) {
                  Disturbance__pr_survival(self, time)
                },
                pr_survival_conditional = function(time, time_start) {
                  Disturbance__pr_survival_conditional(self, time, time_start)
                },
                cdf = function(time) {
                  Disturbance__cdf(self, time)
                }),
              active=list(
                mean_interval = function(value) {
                  if (missing(value)) {
                    Disturbance__mean_interval__get(self)
                  } else {
                    stop("Disturbance$mean_interval is read-only")
                  }
                }))

##' Control parameters that tune various aspects of the numerical solvers.
##' @title Control parameters
##' @param ...,values Values to initialise the struct with (either as
##' variadic arguments, or as a list, but not both).
##' @export
Control <- function(..., values=list(...)) {
  ret <- Control__ctor()
  if (length(err <- setdiff(names(values), names(ret))) > 0L) {
    stop(sprintf("Unknown fields: %s", paste(err, collapse=", ")))
  }
  to_set <- intersect(names(values), names(ret))
  ret[to_set] <- values[to_set]
  ret
}

##' Strategy parameters that tune various aspects of the biological model.
##' @title Strategy parameters
##' @param ...,values Values to initialise the struct with (either as
##' variadic arguments, or as a list, but not both).
##' @export
Strategy <- function(..., values=list(...)) {
  ret <- Strategy__ctor()
  if (length(err <- setdiff(names(values), names(ret))) > 0L) {
    stop(sprintf("Unknown fields: %s", paste(err, collapse=", ")))
  }
  to_set <- intersect(names(values), names(ret))
  ret[to_set] <- values[to_set]
  ret
}

##' Strategy parameters that tune various aspects of the biological model.
##' @title Strategy parameters
##' @param ...,values Values to initialise the struct with (either as
##' variadic arguments, or as a list, but not both).
##' @export
Parameters <- function(..., values=list(...)) {
  ret <- Parameters__ctor()
  if (length(err <- setdiff(names(values), names(ret))) > 0L) {
    stop(sprintf("Unknown fields: %s", paste(err, collapse=", ")))
  }
  to_set <- intersect(names(values), names(ret))
  ret[to_set] <- values[to_set]
  ret
}

##' Gauss-Kronrod Quadrature
##' @param rule Degree of the rule; valid sizes are 15, 21, 31, 41, 51, 61.
`QK` <- function(rule) {
  QK__ctor(rule)
}
.R6_QK <-
  R6::R6Class("QK",
              portable=TRUE,
              inherit=NULL,
              public=list(
                .ptr=NULL,
                initialize = function(ptr) {
                  self$.ptr <- ptr
                },
                integrate = function(f, a, b) {
                  QK__integrate(self, f, a, b)
                },
                integrate_vector_x = function(a, b) {
                  QK__integrate_vector_x(self, a, b)
                },
                integrate_vector = function(y, a, b) {
                  QK__integrate_vector(self, y, a, b)
                }),
              active=list(
                last_area = function(value) {
                  if (missing(value)) {
                    QK__last_area__get(self)
                  } else {
                    stop("QK$last_area is read-only")
                  }
                },
                last_error = function(value) {
                  if (missing(value)) {
                    QK__last_error__get(self)
                  } else {
                    stop("QK$last_error is read-only")
                  }
                },
                last_area_abs = function(value) {
                  if (missing(value)) {
                    QK__last_area_abs__get(self)
                  } else {
                    stop("QK$last_area_abs is read-only")
                  }
                },
                last_area_asc = function(value) {
                  if (missing(value)) {
                    QK__last_area_asc__get(self)
                  } else {
                    stop("QK$last_area_asc is read-only")
                  }
                }))


`QAG` <- function(rule, max_iterations, atol, rtol) {
  QAG__ctor(rule, max_iterations, atol, rtol)
}
.R6_QAG <-
  R6::R6Class("QAG",
              portable=TRUE,
              inherit=NULL,
              public=list(
                .ptr=NULL,
                initialize = function(ptr) {
                  self$.ptr <- ptr
                },
                integrate = function(f, a, b) {
                  QAG__integrate(self, f, a, b)
                },
                integrate_with_intervals = function(f, intervals) {
                  QAG__integrate_with_intervals(self, f, intervals)
                }),
              active=list(
                last_area = function(value) {
                  if (missing(value)) {
                    QAG__last_area__get(self)
                  } else {
                    stop("QAG$last_area is read-only")
                  }
                },
                last_error = function(value) {
                  if (missing(value)) {
                    QAG__last_error__get(self)
                  } else {
                    stop("QAG$last_error is read-only")
                  }
                },
                last_iterations = function(value) {
                  if (missing(value)) {
                    QAG__last_iterations__get(self)
                  } else {
                    stop("QAG$last_iterations is read-only")
                  }
                },
                last_intervals = function(value) {
                  if (missing(value)) {
                    QAG__last_intervals__get(self)
                  } else {
                    stop("QAG$last_intervals is read-only")
                  }
                },
                is_adaptive = function(value) {
                  if (missing(value)) {
                    QAG__is_adaptive__get(self)
                  } else {
                    stop("QAG$is_adaptive is read-only")
                  }
                }))

##' Spline interpolation
##' @export
`Interpolator` <- function() {
  Interpolator__ctor()
}
.R6_Interpolator <-
  R6::R6Class("Interpolator",
              portable=TRUE,
              inherit=NULL,
              public=list(
                .ptr=NULL,
                initialize = function(ptr) {
                  self$.ptr <- ptr
                },
                init = function(x, y) {
                  Interpolator__init(self, x, y)
                },
                eval = function(x) {
                  Interpolator__eval(self, x)
                },
                deriv = function(x) {
                  Interpolator__deriv(self, x)
                }),
              active=list(
                type = function(value) {
                  if (missing(value)) {
                    Interpolator__type__get(self)
                  } else {
                    stop("Interpolator$type is read-only")
                  }
                },
                x = function(value) {
                  if (missing(value)) {
                    Interpolator__x__get(self)
                  } else {
                    stop("Interpolator$x is read-only")
                  }
                },
                y = function(value) {
                  if (missing(value)) {
                    Interpolator__y__get(self)
                  } else {
                    stop("Interpolator$y is read-only")
                  }
                },
                xy = function(value) {
                  if (missing(value)) {
                    Interpolator__xy__get(self)
                  } else {
                    stop("Interpolator$xy is read-only")
                  }
                },
                size = function(value) {
                  if (missing(value)) {
                    Interpolator__size__get(self)
                  } else {
                    stop("Interpolator$size is read-only")
                  }
                },
                min = function(value) {
                  if (missing(value)) {
                    Interpolator__min__get(self)
                  } else {
                    stop("Interpolator$min is read-only")
                  }
                },
                max = function(value) {
                  if (missing(value)) {
                    Interpolator__max__get(self)
                  } else {
                    stop("Interpolator$max is read-only")
                  }
                }))

##' Environment object
##' @param p A Parameters object
##' @export
`Environment` <- function(p) {
  Environment__ctor(p)
}
.R6_Environment <-
  R6::R6Class("Environment",
              portable=TRUE,
              inherit=NULL,
              public=list(
                .ptr=NULL,
                initialize = function(ptr) {
                  self$.ptr <- ptr
                },
                canopy_openness = function(height) {
                  Environment__canopy_openness(self, height)
                },
                patch_survival_conditional = function(time_at_birth) {
                  Environment__patch_survival_conditional(self, time_at_birth)
                },
                clear = function() {
                  Environment__clear(self)
                },
                set_seed_rain_index = function(x) {
                  Environment__set_seed_rain_index(self, x)
                }),
              active=list(
                patch_survival = function(value) {
                  if (missing(value)) {
                    Environment__patch_survival__get(self)
                  } else {
                    stop("Environment$patch_survival is read-only")
                  }
                },
                seed_rain_rate = function(value) {
                  if (missing(value)) {
                    Environment__seed_rain_rate__get(self)
                  } else {
                    stop("Environment$seed_rain_rate is read-only")
                  }
                },
                disturbance_regime = function(value) {
                  if (missing(value)) {
                    Environment__disturbance_regime__get(self)
                  } else {
                    Environment__disturbance_regime__set(self, value)
                  }
                },
                time = function(value) {
                  if (missing(value)) {
                    Environment__time__get(self)
                  } else {
                    Environment__time__set(self, value)
                  }
                },
                light_environment = function(value) {
                  if (missing(value)) {
                    Environment__light_environment__get(self)
                  } else {
                    Environment__light_environment__set(self, value)
                  }
                }))


`Plant` <- function(strategy) {
  Plant__ctor(strategy)
}
.R6_Plant <-
  R6::R6Class("Plant",
              portable=TRUE,
              inherit=NULL,
              public=list(
                .ptr=NULL,
                initialize = function(ptr) {
                  self$.ptr <- ptr
                },
                leaf_area_above = function(h) {
                  Plant__leaf_area_above(self, h)
                },
                compute_vars_phys = function(environment) {
                  Plant__compute_vars_phys(self, environment)
                },
                germination_probability = function(environment) {
                  Plant__germination_probability(self, environment)
                },
                copy = function() {
                  Plant__copy(self)
                }),
              active=list(
                height = function(value) {
                  if (missing(value)) {
                    Plant__height__get(self)
                  } else {
                    Plant__height__set(self, value)
                  }
                },
                mortality = function(value) {
                  if (missing(value)) {
                    Plant__mortality__get(self)
                  } else {
                    Plant__mortality__set(self, value)
                  }
                },
                fecundity = function(value) {
                  if (missing(value)) {
                    Plant__fecundity__get(self)
                  } else {
                    Plant__fecundity__set(self, value)
                  }
                },
                heartwood_area = function(value) {
                  if (missing(value)) {
                    Plant__heartwood_area__get(self)
                  } else {
                    Plant__heartwood_area__set(self, value)
                  }
                },
                heartwood_mass = function(value) {
                  if (missing(value)) {
                    Plant__heartwood_mass__get(self)
                  } else {
                    Plant__heartwood_mass__set(self, value)
                  }
                },
                leaf_area = function(value) {
                  if (missing(value)) {
                    Plant__leaf_area__get(self)
                  } else {
                    stop("Plant$leaf_area is read-only")
                  }
                },
                survival_probability = function(value) {
                  if (missing(value)) {
                    Plant__survival_probability__get(self)
                  } else {
                    stop("Plant$survival_probability is read-only")
                  }
                },
                strategy = function(value) {
                  if (missing(value)) {
                    Plant__strategy__get(self)
                  } else {
                    stop("Plant$strategy is read-only")
                  }
                },
                vars_size = function(value) {
                  if (missing(value)) {
                    Plant__vars_size__get(self)
                  } else {
                    stop("Plant$vars_size is read-only")
                  }
                },
                vars_phys = function(value) {
                  if (missing(value)) {
                    Plant__vars_phys__get(self)
                  } else {
                    stop("Plant$vars_phys is read-only")
                  }
                },
                vars_growth = function(value) {
                  if (missing(value)) {
                    Plant__vars_growth__get(self)
                  } else {
                    stop("Plant$vars_growth is read-only")
                  }
                }))


`Cohort` <- function(strategy) {
  Cohort__ctor(strategy)
}
.R6_Cohort <-
  R6::R6Class("Cohort",
              portable=TRUE,
              inherit=NULL,
              public=list(
                .ptr=NULL,
                initialize = function(ptr) {
                  self$.ptr <- ptr
                },
                leaf_area_above = function(height) {
                  Cohort__leaf_area_above(self, height)
                },
                growth_rate_gradient = function(environment) {
                  Cohort__growth_rate_gradient(self, environment)
                },
                compute_vars_phys = function(environment) {
                  Cohort__compute_vars_phys(self, environment)
                },
                compute_initial_conditions = function(environment) {
                  Cohort__compute_initial_conditions(self, environment)
                }),
              active=list(
                plant = function(value) {
                  if (missing(value)) {
                    Cohort__plant__get(self)
                  } else {
                    stop("Cohort$plant is read-only")
                  }
                },
                height = function(value) {
                  if (missing(value)) {
                    Cohort__height__get(self)
                  } else {
                    stop("Cohort$height is read-only")
                  }
                },
                leaf_area = function(value) {
                  if (missing(value)) {
                    Cohort__leaf_area__get(self)
                  } else {
                    stop("Cohort$leaf_area is read-only")
                  }
                }))


`Species` <- function(strategy) {
  Species__ctor(strategy)
}
.R6_Species <-
  R6::R6Class("Species",
              portable=TRUE,
              inherit=NULL,
              public=list(
                .ptr=NULL,
                initialize = function(ptr) {
                  self$.ptr <- ptr
                },
                clear = function() {
                  Species__clear(self)
                },
                compute_vars_phys = function(environment) {
                  Species__compute_vars_phys(self, environment)
                },
                leaf_area_above = function(height) {
                  Species__leaf_area_above(self, height)
                },
                add_seed = function() {
                  Species__add_seed(self)
                },
                plant_at = function(index) {
                  Species__plant_at(self, index)
                }),
              active=list(
                size = function(value) {
                  if (missing(value)) {
                    Species__size__get(self)
                  } else {
                    stop("Species$size is read-only")
                  }
                },
                seed = function(value) {
                  if (missing(value)) {
                    Species__seed__get(self)
                  } else {
                    stop("Species$seed is read-only")
                  }
                },
                height_max = function(value) {
                  if (missing(value)) {
                    Species__height_max__get(self)
                  } else {
                    stop("Species$height_max is read-only")
                  }
                },
                height = function(value) {
                  if (missing(value)) {
                    Species__height__get(self)
                  } else {
                    Species__height__set(self, value)
                  }
                },
                plants = function(value) {
                  if (missing(value)) {
                    Species__plants__get(self)
                  } else {
                    stop("Species$plants is read-only")
                  }
                },
                leaf_area = function(value) {
                  if (missing(value)) {
                    Species__leaf_area__get(self)
                  } else {
                    stop("Species$leaf_area is read-only")
                  }
                },
                leaf_area_error = function(value) {
                  if (missing(value)) {
                    Species__leaf_area_error__get(self)
                  } else {
                    stop("Species$leaf_area_error is read-only")
                  }
                }))

## This section of code is only included where templated classes are
## included.  Don't rely on the approach taken here, as it may change
## soon.
check_type <- function(type, valid) {
  i <- match(list(type), valid, nomatch=NA)
  if (is.na(i)) {
    choices <- paste(sprintf("\t%s", sapply(valid, paste, collapse=", ")),
                     collapse="\n")
    stop(sprintf("Invalid type '%s'; expected one of:\n%s",
                 paste(type, collapse=", "), choices))
  }
  names(valid)[[i]]
}
