name: Add new issues to plant board #5
on:
  issues:
    types: [opened]
jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/orgs/traitecoevo/projects/5
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
