on:
  push:
    branches:
      - main
      - master
      - develop
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - main
      - master
      - develop

name: bench

jobs:
  lint:
    if: github.event.pull_request.draft == false
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install package
        run: R CMD INSTALL .

      - name: Benchmark
        run: plant::run_plant_benchmarks()
        shell: Rscript {0}
